### ISSUE TITLE
MemberLookup plugin results instead of base class

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#1002]
* Version of CORE? 2.7, but I think it still applies in master

* Issue with Office, Lane, or both? Lane

* Is this [mostly] a bug report, feature request, or question? Question and/or Feature Request

I'm using a plugin that extends `MemberLookup` to flag some members in the list by appending some text to the name in the item for the dropdown.  It works but the item is being overwritten by the later call to the base class.  I can prevent this in `memlist->checkResults()`:
```PHP
        foreach ($chk['results'] as $key=>$val) {
            if (! isset($results["$key"])) {
                $results[$key] = $val;
            }
        }
```
This is the way [`productlist`](https://github.com/CORE-POS/IS4C/blob/master/pos/is4c-nf/gui-modules/productlist.php#L125) works with plugin results and I expected `memlist` to do the same.  Is it done differently, or some reason not to?

**Comment by gohanman** [comment]
That looks reasonable to me. I can't think of any reason not to put that check in place. Any search that hands back a URL instead of a set of results will effectively overwrite other results but I don't know if that functionality is even used anywhere.

**Comment by gohanman** [comment]
Sorry for letting this linger so long. It's in now.
