### ISSUE TITLE
HourlyTransReport Double-Counting transactions

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#1003]
* Version of CORE?
Production version 2.3

* Issue with Office, Lane, or both?
Office

* Is this [mostly] a bug report, feature request, or question?
Reporting bug

[HourlyTransReport](https://github.com/CORE-POS/IS4C/blob/master/fannie/reports/HourlyTrans/HourlyTransReport.php#L214) double-counts transactions that span across 2 hours.
e.g. a transaction that starts at 4:58 and ends at 5:01 get counted twice.

**Comment by gohanman** [comment]
I can't think of any practical way to fix this. SQL aggregates can't do what's being requested here and scanning through every single transaction record on the PHP side to do it manually has a non-trivial performance penalty.

I'm not sure this particularly matters. Any double counts should be randomly distributed. As a method of assessing traffic patterns and when the store is busier or slower the results should still be effectively correct. It's not like someone's going to staff differently if the report listed 103 transaction in the 11am hour when really it was just 100.

**Comment by gohanman** [comment]
I'm closing this as not fixable. You could sort of do it using the [warehouse plugin](https://github.com/CORE-POS/IS4C/blob/master/fannie/modules/plugins2.0/CoreWarehouse/models/TransactionSummaryModel.php) tables but that adds a non-trivial layer of maintenance and upkeep to make sure the summary tables are getting built correctly and IMO it shouldn't be required for this kind of basic reporting.
