### ISSUE TITLE
Automagically marking lanes offline/online

### ISSUE THREAD

**Issue by otc-narendra** [CORE-POS/IS4C#1004]
* Version of CORE? 2.7
* Issue with Office, Lane, or both? Office
* Is this [mostly] a bug report, feature request, or question? Feature request

The current offline lane functionality issue [#947](https://github.com/CORE-POS/IS4C/issues/947) is super handy and the way we're mainly using it is for a temporary laptop lane that we only bring online a few times a week when things get super busy. It would be really great to automate some of the steps that currently require manual intervention:

1) Taking a lane online: It would be nice to have something in the fannie UI (not in the install page) that marks a lane online/offline. The install page UI is fully functional of course but I hate letting staff into the install pages... Something on a fannie admin page would be cool.

2) Taking a lane offline: It would be nice to have a lane marked automatically offline if it cannot be found. All too often, staff shuts down the laptop and forgets to mark the lane offline which slows things down and fills up the log files with errors. The most elegant implementation would be for the lane to send a "I'm offline" message to the server when it shuts down and a "I'm online" message when it starts. This would be super resilient in situations where temporary network glitches can cause the server to lose connection with the lane.
- Narendra

**Comment by gohanman** [comment]
Having an alternate UI is pretty straightforward.

Automation seems a little trickier. I don't know what we could hook into on shutdown that would send a message just before powering off. Sending the "I'm online" message on boot is easier, and that in conjunction with marking the lane offline the first time the server attempts to connect to the lane and fails could work.

Where this could break down is on a transient network error. If a single server=>lane communication attempt fails and the lane **isn't** actually powered off / rebooting / etc then the server would mark it offline and the lane might not re-send an "I'm online" message for quite some time.

**Comment by otc-narendra** [comment]
I agree that transient network errors could create problems if this is done on the server side alone. That's why I was wondering if the lane can send a message to the server. When the MySql server shuts down on the lane, is there no "shutdown" or "cleanup" script run? One could also set up a shutdown script at the OS level...

**Comment by gohanman** [comment]
> When the MySql server shuts down on the lane, is there no "shutdown" or "cleanup" script run?

Not anything that you can hook into to run custom commands.

> One could also set up a shutdown script at the OS level...

You can with Group Policy on Pro editions of Windows. As far as I can tell there's no way to do the same on Home editions. 

That's not a problem per se, it just seems like there isn't a solution that would be self-contained and reasonably OS-agnostic.

**Comment by flathat** [comment]
I'm getting `fannie.log`:
```
[2018-07-13 13:12:50] fannie.DEBUG: Array to string conversion Line 63, 
/var/www/html/Our-Table/fannie/admin/LaneStatus.php [] []
```
and lintcheck error in `config.php`:     
`PHP Parse error:  syntax error, unexpected ')', expecting '(' in config.php on line 17`
`L#17 ... 'offline'=>Array)`
```
// L#17:
$FANNIE_LANES = array(array('host'=>'192.168.1.101','type'=>'MYSQLI','user'=>'corelane','pw'=>'corelane','op'=>'opdata','trans'=>'translog','offline'=>Array),array('host'=>'192.168.1.102','type'=>'MYSQLI','user'=>'corelane','pw'=>'corelane','op'=>'opdata','trans'=>'translog','offline'=>Array),array('host'=>'192.168.1.103','type'=>'MYSQLI','user'=>'corelane','pw'=>'corelane','op'=>'opdata','trans'=>'translog','offline'=>Array),array('host'=>'192.168.1.104','type'=>'MYSQLI','user'=>'corelane','pw'=>'corelane','op'=>'opdata','trans'=>'translog','offline'=>Array));
```
Is `post_handler()` getting called instead of  `post_id_handler()`?  Four lanes.  There doesn't seem to be an `id` in the form.

**Comment by gohanman** [comment]
Mixed up a variable there.

Yes, it's `post_handler`. The `post_id_handler` is there so that theoretically an OS could call it on startup and shutdown. I don't see that ever being built-in functionality since parts are too far out of CORE's control but I figured I'd make an HTTP endpoint available if someone wanted to try.

**Comment by flathat** [comment]
After changing that it doesn't report errors anymore but doesn't change `offline=` in `config` or offline status in `Necessities`.

**Comment by gohanman** [comment]
I forgot the increments (which just so happens to work in a toy test environment with just one lane configured).

**Comment by otc-narendra** [comment]
Thanks Andy, LaneStatus.php seems to work great from the Fannie UI now. I haven't tested the post_id_handler yet but will do so later this week. One comment is that when you update a lane's status on the Fannie UI, and press the "Update Offline Status" button, it sure would be nice if the page could automatically refresh to show the new updated status. Right now, I have to manually refresh to see the changes I just applied.

**Comment by gohanman** [comment]
That's strange. It definitely should refresh and does for me.

**Comment by otc-narendra** [comment]
Tested the post_id_handler and it works great!

**Comment by otc-narendra** [comment]
@gohanman I'm thinking it would be nice to have some lane sync code in the post_id_handler() when a lane is market online - i.e. sync up some tables to ensure that the lane is up to date. I'm happy to give this a shot but am wondering if there are any reasons why this would be a bad idea.

**Comment by gohanman** [comment]
I think the main downside is web requests that timeout don't fail gracefully and syncs tend to be longer running operations. It's harder to guarantee it works. 

Putting the database sync into the "I'm online" script would probably be more reliable. I think the powershell syntax would be something like:

```
cmd /c " `"C:\path to\mysqldump.exe`" -h [server] -u [user] -p[password] opdata products custdata employees | `"C:\path to\mysql.exe`" -h localhost -u [user] -p[password] opdata"
```
