### ISSUE TITLE
Model for batchReviewLog

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#1015]
* Version of CORE? 2.10

* Issue with Office, Lane, or both? Office

* Is this [mostly] a bug report, feature request, or question? bug report

Can you provide a Model for `core_op.batchReviewLog` which is used in:     
`./item/ProdReviewPage.php:            INSERT INTO batchReviewLog (bid, vid, printed, user, created, forced)`   
and    
`./item/ProdReviewRequest.php`

**Comment by gohanman** [comment]
Sorry about that.

**Comment by flathat** [comment]
Could you backport it to `version-2.10`?  Or should I begin a Pull Request? -- I'm not sure how that works in this situation.

**Comment by gohanman** [comment]
Sure; I also backported the hardcoded URL problem w/ ignored barcodes.

**Comment by flathat** [comment]
Maybe the right place for this issue.

`ProdReviewRequest::updateComment()` has:    
`$prep = $dbc->prepare("UPDATE batchReviewLog SET comments = ? WHERE bid = ?");`  
but the `TEXT` field in `batchReviewLog` is called `notes`.

`ProdReviewPage::get_batchLog_view()` also refers to `batchReviewLog.comments`

Should the field in the model be `comments` instead of `notes`?

**Comment by gohanman** [comment]
Yes, it looks to me like the model is wrong and it should be `comments`.
