### ISSUE TITLE
Hardware advice

### ISSUE THREAD

**Issue by otc-narendra** [CORE-POS/IS4C#1017]
I am looking to add a third lane to my setup located at an outdoor food service counter (at a patio) attached to my outdoor kitchen. I am going to use a touch-screen laptop for my lane with the custom touch-screen keyboard that we've successfully used in the past. Some questions about accessory hardware:

1) Receipt printer: I don't want to hook a printer up directly to this lane -- instead I want to use a network printer so that the same printer can do double-duty as a remote printer from other lanes. I assume this is not a problem.

2) Cash drawer: can you make a recommendation for a USB cash drawer? I don't want the cash drawer to be connected to the printer for reasons specified above. Is there a kicker module that will automatically open a USB cash drawer?

3) Card reader: Is the ingenico isc250 still the best option here for a chip/swipe reader? I do want to be able to process tips at the reader and theoretically the isc250 allows for this (and Andy enabled it a while ago) although I haven't managed to test out this functionality yet.

4) Barcode scanner: A simple USB barcode scanner should be more than sufficient - any recommendations on something affordable and reliable?

Thanks!

- Narendra

**Comment by joelbrock** [comment]
1. So multiple lanes would have the same remote printer configured?  I don't see this as being a problem.
2. I've never used this before but i did find [a device that purports](https://www.amazon.com/BT-100U-Drawer-Driver-Trigger-Interface/dp/B00OM9ML2K) to allow you to connect the cash drawer to the PC and not the receipt printer.  Again, I have no first-hand experience with this but its an inexpensive gamble.
3. ISC250 is still a good option.  A cheaper alternative (that lacks digital signature support) would be the Verifone VX805 which is also fully-integrated with CORE-POS and roughly a third of the cost of the isc250.
4. Barcode scanners are cheap, but if you want one that is ALSO reliable and rugged, I generally lean towards the Motorola / Symbol handhelds.  The LS2208 is a classic, and not expensive.  Though I'm a fan also of their cordless handhelds, the LI4278 is a good one.  For use outdoors you may even consider looking at the options rated for industrial use.  For added durability & drop-proof-ness.

**Comment by gohanman** [comment]
(What Joel said, basically)

1. I've found Epson TM-T88V to be simple to deal with as a network printer. You can send it the exact same bytes as a locally connected printer just via a TCP connection instead of LPT1. I'd imagine this is true generally of Epson ESCPOS compatible printers but this is the only model I've used myself.

2. I've never used a USB cash drawer. Poking around Google they seem like potentially simple devices. From a research standpoint on a given device if there's information how to open it from the Windows command line (or more ideally a batch file) that's probably enough to make it work.

3. [This](https://www.datacapsystems.com/compatible-devices) is the full list. Processor specific support varies a bit from one device to another. The devices I've used personally are the the iSC250 and the Verifone VX805.

4. I also use the LS2208 or LI2208. The LS is reflective and the LI is more camera-y (probably not the technical term) but the upshot is the LI can successfully scan a barcode off a glass phone screen much more often than the LS.

**Comment by otc-narendra** [comment]
I do plan to use the Epson TM-T88V printer.

The Verifone VC805 sounds like the way to go: @gohanman any idea if it will support the ability for a customer to select a tip amount?

As for the cash drawer, I like the idea of a dongle that adapts the regular cash drawers to USB like @joelbrock suggested so might try that. What cash drawer would you recommend?

**Comment by joelbrock** [comment]
Generally I go with the APG brand for cash drawers.  The Vasario Series is a good medium-duty option.  Although I like the Series 400 for the added ruggedness.  
https://posguys.com/cash-drawer_32/APG-Vasario-Series_61/
Just make sure the dimensions and features are right i.e. electric kick, bell/no bell, number of till slots, etc.

**Comment by gohanman** [comment]
As far as I know tipping works fine on the VX805. That may have even been
the device I was using when testing it but it's been long enough that I
don't recall for sure.

**Comment by otc-narendra** [comment]
Thanks for the advice. @joelbrock can you guys order the VX805 for us so that all the appropriate encryption keys, etc. are injected properly? I'm assuming you'll use JRS or someone similar? I tried to pick all the appropriate options on the JRS order page for your reference (note that I'd like the USB port-powered version - unless you advice against that - and a low-profile tilt-swivel stand). 
![image](https://user-images.githubusercontent.com/29678134/54782420-2066b100-4bdc-11e9-8e58-630e391a44bf.png)
Thanks!

**Comment by joelbrock** [comment]
We certainly can.  But if you wanted to yourself you've got the form filled out completely already.  For the Mercury injection we do not need to specify the Debit Key ID, it's included in the processor package.  You can leave that field on the form blank.

But definitely let me know if you'd rather us acquire on your behalf and i can do that today.

**Comment by otc-narendra** [comment]
I don't have an account with them so if it's ok with you, I'd prefer that you place the order. Thanks!
