### ISSUE TITLE
Prompt for count?

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#1018]
* Version of CORE?
2.7.0-2017.06.30

* Issue with Office, Lane, or both?
Lane

* Is this [mostly] a bug report, feature request, or question?
Feature request

At our co-op, member-workers are cashiers. We want to do everything possible to help these cashiers succeed without demanding more practice than is strictly necessary.

One area they sometimes struggle with is correctly entering counted vs weighed produce.

It would be helpful if, for counted (non-weighed) produce, CORE-POS prompted cashiers whenever an item is rung in without an item count *but* with a weight on the register. (Especially if it notices the weight on the register doesn't match the last weighed item — but it would be helpful even without that tweak.)

Thoughts?

**Comment by gohanman** [comment]
I think the correct way to do this would be setting QtyFrc on all counted produce.

**Comment by scannerdarkly** [comment]
I'm a bit ashamed I didn't think of this. (I'd been thinking of this flag as only being for ounce weights.)

Thanks so much!
