### ISSUE TITLE
How best to populate `CardNo` values

### ISSUE THREAD

**Issue by lgedgar** [CORE-POS/IS4C#1026]
* Version of CORE?

any / latest

* Issue with Office, Lane, or both?

Office

* Is this [mostly] a bug report, feature request, or question?

question and/or feature request

Really what I'm after here is a better understanding of how/when new member records are added to CORE, specifically as it relates to the `custdata.CardNo` field and integration with external systems.

It appears the "normal" use case is to create new member record(s) via `mem/NewMemberTool.php` and the value of `CardNo` will effectively be generated via auto-increment, starting either with a number provided by the user, or (default) is to start with the "max" number currently present for `custdata.CardNo` within the DB.

Presumably then, any time a new member record is created via this normal method, it is "immediately" given a unique `CardNo` value, so basically, problem solved.  The member record can be further edited within CORE but its `CardNo` should not change.

If a "new" member record is being imported from another system (e.g. CiviCRM) then this could go one of two ways.  Simplest behavior would be for it to create a new member record in CORE, and probably auto-generate its `CardNo` using the "max" starting point as described above.

If for some reason there were "pending" NEW MEMBER records already in CORE, and you wanted to "use" one of these for the new record coming from external system, then I suppose the `CardNo` value should already exist and would (again) not need to change within CORE.  (Nevermind how the other system tracks it, I'm just concerned with CORE here.)   But then what happens if you "run out" of NEW MEMBER records and need to actually create a new record?  The simpler behavior in last paragraph seems to have no such issues and likely should be preferred.

So I'm just hoping someone can give me a sanity check on this.  Can it be confirmed that:

* normal CORE behavior is just fine currently, but
* new member records brought in from external systems should ideally cause new member records to be created in CORE, with `CardNo` values generated via auto-increment based on max current value

Is the `CardNo` field more magical than that?  Or does it just need to be unique?

Again I'm explicitly *not* considering the needs of the integration (data sync) itself.  I'm only trying to figure out if CORE would be "happy" (wrt. data integrity) with this approach.

**Comment by gohanman** [comment]
You would definitely want to give new accounts from an external system a new `CardNo`. Unless there's some particular reason to do otherwise `MAX(CardNo)+1` is the best choice.

In practice accounts get pre-allocated so you can ring up the first equity purchase under the account number. The field itself is not magical but wrt data integrity a new account from an external system ought to have a corresponding transaction representing any equity purchased via the external system. I personally treat online purchases as a separate store (i.e., `dtransactions.store_id`) and that can simplify some accounting stuff like reconciling PayPal statements but there's no hard requirement in CORE that they differ from B&M transactions.

**Comment by lgedgar** [comment]
So any pre-allocated accounts are for the sake of CORE itself (and customer workflows within it), but there would be no inherent reason to try to "use" those when importing from external system?  Since the "first transaction" would be imported also, and therefore not yet be tied to any CORE account until import, at which time it could assume the newly-generated `CardNo` value.

Now I feel I can bring in the integration / sync itself.

In the specific case of CiviCRM (#401), the `CardNo` has been made to match Civi's `Membership.id` value, which is why those values aren't generated with `MAX(CardNo)+1` - but if there were some other way to keep track of the "shared key" between systems, then `CardNo` could be generated the normal way.

CiviCRM provides the `Contact.external_identifier` field, in which we could store CORE's `CardNo` values for the sake of tracking the sync.  Or, we could add "another" field to CORE, in which we store Civi's `Membership.id` values, for tracking.  (Either would let us populate `CardNo` in the "conventional" way.)  It seems that if CORE in the wild needed to sync with "various" systems then a new field may be warranted; however one such field could perhaps only be used for sync with one system at a time.  (Maybe it's unlikely that a given CORE install would need to sync with multiple systems?  But if so it might need a field per system, unless the "other" system provides a field we could use, as in Civi's case.)

Is there any reason to add "external ID" field(s) in CORE at this point?  Seems to be no need for CiviCRM since they provide one.

Since the CiviCRM integration already exists, I'll "ignore" that for this question:  Assuming a new integration with say, SugarCRM, is there any reason not to use the approach(es) described here?  Or would there be some inherent benefit to making `CardNo` match the external system's key value?

**Comment by gohanman** [comment]
I'd go farther and say it'd cause problems to use pre-allocated accounts for syncing. You can pre-allocate some accounts, print them, and put them at store A. Then you can pre-allocate some more accounts, print them, and put them at store B. As long as no external thing is grabbing the accounts there won't be collisions.

I don't see a reason to make the IDs match, but a single external ID field also seems insufficient. I think you'd want a `cardNo, otherID` mapping table per external service. I think the general outline would be a plugin with a model class defining the mapping table and task class(es) to do the syncing (or of course a separate python/rattail process doing the syncing).

**Comment by lgedgar** [comment]
Interesting, makes sense.  Any reason to prefer such a mapping table in CORE as opposed to just using a field provided by external system, when available?  Obviously once a mapping table existed, "might as well" use it, but until then, seems easier to leverage external capabilities.

**Comment by gohanman** [comment]
It might provide some convenience if there's bi-directional syncing and
you want to stick to an API instead of reaching directly into the external
database. With one-way sync it probably doesn't matter.

**Comment by lgedgar** [comment]
Thanks, I think that's all I needed for now.
