### ISSUE TITLE
houseVirtualCoupons or HouseVirtualCoupons

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#1027]
* Version of CORE? master

* Issue with Office, Lane, or both? Both, or just Office.

* Is this [mostly] a bug report, feature request, or question? Bug, of sorts.

Can there be agreement on the case of the first letter of the name of the House Virtual Coupons table?  The Fannie Module has is capitalized and the lane Module has it lowercase. Fannie sync has lowercase. The lane `VirtualCoupon` plugin has lowercase.

My preference is for lowercase, to sort with `houseCoupons` and `houseCouponItems`.

**Comment by gohanman** [comment]
Seems reasonable enough. Looks like the lowercase variant is more common in existing code, too.
