### ISSUE TITLE
Browse Vendor search returns nothing when $brand contains an ampersand

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#1031]
* Version of CORE? 2.11

* Issue with Office, Lane, or both? Office

* Is this [mostly] a bug report, feature request, or question? Bug, or increased robustness request

If the brand selected from the dropdown in `item/vendors/BrowseVendorItems.php` contains an ampersand ('&') the list of items created by `showCategoryItems()` is empty. Might this be similar to #385?

**Comment by gohanman** [comment]
That should fix it. I only dropped it back into the 2.11 branch although I'd guess this bug is present in every version branch. It's a pretty small thing to backport further manually if needed.

**Comment by flathat** [comment]
Yes, that did it. Thank you.
