### ISSUE TITLE
Live Scale in MAGELLAN 8500XT

### ISSUE THREAD

**Issue by Komel-Lakhani72** [CORE-POS/IS4C#1032]
We are facing a time delay issue in live scaling. we have used Microsoft Point Of Service SDK using ScaleLiveWeight function in window base application(C#) but it's Scaling is taking 2 seconds to scale the product but we want to make it a little faster than now,

Kindly help us to find any solutions for LiveWeight scaling faster.

Thanks in advance.

**Comment by gohanman** [comment]
Is this a generic Magellan question? I'm afraid I don't have much insight for you. We're using a plain old [SerialPort](https://docs.microsoft.com/en-us/dotnet/api/system.io.ports.serialport?view=netframework-4.8) to interact with the scale and not the MS POS SDK.

Apologies if I'm misunderstanding and you're trying to utilize this repo's C# code. If so further clarification would help.
