### ISSUE TITLE
TransArchiveTask failed due to primary key collision

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#1034]
* Version of CORE?
2.7.0-2017.06.30

* Issue with Office, Lane, or both?
Office

* Is this [mostly] a bug report, feature request, or question?
bug report

```
TransArchiveTask: Failed to archive 2020-02-29 in transarchive (last quarter table)
                    Details: Failed Query on ../CORE-POS/fannie/classlib2.0/FannieTask.php
INSERT INTO transarchive 
                               SELECT * 
                               FROM dtransactions 
                               WHERE datediff(datetime,?)= 0
Parameters: 2020-02-29
Duplicate entry '1302' for key 'PRIMARY'
```

The primary key in question appears to be ```store_row_id```. Any guidance here? Office reporting is now missing several days' data...

**Comment by gohanman** [comment]
I guess it depends how the primary key got there. The installation doesn't put a primary key on that column by default so the simple answer is to remove it. But if there's some particular local reason you want that PK then it's a question of where the duplicate value(s) came from.

**Comment by scannerdarkly** [comment]
Interesting!

``fannie/classlib2.0/data/models/trans/DTransactionsModel.php`` does show  ```
$this->columns['store_row_id']['primary_key'] = true;```

but that's only for ``dtransactions``, not ``transarchive``. I wonder if I made it PK for the latter as well, not understanding the ramifications. I have no reason I'm aware of to keep it this way, so I guess I'll de-key it and see how things go.

Any further thoughts or suggestions before I go ahead with this?

**Comment by gohanman** [comment]
I don't think so. Removing the PK will definitely let the rotation happen. Might be worth checking whether the records w/ the same `store_row_id` in `transarchive` and `dtransactions` are the same or different.

**Comment by scannerdarkly** [comment]
They're different. One's from February 21st, the other from February 29th.

What's ``store_row_id`` actually used for?

**Comment by gohanman** [comment]
Nothing in particular. It's a more convenient identifier for a [per-store] unique record than date + emp_no + register_no + trans_no + trans_id.

The duplication is a little weird though. I've certainly never seen an auto-increment column repeat values.

**Comment by scannerdarkly** [comment]
They're from different lanes, and the February 29th record was from a lane that was in training mood. Could either of these details have something to do with it?

**Comment by gohanman** [comment]
Shouldn't; the column only exists on the server side so the lanes aren't
responsible for the values. They should get generated on INSERT when the
lanes upload data to the server.

**Comment by scannerdarkly** [comment]
Oh, is ``dtransactions`` subject to an SQL ``TRUNCATE``? If so, ``store_row_id`` would be automatically reset on every truncation, since it's ``AUTO_INCREMENT``. (See [here](https://oracle-base.com/articles/mysql/mysql-how-truncate-table-affects-auto-increment) for docs)

**Comment by gohanman** [comment]
Nope. https://github.com/CORE-POS/IS4C/blob/master/fannie/cron/tasks/TransArchiveTask.php#L278

**Comment by scannerdarkly** [comment]
Hmmm. And I can't imagine how any of these would have been run:
* ``documentation/Reference Code/Wedge/is4c/connect.php.ref``: ``sql_query("truncate table dtransactions", $connect);``
* ``documentation/Reference Code/Wedge/installation/mysql/opdata/jobs/dayendreset``: ``truncate table translog.dtransactions;``
* ``fannie/install/sample_data/LoadSampleTrans.php``: ``$dbc->query('TRUNCATE TABLE unit_test_trans.dtransactions');``
* ``scripts/dlog_rotate.sh``: ``mysql -uroot -p_____ is4c_log -e "TRUNCATE TABLE dtransactions"``

Curiouser and curiouser.

**Comment by scannerdarkly** [comment]
Okay, I removed the primary key from ``dtransactions``, and I guess that part completed okay.

Now we've got:
```
TransArchiveTask: Failed to reload dlog_15. Details: Failed Query on ../CORE-POS/fannie/classlib2.0/FannieTask.php
INSERT INTO dlog_15 
                                 SELECT * 
                                 FROM dlog_90_view 
                                 WHERE datediff(NOW(),tdate) <= 15
Duplicate entry '2222' for key 'PRIMARY'
```
I assume I should remove ``dlog_15.store_row_id``'s primary key status as well?

**Comment by gohanman** [comment]
Yeah. Whatever caused the duplicate values is going to be an issue anywhere w/ that primary key.

**Comment by scannerdarkly** [comment]
Okay, switching the second primary key has finally allowed the overnight tasks to complete. Thanks for your help!
