### ISSUE TITLE
More about $FANNIE_CARDNO_MAX

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#1066]
* Version of CORE? master

* Issue with Office, Lane, or both? Office

* Is this [mostly] a bug report, feature request, or question? question

Could you say a bit more about the possible use cases for `$FANNIE_CARDNO_MAX`?  Install > Members says:
> The maximum number of normal customer accounts. This should be a high value and defaults to one billion. The purpose of the limit is to create a space for non-normal accounts that are automatically generated and not used directly by people. Cordoning these off keeps the length of the account numbers real people are using from growing too quickly.

At one store I had some special users that represented departments in the store (Kitchen, Regular Retail) that were used for representing intra-store transfer of products.  Their transactions needed to be excluded from movement reports.  Their `CardNo`s were between `99000` and `99998`, below Non-member `99999`.  Might having  `$FANNIE_CARDNO_MAX = 99999` and their `CardNo`s above that made the exclusion more generalizable, not `$FANNIE_COOP_ID`-specific?  I don't see `$FANNIE_CARDNO_MAX` being used for exclusion in current reports so maybe the intended use is different.

**Comment by gohanman** [comment]
It's about credit card data. Individual people who are non-members can be identified via card data, and assigning them customer numbers gives better understanding of the behavior of non-members.

Separately, the issue you're bringing up can be addressed via 853a4ca194442782f05dcb4ba66bf97053e28bd8
