### ISSUE TITLE
Report Headers repeating in export

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#1103]
* Version of CORE?
Latest / master

* Issue with Office, Lane, or both?
Office

* Is this [mostly] a bug report, feature request, or question?
Question:

How to prevent the exported CSV or XLS files from repeating the report header before each table in the report?
Just need it that one time, at the top of the page.

![General_Range_Report_October_2021](https://user-images.githubusercontent.com/52835/139954612-0997d233-dd48-475b-936b-ab9342782dc1.png)

**Comment by gohanman** [comment]
Like that. I guess I never noticed since the HTML and proper XLSX versions both don't do that.
