### ISSUE TITLE
Auto-focus for member search list at POS

### ISSUE THREAD

**Issue by lgedgar** [CORE-POS/IS4C#1144]
* Version of CORE?
2.11

* Issue with Office, Lane, or both?
Lane

* Is this [mostly] a bug report, feature request, or question?
bug report

[This commit](https://github.com/CORE-POS/IS4C/commit/604191dba23d5dde460a5733558f20fb64a17418#diff-d8da8d6b9f76953e35479a7be191cc8dc9e138d745ed1c8243d7770917c8b117L236) seems to have changed behavior for auto-focus of `<select>` element for member search results.  Previously the list was auto-focused, but no longer.

Wasn't sure if that was intentional or just an accident given the nature of that commit.  As you can see it now auto-focuses `#reginput` in all cases.

While troubleshooting this I also found that in [BasicCorePage->commonHeader()](https://github.com/CORE-POS/IS4C/blob/master/pos/is4c-nf/lib/gui/BasicCorePage.php#L218) it always auto-focuses `#reginput` - so was wondering if the `memlist.php` should do that?  It appears to me that `memlist.php` could auto-focus `#search` but only if there were results, otherwise don't bother auto-focus anything since BasicCorePage would handle it.

**Comment by gohanman** [comment]
I think the breakage was here: 52cb01d0a27fec2cb2dbe65eb45083bdd777bd77

A 2nd `id` attribute gets added onto the `<select>` and screws things up - although I did check the 2.11 branch and it does not contain this commit.

**Comment by lgedgar** [comment]
Thanks - that did the trick.

I guess the code was more based on master than version-2.11..
