### ISSUE TITLE
batchUpdate.batchName to 80 chars

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#1158]
* Version of CORE? current

* Issue with Office, Lane, or both? Office

* Is this [mostly] a bug report, feature request, or question? bug report/feature request

Is there any reason not to increase the width of `batchUpdate.batchName` to 80 characters to match `batches.batchName` to prevent:
```
[2022-09-13 12:56:27] fannie.WARNING: Failed Query on /is4c/fannie/batches/newbatch/BatchListPage.php 
INSERT INTO batchUpdate (`updateType`,`batchID`,`batchType`,`modified`,`user`,`startDate`,`endDate`,
`batchName`,`owner`) VALUES (?,?,?,?,?,?,?,?,?) 
Parameters: BATCH CREATED 133 1 2022-09-13 12:56:27 0205 2022-09-14 2022-09-30 
Produce Local Specials September Produce
Data too long for column 'batchName' at row 1 [] []
```

**Comment by gohanman** [comment]
Not that I can think of. I figure as long as it's changing it might as well go all the way to 255. The limit of 80 was itself an arbitrary choice someone made years ago.
