### ISSUE TITLE
Notifiers in AutoLoader

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#1172]
* Version of CORE? 3.0.0-dev

* Issue with Office, Lane, or both? Lane

* Is this [mostly] a bug report, feature request, or question? bug/question

I've enabled the `CashDrop` plugin that is in the main CORE repo (not the separate one).  I expected [`CashDropNotifier`](https://github.com/CORE-POS/IS4C/blob/master/pos/is4c-nf/plugins/CashDrop/CashDropNotifier.php) which `extends Notifier` to be auto-loaded but it was not; the Notifier does not appear when the conditions for it are met.

In `CashDropPreParser` I've added:    
`if (!class_exists("AutoLoader")) include_once(realpath(dirname(__FILE__).'/../../lib/AutoLoader.php'));`

If in `CashDropPreParser->check()` I look for `CashDropNotifier` in the array returned by `CoreLocal::get('Notifiers')` it is absent.   If I add it to the `Notifiers` array in `CoreLocal` then it becomes usable in the plugin.

Should `AutoLoader` be loading it?  If so, what is needed for that to happen?

I found that `TermStateNotifier` from the `Paycards` plugin is in the `Notifiers` array at the the point when `CashDropNotifier` is not even though the `Paycards` plugin isn't enabled.

**Comment by gohanman** [comment]
Notifiers need to be configured under the "Extra" tab.

https://github.com/CORE-POS/IS4C/blob/master/pos/is4c-nf/install/extra_config.php#L300-L316
