### ISSUE TITLE
SNAP not recognized in  “Charge Available Card” 

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#1174]
* Version of CORE? 2.11 and later

* Issue with Office, Lane, or both? Lane

* Is this [mostly] a bug report, feature request, or question? Problem/bug

Statement of issue: We always use the “Charge Available Card” option but EBT transactions do not get run unless we explicitly choose the EBT option instead.

It's not clear exactly which version of various part of  `Paycards` is being used but it is reported that this has been an issue for a long time (several years), predating any recent changes.

Could you suggest where the detection of type of card is implemented to help us figure out what is affecting it?

**Comment by gohanman** [comment]
There is no type of card detection. This is a fundamental limitation of how Datacap's software works. It's always been the case that running an EBT transaction requires explicitly choosing the EBT option instead.

**Comment by flathat** [comment]
OK, thanks, saves us a pointless chase.
