### ISSUE TITLE
Support separate UnitOfMeasure in DefaultUploadPage

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#1195]
* Version of CORE? Current

* Issue with Office, Lane, or both? Office

* Is this [mostly] a bug report, feature request, or question? Feature offer

I have a catalogue from a new vendor that loads very nicely with `DefaultUploadPage.php` with one exception: it has UnitOfMeasure in a separate column from Unit Size, which contains only the number.  Would you be open to the addition of support for an optional UoM column which would be appended to Unit Size?  Also in `UpdateUploadPage.php`.  If so I'm happy to code and submit a pull request.

**Comment by gohanman** [comment]
Sure, that sounds perfectly reasonable.

**Comment by flathat** [comment]
Done in https://github.com/CORE-POS/IS4C/commit/3d8493efa2fb5043db4936d3185e4c36cbac5195 .
