### ISSUE TITLE
Use of Mettler-Toledo Backup file for PLU refresh

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#1196]
* Version of CORE? current

* Issue with Office, Lane, or both? Office

* Is this [mostly] a bug report, feature request, or question? Question

Does anyone have experience with using, or trying to use, a file in the format of a Mettler-Toledo model IMPACT-S Backup/Restore file for refreshing PLU data on the scale?  I want to replace the PLU data in the Backup file and re-load it using Restore.  M-T support is not clear about whether this is actually possible.

Backup/Restore from the scale is to a USB stick on the scale that must have a license key file on it.  That license seems to be an "extra", a separate purchase.   The scale I have was purchased used so I'm not sure what comes with new ones.

If you've done this, or even if you've only done Backup, can you share anything about the format of the file?

**Comment by gohanman** [comment]
We've always used MT's bSoft program for this kind of thing. I'm not having any luck turning up a download site. I know our MT rep gave it to me for free, but I don't know if it's generally available.

**Comment by flathat** [comment]
My M-T rep says "B-Soft only works on the B-Pro scale which has been discontinued."

**Comment by flathat** [comment]
I've not been able to find more on the use of Backup/Restore one way or the other.

Mettler-Toledo's solution for refreshing PLU data on an IMPACT involves both of:
+ WinDataBack app running on a PC. USD 800.00 plus $97.80/yr license renewal.
+ USB stick with License Key to plug in to scale. USD 552 plus $16.00/yr license renewal.
