### ISSUE TITLE
Phone column size mismatch

### ISSUE THREAD

**Issue by lgedgar** [CORE-POS/IS4C#1197]
* Version of CORE? latest

* Issue with Office, Lane, or both? Office

* Is this [mostly] a bug report, feature request, or question? bug report / question

There is a mismatch of sorts between schema for [meminfo.phone](https://github.com/CORE-POS/IS4C/blob/006d06e26b6cb8b14ab014f8bbf1afb8d5fccebc/fannie/classlib2.0/data/models/op/MeminfoModel.php#L46) (30 chars) and [Customers.phone](https://github.com/CORE-POS/IS4C/blob/bac68f990cea2292780d39370ccc421a51b63722/fannie/classlib2.0/data/models/op/CustomersModel.php#L47) (20 chars).

The [ContactInfo module](https://github.com/CORE-POS/IS4C/blob/b78340cbd299d4b4d6eae270c38bd3789a0d389f/fannie/mem/modules/ContactInfo.php#L99) limits the text input to 30 chars.  (Specifically I'm looking at the "Alt. Phone" field here.)

I noticed this problem when using the webservices API, which (I think) always interacts with both customer schemas.  In the real world, I used API to "get" a member record which had a full 30-char value for alt phone, and it returned the 30-char value.  But when I tried to "post" the same data back to API, it failed.

In my one example so far, a reasonable fix is to edit the customer in question and be done with it.  But then I'd like to add a 20-char limit on the text input to avoid it in the future.  Or perhaps better is to grow `Customers.phone` to 30 chars?  Both seem simple enough but latter would require schema upgrade.

Happy to submit a PR but thought I should feel it out first.  See also #882 for previous related background esp. since my real-world involved alt phone?

**Comment by gohanman** [comment]
In general when a character limit comes up, I think unless there's a concrete, practical reason to impose a limit it might as well expand out to 255. And I don't see any particular reason for a low cap here.
