### ISSUE TITLE
POS auto-popup when member selected?

### ISSUE THREAD

**Issue by lgedgar** [CORE-POS/IS4C#1203]
* Version of CORE? latest

* Issue with Office, Lane, or both? Lane

* Is this [mostly] a bug report, feature request, or question? question

Someone wants a popup to display automatically for cashier, after a member is chosen, if that account is behind on equity.

I see [Customer Specific Notifications](https://github.com/CORE-POS/IS4C/wiki/Customer-Specific-Notifications) but they're asking for a more interactive popup with payment options, similar to what happens in [EquityCheck](https://github.com/CORE-POS/IS4C/blob/9203b252fad908d3413cd958e7a04bf23decf251/pos/is4c-nf/parser/parse/EquityCheck.php#L59).

Anyway hadn't found anything like that yet and just wanted to double-check here.  Am I just missing it or is "auto popup on member selection" not a thing?

**Comment by gohanman** [comment]
There isn't anything like that currently. That documentation is a bit out of date; there's also a notification type `callback` that can run some code when a specific customer is selected. Currently it can only modify the transaction and not redirect to another page to display a message/options, but it seems like a fairly small adjustment to allow for a redirect.

**Comment by lgedgar** [comment]
Okay thanks, will come back to it if time/interest allow.  Under the gun at the moment so will just do a cashier-initiated popup.
