### ISSUE TITLE
Help understanding CashBack

### ISSUE THREAD

**Issue by jamesTSCoop** [CORE-POS/IS4C#1224]
* Version of CORE?

* Issue with Office, Lane, or both?

* Is this [mostly] a bug report, feature request, or question?

**Comment by jamesTSCoop** [comment]
Hi Andy, I canvassed Eric and Lance to see if any of us knew how CashBack is indicated in POS, and we seem to think it's only ever offered as an option on the card terminal.  However I notice that there's code in Datacap that checks to see if CashBack is present and adds it to the requested amount if so.  This implied to me that there might be elsewhere that cashback is indicated, by maybe the cashier typing "2000CB" or something but I can't find anything.  Since I need to sort it for DC Direct (which can do either POS supplied cashback amount or prompt the cardholder) I wanted to check and see if there is in fact a non-terminal way of indicating CashBack that I want to make sure is supported so that I can test it.  The code seems pretty clear how to proceed if there is a cashback amount set.  Thanks!!

**Comment by gohanman** [comment]
We never offered cashback, so I don't know exactly how far this got at other places, but it looks to me like the idea was when prompted to confirm the amount either:

* Enter e.g. "2000CA" to set the cashback amount (and re-use the Cash key)
* Enter an amount greater than the amount due and the difference is assumed to be cash back

**Comment by jamesTSCoop** [comment]
Cool, thanks!
