### ISSUE TITLE
Lane session hangs when printer offline

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#321]
At the Techhub conference call today (@DavidHermann) the issue described but not resolved on the forum [Printer error and finishing transaction](http://www.techhub.coop/forum/viewtopic.php?f=18&t=1901&p=9280#p9280) came up again. Quoting from there:

>Re: Printer error and finishing transaction
>Postby andy_wfc » Fri Jan 25, 2013 11:51 am
>There are two intertwined issues here. The relevant script is ajax-callbacks/ajax-end.php which prints the receipt, clears out ltt, and increments the transaction number. When the printer fails while PHP is writing to it (or trying to) these are the issues that arise:

>1. ajax-end.php hangs at that line
>This means nothing beyond that line executes. There may be some operating system differences in behavior but my experience is it will block there forever until Apache restarts or the printer becomes available. Any timeouts or execution time limits in PHP's configuration are ignored. For me, calling is_writable() on the device file also blocks indefinitely if I try to preemptively check whether the printer is available.

>2. The session might lock
>Because ajax-end.php has not completed, any subsequent actions or pages that use $CORE_LOCAL (i.e., everything) might hang. Apache keeps all the subsequent requests queued up until ajax-end.php completes and unlocks the session file. The pending requests still run once the printer clears so I expect that's why items eventually show up on screen. I've found the Apache configuration is relevant here. If I'm using mod_php then the session will lock up; if I have PHP configured as CGI it won't.

>I've tried to move everything in ajax-end.php ahead of writing to the printer so ltt still clears and trans_no still increments but that doesn't address the session locking issue. Writing the receipt to a temporary file and then using fork() or register_shutdown_function() to print it in a separate process might avoid the session lock but I don't know how we'd relay a message back to the cashier to show something went wrong.

I wonder if something like this might make it possible to alert the cashier:
1. A cronjob to uses PHP is_writable() or similar at a defined interval (1 min, 5 mins) and on success puts a timestamp in a file or touches it.
2. ajax-end.php checks that file and if the timestamp is stale alerts the cashier before printing.

**Comment by gohanman** [comment]
There's still an issue here but I'm not convinced adding a driver layer between PHP and the printer is a better approach than managing the session lock more carefully. Certainly in 2 years there has been any real movement towards the suggested approach.
