### ISSUE TITLE
Documentation questions

### ISSUE THREAD

**Issue by chaploeb** [CORE-POS/IS4C#355]
I see there is documentation in the CORE tree.  Is there a place online where one can see the most current documentation?  I've been using http://is4c.gohanman.com/git/IS4C/documentation/ which I've now realized is substantially behind the documentation that's actually checked into the source tree.

I can certainly create a local site with the current docs, but I'm wondering if we have, or should have, a process that automatically pushes the most current docs out somewhere on the web.  It would be helpful for bootstrapping.

I also realize there is separate documentation at techhub.coop/media.  Any comments on currentness of wiki docs vs source tree docs?  Should we maybe pick one or the other going forward?

I ask this in preparation for likely submitting a significant number of doc patches over the next few weeks...

**Comment by gohanman** [comment]
I think this decision is mostly settled. There's work to do writing documentation but that never ends so I don't think the issue needs to hang around as open forever.
