### ISSUE TITLE
Pushing parameters to lanes

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#428]
I have a server-side plugin in which department numbers are referred to that then need to appear in the lane-side `SpecialDeptMap` config parameter.  It is conceptually attractive to have a `core_op.parameters` table on Fannie that the plugin would update and then use `$BasicModel->pushToLanes()` but the fannie-side model and table don't seem to exist (there is a model lane-side: `lib/models/op/ParmetersModel.php`).

After updating the lanes the session would have to be restarted for `CoreState::loadParams()` to get the new value.  But as I understand per #363 it will be overwritten by the now-old value in `ini.php`.

I'm just wondering at this point if there's a reason not to set this up and try to figure out a way to keep the new value from being overwritten from `ini.php`.

My version of fannie is a bit old so this may have already been addressed or dealt with a different way.

**Comment by gohanman** [comment]
I think this is mostly covered by #434.

The next release *will* move existing ini.php values into opdata.parameters *and* remove them from ini.php. Some migration notes need to go in the other issue thread, but centralized management should be ready to go once all the settings move.
