### ISSUE TITLE
Meaning of Discount in MemType module

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#431]
The value labelled Discount in the current Membership editor Membership Type module ```MemType.php``` is ```custdata.Discount```.  Since my coop uses the Mem type table feature ```(opdata.parameters.param_key.useMemTypeTable = 1)``` (prefer the current value of memtype.discount to custdata.Discount) I want the editor to show what the member's current discount is.  I'm a bit behind on Fannie releases but plan to upgrade soon.  Is there now, or expected to be, a Fannie-side parameters table where I could check the value of:
```param_value WHERE param_key ='useMemTypeTable' AND store_id =0 AND lane_id =0```
to decide whether to use ```custdata.Discount``` or the appropriate ```memtype.discount``` should be displayed?

**Comment by gohanman** [comment]
27def6101369fa45f4a6e1444a5e2ac5876c390a
