### ISSUE TITLE
Agenda Ideas 2015-01-09

### ISSUE THREAD

**Issue by gohanman** [CORE-POS/IS4C#433]
### Configuration
Sort of two subjects. First, is it worth trying to actively convert existing configurations by trimming lane settings out of ini.php and pushing them into the parameters table (#428)? Standardizing where different settings live would be a plus.

Second, I've been kicking around the idea of replacing the PHP configuration files for both Fannie and POS with something not-PHP like JSON or YAML. The main upside would be that because file isn't executing as code an error in the file can't crash the whole process. On the lane side it would also be simpler to manage which settings from ini.json or ini.yml get used without overwriting parameters. The C# hardware driver might be able to tie into the same configuration, too, instead of having a separate ports.conf.

### Dashboard / Notifications / Error Reporting
Old(ish) issues #369 and #370. What kind of things belong on a dashboard for system status? What events should be able to trigger notifications? What would need to be scrubbed out for anonymization to go forward with the "phones home" idea where installs can report error logs upstream?

I think reducing the number of logs could be useful. Having two separate logs for PHP errors and SQL errors just means checking two places. I don't know if that's just a single log, or an error log for PHP, SQL, and Task errors with a separate log for Task non-error-related output. I lean towards just the one log with a standardized, grep-able format. A mechanism that lets lanes ship their log(s) to Fannie could centralize monitoring even further. Following some kind of standard (syslog?) might give more flexibility for people not using Fannie or simply having a more comprehensive org-wide log gathering setup.

**Comment by gohanman** [comment]
Configuration: no real objections voiced to migrated more strongly towards parameters, exploring alternate markup setups.

Dashboard etc:
Synchronizing tables to the lane need notifications. Ditto for transaction archiving. Not as much consensus and changing logging. Whether or not PHP errors belong with logical, *purposely* generated log entries is not clear.

Searching on the lane & duplicate items:
Show linked / likecoded items in search results as one item. At minimum needs likecode present on lane.

Tracking scan source in item record. Possible? Can it be handled in the driver/pos communication?

More multi-store discussions in a future call especially regarding the Wedge's 2nd store launch.

**Comment by jdpurdyvi** [comment]
While it's a bit crude, I've had some success using custom error logging to generate "application" level logs. This works well when you have a mixed language environment. And also with merging in PHP CLI errors. It's certainly not using any syslog standards, but it's sufficient for me to grep through.

An PHP example for an in-house application named Taura - 
```php
error_log("Taura error #0079: load given to UpdateOrder is too long. ".$args['load']."\n", 3, '/var/log/taura.log');
```
Doing this helps separate application errors from language/syntax errors. Although I do see some value in using PHP's E_USER_ERROR/WARNING/NOTICE levels, becuase then we could leverage PHP's platform independent logging.

**Comment by gohanman** [comment]
I like [PSR-3](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md) as a starting point. Eight log levels might be a *bit* excessive, but it's a very standard set (debug, info, notice, warning, error, critical, alert, emergency).

I don't think PHP's terms map directly to the levels. I'd send all language/syntax messages to "debug". It's information relevant to a developer working on the application as opposed to an end user. Mapping particular log level(s) to particular file(s) should be able to cope with everyone's preferences for what gets combined vs what stays separate.

So something like this:
```php
$logger = new FannieLogger();
$logger->log('info', 'server on fire');
// or equivalently
$logger->info('server on fire');
```
logs something like this:
```
Jan 11 11:09:32 alkan fannie[19282]: (info) server on fire
```
