### ISSUE TITLE
Configuration Refactoring

### ISSUE THREAD

**Issue by gohanman** [CORE-POS/IS4C#434]
See #433 

I'm moving forward with plans to support markup-based configurations (as opposed to executing code) as well as to better manage the lane-side split between centrally manageable settings in the parameters table and minimal required settings in a local configuration file. To start with, I'm building a wrapper class on top of the configuration files so the rest of the application doesn't interact with it directly & doesn't need to know how it's formatted.

Lane examples:
```php
/* Old way */
function foo()
{
    global $CORE_LOCAL;
    return $CORE_LOCAL->get('bar');
}
/* New way */
function foo()
{
    return CoreLocal::get('bar');
}
```
Coincidentally, this eliminates all mistakes related to forgetting to use the "global" keyword.

Fannie examples:
```php
/* Old way */
function foo()
{
    global $FANNIE_ROOT;
    return $FANNIE_ROOT . '/bar';
}
/* New way (longest) */
function foo()
{
    $config = FannieConfig::factory();
    return $config->get('FANNIE_ROOT') . '/bar';
}
/* New way (omit FANNIE_) */
function foo()
{
    $config = FannieConfig::factory();
    return $config->get('ROOT') . '/bar';
}
/* New way (most contexts) */
function foo()
{
    return $this->config->get('ROOT') . '/bar';
}
```
I made the "FANNIE_" prefix optional since most (perhaps even all) settings include it. Being able to leave it out saves keystrokes. Classes that inherit from FanniePage or FannieTask have a $config property that is automatically initialized.

Everything is still backwards compatible at this point so either approach works. The lane is the higher priority at the moment. Migrating settings cleanly into the parameters table is more important than supporting JSON/YAML/whatever files.

**Comment by joelbrock** [comment]
will there be either/or support for ini.php-based installs?  Or even better, auto-generating of the configs text file based on ini / opdata.parameters?

Just concerned about the path-to-upgrade for existing installations....

**Comment by gohanman** [comment]
For ini.php vs opdata.parameters, the goal would be to identify a setting in ini.php, write it out to opdata.parameters, then remove it from ini.php.

For ini.php vs ini.json, I was thinking either/or. Load whatever's present.

**Comment by gohanman** [comment]
I started testing parts of the new lane setup today. I have a mix of CoreLocal class and global $CORE_LOCAL variable and they seem to be inter-operating just fine.

I didn't go all-out on migrating ini.php to opdata.parameters [yet]. I let it write settings from ini.php into opdata.parameters and that worked well but I did not let it delete things from ini.php. I'll try that on the next lane I update.

**Comment by gohanman** [comment]
I've now got a lane running after a successful settings migration - ini.php is mostly empty with everything else in opdata.parameters. A few notes on the process so I don't forget (should also go into release notes):

* Migration occurs in the top-level login.php script. I think in most configurations this would mean opening a new browser window or using the "home" button.
* Settings are written to opdata.parameters with lane_id equal to that lane's number. To create a set of global settings, copy that table to the server and update lane_id to zero.
* Settings from opdata.parameters are reloaded every time gui-modules/login2.php runs. If you're updating settings remotely that means they'll take effect the next the cashier logs out & back in.

**Comment by gohanman** [comment]
This stuff is in 1.1.0
