### ISSUE TITLE
Disallow Equity payments by memType = 0

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#437]
I kind of thought this was already built in.  But it doesnt appear to be the case.

I added `|| CoreLocal::get("memtype") == 0` into the `if` statement of the handle function of the EquityWarnDept subclass to get the desired behavior.  Is this worth including in the codebase?  Reasons not to?

**Comment by gohanman** [comment]
#361

Set departments.memberOnly = 1 for equity department(s)

**Comment by gohanman** [comment]
Addressed?

**Comment by joelbrock** [comment]
yes, addressed.  thanQ.
