### ISSUE TITLE
Agenda & Minutes 2015-01-23

### ISSUE THREAD

**Issue by gohanman** [CORE-POS/IS4C#438]
Here's a more off the wall topic:

I'm starting to add some clickable (and more importantly, touchable on a touchscreen) elements to POS. I don't foresee a keyboard-less POS or anything since entering letters & numbers would be horrifically slow, but where possible I'd like to give both options: press a key OR click a button.

Here's an error dialog example - coincidentally, you don't **have** to press clear and then subtotal. You can just press subtotal while the error is displayed. That was a surprise to me but it saves a keystroke.
![dialog1](https://cloud.githubusercontent.com/assets/426966/5877177/634f6ae4-a2e3-11e4-8660-130e746c1ae5.PNG)

Here's the member list with a bunch of buttons. You can, of course, click the list itself too but I think bigger targets work better on an actual touchscreen.
![memlistpage](https://cloud.githubusercontent.com/assets/426966/5877176/634e029e-a2e3-11e4-99d0-8cd887eb8aca.PNG)

Does this seem like a generally sensible approach? The alternative would be an entirely separate interface for touch. What I like about this, besides not reinventing every page from scratch, is that everybody could mix and match what's available on the keyboard and what isn't.

**Comment by gohanman** [comment]
Options to separate out savings into separate lines

**Comment by gohanman** [comment]
Implementation of combined vs separate savings line on receipt setting
b767b2863fab773451d4d3a59f10653181ef2622

**Comment by DavidHermann** [comment]
Cool!  Thanks Andy.

 

David Hermann

Database Programmer

Harvest Co-op Markets

(617) 874-5134

dhermann@harvest.coop
