### ISSUE TITLE
Touchscreen UI Elements Discussion

### ISSUE THREAD

**Issue by gohanman** [CORE-POS/IS4C#439]
Continued from #433

For reference, here's the dialog screen:
![dialog1](https://cloud.githubusercontent.com/assets/426966/5877177/634f6ae4-a2e3-11e4-8660-130e746c1ae5.PNG)

And here's a revised version of the member list based on our discussions:
![revised memscreen](https://cloud.githubusercontent.com/assets/426966/5882051/bb10caca-a30b-11e4-9b7a-e092aedbb1b4.PNG)
The horizontal arrangement suggested by Jon definitely looks better to me with the arrows by the 
select box. The icons I came up with aren't great but I think the uniformly sized buttons help make the page look a lot cleaner.

Opinions on the call really ran the gamut from "no interest in touchscreen" to "get rid of the keyboard entirely". My approach thusfar has been to label buttons with:
* What they do
* What keyboard key you can press instead

This doesn't look as fancy as using icons for one or both, but sidesteps the problem of figuring out what an icon would be for "total" or "subtotal". Both keyboard and touchscreen interactions will work. A purely touchscreen mode would be easy via CSS. Adding this to the store's custom css should drop hide all the text in square bracks:
```css
button.pos-button span.smaller { display: none; }
```
A purely keyboard mode would actually be more difficult. The text on some of the buttons is important to convey what options are available. Simply removing the colored backgrounds doesn't cause much of an improvement. Rewriting the text on the fly to produce something closer to full sentences would be challenging. My current thinking is that the purely keyboard mode should only hide a subset of the buttons. In the examples, the up/down/page buttons would disappear but the other ones would stay. Fortunately, POS doesn't have too many different looking screens. These two examples cover a significant majority of situations.

The other main addition needed is some launcher buttons to get into deeper menus of functionality. Buttons that appear based on context are great, but having a button for every possible action at the "main" screen isn't feasible. This part has been around forever; I just adjusted the styling to be more in line with the buttons above. The launcher buttons would also disappear in pure keyboard mode.
![launcher buttons](https://cloud.githubusercontent.com/assets/426966/5882498/a3ca1eda-a30f-11e4-8414-bbc9b5907632.PNG)
![qkmenu](https://cloud.githubusercontent.com/assets/426966/5882543/0cbdd2b0-a310-11e4-9f0a-ffb1966f61e0.PNG)

**Comment by gohanman** [comment]
Bump.

This is kind of "speak now or hold your peace at least for a little while".

The next release is nearly ready and it's going to look pretty uniformly like the examples above. The up/down arrows on lists only appear if the touchscreen setting is specifically enabled, but the rectangular buttons are always present.

I think in general this is a UI improvement even without a touchscreen. The cashier's options, whether by click or by keyboard, are explicitly shown rather than just implied.

The CSS classes on the rectangular buttons are *also* consistent, so if you really hate them you can alter them or axe them entirely with the store CSS file.

**Comment by joelbrock** [comment]
Great stuff @gohanman "All power to your elbows!"

I'm still somewhat interested, or atleast curious about the hard/soft keyboard combo.  The NCR combo keyboard that alvin showed us is pretty decent option.
