### ISSUE TITLE
Cash Back notes

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#440]
This is mostly towards documentation of setting up Cash Back. (And checking that I have it right before implementing.)  Also a couple enhancements.

Cash back is accomplished at the lane by tendering an amount in excess of the amount due with a tender that will debit an account the member has at a bank: CK (cheque/check) or DC (debit card) and.  The excess is given to the member as you would give change from a Cash tender, and is labelled "Change" on receipts (something I would like to to be otherwise) and in the transaction record.

The handler for the tender must be one that allows tendering in excess of amount owed.  Generally, CheckTender supports this but CreditCardTender does not (because of the additional expense to the store). The handler is chosen at:
Lane Config > Extra > Tender Settings
Two other config options there can also affect handlers that allow cash back:
Allow members to write checks over purchase amount: Yes
Check over limit: $ 50

If you want to allow cash back on debit purchases, set (Map To) Debit Card to CheckTender.  The tender will retain its "DC" identity in transaction records but be subject to the Check rules, including allowing allowing cash back to members up to the stated amount.

You will also probably want to tick the "Tender Rept" boxes so the tender will appear in the Tender Report.

In DC transactions the cash back does not, in most agreements, add to the merchant's cost for using the service.  [Some encourage] (http://en.wikipedia.org/wiki/Debit_card_cashback) cash back because it rids the store of costly-to-process cash.

The field tenders.TenderCode, editable in the Admin tenders editor, affects how cash back appears on a tender report. If it is set to CA it will appear as positive values in the Cash Detail (if there is one):
```
                          C a s h
  ------------------------------------------------------
  Time      Lane    Trans #   Emp #   Mem #      Amount
  09:41 PM  1        3           62   484         10.00 [cash back]
  09:45 PM  1        4           62   484         10.00
  10:26 PM  1        6           62   484         20.00
  11:17 PM  1        7           62   484          3.01 [change for the tender below]
  11:17 PM  1        7           62   484        -10.00 [cash tender]
  11:22 PM  1        8           62   484         10.00
  11:25 PM  1        9           62   484         10.00
  ------------------------------------------------------
                                 Count: 7  Total: 53.01
```
The negative amounts are cash tenders.
In a Summary, the Cash Detail total appears as a negative
```
  NET Total:             78.88
  (Only: Cash, Cheque, Debit, Credit)

  CASH                  -53.01       7
...
```
indicating more cash went out than came in.

If TenderType is set to the same as TenderCode the cash back will appear in the Debit or Cheque Detail as positive amounts:
```
                    D e b i t   C a r d
The list includes items for all lanes.
  ------------------------------------------------------
  Time      Lane    Trans #   Emp #   Mem #      Amount
  09:41 PM  1        3           62   484         10.00 [cash back]
  09:41 PM  1        3           62   484        -13.49
  10:26 PM  1        6           62   484        -61.98
  10:26 PM  1        6           62   484         20.00 [cash back]
  ------------------------------------------------------
                                Count: 4  Total: -45.47

```
Summary:
```
  NET Total:             59.20
  (Only: Cash, Cheque, Debit, Credit)

  CASH                    0.00       0
  CHEQUE                  6.74       4
  VENDOR COUPON           0.00       0
  CREDIT CARD             6.99       1
  DEBIT CARD             45.47       4
```
This may seem to give a truer picture of the actual amount of goods purchased with Debit but is probably not the right thing to do for a Tender Report since does not tell you what should be in the till.

Re: TenderType, the internal docs in the table setup script `install/sql/op/tenders.php` say:
```
TenderType and TenderID are mostly ignored.
```
I think this should be changed in light of TenderType's role in cash back.

Another bugfix or enhancement would be to use the `tenders.ChangeMessage` value as a label on receipts for the cash back amount.

Finally, using a hyphen to connect the words in "check-over" would make the meaning of the term clearer.

**Comment by gohanman** [comment]
This looks pretty accurate to me.

Upstream the tender editor UI labels the TenderType column "Change Type" for accuracy. Actually using the ChangeMessage column is a perfectly reasonable request.

"Check-over" seems less clear to me (dictionary defines the hyphenated version as a synonym for "examine") but the line could stand to be rephrased. It may be possible to reduce those two settings down to a single one - i.e., a limit of 0 means members cannot write checks over.

I continue to **strongly** believe the correct solution for cash tender reports is "don't have one". Cash totals should be a separate, backend only report. If the cashier knows how much cash they're supposed to have and they're over, they can easily pocket the difference. That being said, you do have a third option of recording cashback as a separate code from both DC and CA.

The "member check over amount" functionality is member only (obviously). Simply using the default tender module would allow tender over for all customers albeit with any limit. Also, if using "Enable Check Franking", the CheckTender will prompt to insert the check into the printer for endorsement. I don't know that using CheckTender for debit is a good solution is all situations.

Finally, the CreditTender limit on over tendering has nothing to do with expense to the store. It eliminates roughly half of potential miskeys when cashiers are manually typing a tender amount (and the other half of miskeys which are less than the amount due are easier to fix since those won't end the transaction).

**Comment by gohanman** [comment]
Using tenders.ChangeMessage as the record's description field:
81d23e290456b6f795c3141f735454436365efaa

**Comment by flathat** [comment]
Thanks for enabling ChangeMessage. I like the look of it much better:
![cashback3](https://cloud.githubusercontent.com/assets/1131922/5928156/b497546e-a646-11e4-8093-9646d315d314.png)

I suggest the following for TendersModel::doc():

Instead of: "TenderType and TenderID are mostly ignored."
TenderType is the tender, a valid TenderCode, in which change is given if the amount tendered is more than the amount due.  It may be different than the Tender Code of the record being defined, for example CA for cash back from a payment by check or debit card.

Instead of: "ChangeMessage, MinAmount, MaxAmount, and MaxRefund all do exactly what they sound like."
which is not obvious to me the way the others are:
ChangeMessage is the label on the receipt for change (or cash back) provided and may need to agree with TenderType. It also appears in the description field of transaction records.

I don't see the harm of a little verbosity since the situation and the handling of it is not all that easy to understand.

"check-over" here is short for "check over purchase amount", meant in an idiomatic sense to clarify the relationship of the words in "check over limit" since it isn't obvious, to me anyway.  Perhaps we need an acronym COPA, or TOPA (tender over purchase amount) since this is about a mix of currencies in a transaction. Then "TOPA limit" is clear. And we could also have a dictionary of acronyms. I like the idea of a single parameter: 0 means not allowed.  Maybe make it per-tender and put it in the tenders table.  I can see the rules being different for checks (which are rarely used in Toronto) and involve risk to the store, and debit (which is used a great deal here) and involves no risk.

**Comment by gohanman** [comment]
I like the idea of putting an over-tender limit directly in the tenders table. That should streamline configuration in a lot of cases. tenders.ChangeLimit? tenders.OverAmoutDueLimit? tenders.OverPurchaseAmountLimit?

I would probably leave a separate setting for "member-only check over purchase amount". As you note there's a different level of risk there where it may make sense to offer the service only to members. All the other cases seem straightforward to me. A limit defined in the tenders table would be there simply to ensure cashiers' input falls in an acceptable range.

I agree that verbosity in documentation would be good. I'm not terse on purpose; it's more a consequence of trying to get a bunch of documentation churned out in a short time. Going back with a fresh set of eyes to edit & revise is a very, very good thing.

**Comment by gohanman** [comment]
I tried to capture much of this in the [wiki](https://github.com/CORE-POS/IS4C/wiki/POS-Tenders-Table-and-Records)
