### ISSUE TITLE
Ignore scans after tare entry

### ISSUE THREAD

**Issue by gohanman** [CORE-POS/IS4C#441]
I want an option to ignore scanned barcodes immediately after entering a tare weight. Scanning would resume after a PLU is keyed and the item is weighed.

The main use case would be:
* Customer provides their own bulk container that happens to have a barcode. In setting the container on the scale, barcode accidentally scans. POS produces an "item not found" error or potentially worse recognizes the barcode and adds an incorrect item to the transaction.

Depending on the setup (automatic vs manual tares & scale sensitivity) it may also be helpful with by-weight produce items that have a barcode on their sticker or packaging.

**Comment by joelbrock** [comment]
:+1:

**Comment by gohanman** [comment]
Initial implementation: bf548db66420cb97e5d5dfc2bdb44bc769996548, #446

Should probably have a setting so this behavior can be toggled on or off.

**Comment by gohanman** [comment]
I've got this up and running. It mostly works as expected. Items can still accidentally scan when removing them from the scale. I'm very tempted to just leave that alone and call it improved but not perfect. Any kind of timing rule to wait X after weighing an item could artificially limit overall cashier speed.
