### ISSUE TITLE
Install fails - composer - The requested package gohanman/sql-manager could not be found in any version

### ISSUE THREAD

**Issue by POSBuild** [CORE-POS/IS4C#444]
When running `composer update` I get the following:

> Your requirements could not be resolved to an installable set of packages.

>  Problem 1
>    - The requested package gohanman/sql-manager could not be found in any version, there may be a typo in the package name.

> Potential causes:
>  - A typo in the package name
>  - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.`

Has something moved?

**Comment by gohanman** [comment]
Yep. The package name changed and I forgot to update the composer file. e878c873142375d2e118ecfa0c1d6c47800c8842 (also on dev branch 6e0e86e8a3bce4a90c1c2beb43fc05281b9fe27a)

For what it's worth, the project doesn't use composer heavily. All the packages are optional and everything should work fine without them.

**Comment by POSBuild** [comment]
@gohanman thanks for the quick turn around
