### ISSUE TITLE
Distinguish between scanned and keyed items

### ISSUE THREAD

**Issue by gohanman** [CORE-POS/IS4C#446]
From agenda #433. Distinguish between items that are added to a transaction via scanner scale vs items that are hand-keyed.

Updating the hardware driver to add a prefix or suffix that POS can recognize is probably simplest. How to capture the information in dtransactions. I believe on records with trans_type='I' (item) the trans_subtype field is always blank. That may be safe place to add a secondary scan/key indicator without disrupting existing code.

**Comment by gohanman** [comment]
This actually related to #441 too.

After looking into this a bit more, I think that 0XA will work well as a prefix. The reason it will work well is
that PHP considers both these values integers:
0006532281232
0XA0006532281232

That means the prefix won't create issues for preparsers (refund, tax shift, quantity multiplier, etc) since the value looks like a number. When it gets to the actual UPC handler I can simply strip off the prefix.

Adding the prefix in javascript works so far in my limited testing - that saves needing to recompile the hardware driver. bf548db66420cb97e5d5dfc2bdb44bc769996548

I'm not yet saving any information about whether an item was keyed or scanned in the transaction record. I'm just trying to distinguish between the two for the sake of #441.

**Comment by DavidHermann** [comment]
Slick!  (The prefix can be defined as a constant so that it doesn't get hardcoded in multiple places, right?)

**Comment by gohanman** [comment]
Not quite. It'd probably be easier to define twice - once in javascript and once in PHP. But minimizing places it's hardcoded is definitely a good idea.

**Comment by gohanman** [comment]
The trans_subtype column seems to be uniformly blank on item (trans_type I) records so that seem like a sensible enough place to indicate a scanned item. I use SS (scanner-scale). I also made the prefix a proper constant.
a5ae80f04d2c10438541c73bc78d4cc9c74531c9

**Comment by DavidHermann** [comment]
It looks like you're keeping trans_subtype=blank for keyed items.  Would it be better to have a second explicit non-blank subtype?

Could a second UPC prefix and third subtype be used for dedicated keyboard keys?  This would distinguish between the cashier (a) keying 4,0,1,1 and (b) pressing the "Bananas" key.

**Comment by gohanman** [comment]
My thinking with leaving it blank was that I don't know for certain it was keyed; I just know it didn't come through the scale.

There's 0xB, 0xC, 0xD, 0xE, and 0xF remaining (unless we go to longer prefixes). I could certainly see having one for dedicated keys if a store wants to track that - it might yield a bunch of insight into which items deserve dedicated keys.

The other entry method I could potentially see a case for tracking by prefix is a USB-HID scanner. Depending on the setup there may be value in knowing how much the scanner-scale is used vs the secondary device.

The catch with both the keyboard and the USB device is that tracking the inputs that are really keyed in one number at a time is contingent on how you've configured your hardware. I'd rather have blank or a "generic" subtype that call it out specifically as keyed. It's up to the store to determine what all falls in the generic category.

**Comment by jonkeim** [comment]
My vote is for a generic subtype, rather than blank.  Better to distinguish between records generated before & after scan-source-logging was put into use.

A friend of mine had to distinguish between hand-keyed entry and keyboard wedge-scanned bar codes in a web app, so she used speed of entry.  Something like:

if (time between first keystroke and [enter]) < (some fraction of a second) then { used scanner wedge }

**Comment by gohanman** [comment]
Follow-up: dd6f1d4f81cbbd09c5fc513c2734ec97f541847e

Generic subtype is **NA** (for not applicable or n/a; I couldn't think of a good two letter code for generic or unknown)

Prefix 0XA is subtype **SS* (scanner-scale)

Prefix 0XB is subtype **KB** (programmed keyboard key)

Prefix 0XC is subtype **HI** (often an HID device in modern usage)

**Comment by gohanman** [comment]
I've got this running in production now. No problems of note (yet). Should be in the next release.
