### ISSUE TITLE
Reduce CPU usage for Scanner-scale driver under linux

### ISSUE THREAD

**Issue by gohanman** [CORE-POS/IS4C#447]
From agenda #442. Driver reported to sit more or less constantly at 100%. Most likely effectively spin-locking on the read loop. Need to ensure one way or another that timeouts between failed reads actually occur.

**Comment by joelbrock** [comment]
Stumbled back across this and wondering if this factors into any of the recent scanner scale issues witnessed at RVM, ACG, others.  At ACG I definitely saw mono running upwards of 100% CPU

**Comment by gohanman** [comment]
I tried reproducing this today and I can't. The highest I've seen the CPU usage go in testing is 0.3%. This is CentOS rather than Ubuntu since that's what I have handy, but whatever's going on isn't strictly a mono or Linux issue.

This is more specifically what I'm running for mono if it's a useful point of comparision:
```
$ mono --version
Mono JIT compiler version 3.2.8 (tarball Mon Mar 16 15:06:46 CDT 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen
```

Test scale is an 8500 omega. It's plugged directly into the serial port as opposed to using a USB adapter.

I did notice that the rate limiter is not working as intended (although that's my theoretical solution to the complete freeze / beep of death, not CPU usage): 0efd72f916a9b49627f9fdf4fcce084362918d7f

**Comment by gohanman** [comment]
Other possible remedies - although I'll some grant this is a more experimental direction and trying to alleviate load on the browser & Apache by eliminating javascript polling:

### Use RabbitMQ
1. Download, install, and start RabbitMQ service
2. Enable RabbitMQ web-stomp plugin
3. Download official .NET binary
4. Drop the RabbitMQ.Client.dll file into NewMagellan and recompile (yes, this does work in linux+mono)
5. See what goes haywire

### Use node-webkit
1. Download and install node-webkit
2. [Probably] update and rebuild driver so it supports the full_udp command
3. Go to https://github.com/CORE-POS/IS4C/tree/master/pos/app
4. Run: nw .
5. See what goes haywire

### Use nginx instead of Apache
Unlike the other options, it's very unlikely that anything will go wrong. It is by almost every conceivable metric a better-performing web server. It may well also perform better when mono is tying up the CPU excessively.

**Comment by joelbrock** [comment]
Thanks @gohanman.  Tinkering now on my testlane.  A couple things pop up.

__RabbitMQ__ installed
1. `$ sudo apt-get install rabbitmq-server`
2. `$ rabbitmq-plugins enable rabbitmq_web_stomp`
3. [.NET dependencies installed](http://dotnet.readthedocs.org/en/latest/getting-started/installing-core-linux.html)
4. re-compile fails until i edit [Magellan.cs:118](https://github.com/CORE-POS/IS4C/blob/master/pos/is4c-nf/scale-drivers/drivers/NewMagellan/Magellan.cs#L118) to read: `rabbit_channel.QueueDeclare("core-pos");`
5. Now `$ rabbitmqctl list_queues` shows a "core-pos" queue
6. Now what?  I actually have no idea where to go from here.....

__Other things:__   When i run pos.exe via posdriver-sph-debian i see mono running at btwn 99 and 105% of CPU.  _However_ if i manually run it via `$ sudo mono pos.exe -v` then the mono process hovers around 0.7% of CPU.

This makes me wonder what the heck posdriver-sph-debian is doing?

**Comment by gohanman** [comment]
I've never used the .NET dependency you linked. I just downloaded the .NET client from here: https://www.rabbitmq.com/download.html. In any event, there's no configuration in POS at all. It checks for a RabbitMQ server listening on port 15674 and if it finds one sends an "mq_up" command to the driver to switch communication modes.

I have no idea what weirdness the init script is causing. Nothing stands out to me although I don't think I wrote that one.

**Comment by gohanman** [comment]
Well, this is the CPU spike issue: 75a813ff3afe53a290a59219b0b627408f79c89c

**Comment by joelbrock** [comment]
That does seem to address the CPU usage issue on my end...

**Comment by gohanman** [comment]
I think this makes just a hair more sense although the performance difference ought to be negligible.
65459809aa3b06e3fc3479ab1206c11866508787

The basic issue is really rather dumb to have hung around this long. The main thread of the driver was using Console.ReadLine() to effectively wait forever rather than exit. In theory someone could manually enter driver commands via STDIN but no one really did that. In a detached console, mono handles STDIN strangely and ReadLine() returns instantly creating an infinite loop - even if you provide a STDIN that will never include a newline character, e.g.:
```
mono pos.exe < /dev/null &> /path/to/log
```

I think the issue is effectively solved and could be interim-addressed without a single code update by simply not backgrounding the driver. Replacing the browser icon/launcher/whatever with a script that does something like this would probably work:
```
#/bin/sh
/usr/bin/firefox &
sudo mono /path/to/pos.exe &> /path/to/log
```

For the semi-unrelated stuff discussed here, I like the node-webkit solution a bit better than the RabbitMQ solution - #513 not withstanding. Having the message broker attached directly to the browser rather than adding a third service between the driver and browser seems advantageous as does having fine control over exactly what webkit/chromium version is running. But if the reduced CPU usage addresses current issues I see no reason to jump onto more radical changes immediately.

On the other hand, I do think using nginx instead of Apache for linux installs should probably be the default recommendation for both lane-side and server-side.
