### ISSUE TITLE
doxy update for 1.1.0 interrupted?

### ISSUE THREAD

**Issue by jonkeim** [CORE-POS/IS4C#449]
documentation/doxy/output/fannie/html/ seems to be missing about 2,300 files in the master branch.  Did the update for 1.1.0 get interrupted?

**Comment by gohanman** [comment]
Related to these?
c79ba1bd74647ac802bdded0e958a3ed6521c2ad
318472a08a3b4df2d905ae669a1ce32df0f88b46

I rebuilt doxygen to remove references to non-CORE code (mostly ADOdb) and to get rid of old files. Running doxygen and just adding the result doesn't get rid of files that no longer apply.

**Comment by jonkeim** [comment]
Specifically I was looking for class_basic_model.html, which I thought was custom to CORE.  It's present in the 1.0.0 branch (https://github.com/CORE-POS/IS4C/blob/1.0.0-2014.12.04/documentation/doxy/output/fannie/html/class_basic_model.html), but 404's in master (https://github.com/CORE-POS/IS4C/blob/master/documentation/doxy/output/fannie/html/class_basic_model.html)

**Comment by gohanman** [comment]
OK, I'm seeing that too. Unfortunately, re-running doxygen doesn't help. As far as I can tell, there's a bug of some kind in doxygen's code parsing causing it to claim the entire file isn't documented when all the requisite comments are still there.

**Comment by jonkeim** [comment]
Did some testing.  My steps, for sanity checking:

cd {git root}
git fetch origin master
git checkout origin/master
mv documentation/doxy/output/fannie/html documentation/doxy/output/fannie/html_old
mkdir documentation/doxy/output/fannie/html
{visually confirm that EXCLUDE directives in fannie.doxyfile match between GitHub & Local}
doxygen documentation/doxy/config/fannie.doxyfile

html_old/ contains 136 items.  html/ now contains 2,468 items.  Diffed the two directories, nothing too instructive in what /is/ common between the two.  There are a surprising number of files in html_old/ that aren't in the newly generated html/, however.

Checked out Ypsilanti/Master (appx. == to CORE-POS/IS4C at 0.9.13-2014-04-30).  output/fannie/html now contains 1,361 items.  Diffing /this/ directory & the one I generated w/ the fresh doxygen run does show significant churn in classes documented, so the EXCLUDE directives definitely cleaned up some stuff.

I'm running Doxygen 1.8.6-2 on Mint 17 w/ latest updates.

Probably unrelated, but https://github.com/CORE-POS/IS4C/blob/master/documentation/doxy/config/fannie.doxyfile#L696 seems to duplicate https://github.com/CORE-POS/IS4C/blob/master/documentation/doxy/config/fannie.doxyfile#L710

(...incidentally, ncurses upon Firefox for binding ^w to "close tab" instead of "erase word".)

**Comment by gohanman** [comment]
I'm pretty sure the EXCLUDE doesn't work but the EXCLUDE_PATTERNS do. I
never did figure out why.

I'll double check what version I'm running. I imagine different doxygen
version would cause even more discrepancies and make it harder to tell
what's common and what's different.

**Comment by gohanman** [comment]
I re-ran doxygen w/ 1.8.4. That was the newest version I could build without updating a bunch of other stuff. The whole HTML theme changes so that may account for much of the difference.

Beware this commit may produce a massive, browser-hanging diff.
70b582c2c35f32d9f4cf631ea772d82cf96a5c99

**Comment by gohanman** [comment]
I think this is effectively fixed and the main takeaway is "don't use ancient versions of doxygen".
