### ISSUE TITLE
Scanner/scale upgrade advice?

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#450]
We are looking to replace our SL384's with newer Magellan models.  Any suggestions or cautions?  It seems that Magellan 8500 and 9500 are both no longer manufactured (have reached "end of life" and are not in [Datalogic's catalogue] (http://www.scanning2.datalogic.com/e-catalog/default.aspx)) but 830x, 840x and 8500Xt still are. However 8500's still appear in vendor catalogues, but are perhaps in fact Xt's.

The Xt offers "The Dual Interval Scale model offers more accurate weighing for smaller, high-priced items", which may be a good for very light things such as spices. 

Any news since #407 on use of USB interfaces?  RS232 still seems widely available.

AFAICT the difference between 8500 and 9500 is "EAS Electronic Article Surveillance Deactivation", de-magnetizing a tag.  Not something we need. 8500Xt may also have it.

We did well with refurbished (used) SL384's and will consider refurbished upgrades.  A somewhat separate topic and known to be controversial.  Any different in the 85xx* line?

Datalogic's newest non-tunnel model is [9800i] (http://www.scanning2.datalogic.com/e-catalog/ec-mg9800i.aspx) (and [video] (https://www.youtube.com/watch?v=Y2xO1ytQ_qU)) which uses digital camera, not laser, and can read QR and barcodes from customers' phones and has a customer-facing reader for this.

**Comment by gohanman** [comment]
#407 is still spot on. I've never had access to a USB one myself. I'm hesitant to say how much since the datasheet doesn't mention a USB device class. If it's HID like the terminals I've worked with then it's probably simple. If it's something else then I don't know enough to hazard a guess.

I've used 8500s, 8500 Omegas, and 8500 Xts. I've noticed no practical difference. I've found them completely interchangeable - unplug one model, plug in a different one, it'll keep working. Don't even have to change the cables.

The interface section on the 9800i datasheet is identical to the 8500Xt. I'm pretty sure that means it'll speak the same low level protocol and scanning/weighing will work with the single cable RS232 mode. But I'd make sure there's a solid return policy before buying one just in case.

I also wouldn't assume the customer-facing reader works - better to be pleasantly surprised then over promise and under deliver. If POS has to send commands to the scale to activate the reader, I don't know what those are. If it's always enabled or comes on automatically with some kind of proximity sensor, that would be easier to figure out.

**Comment by pierced** [comment]
Hi Eric,
      
      Most of our scanner scales are Magellan 8500's and we do have some
      8500XT models because that is all we could get at the time.  We do
      have issues with the 8500XT models where they stop scanning and
      weighing or sometimes just weighing at times.  When this happens
      our fix is to recycle the power on the scale and sometime the
      cashier needs to sign out and back in for it to start working
      again.  It would be great if someone could figure out why this
      happens.  I would be willing to ship one of these scales to
      someone for testing.  Although it is almost impossible to
      reproduce this behavior unless the scale is on a busy production
      lane.
      
      Thanks
    
    
    
      


-------------------------------- 
Don Pierce
Information Systems Manager
Harvest Co-op Markets
617-874-5123
--------------------------------

**Comment by roberski** [comment]
Don,

Remember when we did our install how we were having so many issues with our scales?
One of them was the exact issue you just described and I've never fully ditched it.
Do you know what error code is being displayed on the led next to the scanning lasers?
Anyway ours would happen for a coupe of reasons.
1) They were really picky about accepting calibration. Even when it seemed like it worked it hadn't always worked.
2) We don't use check stands at McC and the counter mounts we had put in were not well done so they were slightly unstable. (One of them you can still change the reading on it if you push the counter just so even after we have had it reinforced)
3) Cashiers were leaving light things on the scales for long periods of time. (Like their plu sheets) Which would cause the scales to freak out after awhile (a few hours).

We mitigated the issues by:
1) I recalibrate them until I think I got them right. We don't have an external display which means I'm just going by beeps so I'm not sure I had it right the first time.
2) We stabilized the counters, I also turned off or down a couple of the auto stabilization features (I would have to reread the programming manual to know which).
3) Got better management who was willing to train staff, trained staff.

I probably won't make the call but I do have a keen interest in this topic.

**Comment by roberski** [comment]
Oh and when I say never fully ditched I mean that it used to happen a coupe of times a week now it only happens every couple of months.

What we still have constant problems with is the reliability of our zero button. It works but it's really finicky. You have to put a heavy weight on it and remove it before it will actually zero.

**Comment by pierced** [comment]
Thanks Rowan.  I will let you know
      if I have any luck or have any questions.
    
    
    
      


-------------------------------- 
Don Pierce
Information Systems Manager
Harvest Co-op Markets
617-874-5123
--------------------------------

**Comment by pierced** [comment]
good to know!
    
    
    
      


-------------------------------- 
Don Pierce
Information Systems Manager
Harvest Co-op Markets
617-874-5123
--------------------------------

**Comment by joelbrock** [comment]
Avoid the 8500xt!  
I've worked with the Magellan SL384s, 8100s, 8300s, as well as the 8500xts.  I have seen this exact issue now in 3 different POS installations and **only** with the 8500xt.  It is a pattern that is impossible for me to ignore.  Avoid the 8500xt!
FWIW:  All the rest of them being equal, i favor the low-profile design of the 8300s.  They have a smaller, rounder scanner hood that i think makes them appear less bulky above the counter.

**Comment by pierced** [comment]
Hi Rowan,
      
      1) There is no error code displayed on the LED next to the
      scanning lasers while the 8500XT is in the state where it cannot
      weigh.  There is just a dot "."
      
      2)  When you speak of the "auto stablilization" are referring to
      the auto zeroing function of the scale?  I do not find anything in
      my manual about auto stabilization.
      
      Thanks
    
    
    
      


-------------------------------- 
Don Pierce
Information Systems Manager
Harvest Co-op Markets
617-874-5123
--------------------------------

**Comment by roberski** [comment]
I read it and I don’t see what I thought I used either. Weird.
I defiantly changed the auto zeroing but I didn’t think that was what fixed the failure problem. I really thought there was a setting that had something to do with stabilization but maybe I’m making that up.
I know I played with the Baud rate also but I don’t know if I ended up changing it premaritally or keeping it the same.

the “.” error code is "“3.3 V Present”  Which is a spectacularly uninformative error message. How often does it happen?
Our scan coordinator is out so I’m doing her job right now, I’ll try to look in to it more tomorrow.

**Comment by joelbrock** [comment]
>    2)  When you speak of the "auto stablilization" are referring to
      the auto zeroing function of the scale?  I do not find anything in
      my manual about auto stabilization.

older versions of the Magellan series had a programmable config, i want to say it was called "motion filter"?....  I have looked for this very thing in the 8500xt manual and it is gone.  Perhaps Datalogic has a more comprehensive programming guide than the manual readily available online? 

Note, if you do find such a thing, PLEASE SHARE!  THanx!

**Comment by gohanman** [comment]
I'm fairly certain the "dot" is always there. The corrective action for it in the manually says "If *not* lit, call tech support". I think having that light on just means the scale is receiving power at the correct voltage.

With a scale that will scan but will not weigh and will not respond to the zeroing button, I usually see:
* The dot/decimal point light on the segmented display
* A single dash/hyphen on the remote display.

The single dash does not correspond to any documented error code for any revision of the 8500. I've asked Datalogic about it before and never gotten a straight answer what it means. The closest match is the "- 0 -" error code which means a zeroing related problem.

The 8500/8500omega guide does have barcodes for "Scale Motion Level Filter" and "Scale Automatic Zeroing" where as the 8500xt guide does not. No idea whether those settings are actually gone in the XT or just no longer documented.

Both guides have something called "Scale Enforced Zero Return" that could be worth tinkering with. It's supposed to be disabled by default but it wouldn't hurt to double check.

**Comment by DasBoots** [comment]
It's interesting to note, but we have 2 Magellan 8400s (specifically 8405s) and have this issue with just one of them.  Currently looking at replacing it until we can get it to work more consistently.

**Comment by roberski** [comment]
It turns out I did use the barcode from the 8500 manual. for the motion level filter. It seems to have helped but maybe it actually did nothing.

**Comment by flathat** [comment]
Another facet of this selling very light, and in some cases very high-cost, things by weight. The illustration below is from a PDF about the 8500Xt, _Less Equals More with Magellan™ Scale Technology
A Guide to Dual Interval Weighing and Increased Profits at the Point-of-Sale_
which you can find by googling. The feature is not available on other models.
It says that in light-things mode the scale is twice as sensitive, to 0.005 lb instead of to 0.01 lb.
I'm curious about the "Minimum weight to sell" of 20 x interval, so with regular scales you don't attempt to distinguish less than 3.2 oz, or with small-interval less than 1.6 oz. That's still a lot of saffron.  I would expect this to be jurisdiction specific.  I'd not heard of it.  Does it apply where you are?  Is it observed?

![8500xt_intervals_031715_064206_pm](https://cloud.githubusercontent.com/assets/1131922/6699157/bd295090-ccd5-11e4-89f8-f8b365451c13.jpg)

**Comment by gohanman** [comment]
Based on everyone I've talked to, the rules vary **wildly** by jurisdiction.

My XTs don't actually report a weight to three decimal places - i.e., it'd never say 1.125 lb. Since the low-level serial protocol doesn't even include a decimal point I'm not sure how it would communicate variations in the number of decimal places to POS. As I understand it, the increased internal accuracy reduces rounding error in the two decimal place weight actually reported by the scale.

**Comment by gohanman** [comment]
Came across something kind of interesting today (github won't link FTP apparently so you'll have to cut&paste; sorry):
ftp://www.scansourcela.us/NCR%20Retail%20Systems%20Latin%20America/NCR%20Scanners/NCR%20Scanner%20Programmer%27s%20Guide.PDF

That's an **NCR** scale interface programming guide. As far as I can tell, the RS232 protocol is identical to what the Datalogic scales use. The Magellans use 0x53 (ASCII "S") as the optional prefix byte and 0xD (carriage return) as the optional terminator byte. But the rest of the documentation all looks spot on.

Number one, it's nice to actually **have** a formal document with this info. Number two, I suspect an NCR scale that supports RS232 could be made to work with CORE with minimal (or maybe even zero) effort.

Anybody got good sources for old POS hardware? I'm trying to track down a power supply for an NCR 7870 to actually try this out and see what happens.

**Comment by pierced** [comment]
you can try this place:
      
http://www.surplustraders.net/ncr-0068600416-power-supply-for-the-ncr-7870-ncr-7875-power-supplies.html
    
    
    
      


-------------------------------- 
Don Pierce
Information Systems Manager
Harvest Co-op Markets
617-874-5123
--------------------------------

**Comment by gohanman** [comment]
Housekeeping. This did lead me to notice the documentation was missing comprehensive info about supported hardware.
https://github.com/CORE-POS/IS4C/wiki/Supported-Hardware

**Comment by roberski** [comment]
I know this is long dead but I figured I should stop in and say that NCR 7875s and 7870's do both work once they are programmed properly to use normal RS-232 and have the proper prefix and terminator byte. I suspect that it would work with any 78XX model.

No driver code needed to be changed just finding the right parameters for the scales.
