### ISSUE TITLE
Agenda Idea for 2015-02-13 -- CORE-POS boot camp syllabus

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#451]
I've learned the POS (I'm talking only about the front end, cashier side) as I've needed to for particular fixes and additions but I find that a couple years on there are still a lot of cases where I don't know where to start to figure out how to change or do something.  So perhaps the time has come for a more systematic approach, some basic training that will pay off in many later instances.

How can one study and understand POS in a systematic way?  Below are some of the groupings of information that I see.  I want to fill the list, the Table of Contents or syllabus```*``` out and indicate an efficient path or paths through it.  There are some good (invaluable) sections in the existing documentation, but not a way to connect them.

Where to start will vary a bit depending on what you already know.

**Object Orientation.** This is a big one. If your brain is not already wired this way it takes some learning.
Classes and the variables and methods that belong to them: public, protected, private.  What is and isn't available from within a class.
Libraries: static methods that don't belong to a particular class.

How classes become available. The autoloader, where it looks, what does it make available and what it might not load and how to load those. What do you assume is available to you once it has run: it is a lot.

(In my pre-OO days I put everything for a system in one or two files which were comprehensive if unwieldy; now what is auto-loaded into the effective environment is spread over dozens of files.  One thing I've learned is how to use vim sessions to contain a list of the files that are pertinent to a specific thing, say the parent classes and several libraries, and open them all at once as a complete effective environment.)

**Plugins**  What becomes available, and what must not be left in a broken state, when a plugin is enabled. That a plugin can contain classes that would be in different places if in the main body of CORE-POS.

**AJAX.** How does it work (point to  but not repeat what is explained elsewhere), but more importantly for POS what things are implemented with it and why.  What techniques are generally used?  Helps for debugging transactions that are "in the background", don't have a screen to write to.

**Jason.** Briefly, what it is, less briefly why and how it is used here.

**HTML form submission** and other ways of sending information and changing context. Not an HTML 101 text, but the demands of POS involve several techniques, sometimes implemented in JavaScript.

**jQuery.** Not to repeat what has been done elsewhere, but point to description of how jQuery syntax maps to the Document Object and what JavaScript it is shorthand for. Point to external resources, explain any POS characteristic/idiomatic uses.

**Particular devices**, especially the scanner/scale. Perhaps a subject unto itself.

**The main subdirectories of pos/is4c-nf/**, what is in them, why are they grouped that way, what to expect to find in each:
- parser-class-lib
- lib (has become so deep)
- gui-modules
- gui-class-lib
- ajax-callbacks
- plugins

One of the key mechanisms I have grasped is the Parser Classes, how POS examines the string typed, scanned or buttoned into the main input box and decides how to act on it. This may be the, or a, good way to organize a systematic study: beginning from login, type something and follow what happens and how it is done.

The parser classes invoke code from the libraries.  I have a harder time following that, or finding exactly what is being executed.  Perhaps some basic understanding is missing.

On of the unproductive things I've done is to start studying a piece of code in a library, perhaps what clearly did the thing of interest, and not be able to understand how it was invoked.

**What is the session?**  How is $CORE_LOCAL initialized and how/at-what-point is it reset or refreshed? When are the vars gotten from ini.php/opdata.parameters?

**The HTML page that is the POS screen** How is it organized?  What is going on as each line is added.

**"popup" or "overlay" pages** How do they work? How does resuming the flow of the transaction work?  What kinds of operations are possible in popups and can you, and how, go from one to another before resuming the transaction?

The page class hierarchy and the significance of "extends".  When I am cloning something, making a "same only different", I often forget the methods in the parent classes that may make the "different" quite straightforward.

**POS database** What tables and views are used to record the transaction, what are their roles? How does the screen map to the database? The idea that localtemptrans, the transaction work-in-progress, is being massaged as things proceed, that it isn't an unchanging audit of items, is something I've had to learn.

What happens in simple things, such as the addition of an item to the transaction?

What happens for "global" or "summary" operations such as totaling, discounts and taxes?

**One documentation approach** I like has two streams, a Textbook, which is systematic, and what I am mostly after in this issue, and a Cookbook, which is how to do particular things, but with references to the Textbook so you can tie it back to the systematic approach.

**Items I am kind of stuck on at the moment** that might suggest what one should know to begin with in order to know where to look, what to do next.

1. How to get from one function to another in the POS interface.  Can you get there from here?  I've created a popup in a Parser class that displays something about the member's account:

![coop_cred_qq](https://cloud.githubusercontent.com/assets/1131922/6185909/9a94268e-b341-11e4-97eb-3a6e0538f603.png)

and returns it in the json object:
```php
$ret = $this->default_json();
/* ... Compose the popup content in $message ... */
$ret['output'] = DisplayLib::boxMsg("$message","",True);
```
As you see in the box, I want to be able to print the same little report to the receipt printer.  But I don't know how to do it. I have in mind re-running the class in "print mode", but don't know how, or if that is the way to do it. What should I know to be able to answer that?

2. In this display of an in-house coupon, how to change MC to IC.
![screenshot_021315_045234_am](https://cloud.githubusercontent.com/assets/1131922/6185837/ec4a2880-b340-11e4-94df-a534da17376d.jpg)

and how to get the "IC" to appear on the corresponding receipt:
```
02/13/15     04:53     AM                        62-1-2
Rooibos Chai Tea 16ct                           5.49   T
Tea and Coffee                                 -0.82 <- Want "IC" here.
Discount                                        0.00
Subtotal 4.67, Tax0.71 #484            TOTAL    5.38
```

```*``` Checking my usage of the term "syllabus" I find a meaning I expect:
1. an outline of the subjects in a course of study or teaching.
and another one we might also observe:
2. a summary of points ... regarding heretical doctrines or practices.

**Comment by gohanman** [comment]
This list is fascinating in terms of giving directions to & shaping documentation ideas.

For co-op cred: when a parser returns an "output" value, that HTML is simply displayed. That means that whatever the cashier enters *next* will go through standard input parsing again. Having a parser that can handle AMB/PCT/BCT/CC4 may be sufficient. The drawbacks are the cashier isn't restricted to those four inputs - they could also scan another item, press a different tender key, or any other valid input. The cashier would also need to type the input strings or have 2-4 dedicated keys for this (depending on whether shift layers are available).

The alternative would be to return a "main_frame" value causing POS to leave pos2.php and load a different, dedicated page. That page would display the dialog (or something like it) and accept inputs. With this setup you can restrict input to the displayed options plus canceling with clear/CL. Using some form of <select> keeps the required keys simply up/down/enter/clear.

---------

The coupon one's a little less fun and gets into CORE's view-heavier history. The onscreen value is defined via translog.screendisplay. The short term answer is "edit the view locally". The long term answer is to make the transformations in PHP instead of SQL so it can be modular. I've written a preliminary DisplayLib::screenDisplay() but I haven't had a chance to exhaustively verify that it produces identical results to the view.

Adding IC to the receipt would again be in views if you're using the non-PHP receipt - an extra clause in whichever CASE WHEN is setting up flags for refund, tax, etc. With the PHP receipt, you could replace the "tag" stage class and tag the instore coupon lines differently. They're currently tagged as "Item" and hence the output string is generated by ItemReceiptFormat. If you tagged them as "WefcCustom" and added a class named "WefcCustomReceiptFormat", then your format class would generate that line of the receipt. This would be a good Cookbook candidate.

**Comment by jonkeim** [comment]
> This list is fascinating in terms of giving directions to & shaping documentation ideas.

I concur.  We could even paste your opening post into the wiki and start expanding from there.

**Comment by gohanman** [comment]
Other topics:

**Debugging** - diagnosing the underlying cause of problems especially related to coding and bugs.

**Architecture** - How does lane=>server data flow, typically.

**Comment by flathat** [comment]
I don't want to make the "learning POS" sound more mysterious than it is.  I've just spent an hour walking through the initial display of `pos2.php` in Firefox and learned a good deal.  That, with the source code open next to it, should, I think, be one of the early bootcamp exercises. Then continue to study it through various events.  We might provide some suggestions on what to try, point some things out, but the "documentation" doesn't need to be heavy, demanding either to create or use. What I seem to need is a suggestion of exercises and an order for them, which is what I mean by "syllabus" or "curriculum".

**Comment by gohanman** [comment]
I started sketching out topics based on this. Edits very much welcome.
https://github.com/CORE-POS/IS4C/wiki/POS-Development

**Comment by gohanman** [comment]
I filled in a couple of recipe ideas:
https://github.com/CORE-POS/IS4C/wiki/POS-Development

Are these in line with what you were thinking of? Other ideas for recipes?

**Comment by gohanman** [comment]
More ideas: print a receipt slip
