### ISSUE TITLE
converting trans_archive tables to partition format

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#453]
Wondering if it's as simple as dumping each individual table into a single table?... e.g.
`INSERT INTO dlogBig SELECT * FROM dlog201301` and repeat for all?  Same for `transArchiveYYYYMM`, `rp_receipt_header_YYYYMM`, and `rp_dt_receipt_YYYYMM`?

Are there other considerations to making this conversion?

**Comment by gohanman** [comment]
You need to copy each transArchiveYYYYMM table into bigArchive (the views can be ignored) as well as create the actual partitions.

SHOW CREATE TABLE bigArchive will show existing partitions. Provided at least one already exists, it would be something like:
```sql
for each monthly archive:
    ALTER TABLE bigArchive
    ADD PARTITION
    (pYYYYMM VALUES LESS THAN (TO_DAYS('<first day of next month>')));

    INSERT INTO bigArchive
    SELECT * FROM transArchiveYYYYMM
```
So e.g. partition p201501 would contain values less than 2015-02-01. Adding partitions and data sequentially is probably a good idea.

**Comment by flathat** [comment]
Can you say a bit about the advantages, or tradeoff, of using a bigArchive partitioned this way vs separate per-month trans_archive tables?

**Comment by gohanman** [comment]
MySQL performance on subqueries - such as a union of a couple per-month transaction tables - can range from bad to utterly horrific. The tipping point probably depends how large a months' worth of transaction data is and how much RAM is available, but at least for me the "disadvantage" of per-month tables is reporting on longer time spans is wholly unusable.

I don't think there are any advantages to the per-month tables. The original usage was in SQL Server which has substantially better performance on the particular queries involved, but even back then a single partitioned table probably would have been a better solution. Even without the drastic performance difference, writing queries for a single table is simpler and column consistency is guaranteed.

**Comment by gohanman** [comment]
Runnable task for converting tables to partitions: d88b675c5eff43ed8483adf8a633242436d3b523

I have not had a chance to test this, but it doesn't *delete* anything from the monthly tables so it shouldn't be able to do anything too catastrophic. Worst case it leaves bigArchive in a weird state where you have to start over.

**Comment by joelbrock** [comment]
Wow, amazing.  OK, i can test this with a current Fannie upgrade I am working on.  Can report back the results...

**Comment by flathat** [comment]
I can confirm that the partition-making utility `ConvertArchiveMonthlyToPartitions.php` works.  It checks for several kinds of problems, only one of which I ran into.  Thanks for doing this and with so much care.

However, when setting up the partitioned table `bigArchive` the installer (`fannie/install/InstallIndexPage.php`) creates an initial partition for the current month's data, `p201502` in my case.
If you change to partitions (`$FANNIE_ARCHIVE_METHOD == 'partitions'`) after you have some `trans_archive.transArchiveYYYYMM` tables and then run the converter it complains for the first (oldest) table:
```
Failed to create partition p201210
Details: VALUES LESS THAN value must be strictly increasing for each partition
Data transfer will not proceed until all partitions exist
No data has been copied
```
I re-created `bigArchive` with an initial partition (I think it must have at least one) for the month before my first month of data, after which the converter ran smoothly.  So I think the installer should do that, make the initial partition for before the first table that currently exists.

I compared timings of a report that UNIONS either fourteen months or fourteen months UNION today (`core_trans.dlog`) using tables and partitions.  The actual number of rows retrieved was small, less than 100. The timings include the `prepare()` and `execute()` steps of the query. The hash-numbers below are consecutive runnings of the report. `$FannieReportPage->report_cache == 'none'`. Results not entirely what I expected:
```
Using Monthly tables
Not including today (core_trans.dlog): Prep and Exec: UNION 14 months
#1 0.08761883
#2 0.00033188  // Much faster, I assume from MySQL or Linux cache
#3 0.00031900
13 months, i.e. a different query:
#1 0.08601284  // Slow the first time
#2 0.00036907  // Fast again
#3 0.00032401
#4 0.00030708
12 months, i.e. different query
#1 0.08381796 // same pattern
#2 0.00032687
Including today (UNION 14 months UNION core_trans.dlog): Prep and Exec:
#1 0.00034499  // So fast the first time!
13 months UNION today, i.e. different query
#1 0.00035715  // Still fast
#2 0.00032687

Partitioned
Not including today, i.e. no UNION: Prep and Exec:
#1 0.00632310 // First time faster than first time for tables
#2 0.00459886 // A little faster, but not nearly as fast as 2nd+ for tables
#3 0.00461292
#4 0.00473809
Including today (dlogBig UNION core_trans.dlog): Prep and Exec:
#1 0.09455395 // About the same as with tables
#2 0.09328580 // 2nd iteration no faster
#3 0.09503198
```

**Comment by gohanman** [comment]
That's fascinating, if completely and utterly confusing. What's the test
report / query? Version of MySQL? Are indexes on the monthly tables the
same as bigArchive?

**Comment by flathat** [comment]
MySQL 5.1.73
```
SELECT d.card_no,
            d.tdate,
            DATE_FORMAT(d.tdate,'%Y %m %d %l:%i') AS 'SortDate',
            DATE_FORMAT(d.tdate,'%M %e, %Y %l:%i%p') AS 'When',
            CASE WHEN (d.card_no > 99900)
                    THEN a.LastName
                    ELSE CONCAT(a.FirstName,' ',a.LastName)
                END AS 'Who',
            trans_status, unitPrice, quantity, total,
            CASE WHEN (d.description != m.dept_name)
                THEN d.description ELSE '' END
                AS 'Comment'
            FROM (SELECT * FROM trans_archive.dlogBig
/* core_trans.dlog if the report includes the current day */
UNION ALL SELECT * FROM core_trans.dlog) d
            LEFT JOIN core_op.custdata a ON a.CardNo = d.card_no
            LEFT JOIN core_op.departments m ON m.dept_no = d.department
            WHERE d.department = 1021
              AND (tdate BETWEEN ? AND ?)
                        ORDER BY DATE_FORMAT(d.tdate, '%Y-%m-%d %H:%i')
``` 
if tables 
```
FROM (select * from trans_archive.dlog201401 union all select * from trans_archive.dlog201402 
union all select * from trans_archive.dlog201403 union all select * from trans_archive.dlog201404 
union all select * from trans_archive.dlog201405 union all select * from trans_archive.dlog201406 
union all select * from trans_archive.dlog201407 union all select * from trans_archive.dlog201408 
union all select * from trans_archive.dlog201409 union all select * from trans_archive.dlog201410 
union all select * from trans_archive.dlog201411 union all select * from trans_archive.dlog201412 
union all select * from trans_archive.dlog201501 union all select * from trans_archive.dlog201502 
/* If report includes the current day */
UNION ALL SELECT * FROM core_trans.dlog) d
```
Indexes on `bigArchive`, from `show create table bigArchive`:
```
 KEY `datetime` (`datetime`),
 KEY `upc` (`upc`),
 KEY `department` (`department`),
 KEY `card_no` (`card_no`),
...
```
Per-month tables also have indexes on those fields and `custdata.CardNo` and `departments.dept_no` are indexed.

**Comment by gohanman** [comment]
A-ha. That at least makes more sense. I may have misdescribed the issue to an extent.

Fannie would do this instead:
```sql
SELECT d.card_no,
            d.tdate,
            DATE_FORMAT(d.tdate,'%Y %m %d %l:%i') AS 'SortDate',
            DATE_FORMAT(d.tdate,'%M %e, %Y %l:%i%p') AS 'When',
            CASE WHEN (d.card_no > 99900)
                    THEN a.LastName
                    ELSE CONCAT(a.FirstName,' ',a.LastName)
                END AS 'Who',
            trans_status, unitPrice, quantity, total,
            CASE WHEN (d.description != m.dept_name)
                THEN d.description ELSE '' END
                AS 'Comment'
            FROM trans_archive.dlogBig AS d
            LEFT JOIN core_op.custdata a ON a.CardNo = d.card_no
            LEFT JOIN core_op.departments m ON m.dept_no = d.department
            WHERE d.department = 1021
              AND (tdate BETWEEN ? AND ?)
                        ORDER BY DATE_FORMAT(d.tdate, '%Y-%m-%d %H:%i')
```

The real hang-up is the subquery in the FROM clause. The unions necessitate that subquery. Partitions don't, although current day + history just isn't supported.

When the query includes something like:
```sql
FROM (SELECT * FROM dlogBig)
```
MySQL creates a temporary table the includes *every record* in the subquery. Nothing in the WHERE clause applies yet to filter down the size of the temporary table. Depending how smart the optimizer is behaving, the temporary table may not include any indexes). As long as the temporary table fits in memory, none of this really matters. Once you have to write it to disk, seconds turn into minutes.

In essence the subquery approach [that monthly tables require] works flawlessly until the amount of transaction data generated exceeds available memory. Then it becomes a complete disaster.

**Comment by gohanman** [comment]
CORE's actual query building would look something like this:

```php
$DLOG_SQL = DTransactionsModel:selectDlog($date1, $date2);

$query = "
SELECT d.card_no,
    d.tdate,
    DATE_FORMAT(d.tdate,'%Y %m %d %l:%i') AS 'SortDate',
    DATE_FORMAT(d.tdate,'%M %e, %Y %l:%i%p') AS 'When',
    CASE WHEN (d.card_no > 99900)
        THEN a.LastName
        ELSE CONCAT(a.FirstName,' ',a.LastName)
    END AS 'Who',
    trans_status, 
    unitPrice, 
    quantity, 
    total,
    CASE WHEN (d.description != m.dept_name)
        THEN d.description ELSE '' 
    END AS 'Comment'
FROM " . $DLOG_SQL . " AS d
    LEFT JOIN core_op.custdata AS a ON a.CardNo = d.card_no
    LEFT JOIN core_op.departments AS m ON m.dept_no = d.department
WHERE d.department = 1021
    AND (tdate BETWEEN ? AND ?)
ORDER BY DATE_FORMAT(d.tdate, '%Y-%m-%d %H:%i')
";
```

This is not terribly elaborate, obviously, but either a table or subquery can be slotted in for $DLOG_SQL without changing the rest of the query.

**Comment by DavidHermann** [comment]
Could the selectDlog function take a WHERE clause as a third parameter, so that each dlog table was filtered before being UNIONed?  Params $date1 and $date2 could also be applied to each dlog table whose span was not entirely within the date bounds, but *not* applied to tables entirely within bounds.

 

In the Harvest databases, I have a table of serialized table names and the dates that each table spans, plus a function that reads the table-of-tables and returns a list/cursor/recordset of relevant tablenames based on a passed-in table type and a passed-in date range.  To report across multiple tables in a serialized set:

 

Execute "DELETE FROM intermediateTable"

Set rst = fnRstSerialized("Tlog", $date1, $date2)

Do While Not rst!EndOfList

    Execute "INSERT INTO intermediateTable

             SELECT *

              FROM  " . rst!TableName . "

              WHERE (conditions) " .

             if(($date1 <= rst!FromDate) And

                ($date2 >= rst!ThruDate),

                "",

                " AND (TlogDate Between " . $date1 .

                                  " And " . $date2 . ")"

               )

    rst.MoveNext

Loop

 

and then report on  intermediateTable.  In Harvest's case, the Tlog data spans tables geared to multiple POS systems with differing columns, so the SQL can be tailored per POS and "homogenize" the data into a more general format.

 

For some reports, I check the running count of intermediate rows as I go, and only let myself, and maybe some I.S. users, go over a limit.  This keeps overly broad report specs from blowing up.

 

David Hermann

Database Programmer

Harvest Co-op Markets

(617) 874-5134

dhermann@harvest.coop

**Comment by DavidHermann** [comment]
Could the selectDlog function take a WHERE clause as a third parameter, so that each dlog table was filtered before being UNIONed?  Params $date1 and $date2 could also be applied to each dlog table whose span was not entirely within the date bounds, but *not* applied to tables entirely within bounds.

At Harvest, I have a table of serialized table names and the dates that each table spans, plus a function that reads the table-of-tables and returns a list/cursor/recordset of relevant tablenames based on a passed-in table type/series and a passed-in date range.  To report across multiple tables in a serialized set:
```
Execute "DELETE FROM intermediateTable"
Set rst = fnRstSerialized("Tlog", $date1, $date2)
Do While Not rst!EndOfList
    Execute "INSERT INTO intermediateTable
             SELECT *
              FROM  " . rst!TableName . "
              WHERE (conditions) " .
             if(($date1 <= rst!FromDate) And
                ($date2 >= rst!ThruDate),
                "",
                " AND (TlogDate Between $date1
                                    And $date2 )"
               )
    rst.MoveNext
Loop
```

and then report on 'intermediateTable'.  In Harvest's case, the Tlog data spans tables geared to multiple POS systems with differing columns, so the SQL can be tailored per POS and "homogenize" the data into a more general format.

For some reports, I check the running count of intermediate rows as I go, and only let myself, and maybe some I.S. users, go over a limit.  This keeps overly broad report specs from blowing up.

**Comment by gohanman** [comment]
It certainly could, provided the WHERE clause passed in only applies to the Tlog structure. There would potentially be some additional legwork upfront before calling the function. For an inner join, for instance, you'd look up the applicable keys and put that into the WHERE clause as an IN to build the appropriate intermediate table.

I have no doubts that breaking it into separate queries can boost performance. What I do like about the single query is it's a little more beginner friendly. So long as performance on the single query is good enough, someone who's just getting started can write one mostly coherent query. Passing around WHERE clauses or reworking JOINs presupposes a bit of SQL familiarity. At minimum the 3rd parameter ought to be optional.

The real trick would be to take a single query like I wrote, parse it all out, and turn it into multiple queries that return the same result using an intermediate table when appropriate. I'm just not confident I can do that in an automated way that's reliable & accurate.

**Comment by gohanman** [comment]
First stab at it: 29464ad5b2559f15975581bf28cd7a91a05b8f64

This:
```php
        $tempTables = array(
            'connection' => $dbc,
            'clauses' => array(
                array(
                    'sql' => 'trans_type IN (?, ?)',
                    'params' => array('I', 'D'),
                ),
            ),
        );
        $dlog = DTransactionsModel::selectDlog($date1, $date2, $tempTables);
```

Will create a temporary table and populate it like this:
```sql
INSERT INTO trans_archive.temp280554f0f4d3d63b7 
SELECT * 
FROM __SOURCE_TABLE__ 
WHERE tdate BETWEEN ? AND ? 
    AND trans_type IN (?, ?)
```
The return value $dlog is then "trans_archive.temp280554f0f4d3d63b7".

The parameter structure should probably be re-written as an object; that array nesting is excessive. But I think everything in there is necessary. Since it uses actual temporary tables, passing the connection in is important. Accidentally creating a new connection (and thus new session) means the caller wouldn't have access to the temporary table. Passing the where constraints as pairs of SQL strings and parameter values is necessary to use prepared statements. Part of the conditional could be user input and statements are safer than trying to escape everything correctly.

Anecdotally it doesn't appear any faster or slower, although I haven't put in any exact time measures or tried very large datasets yet.

**Comment by flathat** [comment]
With partitions and no sub-select, not including today's transactions:
```
            FROM trans_archive.dlogBig d
            LEFT JOIN core_op.custdata a ON a.CardNo = d.card_no
            LEFT JOIN core_op.departments m ON m.dept_no = d.department
```
timings:
```
// Partitions, 14 months, not today
#1 0.00480509  // Faster, but may still cache from the previous day
#2 0.00462389  // Same as coded as subquery. Still much slower than tables.
#3 0.00461602

// Change query to 13 months
#1 0.02034378  // much slower
#2 0.00459695  // same as for 14 months, 2nd same query
#3 0.00462604

// 14 months again
#1 0.00466704  // same as earlier
#2 0.00475717

// Using tables, 14 months, not including today
#1 0.35150695  // "slow"
#2 0.00032306 // As before. 2nd+ till much faster than partitions without subquery.
#3 0.00033212
```
But the time for the page to display feels "almost the same" for all.  Datasets still small.

**Comment by gohanman** [comment]
e915b919ca1266154363731520f4121a5ee21b34

I added a page to run a fairly simple, representative reporting query and time it. It's doing this:
```sql
            SELECT d.dept_name,
                SUM(t.total) AS ttl
            FROM [tlog archive structure]
                LEFT JOIN departments AS d ON t.department=d.dept_no
            WHERE t.datetime BETWEEN ? AND ?
                AND trans_type IN ('I', 'D')
                AND t.department BETWEEN 0 AND ?
            GROUP BY d.dept_name
```
Using a temporary table to collect applicable tlog records before hand take at least twice as long. I'll grant the example query is a little contrived, but intuitively this makes sense to me. It's not sufficient to just collect the transaction records in a temporary table. Real gains would come from **aggregating** the transaction records in a temporary table so subsequent queries are operating on a smaller record set.

Rather than having a catch-all function that builds the best intermediate table in every case, it may be more practical to have several methods that address common situations - e.g., selectDlogSumByUPC(), selectDlogSumByDepartment(), etc.

**Comment by joelbrock** [comment]
In my testing of this i get the same result as @flathat initially got:
```
Failed to create partition p201108
Details: VALUES LESS THAN value must be strictly increasing for each partition
Data transfer will not proceed until all partitions exist
No data has been copied
```
Where p201108 matches the first monthly dlog/transArchive tables.

Not being too familiar with PARTITIONING i'm somewhat lost on this thread.
@flathat, would you be able to provide the sql for the table creation that you did with the partitions beginning before the first month of sales?
Or @gohanman repair the task?

Sorry, i'm on a tear here and dont have time to learn mysql partitioning just this very second....  TIA.

Note, i COPIED the production DB trans_archive to trans_archive_Xfer and updated Fannie's archive DB to point to that one before executing the task via CLI,
```bash
pos-admin@ELFCO-SRV:/pos/ELFCO_CORE/fannie/CORE/cron/tasks/one-time$ php -f ../../../classlib2.0/FannieTask.php ConvertArchiveMonthlyToPartitions
```

**Comment by gohanman** [comment]
The thread wandered more than a little. I don't know if I can repair the task without making it a bit more dangerous/descructive. I believe what you need is:

```sql
ALTER TABLE bigArchive REMOVE PARTITIONING;

ALTER TABLE bigArchive
PARTITION BY RANGE(TO_DAYS(datetime))
(PARTITION p201108
    VALUES LESS THAN (TO_DAYS('2011-09-01'))
);
```

The REMOVE could make a mess if someone doesn't know what they're doing. A better fix might be changing table creation so it creates the very first partition well in the past (1901-01-01 or something) instead of using the current month. The way-back-when partition would be empty but both new installs and conversions would work cleanly.

**Comment by joelbrock** [comment]
After tweaking your query (thankU @gohanman ) thusly:
```sql
ALTER TABLE bigArchive 
  PARTITION BY RANGE(TO_DAYS(datetime)) 
  (PARTITION p1900 VALUES LESS THAN (TO_DAYS('1900-01-01')) 
);
```
I can now run ConvertArchiveMonthlyToPartitions....with these errors
```
...
...
...
Migrating data from transArchive201501 to bigArchive...
	An error occurred
	Details: Column count doesn't match value count at row 1
Migrating data from transArchive201502 to bigArchive...
	An error occurred
	Details: Column count doesn't match value count at row 1
Migrating data from transArchive201503 to bigArchive...
	An error occurred
	Details: Column count doesn't match value count at row 1
Process complete
```

I see bigArchive looks like this:
```
mysql> desc bigArchive;
+-----------------+---------------------+------+-----+---------+-------+
| Field           | Type                | Null | Key | Default | Extra |
+-----------------+---------------------+------+-----+---------+-------+
| datetime        | datetime            | YES  | MUL | NULL    |       |
| store_id        | smallint(6)         | YES  |     | NULL    |       |
| register_no     | smallint(6)         | YES  |     | NULL    |       |
| emp_no          | smallint(6)         | YES  |     | NULL    |       |
| trans_no        | int(11)             | YES  |     | NULL    |       |
| upc             | varchar(13)         | YES  | MUL | NULL    |       |
| description     | varchar(30)         | YES  |     | NULL    |       |
| trans_type      | varchar(1)          | YES  | MUL | NULL    |       |
| trans_subtype   | varchar(2)          | YES  |     | NULL    |       |
| trans_status    | varchar(1)          | YES  |     | NULL    |       |
| department      | smallint(6)         | YES  | MUL | NULL    |       |
| quantity        | double              | YES  |     | NULL    |       |
| scale           | tinyint(4)          | YES  |     | 0       |       |
| cost            | decimal(10,2)       | YES  |     | NULL    |       |
| unitPrice       | decimal(10,2)       | YES  |     | NULL    |       |
| total           | decimal(10,2)       | YES  |     | NULL    |       |
| regPrice        | decimal(10,2)       | YES  |     | NULL    |       |
| tax             | smallint(6)         | YES  |     | NULL    |       |
| foodstamp       | tinyint(4)          | YES  |     | NULL    |       |
| discount        | decimal(10,2)       | YES  |     | NULL    |       |
| memDiscount     | decimal(10,2)       | YES  |     | NULL    |       |
| discountable    | tinyint(4)          | YES  |     | NULL    |       |
| discounttype    | tinyint(4)          | YES  |     | NULL    |       |
| voided          | tinyint(4)          | YES  |     | NULL    |       |
| percentDiscount | tinyint(4)          | YES  |     | NULL    |       |
| ItemQtty        | double              | YES  |     | NULL    |       |
| volDiscType     | tinyint(4)          | YES  |     | NULL    |       |
| volume          | tinyint(4)          | YES  |     | NULL    |       |
| VolSpecial      | decimal(10,2)       | YES  |     | NULL    |       |
| mixMatch        | varchar(13)         | YES  |     | NULL    |       |
| matched         | smallint(6)         | YES  |     | NULL    |       |
| memType         | tinyint(4)          | YES  |     | NULL    |       |
| staff           | tinyint(4)          | YES  |     | NULL    |       |
| numflag         | int(11)             | YES  |     | 0       |       |
| charflag        | varchar(2)          | YES  |     |         |       |
| card_no         | int(11)             | YES  | MUL | NULL    |       |
| trans_id        | int(11)             | YES  |     | NULL    |       |
| pos_row_id      | bigint(20) unsigned | YES  | MUL | NULL    |       |
| store_row_id    | bigint(20) unsigned | YES  |     | NULL    |       |
+-----------------+---------------------+------+-----+---------+-------+
39 rows in set (0.00 sec)
```
and the transArchiveYYYYMM tables look like this:
```
mysql> desc transArchive201503;
+-----------------+--------------+------+-----+---------+-------+
| Field           | Type         | Null | Key | Default | Extra |
+-----------------+--------------+------+-----+---------+-------+
| datetime        | datetime     | YES  |     | NULL    |       |
| register_no     | smallint(6)  | YES  |     | NULL    |       |
| emp_no          | smallint(6)  | YES  |     | NULL    |       |
| trans_no        | int(11)      | YES  |     | NULL    |       |
| upc             | varchar(255) | YES  |     | NULL    |       |
| description     | varchar(255) | YES  |     | NULL    |       |
| trans_type      | varchar(255) | YES  |     | NULL    |       |
| trans_subtype   | varchar(255) | YES  |     | NULL    |       |
| trans_status    | varchar(255) | YES  |     | NULL    |       |
| department      | smallint(6)  | YES  |     | NULL    |       |
| quantity        | double       | YES  |     | NULL    |       |
| scale           | tinyint(4)   | YES  |     | NULL    |       |
| cost            | double       | YES  |     | 0       |       |
| unitPrice       | double       | YES  |     | NULL    |       |
| total           | double       | YES  |     | NULL    |       |
| regPrice        | double       | YES  |     | NULL    |       |
| tax             | smallint(6)  | YES  |     | NULL    |       |
| foodstamp       | tinyint(4)   | YES  |     | NULL    |       |
| discount        | double       | YES  |     | NULL    |       |
| memDiscount     | double       | YES  |     | NULL    |       |
| discountable    | tinyint(4)   | YES  |     | NULL    |       |
| discounttype    | tinyint(4)   | YES  |     | NULL    |       |
| voided          | tinyint(4)   | YES  |     | NULL    |       |
| percentDiscount | tinyint(4)   | YES  |     | NULL    |       |
| ItemQtty        | double       | YES  |     | NULL    |       |
| volDiscType     | tinyint(4)   | YES  |     | NULL    |       |
| volume          | tinyint(4)   | YES  |     | NULL    |       |
| VolSpecial      | double       | YES  |     | NULL    |       |
| mixMatch        | varchar(13)  | YES  |     | NULL    |       |
| matched         | smallint(6)  | YES  |     | NULL    |       |
| memType         | tinyint(2)   | YES  |     | NULL    |       |
| staff           | tinyint(4)   | YES  |     | NULL    |       |
| numflag         | smallint(6)  | YES  |     | 0       |       |
| charflag        | varchar(2)   | YES  |     |         |       |
| card_no         | varchar(255) | YES  |     | NULL    |       |
| trans_id        | int(11)      | YES  |     | NULL    |       |
+-----------------+--------------+------+-----+---------+-------+
36 rows in set (0.00 sec)
```

i guess im wondering if there is a way within CORE to update the schema on the transArchiveYYYYMM tables?  Or make the Convert tool aware of the available fieldnames?

**Comment by joelbrock** [comment]
UPDATE:  My workaround was to DROP the feilds from bigArchive.  The Convert task is now humming along at about 20 seconds per month.

**Comment by gohanman** [comment]
Updates in Fannie should offer to add missing columns, although it's only
going to the monthly tables or the partitioned one depending what mode it's
in.

**Comment by joelbrock** [comment]
right!  running update DTransactionModel went through and re-added the
removed fields!

**Comment by joelbrock** [comment]
A possibly silly question:  After running the Convert task successfully, can transArchiveYYYYMM, rp_receipt_header_YYYYMM, rp_dt_receipt_YYYYMM, and dlogYYYYMM all go away?

**Comment by gohanman** [comment]
The rp_* views aren't used at all starting in version 0.9.14. The dlogYYYYMM and transArchiveYYYYMM are not used in partitions mode. It probably wouldn't hurt to put a backup dump of the transArchiveYYYYMM tables on a disk somewhere. Most likely no one will ever need to look at it, but the disk space required to hold onto a copy "just in case" probably isn't all that much.
