### ISSUE TITLE
Hardcoded cashback limit

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#454]
```php
		} else if (substr($str,0,7) == "TERMCB:") {
			$cashback = substr($str,7);
			if ($cashback <= 40) { // <-- hardcoding here
				$this->cb_error = false;
				CoreLocal::set("CacheCardCashBack",$cashback);
			} else {
```

Hardcoding in parser-class-lib/parse/SigTermCommands.php (the "40") prevents cashback in excess of $40.

Could this get moved to a variable in the paycards plugin?

If i were the king of everything:  I'd relabel the BUTTON_500, BUTTON_2000, vars in SPH_SignAndPay_USB.cs to something like BUTTON_001, BUTTON_002, etc. and this way they are slightly more configurable?  At least twice now (maybe 3x) i've had to customize the cashback options by hand-editing the signandpay.cs file to meet the individual co-ops needs.

**Comment by gohanman** [comment]
Reasonable request; shouldn't be confused with coronation.

PHP-side configuration setting for max permissible cashback value: 0c3772344dc9f48d9c21935ca31dcd09fcd67d1b

Buttons constants renamed: e21dabbc7e92471a46b18da90b1b21b04b3e3550
I used BUTTON_CB_OPT1 through BUTTON_CB_OPT5 so there's at least an indication they're cashback related.
