### ISSUE TITLE
VoidLimit works on UPCs but not openrings

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#455]
The title says most of it.  Set voidlimit == 10 and it prompts for mgr. login when voiding >= $10 of scanned items.  Doesnt register at all when voiding open rings.

**Comment by gohanman** [comment]
It does for me. The *current* item doesn't count though, just the total amount already voided. If the first item that I void is a $50 open ring (or UPC item), POS allows it since it isn't counting the current item. Voiding a subsequent open ring (or UPC item) will require a mgr. login.

**Comment by gohanman** [comment]
This fixes what is effectively the real bug:
a9c1c54450e4e7bc1dafbdd176c05cdb5919c500

If the item that's *about to be voided* will result in exceeding the limit, approval is required
