### ISSUE TITLE
Name of return var in FannieTask::listModules()

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#456]
It seems to be safer to give `$ret = array()` (currently at line 265) a less common name.  I got errors:
```
fannie/cron$ sudo -u www-data php $FCL2/FannieTask.php ConvertArchiveMonthlyToPartitions
PHP Warning:  Cannot use a scalar value as an array in 
/var/www/IS4C/fannie/classlib2.0/FannieAPI.php on line 220
#line 220 $ret[] = $class;
```
because
```
 // may redefine $ret as string.
include_once($file);
```
I changed it to `$f_ret` and the Warnings went away but something protected in the class might be even better.

**Comment by gohanman** [comment]
I think it makes more sense to track down the actual cause. A file that has side-effects on include could cause a variety of different bugs. Papering over this particular one without finding the $file that causes it may leave other problems unaddressed.

Does the unit test turn up anything? The CLI syntax would be "phpunit --bootstrap fannie/unit-tests/bootstrap.php fannie/unit-tests/PluginsTest.php"

**Comment by flathat** [comment]
```
phpunit --bootstrap fannie/unit-tests/bootstrap.php fannie/unit-tests/PluginsTest.php
...
1) PluginsTest::testPlugins
/var/www/IS4C/fannie/modules/plugins2.0/WfcGazetteBilling/WfcGazetteBillingPage.php
has defined additional functions: getint4d(/var/www/IS4C/fannie/src/Excel/oleread.inc)
Failed asserting that <integer:1> matches expected <integer:0>.

/var/www/IS4C/fannie/unit-tests/PluginsTest.php:33

FAILURES!
Tests: 1, Assertions: 14, Failures: 1.
```
`WfcGazetteBillingPage.php` uses a string `$ret` locally in functions, `oleread.inc` does not, but that doesn't seem to be what it is complaining about here.

`MembersTest.php` runs into the oringal problem (line 241 was line 220 before):
```
$ phpunit --bootstrap fannie/unit-tests/bootstrap.php fannie/unit-tests/MembersTest.php
...
1) MembersTest::testItems
Cannot use a scalar value as an array
/var/www/IS4C/fannie/classlib2.0/FannieAPI.php:241
/var/www/IS4C/fannie/unit-tests/MembersTest.php:11
FAILURES!
Tests: 1, Assertions: 0, Errors: 1.
```
Many MemberModule's use a scalar `$ret` within functions.  Is the problem an assignment outside a function? I have a MemberModule is a plugin.  It uses scalar `$ret` but not outside a function.

**Comment by flathat** [comment]
Not knowing a more elegant way to do this I jiggered into `FannieAPI::listModules()`:
```php
            // verify class exists
            ob_start();
            include_once($file);
            ob_end_clean();
            /* JIGGER: Report if $ret is no longer an array */
            if (!is_array($ret)) {
                echo "Not: $file\n";
            }
```
and re-ran `MembersTest.php` which pointed me to the file in my plugin where I had copied the code chunk `fannie/sync/special/generic.mysql.php`. This chunk is not coded as a class, so its use of `$ret = 0` is in the same scope as listModules() and causes the problem. (It's not an issue in `fannie/sync` because listModules() doesn't look there.)

In the plugin, I changed its extension, and those of the symlinks to it, from `.php`  to `.inc` and changed the code that looks for `$table.php` to look for `$table.inc`.  This might be a coding best practice.

OK for this situation. Could FannieAPI::listModules() check if the file was meant to contain a class definition, or could it ignore a directory of non-class .php files?  Or does it just have to be a plugin rule that `*.php` contain classes?

**Comment by gohanman** [comment]
Sorry for not following up on this sooner; I must have overlooked an email or something.

The gazette plugin issue was addressed here (b185ed42d49a29d0252e843828056149962a6bc8). I just rewrote oleread.inc so it didn't define a function outside the class.

> OK for this situation. Could FannieAPI::listModules() check if the file was meant to contain a class definition, or could it ignore a directory of non-class .php files? Or does it just have to be a plugin rule that *.php contain classes?
Plugin .php files don't *have* to contain classes, but they're not supposed to cause side-effects (https://github.com/CORE-POS/IS4C/wiki/Coding-Standards). Because plugin .php files may be included() at random times during module discovery, they shouldn't execute anything immediately upon include().

The two current exceptions are files named "index.php" and directories named "noauto". FannieAPI::listModules() ignores these completely so there are no restrictions on those files.

I don't think checking whether a file is meant to contain a class in realtime is pretty impractical. If FannieAPI::listModules() can't simply include the file, there aren't really any good solutions. The choices are pretty much "unreliable", "extremely complicated", or both.

**Comment by flathat** [comment]
>checking whether a file is meant to contain a class in realtime is pretty impractical.

In that case it would seem to be a good idea to try to protect the `listModules()` code from `include()'ed` code.  I realize this can't be perfect, but calling the return var it is building `$moduleList` list or better yet `$this->moduleList` instead of the commonly-used `$ret` will make stumbling into the problem I did less likely.  In a case like mine, had `$ret` in the include been an array the problem would have been even less visible.

The context of this in my case has been that if I import and re-use a piece of code in the plugin it may be subject to risks that don't exist in its original location.  It's a lesson learned, but also something we might try to accommodate and work around in order to be plugin-friendly, and plugin-safe to the extent we can.

**Comment by gohanman** [comment]
I disagree really, really strongly. Changing the variable name doesn't fix the actual problem. FannieAPI::listModules() will return a value but the file in question is still completely unsafe and could cause random problems at any time. Hiding one such problem has a minimal effect on overall safety and worse doesn't notify the developer that their code is unsafe. Unsafe code should crash, hard, as soon as possible. Requiring someone fix an error now is friendlier than leaving them in the dark about potential future errors.

Granted, that's not much of a solution. This is closer - plugin unit testing that can detect side effects:
e90866faa009bd5bc6c519b3423e71334b502b4f

Caveats:
* Composer is required. I'm not going to write my own static analysis tool from scratch.
* Checking only happens during unit testing. Parsing & analyzing files in real-time (i.e., in FannieAPI::listModules() itself) would have a gigantic impact on performance.
