### ISSUE TITLE
Column-head sort not working

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#457]
When I click one of the sort arrows in either FF36.0 or Chrome 40.0.2214.115 m I get, in the Ctrl-Shift-J console:
`TypeError: table.config.parsers[c] is undefined`
points to line 600 of jquery.tablesorter.js
`var s = (table.config.parsers[c].type == "text") ? ((order == 0) ? makeSortFunction("text", "asc", c) : makeSortFunction("text", "desc", c)) : ((order == 0) ? makeSortFunction("numeric", "asc", c) : makeSortFunction("numeric", "desc", c));`
Has something changed in libraries needed?

**Comment by gohanman** [comment]
Where specifically are you seeing this? I don't have any issue with the reports I tried (Department & Item movement).

**Comment by flathat** [comment]
StoreSummary and a report of AR-like inputs that isn't published yet.  The latter works now. I thought it might have to do with other browser tabs or windows being open, but after closing and re-opening I can't replicate.  StoreSummary is a multi-report, with multiple `<thead>` and `<tbody>` tags within a `<table>`, but I don't think it ever did sort per-section; it continues to report the error originally noted. I'm not going to pursue that now.

Department Movement is fine.

**Comment by gohanman** [comment]
Yep, I see that now. On mine the *first* ```<thead>``` sorts the first ```<tbody>``` but all subsequent ones produce the error above. I see two different issues here:

The markup I'm generating isn't valid. The standard says I can only have one ```<thead>``` per ```<table>```. That's relatively easy to fix. The repeated headers can go in ```<tbody>``` tags instead, and ```<th>``` in ```<tbody>``` can be styled correctly.

The tablesorter code only operates on the first ```<tbody>```. It's probably possible to detect each repeated header row and have it sort the adjacent ```<tbody>```, but I'm not enthused about how much work would go into understanding and rewriting big chunks of tablesorter. I think the recommended solution for sorting different sections will be using separate ```<table>```s.

**Comment by gohanman** [comment]
As of 1.2.0 tables only have one <thead>. This alleviates the original error. Sorting separate subsections is a bigger task than I have time to take on. I'm calling "use separate tables" the recommended solution unless someone else is in an extremely javascript-y mood.
