### ISSUE TITLE
loginform redirect loop

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#459]
I've upgraded to d32fa48cd2b5a0da0b4be11370d4f2a9eae72c0d and find that when `$FANNIE_AUTH_DEFAULT = True;` and I access `/fannie/`, or any page that extends `FanniePage`, there is a redirect loop: `https://posdev.westendfood.coop/IS4C/fannie/auth/ui/loginform.php?redirect=/IS4C/fannie/auth/ui/loginform.php?...`. If I set `$FANNIE_AUTH_DEFAULT = False;`, access is successful, but login skipped.

A difference is that `auth/ui/loginform.php` is now coded as a class extending `FannieRESTfulPage`. If I swap in the old `loginform.php`, which is not class-coded then there is no redirect loop and login proceeds normally.

**Comment by gohanman** [comment]
This? f53c78561251fa1ca0a76044e1cb6e8de4959974

**Comment by flathat** [comment]
Yes.
