### ISSUE TITLE
BasicModel --update to report existing view when table expected

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#460]
I'm upgrading Fannie and one of the Install > Updates tasks is:
`php ./BasicModel.php --update core_trans $FCL2DM/trans/CashPerformDayModel.php`. There is already a view `CashPerformDay`.  An error is logged:
```
Failed Query on /IS4C/fannie/install/InstallUpdatesPage.php
ALTER TABLE `CashPerformDay` CHANGE COLUMN `Trans_Num` `trans_num` VARCHAR(25)
'core_trans.CashPerformDay' is not BASE TABLE
```
but there is no indication from the utility itself (on the command line) that it didn't succeed. Would
`if ($sql->isView("$table"))` be enough to catch that?

In this case, I'm pretty sure DROPping the view will do no harm, so I did it. Running the same `BasicModel.php --update ...` again CREATEd the table.

**Comment by gohanman** [comment]
Good suggestion!
df75b3a51aed46487d0cbacd885120e5b02a40c2
