### ISSUE TITLE
Why parameters.param_value only 255 wide

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#466]
Is there a reason `opdata.parameters.param_value` is only `VARCHAR(255)`? My TenderMap has already run out of room and is not done growing.
Edited to add:
If I change the `ParametersModel.php` to `VARCHAR(2000)`
```
 php /var/www/IS4C/pos/is4c-nf/lib/models/BasicModel.php --update opdata op/ParametersModel
==========================================
Checking table opdata.parameters
==========================================
==========================================
Check complete. Need to add 0 columns  0 indexes.
==========================================
```
apparently doesn't handle that type of change.

**Comment by gohanman** [comment]
Habit, mostly. It used to be the max allowed size for VARCHAR. In this particular case, adding a column to the tenders table seems like a good idea. Putting settings related to a particular tender in two different places shouldn't be necessary.

The more detailed updates need the Fannie-style, adodb5-backed version of SQLManager. I don't know off the top of my head exactly what's required to make that switchover on the lane.

**Comment by gohanman** [comment]
Storing module configuration in the tenders table:
5836b53674c6e01b66b0d8f85a40d795d3090254

**Comment by gohanman** [comment]
I'm closing this as answered/addressed, although at the moment the field is still 255 characters wide. We can address it again if it becomes an issue again. I expect in most cases, a situation that calls for a really REALLY long string in param_value would be better addressed by storing the configuration in a different way (like here with opdata.tenders)
