### ISSUE TITLE
lane BasicModel up to date with backend's

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#467]
The syntax for updating to add the first column of a table in lane-side BasicModel as `FIRST` instead of `BEFORE` needs to be brought up to date with the back end version.  May be a little as changing line 646 from:
`$sql .= ' BEFORE '.$this->connection->identifier_escape($their_col);`
to:
`$sql .= ' FIRST';`

**Comment by gohanman** [comment]
Right you are
cc7e45b9fa50c8e9e5ed6e82045cb104fd9bc63d
