### ISSUE TITLE
$CORE_LOCAL->set() vs CoreLocal::set()

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#468]
I have a plugin that uses `$CORE_LOCAL` methods for session variables.  During an upgrade of `CORE` I see this kind of thing is now done with `CoreLocal` methods. I'm struggling with something in the plugin that doesn't work after the upgrade and wonder if mixing the schemes is the problem.  Is there anything to look out for in simply changing all the `$CORE_LOCAL->` `set()`s and `get()`s to `CoreLocal::` ?

**Comment by gohanman** [comment]
The two syntaxes should still be completely interchangeable. But yes it should be a simple change.
