### ISSUE TITLE
Changing ancient names

### ISSUE THREAD

**Issue by gohanman** [CORE-POS/IS4C#475]
So I just made a change that might be uncontroversial or might merit discussion:
6537b96affc0058c014ebabdeceda8e8e6e3639d

For essentially forever, CORE has included a file named pos/is4c-nf/gui-modules/qtty2.php. This is a rather weird name. This whole directory is full of weirdly named files that are vestiges of the original IS4C. I don't think the names are particularly intuitive - especially in cases like login2.php and login3.php - and they don't match the naming conventions anywhere else in the project. On the other hand, these names have been in place for a long time and some people are already familiar with them.

I renamed qtty2.php as QuantityEntryPage.php. In a vacuum, I think it's a substantially better name. Does it make sense to continue this sort of refactor? I don't consider it a high priority one way or another. It'd be more along the lines of: if I'm working on one of these pages for some reason, I'll take some extra time to rename it.

**Comment by joelbrock** [comment]
I'm in favor of this, but also wary of potential hiccups such a change may cause to stores running CORE in production.  Obviously we wouldnt be `git pull`ing from upstream onto a production lane or server, so i guess i'm just putting in my vote for moving fwd. with the change, cautiously!  ...and utilizing unit-test (now that i' have some experience using it!), etc. for ensuring no orphaned referenced remain.

**Comment by gohanman** [comment]
Sure, that makes sense. qtty2 was an appealing example since it's referenced exactly once in UPC.php for qttyEnforced items.

Unit testing happens more or less constantly. I forget who posted an issue suggesting it, but travis-ci runs all the unit tests every time a commit is pushed to github.
https://travis-ci.org/CORE-POS/IS4C

**Comment by flathat** [comment]
I basically like the idea but would grep through plugins for the old name before changing. I put hard-coded links to pages outside the plugin sometimes.

**Comment by gohanman** [comment]
Right; grepping through the all the files for references would be necessary
with any refactor.

**Comment by gohanman** [comment]
I'm reading this as consensus albeit not particularly pressing. Since I opened this is essence as a poll / RFC, it can go away.
