### ISSUE TITLE
CustomerCount report not "bootstrapped"

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#476]
![image](https://cloud.githubusercontent.com/assets/52835/6839167/c8030cac-d321-11e4-9ec1-8c16b1b96d16.png)

NOTE:  this is on version: 1.2.0-2015.03.06 fannieDevelop branch

**Comment by gohanman** [comment]
That's odd. The URL pictured doesn't really exist anymore; index.php is just a redirect to this:
http://core.gohanman.com/fannie/reports/CustomerCount/CustomerCountReport.php

**Comment by joelbrock** [comment]
that was actually helpful thank you!
I found a file on the server called CustomerCount/index_orig.php which had the header redirect in it.  Swapped that with the current index.php and i'm g2g
