### ISSUE TITLE
ReportsIndexPage appears to be running a report?

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#477]
![image](https://cloud.githubusercontent.com/assets/52835/6839200/2fb4bddc-d322-11e4-872c-d9f96786050d.png)

The top half looks like the start of the index page.  The bottom half looks like a report was just executed.

**Comment by gohanman** [comment]
The report index is searching for all existing reports. That looks like something in your reports/ or modules/plugins2.0 path is interrupting the process when included. The PagesTest or PluginTest in unit testing might help identify the culprit.

**Comment by joelbrock** [comment]
So this is what i get when executing the unit-tests you suggest.  Note, i am new to this part of the CORE codebase.  I havent yet had need to tinker, though i have been tracking the developments of late:

pos-admin@ELFCO-SRV:/pos/ELFCO_CORE/fannie/CORE$ phpunit --bootstrap bootstrap.php unit-tests/PagesTest.php
PHP Warning:  require_once(PHP/CodeCoverage/Filter.php): failed to open stream: No such file or directory in /usr/bin/phpunit on line 38
PHP Fatal error:  require_once(): Failed opening required 'PHP/CodeCoverage/Filter.php' (include_path='.:/usr/share/php:/usr/share/pear') in /usr/bin/phpunit on line 38
pos-admin@ELFCO-SRV:/pos/ELFCO_CORE/fannie/CORE$ phpunit --bootstrap bootstrap.php unit-tests/PluginsTest.php
PHP Warning:  require_once(PHP/CodeCoverage/Filter.php): failed to open stream: No such file or directory in /usr/bin/phpunit on line 38
PHP Fatal error:  require_once(): Failed opening required 'PHP/CodeCoverage/Filter.php' (include_path='.:/usr/share/php:/usr/share/pear') in /usr/bin/phpunit on line 38

**Comment by gohanman** [comment]
Looks like phpunit's busted. Ubuntu bug reports suggest this:

sudo apt-get remove phpunit
sudo pear channel-discover pear.phpunit.de
sudo pear channel-discover pear.symfony-project.com
sudo pear channel-discover components.ez.no
sudo pear update-channels
sudo pear upgrade-all
sudo pear install --alldeps phpunit/PHPUnit
sudo apt-get install phpunit

**Comment by joelbrock** [comment]
pear installer has reached EOL.  New method using PHPArchive:

➜ wget https://phar.phpunit.de/phpunit.phar
➜ chmod +x phpunit.phar
➜ sudo mv phpunit.phar /usr/local/bin/phpunit
➜ phpunit --version


Now i can execute phpunit.
Now i see this:
pos-admin@ELFCO-SRV:/pos/ELFCO_CORE/fannie/CORE/unit-tests$ phpunit --bootstrap bootstrap.php PagesTest.php
PHPUnit 4.5.0 by Sebastian Bergmann and contributors.

EPHP Fatal error:  main(): Failed opening required '../../config.php' (include_path='/pos/fannie/vendor/phpunit/php-text-template:/pos/fannie/vendor/phpunit/php-timer:/pos/fannie/vendor/phpunit/php-file-iterator:.:/usr/share/php:/usr/share/pear') in /pos/fannie/fannie/admin/labels/edit.php on line 24

**Comment by joelbrock** [comment]
NOTE: the path listed above `/pos/ELFCO_CORE/fannie/CORE/unit-tests` has a symlink in it.  If i go to the absolute path and re-run i cen the same result.

**Comment by gohanman** [comment]
Hmm. That script doesn't even exist upstream. Stray old or untracked files
could cause a fair amount of havoc, unfortunately.

**Comment by flathat** [comment]
> Stray old or untracked files could cause a fair amount of havoc

I have found it safest that any file of php code that is not coded a proper class be given a name that does not end in `.php`. There are some exceptions, but, increasingly, it is not worth the surprises of this kind to risk it.  Also, whenever `.php` is used be sure class and file names agree.

**Comment by joelbrock** [comment]
Huh, how about that.  phpunit pointed me to the untracked files and i was able to `git rm` them. until PagesTest stopped showing errors with the reports.  Now the Reports list generates cleanly.

Thanks!!

**Comment by flathat** [comment]
Reopen mostly to have it on the Open list for a few days for people to see it since it's interesting.

After updating per instructions:
```
cd $FANNIE
# i.e /var/www/IS4C/fannie.  Needed paths to both .php files
phpunit --bootstrap unit-tests/bootstrap.php unit-tests/PagesTest.php
```

**Comment by gohanman** [comment]
For longer-term use:
https://github.com/CORE-POS/IS4C/wiki/Unit-Testing
