### ISSUE TITLE
member discounts are being applied to refunds

### ISSUE THREAD

**Issue by pierced** [CORE-POS/IS4C#48]
Refunds should not be discountable.

Refund amounts are always entered as exact final dollar amounts, based on the original receipt.

If a $5 item is bought with a 20% discount and then returned, the cashier will do a return for $4 (the original discounted amount), not $5.

We can't assume that a given shopper's register discount percentage is the same at the time of the return as it was at the time of the purchase.

**Comment by flathat** [comment]
In the situation where someone bought something on a MAD day and returned it on a regular day you can:
Enter the member id: *number*ID
Enter the refund at the current price: *upc*RF
Total: TL
The equivalent of MAD-discount on the whole transaction: 15DA
Total: TL
Tender: ...
