### ISSUE TITLE
Customizing memlist

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#482]
What would be the recommended method for adding data to the member select list?  A co-op wants to be able to see the total amt. of equity invested  by each member# when they search for them at the frontend.

Would this be a plugin?  Or a custom edit to memlist.php?  The immediate need is simply to be able to see the current equity total + date last pmt. was made.

FWIW:  I could envision this as a plugin that would allow you to select various member-specific data points to include, or to customize the output in memlist.
- Total equity
- date last pmt. made (and/or date next payment due if available)
- % discount assoc. w/ member#
- memtype / Type
- check-writer eligible

to name a few.

**Comment by gohanman** [comment]
This could be done with a plugin-provided MemberLookup module. A member search runs any plugin-provided modules before the default one, and there are no restrictions on the labels. You could tack on whatever you want before/after the name (or even omit the name although I can't think of a case where that would make sense).

I think the main problems as it's currently implemented would be horizontal space and just general alignment. The ```<select>``` isn't tabular so trying to align info in columns for legibility would be extra work. Icons might be helpful conveying info at a glance without taking up lots of space, but per standards ```<option>``` tags aren't required to support anything but text.

Writing this info into custdata.blueLine seems like the best approach to me. The information would still be visible even after the memlist screen, and there wouldn't be any extra tables to sync to the lanes.

**Comment by gohanman** [comment]
e8517815128f36a51fa12fa2eb486365c93e501c

CustomerNotifications can be used here, above problems notwithstanding. Appending text to member search results isn't the prettiest UI approach but it works and given the constraints of ```<select>``` tags may be the most practical solution without redoing the entire list concept.

**Comment by gohanman** [comment]
Documented as notifications:
https://github.com/CORE-POS/IS4C/wiki/Customer-Specific-Notifications

I'm not worrying about limited CSS options with ```<select>```s, graphical icons, etc for the moment. My earlier comment about blueLine looks misguided now. Notifications (#519) work on blueLine, too.
