### ISSUE TITLE
Roadmap & Planning v1.4

### ISSUE THREAD

**Issue by gohanman** [CORE-POS/IS4C#483]
Version 1.3 is rounding into shape and should be released within the week. With that in mind I'd like to start discussing priorities for 1.4. I'm thinking of this as an informal poll as well as place for suggestions. Ideally I'd like to be a little less haphazard about what's going on upstream so [hopefully] other tracking development have a big picture view of where the commits they're seeing are headed.

## High Priorities (for me)
* Clean up whitespace across the board. I want to write a "unit test" that scans every single PHP file and throws an error any time there's a tab character or a carriage return. It's not really testing per se since there's no functionality involved, but automated testing on every posted commit will keep whitespace consistent moving forward. The reason I want to fix this is inconsistent whitespace makes merges and diffs unnecessarily complicated. Sometimes a bunch of lines (or even entire files) differ only in whitespace and it's a pain to track down actual differences.
* Get everything in the documentation directory into the [wiki](https://github.com/CORE-POS/IS4C/wiki) and add clear links in the existing docs pointing people to the wiki. The current split with information scattered about needs fixing ASAP.
* Reach a terminology conclusion on #471 renaming Fannie. Migrating documentation to the wiki with the current name intact just makes the down-the-road renaming project bigger. Might as well start dealing with it now.
* Formalize a new branching strategy. I've found it helpful having a dedicated version-1.2 branch. When 1.3 is released I'm going to make a dedicated 1.3 branch. Stepping back in time (so to speak) to address bugs works great without any merging back and forth between released versions and ongoing development. The version-x.y branches can just exist in parallel forever.

## Other Ideas
* Make errors (optionally) obtrusive instead of simply logging them. This would be strictly a developer feature. I've found Travis CI really helpful in that it emails me every time a unit test fails. Automation trumps remembering to manually check for errors. I'm imagining every logged error/warning/notice results in an email or something visible in Fannie's UI (or both). The goal would be reaching a point where error logs are normally empty rather than churning with random noise.
* Let POS submit logged errors to Fannie somehow for centralization of information.
* Revisit the dashboard concept from #369 and #370
* Finish contextual help content in Fannie. The new(ish) menu includes a "Help" entry but not all pages have content for it. The button needs to produce information in the vast majority of cases (minimum ~75%?) or users won't both clicking on it
* Write/merge a single BasicModel class that works with both POS and Fannie. Possibly also use a single model for tables that exist on both (e.g. departments, tenders, etc) rather than maintaining separate ones.
* Document NewMagellan better from a developer standpoint. I doubt everyone needs (or wants!) to learn C#, but more information about .NET framework version numbers vs Mono version numbers and how different build tools work might help people get up to speed faster. Protocols for interacting with different hardware - i.e., commands they understand and messages they send to POS - are also hard to figure out without digging around in both C# and PHP.

## Crazy Ideas
* End user bug-filing tools. Build a feedback form into Fannie that posts an issue to github. Put a feedback link in the layout somewhere so it's accessible from more-or-less every page.

-----------------

Add your own, or just give stuff thumbs up / thumbs down.

**Comment by joelbrock** [comment]
#### RE: Dashboard
here's a custom bit from co-op that i've seen and liked.
Shows transaction count and gross (or net) total, as well as a runining total for "today".  I might also add comps to last years DayofMonth as a %.
![fannie_-_the_is4c_backend](https://cloud.githubusercontent.com/assets/52835/6985680/cf8b05f4-d9ea-11e4-91a8-55cf49dcdbb1.png)
Would be great to see comps as a trendline store-wide AND/OR per department), indicating sales growth.  A super clear and simple way for ALL staff members to see the current "health" of the stores sales.

#### RE: your "crazy idea"
:+1: 

#### RE: documenting NewMagellan 
(although some of these are probably just suggestions for NewMagellan improvements)
- I am forever fussing with `auto_state_change = true | false` and "Communication: Direct | Messages".  Simplifying, clarifying, or obviating this seems worthwhile
- I'd like to know more about the graphic/logo uploading that got added in
- Setting a switch to log SOAP to a txt file i.e. `mono pos.exe -v -l /tmp/debug.xml`? 
- (this may well be impossible but would be __epic__ in terms of remote support and troubleshooting) Commands or someway to trigger keypresses of the _physical_ buttons, and perhaps even trigger a fake "swipe" event.  All via remote/SSH

**Comment by gohanman** [comment]
RE: Dashboard: I was thinking more along the lines of administrator system status - is everything running OK. Finding a single sales view that everyone like is probably a lost cause.

RE: NewMagellan
* It's a bigger project, but what **should** happen is ini.php should be replaced with ini.json and both PHP and pos.exe should read the same configuration file. Parts of this are actually done; I left it off the list on purpose to make this a less disruptive set of changes.
  * I would **love** to obviate this. Messages should be the only mode. It's just messy to push out changes without breaking things. I can update the code, but there's still always a compilation step to pick up changes.
* Make a file named logo.jpg. Put in NewMagellan directory. Restart driver. Mine's 181x200.
* The driver doesn't handle any of the SOAP communication; that's all on the PHP side.
* You can, sort of. "echo [device output] > ss-output/1". The lane'll pick it up and do whatever it would normally do in response to hardware output. The Messages communication mode essentially will trigger keypresses; that doesn't really fix reliability.

I think the basic route forward has to be using HidSharp to take care of reading/writing the device. If that isn't reliable, nothing built on top of it is going to be reliable. And I don't have the time, knowledge, or piles of spare hardware to debug different issues in different distros one at a time.

**Comment by gohanman** [comment]
Some updates:

* It's not *converting* documentation, but I added some *new* documentation on writing unit tests for currently untested code. https://github.com/CORE-POS/IS4C/wiki/Unit-Testing#comprehensive-example
* Tabs and carriage returns are gone in the master branch. The WhiteSpaceTest should ensure they stay gone.
* I spent some time updating POS and Fannie to Lane and Office (respectively) in the wiki documentation. I like "Lane" but I'm still somewhat unsatisfied with "Office". It's good enough in an eliminating-profanity sense but I wouldn't mind reconsidering that term again. I do still think a generic, descriptive term is the route to go but suggestions welcome.

RE: NewMagellan: it occurs to me I may have overlooked the stupidly obvious solution: make two different SignAndPay modules with the different behaviors. It doesn't solve nearly all the awkwardness involved, but at least you could simply **look** at the existing ports.conf to figure out how the system is currently configured rather than tinkering in code and recompiling to change settings.

**Comment by gohanman** [comment]
Following up on the NewMagellan stuff: ab5ea0f754b0760f42f921e45908fc3bbf98b424

There are now **three** different driver modules. There are no longer any "future" flags or recompiling to get different settings. The different modes of operation still exist (for now), but all configuration is controlled by which module is selected in ports.conf.

Since HidSharp is always included in compiled (even if it isn't used at run time), the compiler/runtime versions probably bump a bit. I'm using mono 3.2.8 at the moment. It's .NET 3.5 on the Windows side. This is circa 2007 tech so I don't feel I'm being too demanding.

Each driver module also prints information about itself on startup. Ex:
```
Loading Sign and Pay module
  Screen Control: POS
  Paycards Communication: Messages
  USB Layer: HidSharp
```
or
```
Loading Sign and Pay module
  Screen Control: Auto
  Paycards Communication: Direct
  USB Layer: Posix Device File
```
I'm hoping this alleviates some of the setup and configuration headaches. In the long term it would be better if the alternate versions went away, but I'd have to break backward compatibility somewhere.

**Comment by gohanman** [comment]
More NewMagellan: 2946bb43b58152c170da95833dafabbe6239d2af

On startup, the driver sends POS a command indicating which screen control mechanism its using. POS updates its configuration to match. Manual configuration on the POS side should no longer be necessary.

**Comment by gohanman** [comment]
Contextual help milestone: halfway!

![help-progress](https://cloud.githubusercontent.com/assets/426966/7262981/601d41ac-e843-11e4-8651-7e4dfc108cdf.png)

**Comment by gohanman** [comment]
Logging improvements:
4d4e607447640380de2f1b93dd9f15d0230456ac

Having CORE ship logs to a dedicated log server works nicely at a local level for centralized audit and review. It's not sufficient for the idea of end-user installations sending error info upstream. At minimum the transmission channel would need encryption, and some kind of anonymization would also be a very good idea.

![syslog settings](https://cloud.githubusercontent.com/assets/426966/7353186/4d23f3dc-ecd7-11e4-9e36-e03fd19e72d8.png)

![kibana](https://cloud.githubusercontent.com/assets/426966/7353187/596b83ee-ecd7-11e4-848b-86eccc34484b.png)

Also, Logstash + Kibana makes for awesome centralized logging.
