### ISSUE TITLE
Agenda Idea for 2015-04-03 - CORE 1.4

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#484]
I suggest we discuss issue #483 "Roadmap & Planning v1.4"

Other Agenda Ideas, not yet scheduled:
+ Inventory - Perpetual and Count
+ Plugins and the Coop Cred plugin

Please add your agenda ideas.

**Comment by gohanman** [comment]
Expanding a bit on the point about branching strategy:
https://github.com/CORE-POS/IS4C/wiki/Git-Practices
