### ISSUE TITLE
Agenda Idea for 2015-04-10 - So you want to write a plugin: the Coop Cred experience

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#488]
In this issue I want to:
- introduce a plugin I wrote recently
- describe the plugin architecture and how I used it
- describe some of the issues that came up along the way
- encourage you to write one

The Co-op Cred plugin is for creating, funding and managing debit accounts for members, a form of tender. The initial type at WEFC Toronto was developed to make it possible for people in an addiction recovery program and on social assistance to buy more and better food than they would otherwise be able to afford. It is one example of an alternative currency that the co-op uses to get around some of the restrictions of regular tenders. It can be distributed in a way that avoids the clawback that can apply to income of people on social assistance. This is a big issue because after paying rent most social assistance recipients have very little money left for food. Because there are different Coop Cred Programs not all of which are associated with ability to pay there is relatively little stigma associated with using it at cash.

Technically it is based on the CORE Store Charge ("A/R") scheme which lets members "run a tab", except that it is a Prepay system in which there is a negative balance in the member's account which purchases may bring to no higher than 0. It has one feature that StoreCharge/Prepay systems don't have: a Program Account, or Banker, a pseudo-member whose role is to receive external inputs of money from funders and transfer money from that account to Program Members. The designers of Co-op Cred were concerned about fraud and required that the whole Program and individual membership be easy to suspend if a problem came up.

There can be any number of Programs, each with a different Bank, and different rules about putting money in and transferring to other members. Each Program has a dedicated Tender (taking the role of `MI` for Store Charge) and Department for receiving inputs (taking the role of the Store Charge Department). Co-op members can belong, have a balance in, more than one program.
WEFC currently has six programs including the one mentioned for people on social assistance,
- one for diabetics (also on social assistance)
- a way of being repaid for loans to the co-op
- a way of giving small honorariums to volunteers
- a way of paying for services to the co-op (I have Co-op Cred earned this way), which also effectively discounts the cost of the service to the co-op.

Plugin basics
A CORE plugin is some code that lives apart from the main code base in e.g. `fannie/item/` or `fannie/mem/` in a subdirectory of `fannie/modules/plugins2.0`, or lane-side, `pos/is4c-nf/plugins`, for example `CoopCred/`.

It is generally not changed as part of upgrades to the main CORE code base. (A side effect of this is that some changes to CORE, for example the new menu layout and Bootstrap encoding can make your plugin not integrate with other modules and basically be too strange-looking for anyone to want to use if not technically inoperable.)

In the plugin directory is a program of the class `FanniePlugin` that CORE's plugin system (`Install > Plugins`) can find and give the option to Enable the plugin. A plugin has to be "enabled" before it can be used; before enablement the code except for the plugin control file is invisible. When the plugin is first enabled it may create a database and/or tables.

CORE's object-oriented structure is a big part of the implementation of plugins. The most important feature of that for this discussion is the mechanism for finding modules that are identified as being of a certain type, that is, subclasses of a certain class, such as membership features or end-of-receipt messages. This has already been mentioned in how `Install > Plugins` finds plugins, but after the plugin is enabled all of the other finding mechanisms will also scan the plugin directory for classes of a given type. (A side-effect of this is that every .php file in a plugin directory tree must be scannable and includable without breaking the scanning mechanism. I had some trouble with this which was partly addressed by unit testing and partly by using non-.php extensions for non-class files.)

Plugins can have different levels of interaction with the main CORE systems.  Some are freestanding, with little or no interaction, some are completely integrated, consisting only of classes that appear next to existing classes such as, say, member editing modules, the blocks in the Member editor.  Others, such as Co-op Cred, have both integrated and separate parts. Both back end and lane support plugins; Co-op Cred has both.

When I started working on the Co-op Cred system most of the code was in the plugin directory but it also needed some changes in the main CORE  code bases.  I brought some of these up as issues and they were usually resolved in a way that made it possible for the code to be in the plugin instead of the main code. I became aware that is what makes a good plugin architecture and implementation.
If you're developing a plugin I encourage you to bring places where the CORE code would need to be changed forward as issues in this queue.

When all or almost all of the code for a system can reside in the plugin it becomes a pleasant little world of its own that can be developed according to its own needs still participate in main body of CORE.  Co-op Cred got cozier that way as time went on.

I benefited from progress that was made before I got around to asking: originally the MemberModule class definition was not under `classlib2.0/` and I had to make a non-standard symlink to it in order for it to be available when I needed it, which led to some odd complaints from php.

Outstanding item
This is an example of the kind of thing that can be a problem for a plugin that needs to do something similar to what the main code does but in a different environment.  I got around it by duplicating a standard class within the plugin but it would probably be better to try to get the capability upstream:  The class `SyncLanes`, for copying a table to lanes, only allows for the table to be only in one or the other of `$FANNIE_OP_DB` or `$FANNIE_TRANS_DB` but the plugin's tables are in different ones (server and lane). I cobbled together a way around it in class within the plugin that extends `SyncLanes` without needing to change the CORE code.  I would rather use a CORE class that was able to do it since this is not really a situation that is unique to my plugin.

Configuration.
The `FanniePlugin` and `[Lane]Plugin` classes support an array `$plugin_settings` that typically include the name of a database to create to isolate the plugin's tables, but can contain anything you might want to configure and refer to later.  The setting names are array keys and are system wide and so have to be chosen with care. I began to need a number of configurable values to allow Co-op Cred-related items such as tenders and departments to be identified and managed. At first I was going to make them `$plugin_settings` and it occurred to me that that simple array could be an array of arrays with multiple items effectively tagged as belonging to a particular plugin, the key of the first-level array. I still think that's a good idea, but I didn't want the configuration items I had in mind to be in the `Install > Plugins` process and so made a special table and editing form for them. The values themselves are important to making Co-op Cred fit in the tender, department and membership schemes another co-op might use. (There may be a few more WEFC_Toronto-specific values in the plugin that I need to move to that mechanism.)

CORE-Admin-side Co-op Cred consists of:
A database with tables:
CCredPrograms - Identifies Programs, links them with tender and department, activates/deactivates
CCredMemberships - Extends custdata to link the member to the program and hold the balance
CCredConfig
Tables and views like the core_trans.ar_* ones, except that they refer to the member in a particular Co-op Cred program
CCredHistory*
CCredLiveBalance
CCredMemCreditBalance

Model files for all of these.
Andy added view-management to database management by model to accommodate this

It uses and updates records in the main CORE tables:
tenders
departments
custdata

An editor for Programs, based on the CORE Departments editor
  It re-creates the views that need enumerated lists of tenders and departments
  Updates lanes.
  Can suspend a Program immediately.
A membership module that appears in the CORE membership editor
  Adds a Member to Program, monitors balances
  Updates lanes.
  Can be used to suspend a Membership, the ability to use a type of Co-op Cred, immediately
A configuration editor

Utilities for transferring money, like the ones for StoreCharge and Prepay

Reports of
- Program Events: Inputs and Disbursements
- Summary of activity of all Members of a Program
- List of transactions for each member

Automated Tasks like the similar ones for A/R for
- updating lanes with new balance data
- updating CCredMemberships end-of-day balance data
- refreshing the lanes with Program and Membership tables, like the CORE `lanesync`

Lane Co-op Cred has:
A database with tables
CCredPrograms
CCRedMemberships

Tender module that all Co-op Cred tenders use
Department module that all Co-op Cred input departments use
Report, at cash, of all balances of a user
Receipt balance report
Receipt signature slip
Tendering list of only Co-op Cred tenders

**Comment by gohanman** [comment]
Couple follow-up commits on the help dialog discussion:
* Make modal dialog draggable (hat tip Joel; jQuery-UI) 678fcda2378179677f670e70ff3c28d89f76b7db
* "Pop Out" button that kicks modal content into a separate window. 3b9f0aa24b08ec15ec0c92173c65a10864a08893
