### ISSUE TITLE
changelog, or similar listing of what's different in each version

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#491]
I'd consider this a nice-to-have. 
End-users might consider it essential?

If there is currently a way to see this easily on github somewhere, sorry.  Can you show me?

**Comment by gohanman** [comment]
https://github.com/CORE-POS/IS4C/releases

Clicking the version number (not the commit hash) shows that tag message. I try to be pretty verbose. I see a separate "Release Notes" mechanism under Tags (but oddly not Releases). I'm not quite sure how that works.

Concat-ing the different tag messages into one big CHANGELOG file probably wouldn't be difficult if that's something you'd find useful.

**Comment by joelbrock** [comment]
Nope!  This is great!  
face, meet palm.
