### ISSUE TITLE
Agenda Idea for 2015-04-17 - Everything Inventory

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#492]
With the recent March 31 end of the fiscal year for many co-ops, inventory has been on our minds and maybe kept us up late.  The topic has also come up recently as an extension to the transactions-and-reports base of POS.  There are many facets to it and constraints and points of view on how it should be done.

Inventory support is a work in progress in CORE.  Andy Theuninck's [*CORE-POS Whitepaper on Inventory*] (https://drive.google.com/file/d/0B24ZJQ7zS83qakkxSXhYMHFUMjA) (PDF) is the best general starting point, but today we can go into detail on some of the issues below, or others that are on our minds.

The whitepaper begins:
>Inventory is a very simple concept: how much product do we have on hand, right this moment? The devil is in the details as the number constantly fluctuates.
>
>Inventory can also be understood as a means to an end: items on hand is merely one component of measuring whether or not a store is making margin, overall or on an item or group of items.
>
>So how do co-ops approach this problem? There are two somewhat distinct methods:

Inventory Count vs/and Perpetual Inventory
+ Why one or the other, or some of each
+ tradeoff: Cost vs Complete, Current Knowledge

#### Inventory Count Tools
+ Shelf Audit Plugin    
The interface is formatted for use on a portable device with a handheld scanner.

![screenshot_041615_012257_am](https://cloud.githubusercontent.com/assets/1131922/7174487/29d92400-e3d7-11e4-98c2-261b5f00b1cb.jpg)
+ Other tools, services used

#### Perpetual Inventory
+ What it involves: counting everything all the time
+ What CORE currently offers
   + The essential `vendorItems` `<=>` `products` link is [described in detail] (https://github.com/CORE-POS/IS4C/wiki/Products-and-Vendors)
   + `PurchaseOrder` and `PurchaseOrderItems`
       + `[Ordered]quantity`
       + `receivedQty`
   + For Inventory, the crucial number is `receivedQty`
   + Purchase Orders:
      + created
      + loaded
          + from external systems
      + from invoices/manifests
           + data capture issues
+ What remains to be developed
   + Reconciling purchase orders against invoices/manifests
   + Comparing purchase orders to movement
+ Receiving use cases
   + floor
   + backoffice

#### Shrink recording at Cash
  + `SK`    
![screenshot_041615_122325_am](https://cloud.githubusercontent.com/assets/1131922/7174024/29995d82-e3cf-11e4-9471-83a0f837de25.jpg)      
`trans_status` = `Z` for all items on the screen

  + Returns and shrink: `RF###`     
![screenshot_041615_123157_am](https://cloud.githubusercontent.com/assets/1131922/7174099/1d894d76-e3d0-11e4-82f7-8b302865d30c.jpg)     
`description` `RF: Spoiled` applies to next item, but for it `trans_status` = `R`, not `Z`
  + StoreCharge accounts for intra-co-op transfers
     + A Shrink member account

#### Backend Shrink Recording
+ Since the whitepaper was written tools have have been added with finer-grain notation of reasons:    
![screenshot_041715_035643_am](https://cloud.githubusercontent.com/assets/1131922/7198113/e6d2c1a8-e4b6-11e4-8e68-644e7dc9938c.jpg)    
This (`fannie/item/shrink/ShrinkTool.php`) adds `trans_status` =  `Z` items.    
+ There is also a tool for editing current-day shrink items.
+ Co-ops can have their own set of Reasons for shrink.

#### Monitoring margin
+ Reports
      + Movement Reports
      + Margin Movement
+ Monitoring loss

#### Other ways to achieve the objective:
+ Monitoring cost
+ Spot-checking received orders

#### What to implement next?
+ What is important to your co-op?

**Comment by gohanman** [comment]
Minor addition: there's a back-end shrink entry tool, too @ item/shrink/ShrinkTool.php. Called "Shrink Entry" in site map.

**Comment by flathat** [comment]
Thanks. Incorporated above.

**Comment by flathat** [comment]
One of the points that came up in the discussion is that there are many possible sources for items-ordered and items-received.  One is systems external to CORE such as spreadsheets.  Our guest last week, james Partanen, showed me a bit of code for direct communication between Excel and CORE.  Below is an Excel macro in VBA.
Running it requires:
+ an ODBC driver which you can [download] (https://dev.mysql.com/downloads/connector/odbc/)
+ selecting Microsoft ActiveX Data Objects 2.8 in VBasic > Tools > References

In the spreadsheet there is a graphical button with the macro assigned to it in cell `O2`; the macro gets the whole `employees` table and displays it starting at `C2`.

Presumably CORE's `PurchaseOrder` and `PurchaseOrderItems` could be added to with a similar macro.

```VBA
'f
' adodb_mysql_test()  Test connection to MySQL DB via ADODB
'
' For this to work MYSQL drivers must be installed on the
' computer running this macro.
'
Sub adodb_msql_test()

    'd
    ' Make sure Microsoft ActiveX Data Objects 2.8 is selected in VBasic > Tools > References
    ' to define the ADODB objects
    '
    Dim myRecordSet As ADODB.Recordset
    Dim conn As ADODB.Connection
    
    Dim ServerName As String
    Dim DatabaseName As String
    Dim UserID As String
    Dim Password As String
    Dim SqlQuery As String
    Dim ConnectionString As String
    
    Dim fCount As Integer
    
    'l
    ' This information is unique to our DB Connection.
    '
    
    ServerName = "mycore.coop"
    DatabaseName = "core_op"
    UserID = "root"
    Password = "mypassword"
    
    'l
    ' Define the connection string.
    '
    ConnectionString = "Driver={MySQL ODBC 5.3 UNICODE Driver};" & _
                       "Server=" & ServerName & ";" & _
                       "Database=" & DatabaseName & ";" & _
                       "Uid=" & UserID & ";" & _
                       "Pwd=" & Password & ";"
    
    'l
    ' Set up a query.
    '
    SqlQuery = "SELECT * FROM employees"
    
    Set myRecordSet = New ADODB.Recordset
    Set conn = New ADODB.Connection
    
    'l
    ' Open a conneciton to the DB.
    '  Fails at this point
    '
    conn.Open ConnectionString
    
    'l
    ' Run the query; records are assigned to an ADODB recordset.
    '
    myRecordSet.Open SqlQuery, conn, adOpenStatic
    
    'l
    ' Interact with the recordset via VBA Object methods.  Loop copying field names first.
    '
    For fCount = 0 To myRecordSet.Fields.Count - 1
     Sheets("Sheet2").Cells(2, fCount + 3) = myRecordSet.Fields(fCount).Name
    Next

    'l
    ' Copy recordset data en masse.
    '
    Sheets("Sheet2").Range("C3").CopyFromRecordset myRecordSet
    
    'l
    ' Tidy up.
    '
    myRecordSet.Close
    Set myRecordSet = Nothing
    conn.Close
    Set conn = Nothing

End Sub

```
