### ISSUE TITLE
BUG: rename var in CronManagementPage

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#493]
foreach ($tab['jobs'] as $job) {
$ret .= sprintf('`<tr>
<td><input type="checkbox" name="enabled[]" %s value="%d" /></td>
<td><input type="text" size="2" name="min[]" value="%s" /></td>
<td><input type="text" size="2" name="hour[]" value="%s" /></td>
<td><input type="text" size="2" name="day[]" value="%s" /></td>
<td><input type="text" size="2" name="month[]" value="%s" /></td>
<td><input type="text" size="2" name="`__wkdy__`[]" value="%s" /></td>
<td><input type="hidden" name="cmd[]" value="%s" />%s</td>
</tr>`',
'checked',$i,
$job['min'],
$job['hour'],
$job['day'],
$job['month'],
~~$job['year'],~~
$job['__wkdy__'],   // change this from `year` to `wkdy`
$job['cmd'],
$job['cmd']
);
$i++;
}

**Comment by gohanman** [comment]
e04de33632ce0f1ac051b8a9db0a4e7474566c13
