### ISSUE TITLE
Agenda Idea for 2015-04-24 - Everything Inventory part 2: The Shrink Show

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#495]
We had a good discussion last week about Inventory count and the items-received-capture aspects of perpetual inventory but didn't really get to the shrink-capture aspects of it. There any many issues and techniques so I thought we might return to that today. #492 

Is Friday, at the current time (11 CT) of this conference, good for you?  What would be better? Please comment in person on Friday or at #494.

There is always an opening in these calls for questions and issue that are on your mind; the Agenda is not a constraint.

**Comment by gohanman** [comment]
Search! Pages should be found via search! Credit @joelbrock
