### ISSUE TITLE
Keeping Equity History current

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#496]
For stores looking to rely more heavily on CORE member mgmt tools this could be a useful adjustment.

Currently EquityHistoryTask populates a summary table from record in dlog_15.  The task runs overnight.  Meaning any of "todays" equity sales, and any adjustments (conversions/transfers) made in Fannie are not visible until "tomorrow".

Equity total in Fannie is always current.  But Equity history report is always 1-day behind.

Propose adding a UNION SELECT to EquityHistoryTask to also look at "todays" (dtransactions) equity transactions.  This task could then be run every minute, or 5 minutes, to keep the equity history in line with the equity total.

**Comment by gohanman** [comment]
Er, you want to union "today" and stockpurchases. That's how the total is kept current. There's no need to run the task constantly.

**Comment by gohanman** [comment]
c51e18ebcb968a6105e2e26f2b4020a2b159a64e
