### ISSUE TITLE
New Credit Card Integration troubleshooting 

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#499]
See compilation error below.  no pos.exe is created.  
How to resolve the namespace issue?  
running mono-complete 3.2.8

`pos-admin@CORE-TEST:/var/www/html/RVM/pos/is4c-nf/scale-drivers/drivers/NewMagellan$ sudo make`
gmcs -target:library /r:System.Drawing.dll -out:DelegateForm.dll DelegateForm.cs
cd HidSharp; make
make[1]: Entering directory `/var/www/html/RVM/pos/is4c-nf/scale-drivers/drivers/NewMagellan/HidSharp'
gmcs -target:library -unsafe -out:HIDSharp.dll ReportDescriptors/GlobalItemTag.cs ReportDescriptors/CollectionType.cs ReportDescriptors/ItemType.cs ReportDescriptors/MainItemTag.cs ReportDescriptors/LocalItemTag.cs ReportDescriptors/Parser/ReportSegment.cs ReportDescriptors/Parser/ReportType.cs ReportDescriptors/Parser/LocalIndexes.cs ReportDescriptors/Parser/ReportMainItem.cs ReportDescriptors/Parser/IndexList.cs ReportDescriptors/Parser/Report.cs ReportDescriptors/Parser/IndexBase.cs ReportDescriptors/Parser/ReportDescriptorParser.cs ReportDescriptors/Parser/IndexRange.cs ReportDescriptors/Parser/ReportCollection.cs ReportDescriptors/EncodedItem.cs ReportDescriptors/Units/TimeUnit.cs ReportDescriptors/Units/Unit.cs ReportDescriptors/Units/UnitSystem.cs ReportDescriptors/Units/TemperatureUnit.cs ReportDescriptors/Units/LuminousIntensityUnit.cs ReportDescriptors/Units/CurrentUnit.cs ReportDescriptors/Units/MassUnit.cs ReportDescriptors/Units/LengthUnit.cs ReportDescriptors/DataMainItemFlags.cs HidDevice.cs Throw.cs AsyncResult.cs Properties/AssemblyInfo.cs HidStream.cs HidDeviceLoader.cs Platform/HidManager.cs Platform/Libusb/LibusbHidManager.cs Platform/Libusb/NativeMethods.cs Platform/MacOS/MacHidManager.cs Platform/MacOS/MacHidStream.cs Platform/MacOS/MacHidDevice.cs Platform/MacOS/NativeMethods.cs Platform/Utf8Marshaler.cs Platform/HidSelector.cs Platform/Windows/WinHidManager.cs Platform/Windows/WinHidDevice.cs Platform/Windows/WinHidStream.cs Platform/Windows/NativeMethods.cs Platform/Unsupported/UnsupportedHidManager.cs Platform/Linux/LinuxHidStream.cs Platform/Linux/LinuxHidManager.cs Platform/Linux/LinuxHidDevice.cs Platform/Linux/NativeMethods.cs
ReportDescriptors/EncodedItem.cs(78,21): warning CS0219: The variable `bytes' is assigned but its value is never used
HidDevice.cs(58,30): warning CS0168: The variable `e' is declared but never used
Compilation succeeded - 2 warning(s)
make[1]: Leaving directory `/var/www/html/RVM/pos/is4c-nf/scale-drivers/drivers/NewMagellan/HidSharp'
cp HidSharp/HIDSharp.dll .
gmcs -target:library /r:System.Drawing.dll -r:Mono.Posix.dll -r:HIDSharp.dll -out:USBLayer.dll USBLayer.cs USB-Posix.cs USB-HidSharp.cs
gmcs -target:library /r:System.Drawing.dll -r:Mono.Posix.dll -out:ParallelLayer.dll ParallelLayer.cs Parallel-Posix.cs
gmcs -target:library /r:System.Drawing.dll -out:Bitmap.dll BitmapConverter.cs
gmcs -define:MONO -target:library /r:System.Drawing.dll \
		-r:DelegateForm.dll -r:USBLayer.dll -r:ParallelLayer.dll -r:Bitmap.dll \
		-out:SPH.dll \
		SerialPortHandler.cs SPH_Magellan_Scale.cs SPH_Parallel_Writer.cs SPH_IngenicoRBA_IP.cs \
        SPH_SignAndPay_USB.cs SPH_SignAndPay_Auto.cs SPH_SignAndPay_Native.cs \
		SPH_IngenicoRBA_USB.cs SPH_IngenicoRBA_RS232.cs SPH_IngenicoRBA_Common.cs
gmcs -target:library /r:System.Drawing.dll -r:DelegateForm.dll -out:UDPMsgBox.dll UDPMsgBox.cs
gmcs -target:exe /r:System.Drawing.dll -r:SPH.dll -r:DelegateForm.dll -r:UDPMsgBox.dll -out:pos.exe Magellan.cs
Magellan.cs(49,7): __error CS0246: The type or namespace name `Discover' could not be found. Are you missing an assembly reference?__
__Compilation failed: 1 error(s), 0 warnings__
make: *** [all] Error 1

**Comment by gohanman** [comment]
I can fix the Makefile, but in the meantime xbuild probably works.
https://github.com/CORE-POS/IS4C/blob/master/pos/is4c-nf/scale-drivers/drivers/NewMagellan/README

**Comment by joelbrock** [comment]
xbuild worked like a dream.

and now so does the IDTech.
Currently using USB module.  I will figure out how to stress test this.
I will test the Auto module as well.

**Comment by gohanman** [comment]
Auto probably doesn't work as well. It uses the old-style USB communication
that's problematic on linux.

**Comment by gohanman** [comment]
Makefile fixes: ecb54514530dfb4d965a7e0a1daf8cdd39e329d3
