### ISSUE TITLE
Receipt Grouping to include "you saved" lines

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#502]
Ring 2 identical items.  On sale.
Then scan vendor coupon.
![2015-05-12 12 55 22](https://cloud.githubusercontent.com/assets/52835/7593233/9b81f27e-f8a6-11e4-8df7-ef8f92d8e849.jpg)

On a grouped modular receipt the items both show up on one line (as intended) but there are still 2 "> you saved $X.XX <" lines.  These should be combined into one.
![2015-05-12_12_55_52](https://cloud.githubusercontent.com/assets/52835/7593284/f7909458-f8a6-11e4-9f82-d533113d1f26.jpg)

**Comment by joelbrock** [comment]
Perhaps also indicate _why_ you saved.  i.e. "> ITEM ON SALE - You Saved $X.XX <"

**Comment by joelbrock** [comment]
NOTE:  this was using Modular receipts with the GroupSavings Sorting Mod (all other mods Default)

**Comment by joelbrock** [comment]
I may have answered my own question..... I see that `translog.ltt_grouped` is building the receipt in the desired fashion.  Receipt type "Grouped (static,legacy)" accomplishes this for me.

**Comment by gohanman** [comment]
So, meta commentary: this has been happening for at least a year, probably longer. I would not be surprised if I've given out in the neighborhood of a 100k receipts with this particular oddity without comment from anybody. The problem should still get fixed of course, but I find it interesting in terms of how closely people are looking at receipts - or differences in behavior in different markets.

**Comment by joelbrock** [comment]
RE: my second note: https://github.com/joelbrock/HARVEST_CORE/commit/54d62ea0b1da2277de65fd2e805593fb842b5cd2

Which matches up to the language used in this mod: https://github.com/joelbrock/HARVEST_CORE/commit/dec6d54b079f4e6912c049fc4e0b855b5164416e

So the body of the rcpt. says "Item On Sale" and the YOU SAVED portion says "Items On Sale" so presumably its easier for customers/cashiers to idetify where their savings came from.

**Comment by gohanman** [comment]
This addresses the basic issue so that item and savings lines are are joined consistently. I didn't do anything with the description text. From a code aesthetics standpoint, that should really happen in ItemReceiptFormat when the final output string is built.

**Comment by gohanman** [comment]
Basic fix included in 1.4
