### ISSUE TITLE
Tender IC calls HouseCouponList

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#503]
...and i can see that this is intended.  However, IC is a common TenderCode for Instore Coupons.  And if a store doesnt have any House Coups. or if a cashier hits the House Coupon button w/o entering an amount an empty select menu appears.

Setting Instore Coupon to NoDefaultAmountTender does __not__ prevent the empty select box from appearing
![image](https://cloud.githubusercontent.com/assets/52835/7596149/ac493b04-f8b9-11e4-92e2-d813fd752516.png)

**Comment by joelbrock** [comment]
Also, 
https://github.com/joelbrock/HARVEST_CORE/commit/34811e500be8b630618dc27ce6f274479a8bcb81

**Comment by gohanman** [comment]
Hm. "Reprint". Nice copy/paste, me.

Is the goal here "don't show the menu if it's empty" or "add some option to disable this menu entirely"? The former certainly makes sense to me given that's how things like reprints and suspended transactions already work.

**Comment by joelbrock** [comment]
The goal is for IC{ENTER} w/o and amount preceeding it to do this:

![image](https://cloud.githubusercontent.com/assets/52835/7599545/fd2e08f8-f8d0-11e4-9d80-7bb904bbf4eb.png)

Which is how CP{ENTER} (w/ no amount preceeding it works)

**Comment by gohanman** [comment]
I guess the difference from my perspective is that POS knows about every in-store coupon in existence where as that's not the case with manufacturer coupons. There's no equivalent way to present something like this for CP:
![coupons](https://cloud.githubusercontent.com/assets/426966/7599643/7f7bc8f2-f8c9-11e4-9a23-4817acdc0499.png)

Disabling the functionality via configuration isn't particularly difficult; I just wanted to make sure that was your intent.

**Comment by joelbrock** [comment]
### NO ACTION NEEDED! 

contents of houseCoupon.description were NULL, and the query for this menu requires a description.  

This menu is actually an _improvement_ once the houseCoupons table is properly populated.

**Comment by gohanman** [comment]
Sweet, that's kind of what I was hoping.
