### ISSUE TITLE
Restrict equity PLUs to member-only

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#504]
I imagine this being keyed off the departments.memberOnly field.  Rather than having a new field in products table and another piece of data to maintain in another place.

A PLU in a department marked as memberOnly > 0 would trigger the same restrictions that an open ring to an EquityWard department currently does.

Is that easy to accomplish?

**Comment by joelbrock** [comment]
alternatively, expanding EquityWarnDept to apply to PLU'd items in an equity  department would be a good solution too.

Currently in testing EquityWarnDept is only kicking in on open rings to an equity department.

```sql
mysql> SELECT * FROM specialdeptmap;
+-----------------------+---------+
| specialDeptModuleName | dept_no |
+-----------------------+---------+
| EquityWarnDept        |      71 |
| EquityWarnDept        |      74 |
+-----------------------+---------+
2 rows in set (0.02 sec)

mysql> select * from products where upc = 1230\G
*************************** 1. row ***************************
                   upc: 0000000001230
           description: EQUITY - $25
                 brand: NULL
        formatted_name: NULL
          normal_price: 25
           pricemethod: 0
            groupprice: 0
              quantity: 0
         special_price: 25
    specialpricemethod: 0
     specialgroupprice: 0
       specialquantity: 0
         special_limit: NULL
            start_date: NULL
              end_date: NULL
            department: 74
                  size: NULL
                   tax: 0
             foodstamp: 0
                 scale: 0
            scaleprice: 0
          mixmatchcode: 0
              modified: 2012-06-08 15:52:46
            advertised: 0
            tareweight: 0
              discount: 0
          discounttype: 0
line_item_discountable: 0
         unitofmeasure: NULL
               wicable: NULL
          qttyEnforced: 0
            idEnforced: 0
                  cost: 0
                 inUse: 1
               numflag: 0
               subdept: 0
               deposit: 0
                 local: 0
              store_id: 0
     default_vendor_id: 0
     current_origin_id: 0
                    id: 126324
```

**Comment by gohanman** [comment]
Fix for the latter SpecialDept suggestion: cfd4dd98f2de0fd4361451d7e0be41d611cc0190

**Comment by joelbrock** [comment]
Hrm.  That appears to have worked....a little too well.  Now it wont ring equity purchases for non-owners, __OR__ owners.

**Comment by gohanman** [comment]
That's certainly odd. It does require entering the member # before the equity item/ring - otherwise it cannot verify the person is an owner.

**Comment by joelbrock** [comment]
Tested with NO member #, the NON-member #, and then with an active member #.

In all 3 cases the alert comes up.  

![2015-05-13 10 46 45](https://cloud.githubusercontent.com/assets/52835/7613230/85d6f1ba-f95d-11e4-9a6e-5d4bee710ee5.jpg)

Here is the record for the member i am testing with:
```sql
mysql> SELECT * FROM custdata WHERE cardno = 156319\G
*************************** 1. row ***************************
          CardNo: 156319
       personNum: 1
        LastName: LEWONTIN
       FirstName: AMY
        CashBack: 60
         Balance: 0
        Discount: 0
MemDiscountLimit: 0
     ChargeLimit: 0.00
        ChargeOk: 0
     WriteChecks: 1
    StoreCoupons: 1
            Type: PC
         memType: 1
           staff: 0
             SSI: 0
       Purchases: 0
  NumberOfChecks: 0
      memCoupons: 0
        blueLine: 156319: Welcome Back! Renew Now For The Next Year!
           Shown: 1
      LastChange: 0000-00-00 00:00:00
              id: 2176731
```

**Comment by gohanman** [comment]
Beats me. Your data all looks correct. It should be requiring a member with
custdata.Type='PC'. That's working for me so I'm not really sure how to
help.

**Comment by joelbrock** [comment]
ok, i figured it out.  sometimes it's helpful to know that Andy is stumped.  THat means try __everything__

**Comment by gohanman** [comment]
If any part of **everything** needs to be reported back upstream, feel free to keep adding comments to this issue.
