### ISSUE TITLE
Standardizing Department Form Behavior

### ISSUE THREAD

**Issue by gohanman** [CORE-POS/IS4C#509]
I didn't *quite* have this wrapped up in time for the call...

I've been working on refactors so that sets of super department + department + sub department form elements are drawn via an API method (specifically FormLib::standardDateFields). The initial goal is just to have consistent behavior across all reports. Some characteristics could also be configurable with the logic properly centralized.

This high-quality diagram highlights the section I'm talking about.
![dept fields](https://cloud.githubusercontent.com/assets/426966/7776159/7d562ed4-007e-11e5-887a-bcccc523e8e6.png)

Now the question is how this thing should behave. Here's what I'm proposing:

### Super Department
* Contains a "blank" entry. Users can just skip this field entirely and select a department or departments if they want. A mandatory hierarchy might be simpler but I'm hesitant to change *really* long-standing behavior that some users are accustomed to.
* Contains special entries for "All Retail" and "All". By convention "All Retail" is everything except super department zero and "All" is everything.
* Changing the super department selection filters both the start and end department boxes. The start and end are automatically set to the lowest and highest department numbers (respectively). I think this is the most logical behavior. If the user selects a super department and a date range and doesn't touch any other controls, they probably want to see everything in that super department.

### Department
* Probably has largest potential for configurability.
  * An option to use a multi-select instead is the most obvious although that will require a bit more work on the reports that use this form.
  * Omitting the department number in the dropdown would be simple. I don't think the text input for department number needs to go away. As long as the two options are tied together users can pick whichever they prefer.
* Changing the department selection updates the list of available sub departments

### Sub Departments
* CORE hasn't exposed sub departments in reporting UIs for very long or in very many places. I think we can jump straight to a multi-select without worrying about backwards compatibility here. 
* Sub departments are not automatically selected when the field populates. Items are not required to have a sub department. Similar to above, if the user selects a super department and department(s) without ever touching the sub department field, they should see all items from those department(s).

Other opinions welcome.

**Comment by joelbrock** [comment]
Fully in support of these enhancements!

Additional suggestion:  Easily configurable nomenclature.  
I believe that SPINS hierarchy is like this:
 1. Department 
 2. Category
 3. Subcategory 
But, as we've seen, this varies from store-to-store.  Maybe the answer is to just use the .pot files.  But not sure how deeply integrated those are into the Fannie forms, report headers, everywhere else, etc. yet.

**Comment by gohanman** [comment]
I can see the appeal. However, what concerns me about making this
configurable is writing documentation for this stuff becomes substantially
more difficult. If "department" means something different at different
places, we cannot define that term in generic documentation or some readers
would be misled. Inventing yet another term and expecting readers to
mentally map the documentation terminology back to their internal
terminology sounds awful. It's an extra burden on the reader, obviously,
and picking terms that would never conflict with local usage probably means
really contrived or weird terminology in the docs.

Granted, documentation remains a work in progress, but if good
documentation is a goal (and I think it should be) configurable terminology
creates serious headaches. I think the least confusing approach in the long
run is using consistent, well-defined terminology - even if it requires a
local adjustment in the short term.

**Comment by flathat** [comment]
I tend to agree with Andy about not having the terminology locally configurable.  Department (the middle tier) is the one that is mandatory. I like SuperDept because it implies the relationship to the base, Dept, and SubDept for the same reason. One has to learn that SuperDept membership is an attribute of the Dept, not the item.  I could live with SuperDept being called Category instead but prefer the current term.

I can imagine wanting a Dept to be in more than one SuperDept-level grouping, but I think currently that would cause trouble where one goes up the hierarchy from Dept to extend to the SuperDept.

My actual experience with SubDepts is small. The value is assigned to the item in addition to the Dept and is, or should be, restricted to SubDepts connected to the Dept in the database. As it is, SubDept alone, wihtout Dept, is not assigned, is not assigned and expected to imply Dept the way Dept implies SuperDept.

A multi-select for Departments would, for the Dept sets I've used, generally be much more useful than a range because consecutive Depts are seldom actually related.  If a range is used "End" should default to same as "Start", and changing Start should change End, because a single Dept is almost always what is wanted.

The use of the text Dept input may need some explaining.  I seem to remember forms on which it either doesn't work or doesn't do what I expect it to (change/override the value of the select).

**Comment by gohanman** [comment]
> I can imagine wanting a Dept to be in more than one SuperDept-level grouping, but I think currently that would cause trouble where one goes up the hierarchy from Dept to extend to the SuperDept.

This is already the case, actually. The only catch comes in the context of storewide sales. If department 100 is part of both super departments 1 and 2 and you're looking at total store sales by super department, those department 100 sales will only appear in super department 1. Reporting the same sales in both super departments would throw off the total. But for smaller slices - if you're looking at just super department 1 or just super department 2 - then it's perfectly OK for department 100 to appear in both.

>If a range is used "End" should default to same as "Start", and changing Start should change End, because a single Dept is almost always what is wanted.

I disagree with the first half but agree with the second half. Say for example super department 1 contains departments 100 through 105. If I pick super department 1, the "Start" should jump to 100 and "End" should jump to 105. The only information I've provided is that I want to see super department 1 so I should see all of it. I would also select all options by default with a multi-select; this is logically the same behavior.

But if I change "Start" to 102, "End" should also move to 102. At that point I've provided additional information about what I want to see.

> The use of the text Dept input may need some explaining. I seem to remember forms on which it either doesn't work or doesn't do what I expect it to (change/override the value of the select).

This definitely needs to be consistent so changing the select changes the corresponding text and vice versa.

**Comment by gohanman** [comment]
Better late than never. Reports using FormLib::standardDepartmentFields (which is basically everything with a tiered department selection at this point) can toggle between a range of departments and a multi-select. The default view is configurable on the products tab of install/config but switching back and forth as needed is permitted.
88efa481695497b1178b5482148f575a6dd49c96

I'm closing this as checking off the main requirements: consistency via pushing the forms into an API class and configurability/flexibility in selecting non-sequential departments.
