### ISSUE TITLE
Products Table Column Addition Wishlist

### ISSUE THREAD

**Issue by gohanman** [CORE-POS/IS4C#511]
I want to borrow a Wedge idea (#509) and keep a last-sold date in the products table for quick reference. This seems like as a good a time as any to propose other additions.

For reference, current table:
https://github.com/CORE-POS/IS4C/wiki/Office-Operational-Database#products

I'd like columns for organic and gluten-free. I kind of dislike product flags in numflag. It feels like a bit of a kludge from back when we didn't have a good mechanism for shipping/managing schema changes. There are probably other statuses that merit consideration but those two stand out the most in my mind. I think there's a balancing act here - having 20+ status flag columns would be a bit ridiculous so really esoteric things can stay in numflag but common, mass-appeal stuff should have it's own column.

I'd like *something* for product specific pricing. I'm tempted to just make it a pricingRuleID and shove the logic into another table, but I want to capture more information than just an item-specific margin target. Is it a loss leader and if so how much loss can we tolerate? Is it a price match and if so who's price are we matching? How recently was the competitor price verified? Is it a price threshold e.g. we're trying to keep the price below $5? 

Other suggestions welcome. I may still add more myself after thinking about it a bit.

**Comment by joelbrock** [comment]
I have some hesitancy around dedicated fields for organic, gluten-free, etc.  Do you envision standard checkboxes in the default item editor for organic and GF?  Or perhaps they are defaults in the itemFlags editor module.

I __like__ the itemFlags solution as it is quite a bit. It is universally customizable and configurable.
FWIW, when i set this up initially in IS4C-land i did create a dedicated field in the products table called `props` (properties) for storing the bitwise.  So maybe this data gets moved into another field that isnt `numflag`, which does get used in other places like storing the entered member number.  But i like the approach of keeping it all neat and tidy in one field.

I _could_ see a case for storing this in a lookup table with fields for upc, and one for each flag (or sticking with one field using bitwise).

My 2¢.

**Comment by joelbrock** [comment]
Also, RE: item-specific pricing:  :+1: 

RE: last-sold date: i'm neutral on this one, and/or not sure that the `products` table is the right place for this.

**Comment by DavidHermann** [comment]
Harvest's Fannie analog maintains a last-sold date per UPC and store.  We find it extremely useful for identifying active/inactive items, choosing which Co+op Deals tags to print, etc., without having to join to a big TLog or movement table.

We have similar audit/bookkeeping columns for last regular retail mod, last sale retail mod, and last vendor/cost mod, which save us having to join to the big UPC history table (no counterpart in Fannie, I believe).

**Comment by gohanman** [comment]
> I like the itemFlags solution as it is quite a bit. It is universally customizable and configurable.

This is essentially what I dislike about it. The customizability makes it difficult (impossible?) to build additional tooling around it without adding more layers of configuration on top of it. I can't add "Organic" to the product list for group item editing because I don't know which bit indicates organic at any given install. Heck, I don't even know if the UI is a checkbox or a select as someone might be tracking different levels of certification. There are similar problems if I want to import a UNFI catalog and use its status information to update products' organic status.

I definitely don't want to get rid of item flags. But I want to "promote" the most common ones into dedicated fields so the tooling around those settings can be more powerful.

> We have similar audit/bookkeeping columns for last regular retail mod, last sale retail mod, and last vendor/cost mod, which save us having to join to the big UPC history table (no counterpart in Fannie, I believe).
There is a big UPC history table (prodUpdate). I also have separate tables for UPC price history and cost history. I scan the big UPC history table for changes to those specific columns. I'd think in most cases if I'm interested in the last retail modification date the next piece of information I'm going to want is the previous retail price. So I'd just go straight to one of the dedicated column history tables.

**Comment by jdpurdyvi** [comment]
##### +1 To the "last sold" proposal. 
I'm finding that a small table [upc, branch, datetime] works well on a practical level. I can't remember the decision tree that lead me to use a secondary table versus a column in the products table. But looking forward with a focus on more multiple location operations, I think that it proves itself to be the "more right" choice. The nightly script is a simple cron that runs some SQL not unlike 
```sql
INSERT INTO lastSold SELECT upc, branch, max(datetime) from dTtransactions group by upc, branch ON DUPLICATE KEY UPDATE datetime=max(datetime)
```
##### ±0 To the long tail of item attributes
Organic, Gluten-free. Trendy today. But years late you have a table column "Yeast-free" and questioning your decisions.
##### +1 To "something for product specific pricing"
WIC! For many packaged grocery items, there is a maximum retail price allowed by the WIC program. It's important to managers and scanners to know that to comply with the program. Maybe that can be generalized better?

**Comment by gohanman** [comment]
The point about multiple locations is a good one. It may be time to actually make a decision about what a multi-store products table (or collection of tables) looks like. If products doesn't have a (upc, branch) record for every item and location, then last-sold won't fit in products on a per-location basis.

As I see it, there's three buckets of data:
* Data that should be the same at all locations
* Data that has an organization default but may be overridden at a given location
* Data that should be different at all locations

Harvest's approach with a per-location record for every item covers all three scenarios in a way that's easy to examine and reason about. The main downside I see is it scales a bit awkwardly and duplicates a lot of data. But larger organizations will usually have larger hardware budgets so just throwing money at any space or performance problems may work fine.

The most appealing alternative to me is three dedicated tables for each purpose: a "master" products table with one entry for each item, an "overrides" table with per-location column values that overwrite the master values, and a narrower table for things like per-location last-sold. I'm less enthused about mixing and matching the different types of data in one table - i.e., having both a master record and variable number of store-specific records.

I'm leaning more and more towards the Harvest approach. I worry that trying to come up with a fancier/elegant/efficient solution will wind up meaning complicated, convoluted, difficult to reason about, and difficult to build tools on top of.

---------------

RE: **Item Statuses**: I think I'm going to be outvoted on this one. How about reserving some set of bits so a subset of [currently] common options can be standardized? Say the first 16 bits are user customizable, but the next 15 are reserved for the project and can be used for a default set that will be consistent across installations.

**Comment by gohanman** [comment]
To revive a topic, any objections to reserving some number of numflag bits for upstream use? I'd really like to be able to populate organic / gluten-free fields using the status data UNFI provides - but to do that in a portable way I need a fixed definition of organic / gluten-free. I doubt I'll step on any toes starting at bit number 17. Merging any existing store flags with project-defined flags (global flags?) wouldn't be all that complicated and wouldn't even be an issue until a store want to use the same import routine.

RE: @jdpurdyvi's point about WIC: I think the most extreme generalization is that any exception/variable pricing should have a reason attached to it. Noting the item isn't at normal margin is insufficient. Someone reviewing it later needs to know **why**. I'm currently picturing something like (exceptionID, exceptionTypeID, details) where exceptionTypeID at least lets you filter on broad categories like WIC, Loss Leader, etc but the details would still wind up as free text. I think the literal details will vary enough across the broad categories that a stricter schema would be really difficult or convoluted with dozens of optional columns depending on the exception type. But I'm open to suggestions. There's definitely part of my brain screaming out that "allow free text entry" is a terrible idea.

**Comment by gohanman** [comment]
Updates:

Last sold column and task to maintain. I'm procrastinating on the multi-store products question for now.
8f2521daa98f87e386e9aa6dc032d1e8d87c15dc

Per-item pricing: I went with PricingRules. Products has a FK to PricingRules; one or more products could theoretically use the same pricing rule. It adds a rule ID 1 as generic variable pricing. Still missing user interfaces for building other rules as opposed to a simple variable pricing on/off toggle.
665899afb341a4ef13d34e920b6cfb61ce6711dc

I did not add dedicated columns for organic, GF, etc based on feedback here (thanks!) but did move forward with a set of default flags starting at bit number 17 using sample data.
bfea13503d6cad7fa1081386e2f73b7d613cccc3

**Comment by jdpurdyvi** [comment]
+1 Nice job
 


     On Friday, June 5, 2015 2:06 PM, Andy Theuninck <notifications@github.com> wrote:
   
 

 Updates:Last sold column and task to maintain. I'm procrastinating on the multi-store products question for now.
8f2521dPer-item pricing: I went with PricingRules. Products has a FK to PricingRules; one or more products could theoretically use the same pricing rule. It adds a rule ID 1 as generic variable pricing. Still missing user interfaces for building other rules as opposed to a simple variable pricing on/off toggle.
665899aI did not add dedicated columns for organic, GF, etc based on feedback here (thanks!) but did move forward with a set of default flags starting at bit number 17 using sample data.
bfea135—
