### ISSUE TITLE
Re-modeling Customer Accounts

### ISSUE THREAD

**Issue by gohanman** [CORE-POS/IS4C#514]
On last week's call there was some momentum to re-examine how customers (primarily, but not exclusively, members) are modeled in CORE. My main takeaway from that discussion is there should be a clearer delineation between an account and a person. When each account has exactly one person the distinction doesn't matter, but when an account may include multiple people then which attributes are attached to the account as opposed to attached to an individual person is much more important.

CORE currently has a disastrous mix of account-specific and person-specific data thrown together in custdata which various ancillary tables capturing other bits of [mostly] account-specific data. I think the task at hand it to look at all the customer data currently captured, and decide what should be attributes of a person, what should be attributes on an account, and possibly what should be further normalized.

Here's what I can think of that we're currently capturing:

Attribute | Person/Account | Table 
---------- | -------------------- | --------
Integer ID | Account | Various (e.g., custdata.CardNo)
Member Status | Account | custdata
Customer Type | Account | custdata
Name | Person | custdata
Charge Balance | Account | custdata
Charge Limit | Account | custdata
Charge Allowed | Account | custdata
Checks Allowed | Account | custdata
Discount (%) | Account | custdata
Staff Status | Account | custdata
POS Screen Display | Person | custdata
ID Card UPC | Account | memberCards
Start and end dates | Account | memDates
Street Address | Account | meminfo
Phone Number | Account | meminfo
Email Address | Account | meminfo
Receives Mail | Account | meminfo
Contact Preferences | Account | memContact
Misc. Preferences | Account | custPreferences

Most attributes are currently tied to the account rather than to the person, albeit in a heavily duplicated structure. I did omit the current columns that aren't actively used on purpose, but if I forgot anything important post it and I'll update the table.

Working draft, Account attributes:

Attribute | Reason
----------- | ----------
Integer ID | Basic good DB practices. I think this would inherit the existing member ID.
Member Status | Indicates whether the account is a member of the co-op. Per-person variation is uncommon in co-ops I surveyed and it would make patronage a mess to figure out.
Customer Type | This would be reduced to a means of categorization and would not directly control any other attributes
Charge Balance | I don't want to rip apart and re-do store charge accounts
Charge Limit | See above
ID Card UPC | Per-person cards would create some physical hassles with all the cards that already exist
Start and End Dates | I don't see a reason to bump this down to per-person
Street Address | Co-ops I surveyed all limited membership to a household. I think one snail mail address per account is workable.
Contact Preferences, Receives Mail | Should be possible to merge these together into a single setting
Active Status | Dedicated field for marking accounts as inactive or closed

and Person attributes:

Attribute | Reason
----------- | ------------
Integer ID | Basic good DB practices
Account ID | Foreign key to account record
Name | obviously per-person
Charge Allowed | Restricting permission to make charges per-person seems sensible
Checks Allowed | Same logic as charge allowed
Discount (%) | Could also be re-worked as a Discount ID references a table of known discounts to prevent inconsistencies / typos
Staff Status | I imagine often only one person on an account will be an employee, but I could see this fitting under account instead.
Phone Number | Pre-cell phones attaching a phone number to a household mailing address made sense, but these days its a per-person attribute
Email Address | Definitely a per-person attribute
Is Account Holder | Flag indicating which person is the primary / voting member
Member-only Prices Allowed | Flag whether person gets member-specific sale prices
Member-only Coupons Allowed | Flag whether person can use member-specific store coupons

The main changes as I see it are account benefits being broken out to per-person settings and contact information split apart for modernization. I'm not sure where to attach Misc. Preferences / custPreferences. I think being able to add additional custom preference settings can be useful, although like the item flags discussion their scope is somewhat limited. Custom-defined settings aren't going to tightly integrate with the rest of the project.

Am I missing any attributes? Disagree with where I've placed things? Other comments?

**Comment by joelbrock** [comment]
wow.  this is great!  I dont see any glaring omissions.  My specific thoughts below:

- i could perhaps make an argument for per-person member barcodes.  If a co-op wants the efficiency and convenince of barcoded member cards, it would be counter-productive to scan the card, then force the cashier to select the members name from the menu.  rather than having the scan operation instantly enter in the account+person.
- possibly a person-level contact preference?  specifically thinking about emailed receipts.  The primary member shouldnt get emailed receipts for purchases they didnt make.
-staff status, no change.  Just that i can imagine the scenario where 2 (or more) staff share a member acct.  with other non-staff.
- Lastly:  the Discount(%) sounds like a big refactor, but a very good one!  And i would lobby for making this piece as flexible and extensible as possible, so i lean toward a lookup here to another table or set of tables that define discounts.  And the ability to lump several together into the discount field.

**Comment by gohanman** [comment]
In a vacuum, I agree that person-level barcodes make a lot of sense. But all existing cards at all stores using them would have to be re-issued (or they would misidentify everyone as whichever single person the existing barcode is associated with).

I'm certainly thinking along similar lines pushing email address and phone numbers down to a per-person level. There's still possibly a distinction between messages to individuals and messages pertaining to the whole account.

I'm not really proposing a large refactor to discounts. The problem here has been the same forever. We can have flexible and extensible discounts or we can have reliably correct sales tax collection. Anything beyond stacking or non-stacking percentage discounts to items flagged as discountable makes it difficult (impossible?) for POS to determine the taxable total.

**Comment by gohanman** [comment]
So it's not lost, #519 raises some related issues.

Periodically we want to notify the customer and/or cashier about something when a given account is entered. In the past almost all messages of this sort have been dumped into custdata.blueLine simply for lack of a better option.

Dedicated notifications should:
* Be able to be associated with an account or with a person
* Take an *active* or *passive* approach where *active* requires the cashier to somehow acknowledge the notification and *passive* does not.
* Take an action - e.g., press [enter] to apply this coupon or [clear] to save it for later.

The last point might be a little tricky; it probably can't have infinite complexity. Action might have to be limited to a POS command so on confirmation simply runs the command through the input parser.

Notifications:

Attribute | Reason
----------- | ------------
Integer ID | Good DB practices
Account ID | FK to an account record
Person ID | FK to a person record
Message | Text/html content of the notification
Display Type | Active / Passive, maybe more options down the line
Confirm Action | POS command that runs when an active notification is confirmed

**Comment by gohanman** [comment]
c8cafc22784f7cd7748a943d840cb30ef6abe22a
Tables for accounts and people with ideas for keeping data in sync between old and new tables. Sill debating the best way to implement a switch over.

**Comment by gohanman** [comment]
Basic migration plans: new API class MemberREST has methods get() and post(). Get returns an array of the following format; post accepts an array of the same format and saves the value(s) specified to the database. The API class is responsible for figuring out which tables exist, where to get the data, and where to store the data. The version below using sample data has more nulls than would be typical with real data but I didn't want to publish someone's address, phone#, etc.

```json
{
    "cardNo": "4049",
    "memberStatus": "PC",
    "activeStatus": "",
    "customerTypeID": "1",
    "chargeLimit": "20.00",
    "chargeBalance": "0.00",
    "idCardUPC": null,
    "startDate": null,
    "endDate": null,
    "city": null,
    "state": null,
    "zip": null,
    "contactAllowed": null,
    "contactMethod": "mail",
    "addressFirstLine": null,
    "addressSecondLine": "",
    "customers": [
        {
            "customerID": 0,
            "firstName": "Winona",
            "lastName": "Nall",
            "chargeAllowed": "1",
            "checksAllowed": "1",
            "discount": "0",
            "staff": "0",
            "lowIncomeBenefits": "0",
            "modified": null,
            "accountHolder": 1,
            "phone": null,
            "email": null,
            "altPhone": null,
            "memberPricingAllowed": 1,
            "memberCouponsAllowed": 1
        },
        {
            "customerID": 0,
            "firstName": "Royce",
            "lastName": "Cutchin",
            "chargeAllowed": "1",
            "checksAllowed": "1",
            "discount": "0",
            "staff": "0",
            "lowIncomeBenefits": "0",
            "modified": null,
            "accountHolder": 0,
            "phone": "",
            "email": "",
            "memberPricingAllowed": 1,
            "memberCouponsAllowed": 1
        }
    ],
    "modified": null
}
```

I've been updating the member editor using the API functions and it works quite well for retrieving or saving exactly one membership/account. Situations that reference multiple memberships - primarily reporting - aren't as good a fit. Requesting accounts one at a time wouldn't give the most efficient performance. I think the next steps should be:
* Expand backend use of the API so it covers all cases of displaying or saving a single membership correctly using the custdata, meminfo, etc tables.
* Add new, better tables on the backend. The API methods will then fetch data from the newer tables but save data to both sets of tables.
* Re-write reports. Keeping backwards compatibility should be as substituting an older table into a JOIN.
* Start syncing newer tables to the lanes and using those values instead of custdata

This may be a long(ish) delay from starting on this to having new fields available at the lane, but I think it's the best way to avoid breaking anything. Fortunately some options can be handled fine via custdata (e.g., per-name discount percentages). In some cases, new features with minimal could go into the lane code earlier with the caveat that you'd need an up-to-date backend to manage those features (e.g., per-person email receipt addresses).

**Comment by gohanman** [comment]
I'm rethinking notifications a bit.

Attribute | Reason
----------- | ------------
Integer ID | Good DB practices
Account ID | FK to an account record
Person ID | FK to a person record
Source | Who/what created the message
Type | Receipt, blue line, member list, popup dialog, etc
Message | Text/html content of the notification
Modifier Module | Optional class name

Source seems mandatory for something like a nightly cron job that's adding/removing/updating a message. It needs to reliably find the correct record is multiple jobs are generating their own notifications. A more generic type than active/passive seems more extensible in the long run. Modifier Module is borrowed from the existing custReceiptMessages with a class name that can be invoked at run time to tweak the message if needed based on events in the current transaction.

**Comment by gohanman** [comment]
Status update, as of v1.6.0:

CustomerAccounts (i.e., the account):
* Model exists
* Table is not created by default
* Untested implementations for migrating data, syncing data into older tables

Customers (i.e., the people)
* Model exists
* Table is not created by default
* Untested implementations for migrating data, syncing data into older tables

CustomerNotifications (i.e., the notifications):
* Model exists
* Table exists on both Office and Lane
* Notifications can be displayed on the receipt, blueLine, and member search results.

Editor UIs are all working through MemberREST to display and change member information. One piece I overlooked in the earlier proposed steps is cron jobs. Reports actually aren't that important in the grand scheme of things, but any code that edits memberships needs to interact with MemberREST rather than modifying tables directly. This is going to be the best way to ensure the old and new tables stay in sync. I think these are next on the agenda.

There should also probably be a manual setting to switch over to "new table mode". Simply checking whether the new table exists does not verify whether the data has all been migrated and the user is ready to switch.

**Comment by flathat** [comment]
@gohanman 
> There should also probably be a manual setting to switch over to "new table mode".

After a fetch and merge I've created the table from Install > Updates  and now all member lookups fail.  Assuming that is the reason, can you describe how the "manual switch" should work?  Or would it be simpler to just drop the still-empty `Customers` table until I'm ready to use it?

**Comment by gohanman** [comment]
Drop the table is probably the easier solution at this point. Some kind of
adjustment ought to prevent that update from showing up too.

**Comment by gohanman** [comment]
Temp fix: get those tables off the Updates tab.
76123d0230a11332752d1dca2d53850bd7c35caa

RE: the "manual switch": right now MemberREST tries to looks up & save members in CustomerAccounts and Customers if those tables exist. This is not helpful if those tables are empty. The manual switch should designate which set of tables is authoritative for members.

**Comment by gohanman** [comment]
dda8f16adc8b58739edfd485044643920f35baec

Manual switch added although trying to use the new tables as authoritative **will** blow up badly in various ways. The upside to this setting is the CustomerAccounts and Customers tables may exist without causing any disruption (although they're still not created by default). I currently have it set up so that when using custdata et al as the member data source save operations will *also* write to the newer tables. I hope to catch most bugs related to the new tables this way before actually trying to use them as the primary data store.

**Comment by gohanman** [comment]
I'm going to close this unless/until further activity comes up. The two sets of tables are maintained correctly AFAIK, but trying to officially deprecate `custdata` et al isn't a high priority for me.
