### ISSUE TITLE
Office Permissions - Manage batch types

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#515]
I was just able to manage batch types by adding a new batch type without being logged in.

I cannot view/edit batches themselves.  That does require logging in.

Both should require login.  Manage batch types could arguably require a dedicated permission type.

**Comment by gohanman** [comment]
Makes sense. I added the same requirement to several other batch related pages since the same logic really ought to apply.
e8d39d255f15e7168877c164f7703049245385d8
