### ISSUE TITLE
Reporting on Non-Inventory Dept. Sales

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#518]
Perhaps this is a stupid question, but how does one view dept. sales totals for all non-inventory depts.?

I've combed through the all reports and site maps and dont see a way to do this.....

In the past i've just added this as a customization to a report like the General Sales report.

**Comment by gohanman** [comment]
Movement report grouped by department instead of PLU?

General Day & General Range should both include non-inventory sales (along with all other sales).

**Comment by joelbrock** [comment]
So glad that was in fact a silly question....
![image](https://cloud.githubusercontent.com/assets/52835/8259376/dd425c52-1670-11e5-80ed-5b07ac001843.png)
