### ISSUE TITLE
BUG:  ProductList editor not properly selecting dept. #14

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#522]
![image](https://cloud.githubusercontent.com/assets/52835/8340792/80fde67e-1a75-11e5-8abf-1776ac35628b.png)

This is only happening to items in department 14 - Herbs & Spices.  As illustrated, the first edited row properly selects "Coffee" in the dept dropdown.
The second one _should_ select "Herbs & Spices" but it does not, and instead defaults to dept_no 1 - Beer.

This is at Rutland, FYI.

**Comment by gohanman** [comment]
I'd guess this could be resolved by changing "&" to "and". That's definitely a bug but it's a bit complicated. Somewhere in passing data between PHP and Javascript and trying to match strings in the table there's probably an issue with literal ```&``` in some places and ```&amp;``` in others.

**Comment by gohanman** [comment]
Fixed: a969e1b760fd42dc2be3e48ead9d3fcd4ff267d4

I patched this back into version branches 1.2 through 1.5 too.
