### ISSUE TITLE
Onscreen change amount inconsistencies

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#523]
When tendering out a transaction with a negative subtotal (money owed to customer e.g refunds, bottle returns) there is an inconsistency in the handling of change amounts displayed onscreen.  

_ex. 1_
$10 Refund
entering 0[TENDER] results in a change amt displayed of -$10.00
![image](https://cloud.githubusercontent.com/assets/52835/8442206/63a4d22e-1f32-11e5-8c30-34d3a22fe97f.png)

_ex. 2_
$10 Refund
entering just [TENDER] with no amount (eg. CA) results in a change amt. displayed of $0.00
![image](https://cloud.githubusercontent.com/assets/52835/8442238/a64ec594-1f32-11e5-8b8b-3576db51e7a3.png)
....press {ENTER}....
![image](https://cloud.githubusercontent.com/assets/52835/8442245/b4816d9c-1f32-11e5-8582-379004183470.png)

Seems like the preferred behavior would be _ex. 1_, to display the amount of change owed to the customer.

I do not know exactly if/how these differing results may or may not affect the tender report totals.

**Comment by gohanman** [comment]
The simplest solution here is use 0CA. That gives the desired change line. Tender reports should not be affected one way or the other - both tender records are denominated in cash and they sum to -10.00 regardless of order.

Interpreting negative tenders as change isn't an option; they exist specifically to avoid giving change. With tenders that may received change in cash **and** may receive refunds in some other form (e.g. debit), POS needs to be able to distinguish when change is and is not occurring. The negative tender indicates change is not occurring.

**Comment by flathat** [comment]
Would it work to flag <TENDER> alone as an error or at least need confirmation where the amount is less than 0.00?  I'm thinking of it as a training nudge to use 0<TENDER> in this situation.

Also, I'm not clear on when a negative tender would be correct.

**Comment by gohanman** [comment]
I think CA should definitely be an error w/o an amount by assigning it the NoDefaultAmountTender module. That's the out-of-the box configuration now. Unlike with cards or checks, the customer isn't going to be paying the exact total all that often so autofilling the amount is not helpful. Coupons should also use no-default IMO.

A negative tender is going to be correct in any situation where money is returned to the customer in a form that isn't cash.
