### ISSUE TITLE
Variation in number of fields in UNFI upload

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#526]
The number of fields in the item lines of UNFI CSV files can be less than the number of header columns.
This was patched at abc7efaba3785ce0464a6597e8eaa99c8e28b200 but in Aug 2015 there are four more headers than columns instead of two (I haven't changed the code here).  The first dozen or so of the 24,000 lines have empty fields (trailing `,,,,`, almost all of the rest don't). It seems possible UNFI will increase this in future. There needs to be a way of sensing in `FannieUploadPage preprocess()` what is going on and supplying the `4` here as a variable, perhaps vendor-specific.:
```php
if (count($fileData[$i]) < $num_columns-4 || count($fileData[$i]) > $num_columns+4) {
    continue;
}
```
Or some other test for skipping lines that are probably incomplete.

**Comment by gohanman** [comment]
More generally, is there even value in keeping this check at all? It has to validate each row anyway - if SKU is missing or UPC isn't a number or the cost isn't a number it can't insert a row. I'm sure this conditional was my doing but I'm less sure now that it was a good idea. The simpler solution would be "get rid of it entirely".

**Comment by flathat** [comment]
This is for a co-op that does a fair bit of catalogue loading so I disabled the test and will keep an eye on the loads.

**Comment by gohanman** [comment]
Removing the check as suggested:
18a41f505dd599183975fa93a1cb2d971d73c7fe
