### ISSUE TITLE
Office Permissions - Manage Departments

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#529]
Management of Superdepartments, departments and subdepartments is OPEN to all users not logged in.  This needs to be authenticated and designated only to specific users.

As an adjunct random thought:  What would it look like to have Authenticate All enabled, but to be able to "DMZ" certain pages/tools?   For example, all tools are pass-protected with fannie/item/handheld, and fannie/reports DMZd.  To allow for viewing basic item info and all reports.

**Comment by gohanman** [comment]
RE: Adjunct thought: keeping track of what's in the DMZ seems overly complicated (and I'm not sure there would be complete agreement about what belongs in the DMZ). I think the better solution is to make sure everyone has a login - then authenticate all can do exactly what it says.

I think the key to making that workable is getting authentication out of POS in any sizable installation. I never create accounts for staff directly in POS. I create email accounts for new hires and they automagically get POS accounts since POS auths against the email server using LDAP. Expanding this concept to other services could be useful although I don't know what others people are using.

**Comment by joelbrock** [comment]
You're right, it does seem as though using Authenticate All and a generic login for the most basic level of access would be far far easier.

I like the LDAP integration option, for stores with AD servers winbind might be another integration to look into.  I'll need to do some research into adding LDAP to an Ubuntu LTSP server.

**Comment by gohanman** [comment]
It should be possible to authenticate against AD using LDAP - the settings
would just be different. The username, real name, and userID fields are
probably named differently, and there might be an extra setting to prefix a
domain assuming users don't want to type in DOMAIN\User when logging in. I
don't have an environment to test this though.

**Comment by gohanman** [comment]
More to the actual point of the question:

I could attach this to the existing "pricechange" permission. Anyone who can edit items could also edit departments. This would be minimally disruptive for existing installs.

I could create a new permission specific to editing departments. Existing stores would need to create/import the new permission and assign it to appropriate users to re-enable department editing. This is more disruptive but will offer more granular control of who can edit what in the long run.

I could also do **both**. With that route, I'd want a clear sunset date when "pricechange" users will lose access. Letting both permissions have access would smooth out the transition in some ways, but keeping access for both indefinitely defeats the purpose of having a separate permission just for department editing.

**Comment by joelbrock** [comment]
seems to me like dept. mgmt. would belong to a separate permissions category, along with batchtypes, and tender editing.  these are more administrative utilities that affect how the POS functions at a higher level than managing item data for example.

so my vote would be for a dedicated permissions class.

**Comment by gohanman** [comment]
Makes sense. I added a "departments" auth class and added it to the default set. I also gave "admin" access so hopefully no existing install would get completely locked out by an update.
258ae959cb4df3a7a1ec63cbcbfe213d47b771c1
