### ISSUE TITLE
Department Mgmt. suggestion

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#530]
In cases where there are 100+ departments it can be tricky to determine which departments are not grouped into any Superdepts.  What if there could be a readout on the SuperDept mgmt. UI that displayed all the departments and what SuperDept they belong to?  This could be text-based.  
Color coding a yes/no status would even be helpful in identifying depts. not assigned to any Super.

Just a useability suggestion from someone who uses the software.  A lot.  Let me know if you have questions, or i could mock up a visual of what i imagine.

**Comment by gohanman** [comment]
Well, at a bare minimum it belongs in the Department Settings report.
51f2a0485db5c5ed506061f4d28c1e8b8ff10351

I've used this primarily for auditing tax/FS/margin setting. This also strikes me as an audit situation.

**Comment by gohanman** [comment]
Also, an asterisk next to orphaned/parent-less departments in the SuperDept editor. Color coding is a better visual cue but styling on ```<select>```s doesn't seem very portable across browsers. The act of selecting an entry tends to paint over any CSS coloring with whatever the browser's "selected" color scheme is.

**Comment by gohanman** [comment]
To try and wrap this one up: 1ca68028ef1eb017556e75edb8036bd5cf436d99
Super Department editor links directly to the department settings report. The report highlights any department that's missing a parent super department in red.
