### ISSUE TITLE
Create shelftags by Brand not working

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#537]
admin/labels/CreateTagsByManu.php behaves like it's working.  After submitting you get a green success alert.

But then if you go to the tag queue there are no new tags added.

There is a failed query in queries.log:
```
Jul 27 12:55:11 IS4C-Server fannie[17044]: (debug) Failed Query on /RVM-CORE/admin/labels/CreateTagsByManu.php

                SELECT
                    p.upc,
                FROM
                    products AS p
                WHERE  x.manufacturer LIKE ?

Parameters: %VIBRANT%You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM
                    products AS p
                WHERE  x.manufacturer LIK' at line 3
```

**Comment by gohanman** [comment]
Yep. Upstream fix: ecee1dc4983a701787db73d0639a8ee34747192d

Patches for releases:
* Version-1.6: 9eb07f5d861fded542a296a12e2dc80e42bd82ca
* Version-1.5: 369345ed5768398cc2a548214f11839bc0c84637
* Version-1.4: 437c138a18826a4f958771281b9de23bff0a7fb7

(Bug doesn't exist in earlier versions AFAICT)
