### ISSUE TITLE
Plugin Idea:  User-configurable SalesTax Holidays

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#553]
This is an issue that arises infrequently, but some states do these at least once/year.   When it happens co-ops have to contact me to do the setup and scripting of the tax holiday.  Making this a user-configurable feature would be a boon to both users and those of us who support them.

I can imagine a couple different ways this could operate, but at it's most basic, an "event" can be created and tied to one of the tax ID numbers.  e.g. tax ID 1 would get a start and end date.  As well as the taxrate during that period, 0.00% in the case of a total holiday.

A FannieTask could run nightly, check for a tax "event" that needs to be active--like a sales batch--and apply the changes.  A LaneSyncTask needs to include the taxrates table for the lanes to know about the changes.

This is purely a suggestion.  I'm happy to provide more detail or discussion.

**Comment by gohanman** [comment]
The one tricky piece is that the taxrates table crosses databases in an abnormal way (core_op.taxrates => translog.taxrates). It's probably easier to have the sync work around that than change where the lane expects to find taxrates.

In general making tax rates syncable seems like a good first step. If users can manually edit rates centrally than push changes to the lanes that would be both a basic solution and a failsafe alternative should something go amiss with the scheduled version.

I think it might work better without an end date. Schedule two events (e.g., rate goes to 0% July 1; rate goes to 5% July 2) and we don't have to keep track of the "normal" rate during the holiday. Plus this would work for times when the tax rate actually changes which I've run into a few times.

**Comment by gohanman** [comment]
Proper syncing for the taxrates table: 7202d4e3bbcef89d358a63d31b8aeaef333f1996
