### ISSUE TITLE
META_BOLD constant breaks table sorting

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#555]
the META_BOLD class constant as defined in FannieReportPage.php appears to insert tbody close and open tags and wrap the lines in table header tags.  This has the desired effect of bolding the table row.  This also appears to have the undesired effect of breaking the tablesort.  Only rows ABOVE the META_BOLD rows sort as expected.  For now I'm commenting out the call to META_BOLD in the report page, but i'll bet there's a better way.

![screen shot 2015-08-26 at 3 44 32 pm](https://cloud.githubusercontent.com/assets/52835/9508316/67d147ac-4c09-11e5-9eae-6d420c19489b.png)

**Comment by gohanman** [comment]
Yep. It's this: 8cb11e8788b3a188348bcd7cb868fb7545f04734

**Comment by joelbrock** [comment]
O wow.  That was almost too obvious.  Thanks @gohanman
