### ISSUE TITLE
Receipt / Onscreen Messages editor interface

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#558]
The editor is currently in a goofy place and updating requires several steps.  Lets streamline this for our users!

https://github.com/CORE-POS/IS4C/wiki/Receipt-Messages

**Comment by gohanman** [comment]
This is essentially done although now the screen shots are out of date.
5ab2d5e1e7e13382e1964028013fd55db0c7dc62

There's a single drop-down to select customReceipt.type and then the editor portion populates with that set of strings. Add, edit, and delete are also unified into the single set of fields.

**Comment by joelbrock** [comment]
This is what i see when trying to use this tool:

![image](https://cloud.githubusercontent.com/assets/52835/10210143/25dbb3dc-6798-11e5-901b-e2ba3a43047b.png)

**Comment by gohanman** [comment]
Can you expand on what you were doing? I've tried a number of additions, deletions, and edits without being able to reproduce.

**Comment by gohanman** [comment]
Never mind, you're right. 489b0f02138ef361311959fb6f55e3a6378e956e
