### ISSUE TITLE
Lane config question:  Rootkit hunter on lanes?

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#562]
Trustwave asks whether the POS has rootkit / file integrity scanner software.  I have never employed such a thing but doesn't seem like a terrible idea.  ANyone have experience using such a thing?  Esp. on *nux?

e.g.
https://cisofy.com/lynis/

**Comment by gohanman** [comment]
https://github.com/gohanman/pci-box

OSSEC covers this particular point. I strongly suspect Trustwave's question is either poorly phrased or misunderstood. File integrity monitoring is not a function of POS and should not be. Integrity monitoring should extend beyond POS itself and detect tampering to the underlying operating system as well.

**Comment by joelbrock** [comment]
gosh, well isnt that handy.

**Comment by chaploeb** [comment]
Super handy.  Thanks for this.  This appears to almost perfectly addresses
the gaps in the security tech we currently have in place.

David Chaplin-Loebell, IT Director
Office: (215) 843-2350 x127
Cell: (267) 971-4093


On Wed, Sep 30, 2015 at 4:09 PM, joel brock <notifications@github.com>
wrote:

> gosh, well isnt that handy.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CORE-POS/IS4C/issues/562#issuecomment-144525966>.
>

-- 



Community-owned food markets open to everyone.
www.weaversway.coop
