### ISSUE TITLE
BUGFIX: LaneSyncTask

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#565]
```
PHP Fatal error:  Class 'FannnieTask' not found in /pos/Alberta/fannie/cron/tasks/LaneSyncTask.php on line 74
```

https://github.com/CORESupport/Alberta/commit/4dbd8a97be5bfe80ac202da8bfcc76031c7f79b1

**Comment by gohanman** [comment]
Thanks. The same mistake recurs a few more times: ef711f90cfbe0ac431da3906219d8af935108f3c
