### ISSUE TITLE
TendersEditor GUI Recursion

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#566]
When i hit the "Add new tender" button this happened, Office within Office:

![image](https://cloud.githubusercontent.com/assets/52835/10296935/40ab196c-6b82-11e5-9cdd-51dbad3f0e8a.png)

**Comment by flathat** [comment]
I have an idea what this might be and will check it out.

**Comment by flathat** [comment]
@gohanman 
`TenderEditor->post_newTender_handler()` wasn't getting called and the process was defaulting to regenerating the entire page and placing it in the `#mainDisplay`.
Adding the `type:'post'` parameter to the `.ajax()` call in `addTender()` in `TenderEditor.php` lets it be called and now the new tender is created and the table of tenders including the new one is generated and replaces the original one in the page.
I'm not very familiar with RESTful pages; is there anything else that should be changed here?  I haven't changed the code.
```php
function addTender(){
    $.ajax({
        cache:false,
        type:'post',
        data:'newTender=yes',
        success: function(data){
            $('#mainDisplay').html(data);
        }
    });
}
```

**Comment by gohanman** [comment]
That's exactly the right fix.
