### ISSUE TITLE
BUG: TaxFoodShift when theres no tax

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#567]
PHP Notice:  Undefined index: tax in /var/www/html/Alberta/pos/is4c-nf/parser-class-lib/parse/TaxFoodShift.php on line 55

Using `TFS` to cycle through tax and FS on an item appears to fail if there are NO tax rates set up.  (as in Oregon).

**Comment by gohanman** [comment]
97cb0d9ed58e3d7ce45dc018a86b82b8b1932251
