### ISSUE TITLE
ProductList tool returning no data

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#569]
When choosing "All" or "All Retail" the report comes up with "No data found".  Appears to be working OK for other superDepartments though.  Tested with the dept range menus as well as the newer dept select menus.

No error log output to indicate if there is a query failing somewhere.

**Comment by gohanman** [comment]
1e82944d48b95fc053db68ecbbdcbc80329a0e1b

Fixed, although part of me thinks striking the options all together would be better. The first time I tested "all retail" after fixing it my whole browser crashed and the second time it locked up for a couple minutes trying to render the gigantic table.
