### ISSUE TITLE
Configurable permissions

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#578]
Right now permissions to use a particular page  (association of the current user with certain `$auth_class[]`'s) is coded in the page : `$this->auth_classes[] = 'salesbyhour';`, sometimes within blocks that test `$FANNIE_COOP_ID`.  I'd like to see a process where, probably as part of `CorePage->preprocess()`, or at that level or prior (`PreFlight()`), there would be a check for `$auth_class[]`'s that that co-op requires to run that page.  It would need support from a form to choose auth classes by page and store them outside the page.

**Comment by gohanman** [comment]
I think this ought to work 611e423c54c8ccfcd3028def1be1cb2863564c22
