### ISSUE TITLE
lane install db updates can't find BasicModel

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#587]
Upon merging current (latest commit 888b4a896e78e3aa73afa336b309c8d691872734) master
`$LANE/install/updates.php`
line 54: `$cmd = new ReflectionClass('BasicModel');`
```
PHP Fatal error:  Uncaught exception 'ReflectionException' with message 
'Class BasicModel does not exist' in /var/www/IS4C/pos/is4c-nf/install/updates.php:54
Stack trace:
#0 /var/www/IS4C/pos/is4c-nf/install/updates.php(54): 
       ReflectionClass->__construct('BasicModel')
#1 {main}
  thrown in /var/www/IS4C/pos/is4c-nf/install/updates.php on line 54
```
Perhaps related to [Namespace'd lane SQLManager] (https://github.com/CORE-POS/IS4C/commit/b55513f81f5e3e02a2255ad6f68afb8dc69dca49) ?
All other `$LANE/install` modules seem OK.

**Comment by gohanman** [comment]
Fixing that raised a few other issues in turn but I believe it's all ironed out. I was able to apply updates to a table via the web UI after the fixes.
