### ISSUE TITLE
Some list selects, and password re-prompt, don't return a value

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#589]
Upon merging current (latest commit 888b4a8) master, with `AjaxParser.php`.
POS lists of departments `nnnDP`, tenders `nnnTT`, products `aaaPV` are populated but do not return the selected value, i.e. nothing happens on selecting. No PHP or SQL error reported. Complete entries `nnnDP30000`, `500CA`, `12345` are successful.

List of members `aaaID` does return the selected value.

Also, possibly related, in `login3` prompt for cashier password `isset($_REQUEST['reginput']) == false` after the password has been entered.  Forcing the test to `true` and jiggering in a `$password` allows the routine to proceed.

**Comment by flathat** [comment]
In the case of `tenderlist` called from `100TT` and `DC` chosen the URL returned is
`.../pos2.php?reginput=100DC&repeat=1` which seems correct.

**Comment by flathat** [comment]
I have discovered that in `AjaxParser->ajax()` which originally got `$entered` only from `$_REQUEST['input']`, this makes it possible to do both list requests and handle what `*list.php` returns.  Works for all of DP, TT and PV  The input box on `pos2.php` is `name="reginput"`. Perhaps this will suggest what the real issue is.
```php
    public function ajax($input=array())
    {
        if (trim(FormLib::get('reginput')) != '') {
            // For handling return from list: 'reginput'
            $entered = strtoupper(trim(FormLib::get('reginput')));
        } elseif (trim(FormLib::get('input')) != '') {
            // For getting list: 'input'
            $entered = strtoupper(trim(FormLib::get('input')));
        } else {
            $entered = '';
        }
```

**Comment by gohanman** [comment]
Sorry, I forgot to push a commit Friday. The problem is indeed exactly what you point out with input v. reginput as the field name. 5ca6271942cc5c6e47c75688bd02c0509471333d
