### ISSUE TITLE
Bugreport: plugin db's in lane BasicModel ; other lane plugin db support

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#590]
1.) Lane `BasicModel->normalize()` at line 557 should probably use CoreLocal (which works) or if not needs `global $CORE_LOCAL;` (also works):
and similar in `setConnectionByName($db_name)`
```php
            /**
              Allow for db other than main ones, e.g. for a plugin.
              Force a new connection to avoid messing with the
              one maintained by the Database class
            */
            $this->connection = new \COREPOS\pos\lib\SQLManager(
                \CoreLocal::get('localhost'),
                \CoreLocal::get('DBMS'),
                $db_name,
                \CoreLocal::get('localUser'),
                \CoreLocal::get('localPass'),
                false,
                true
            );
            /* Currently
            global $CORE_LOCAL; // not present
            $this->connection = new \COREPOS\pos\lib\SQLManager(
                $CORE_LOCAL->get("localhost"),
                $CORE_LOCAL->get("DBMS"),
                $db_name,
                $CORE_LOCAL->get("localUser"),
                $CORE_LOCAL->get("localPass"),
                false,
                true
            );
            */
```
2.) and note the NOT test needed at line 565:
```php
            if (!$this->connection->isConnected($db_name)) {
                echo "Error: Unknown database ($db_name)";
                return false;
            }
```
3.) I also suggest adding the plugin branch here to $LANE/install/InstallUtilities.php:
```php
    public static function normalizeDbName($name)
    {
        if ($name == 'op') {
            return CoreLocal::get('pDatabase');
        } else if ($name == 'trans') {
            return CoreLocal::get('tDatabase');
        } elseif (substr($name, 0, 7) == 'plugin:') {
            $pluginDbKey = substr($name, 7);
            if (CoreLocal::get("$pluginDbKey",'') != '') {
                return CoreLocal::get("$pluginDbKey");
            } else {
                return false;
            }
        } else {
            return false;
        }
    }
```
4.) And in the comments in `BasicModel.php` `$preferred_db`:
```php
   /**
      Generic name of preferred database: 'op' or 'trans' or 'archive'
      or for plugins:
       Fannie: 'plugin:key-to-$PLUGIN_SETTINGS'
        Lane: 'plugin:parameters.param_key'
    */
    protected $preferred_db = '';
```

**Comment by gohanman** [comment]
I disagree on 2) but otherwise that all makes sense. A MySQL user account that doesn't have permission to create a new database would be the most likely cause of failure. It might run without that test but the error messaging will be less accurate - e.g., if the table doesn't exist because the database doesn't exist, trying to create the table won't resolve anything.

**Comment by flathat** [comment]
Re 2.), I don't understand what you're saying, but if this is as it was originally (and is at https://github.com/CORE-POS/IS4C/commit/1b8d4cc9bd03679b030b9332d965b974415c1ca4 line 547):
```php
            if ($this->connection->isConnected($db_name)) {
                echo "Error: Unknown database ($db_name)";
                return false;
            }
```
it reports failure if the db exists e.g. Install > DB Updates:
CCredMembershipsModel had errors. Details
```
==========================================
Checking table coop_cred_lane.CCredMemberships
==========================================
Error: Unknown database (coop_cred_lane)
```

**Comment by gohanman** [comment]
OK, but to me that indicates either connecting to the database isn't
working as expected or isConnected is not correctly verifying the
connection. In either case I think finding the actual problem makes more
sense than axing the check.

**Comment by gohanman** [comment]
I added ```$preferred_db``` settings to the CoopCred models upstream (ca36c5c10295c30b088f1ad1ed81f0014ec3c6dc) and I'm not able to reproduce the unknown database issue. It works fine for me using coop_cred_lane as the actual name and plugin:CoopCredLaneDatabase as the preferred name.

**Comment by gohanman** [comment]
Housekeeping. Feel free to re-open or create a new issue with details if still having problems.
