### ISSUE TITLE
Changes to changing-the-db code

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#591]
I'm testing my Fannie-side Coop Cred plugin under master of 8Nov (d05fad7edb8f5ee3d314f1f0c96e0ffc70dc94b6) and find that it is necessary to restate to the connection which database is being used in e.g.:
```php
        $dbc = FannieDB::get($FANNIE_PLUGIN_SETTINGS['CoopCredDatabase']);
        // ...
        // Later, $dbc is the same
        $model = new CCredProgramsModel($dbc);
        // whichDB() is now needed
        $model->whichDB($FANNIE_PLUGIN_SETTINGS['CoopCredDatabase']);
```
and in an in-plugin version of `BasicModel->pushToLanes()` `$this->fq_name` needs to be assigned.
```php
        $current = $this->connection;
        // Also set this aside.
        $save_fq = $this->fq_name;
        // save to each lane
        $laneNumber = 0;
        foreach($FANNIE_LANES as $lane) {
            $laneNumber++;
            $lane['op'] = $coopCredLaneDatabase;
            $sql = new SQLManager($lane['host'],$lane['type'],$lane['op'],
                        $lane['user'],$lane['pw']);
            // ...
            $this->connection = $sql;
            // Now $this->fq_name needs to be assigned in order for save()
            //  to address the correct db
            $this->fq_name = $lane['op'] . $sql->sep() . $this->name;
            /* Update or Insert as appropriate.
             * Return membershipID or False
             */
            if ($this->save() === False) {
                $errors[] = "pTLCC Program save to lane{$laneNumber} failed.";
            }
        }
        /* Restore connection to Fannie. */
        $this->connection = $current;
       // Also new.
        $this->fq_name = $save_fq;
```
Fannie `BasicModel.php` notes "doesn't work" on some `$fq_name` assignments.

Are these "extra" db-name assignments something temporary or just the way it works now?

**Comment by gohanman** [comment]
I don't think there's anything new about the 1st one. FannieDB returns a singleton connection object. If code between your two snippets, likely in a function, also interacts with the connection it may change the selected database. This has been the case as long as FannieDB has existed. Essentially you're sharing $dbc with anything else that runs during that page (or task or whatever).

The 2nd one may need to use the $new parameters (https://github.com/CORE-POS/IS4C/blob/master/common/SQLManager.php#L72). I don't know of anything that has changed here, but the exact behavior is going to depend on whether you're using mysql, mysqli, or PDO and how it recycles connections. (I am assuming in the testing scenario $lane['host'] is probably localhost; with a remote lane a recycled connection would be unlikely).

The bit that doesn't work with fq_name is identifier escaping - e.g., escaped:
```
`opdata`.`products`
```
vs not escaped:
```
opdata.products
```
Some of the middleware functions for things like table structure or existence fail when using backticks, again depending which exact database driver you're using. It seems easier to just avoid using database or table names that require this kind of escaping.

**Comment by gohanman** [comment]
Actually, this (761f25b88f18e7dba24f397856e6268ebb141f27) probably makes more sense than using the $new parameter. Support for creating a new connection isn't equally supported across all the underlying mysql providers. In a testing scenario with the lane and server on the same machine, it might be more representative to create a separate MySQL user from the lane connection. The underlying (as in layers below CORE) system will only recycle a connection when you use the same (host, user, password) combination repeatedly.

I can't think of any way to address the situation w/ FannieDB. Code that interacts with multiple databases just winds up micromanaging the connection state more. Here's a February 2014 example:
https://github.com/CORE-POS/IS4C/blob/master/fannie/modules/plugins2.0/GiveUsMoneyPlugin/GumMainPage.php#L72-L137

**Comment by gohanman** [comment]
This might work for the FannieDB issue: 53cfc95b8e178cf29aab08539909645e2dbb7fdf

Create a ConnectionWrapper around the database connection object and it should automatically adjust the selected database as queries are issued (n.b. I haven't had time to test this out)

**Comment by gohanman** [comment]
Housekeeping. Feel free to re-open or create a new issue with details if still having problems.
