### ISSUE TITLE
Bottle Return SpecialDept Input Unknown

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#592]
I'm at https://github.com/CORE-POS/IS4C/commit/5ca6271942cc5c6e47c75688bd02c0509471333d

I'm getting "Input Unkown" from `25DP90100` when 9010 is my `BottleReturnDept`.

`BottleReturnDept->handle()`:
`$json['main_frame'] = MiscLib::base_url().'gui-modules/boxMsg2.php?autoconfirm=1';`

If not autoconfirm:
```
CoreLocal::set("boxMsg","Bottle Return");
$json['main_frame'] = MiscLib::base_url().'gui-modules/boxMsg2.php?';
```
the "Bottle Return" message appears in the popup but there are no button options. `Enter` accepts the item.

Assigning `'boxMsgButtons'` at the same time as `'boxMsg'` works.

How to figure out what is missing here? It looks like `PrehLib::deptOpenRing()` does the message assigning.

**Comment by gohanman** [comment]
Commenting since I don't know if referencing the issue from a commit generates notifications.

**Comment by flathat** [comment]
> if referencing the issue from a commit generates notifications

Thanks for the comment since it doesn't.

That fixes the "Input Unknown" problem but doesn't address the empty-except-for-icon popup if autoconfirm is not set.

**Comment by gohanman** [comment]
What's the use case for not setting autoconfirm? Of course there's no
message if that calling code does not set up a message. I really don't see
a bug with the empty popup. "Making random changes to the code leads to
weird behavior" is not a fixable problem.

**Comment by gohanman** [comment]
Housekeeping. Feel free to re-open or create a new issue with details if still having problems.
