### ISSUE TITLE
Problem in core pos

### ISSUE THREAD

**Issue by jcharles15** [CORE-POS/IS4C#599]
Trying to run the install from the fannie directory. Seems like it is even preventing anything from working.
Error from php log.

"PHP Fatal error:  Call to a member function isConnected() on boolean in C:\xampp\htdocs\IS4C-master\fannie\classlib2.0\FannieDispatch.php on line 193"

**Comment by gohanman** [comment]
Sorry about that. I'll patch the same thing into appropriate version branches later today. With a smallish user-base from-scratch installation doesn't get tested as often as it probably should.

**Comment by jcharles15** [comment]
Great. That issue has seemed to be resolved. Did some more testing on the master branch. Pos is having trouble trying  to total transaction (TL)  and recognize tenders (100CA).  I can confirm the previous release (1.8)  is working ok.

**Comment by gohanman** [comment]
Well, this is the tender bit: 4fe1db2bec9ed73e2f545066481e69cd4f14488f

I'm not able to reproduce any kind of trouble with TL. Do you have any plugins enabled? Or TotalActions?

**Comment by jcharles15** [comment]
no plugins or totalactions. fresh install on my dev machine. will test again and report back.

**Comment by jcharles15** [comment]
Playing with the design a bit.

![boicore](https://cloud.githubusercontent.com/assets/16151564/11744159/c488f5dc-9fc2-11e5-964c-e504e5cbb056.jpg)
