### ISSUE TITLE
BasicModel create trans_archive.dlog views

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#602]
I thought `BasicModel.php --update` might create a `trans_archive.dlogYYYYMM` view if the table existed but the view didn't.  But it doesn't.  Is there a reason for that?

I'm trying to use Install > Updates for checking up on things between upgrades on a development server.

**Comment by gohanman** [comment]
The reason's pretty basic: there's no specific code to cover that situation. Everything about how the transaction tables are handled is customized and different from other model classes. The "normal" models only examine a single table/view. Any checks on separate, related tables/views would need to be manually added on.
