### ISSUE TITLE
Site Map Links

### ISSUE THREAD

**Issue by jcharles15** [CORE-POS/IS4C#603]
Site map links are leading me to an Error 404 page.
All The links look like this : 
192.168.10.7/corepos/fannie/C:\xampp\htdocs\corepos\fannie\ 

not sure if this is a problem with my xampp setup.

**Comment by gohanman** [comment]
It's the backslashes in Windows' paths.

**Comment by jcharles15** [comment]
I'm not sure how to fix that?

**Comment by gohanman** [comment]
This commit addresses it: 593b8894e751ec1680bb390e15c571e4dc02c8d9
