### ISSUE TITLE
Change Minimum PHP Version Requirement

### ISSUE THREAD

**Issue by gohanman** [CORE-POS/IS4C#609]
The current minimum is 5.3.x (I don't know exactly what "x" is but considering 5.3 reached end-of-support over a year ago no one should have a small number for "x").

This is *probably* not a practical problem. Major linux distros usually backport security fixes into their chosen version of a package even if the upstream project no longer officially supports a version. But I do think there's legitimate value in steering end users towards upgrading their own software - so long as it's balanced against creating excessive headaches for said users. In this specific area there's also some advantage to being on an "officially" supported software version. You **can** dig through package change logs and document that known security issues have been patched for PCI documentation but that approach is a lot more work.

The obvious contenders to me are 5.4 or 5.5.

### 5.4
Pros: this is what Ubuntu 12.04 LTS provides. Users who haven't upgraded to 14.04 would be unaffected.
Cons: 5.4 is also officially unsupported as of September 2015

### 5.5
Pros: still officially supported. Deprecates the original mysql extension. It will still work but log noise from deprecation notices might encourage people to switch to mysqli or PDO. It's what Ubuntu 14.04 LTS provides so there is a clear upgrade path for most users
Cons: potentially extra work for 12.04 users, although it's likely possible to find alternative packages without upgrading the OS if necessary.

Targeting PHP7 would be crazy (although I would like to be 7-comaptible and see what the performance gain is). And 5.6 seems like a dead end. 

If there was buy-in for #370 then part of what CORE "phones home" with could include PHP version. That would give a much better understanding what real usage is.

**Comment by maxolasersquad** [comment]
I am definitely in support of this. 5.5 seems like the obvious target. No sense in going through all the code to update it to support an already unsupported version. 5.5 will likely be around for a while as transitions to major revisions usually take a while. Refactoring code that is deprecated in 7 so that it works in 5.5 and 7 would probably be a good idea too so that anyone with the ability to run 7 can, and will get the performance gains.

**Comment by gohanman** [comment]
There shouldn't be any code changes required for 5.5. The only real issue is the original mysql extension and that's configuration. Using mysqli or PDO works fine already. The code should work in 7 without changes, too. I've fiddled around with a PHP7 lane and haven't yet run into problems. In 7 it'll crash if configured to use original mysql rather than just emitting E_DEPRECATED but that's still solvable without re-coding anything.

I could add nag messages or even start dropping support for the mysql extension but that seems a bit too aggressive.

Realistically this would mean the project can start using things like short array syntax or generators and not worry that the features don't work in 5.3.

**Comment by gohanman** [comment]
Ran into a real-life example today. Doing password hashing correctly in a way that's 5.3 & 5.4 compatible requires an extra dependency via composer and more defensive coding. dc26609d58ace1e63298e17e60fb46ac7b89d06b

**Comment by gohanman** [comment]
I'm going to bump the minimum required PHP version to 5.5 starting in 2.1. That doesn't mean it will immediately stop working in PHP 5.3 or 5.4 but any issues that do come up may be met with "Sorry, that PHP version is no longer supported".

**Comment by gohanman** [comment]
https://github.com/CORE-POS/IS4C/wiki/Supported-PHP-Versions

Nothing has changed on a code level and I'm in no particular hurry to start throwing in newer language features to purposely break compatibility. But the documentation says 5.5+ now.
