### ISSUE TITLE
opendir(): failed to open files

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#612]
Our new lane (CORE-POS version 1.9, Ubuntu 12.04) had just been set up and was running both **install/index.php** and the frontend **login.php** with no issues. But somehow the whole CORE-POS just stopped working. Now, if you navigate to either of those URLs, the system waits 30 seconds and then stops with a blank page.

For each such attempted page load, **/CORE-POS/pos/is4c-nf/log/php-errors.log** shows one corresponding message “**PHP Fatal error: Maximum execution time of 30 seconds exceeded in /CORE-POS/pos/is4c-nf/lib/AutoLoader.php on line [_number_]**”, where the line number ranges between about 268 and 272.

Also, for each of these page loads, **/var/log/apache2/error.log** shows a slew of messages “**PHP Warning: opendir(/CORE-POS/pos/is4c-nf/install/sql/trans): failed to open files in /CORE-POS/pos/is4c-nf/lib/AutoLoader.php on line [_number_]**”, where the line number ranges between about 268 and 272. Except each error message identifies a _different_ directory name as the parameter of `opendir()`.

In our tech support call a few minutes ago, Joel was kind enough to suggest adjusting `ulimit` upwards (I changed it to 32767 from the default 1024), but it didn’t seem to make a difference. Nor did setting `session.auto_start = 1` in **/etc/php5/apache2/php.ini` and restarting.

Other php scripts work fine, just not CORE-POS.

Any further suggestions?

Thanks in advance!

**Comment by gohanman** [comment]
My guess would be there's a symlinked directory somewhere under /CORE-POS/pos/is4c-nf/. AutoLoader is trying to scan through the directory build a list of all the available files. A symlinked directory could create an infinite loop. Exactly what file/directory/line the loop happens to be on when the 30 second limit kicks in would be random.

**Comment by scannerdarkly** [comment]
There's a bunch! Before I delete them all, are any of these needed?
[links.txt](https://github.com/CORE-POS/IS4C/files/77876/links.txt)

**Comment by gohanman** [comment]
Most of those are normal and should not be deleted. This one looks like the
culprit:
```
./pos/is4c-nf/is4c-nf -> /CORE-POS/pos/is4c-nf
```

Trying to walk the directory is just going to keep circling forever.

**Comment by scannerdarkly** [comment]
That, evidently, was it. Thanks so much!
