### ISSUE TITLE
TYPOFIX: custPrefenceID to custPreferenceID

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#614]
`custPrefenceID` seems to be a typo for `custPreferenceID`.
```
class CustPreferencesModel extends BasicModel
{
    protected $name = "custPreferences";
    protected $preferred_db = 'op';
    protected $columns = array(
    'custPrefenceID' => array('type'=>'INT', 'increment'=>true),
```
It leads to a confusing report from `BasicModel.php --update` if there is already a correctly-spelled `custPreferenceID` in the table.

**Comment by gohanman** [comment]
I'll backport it into numbered versions later.

**Comment by flathat** [comment]
Shall I leave it here as I reminder and you can close then?

**Comment by gohanman** [comment]
That'd be all versions now.
