### ISSUE TITLE
Shrink records lack valid store_id

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#617]
`ShrinkEditor`'s UPDATEs of `dtransactions` records INSERTed by `ShrinkTool.php` fail because they lack a valid `store_id` (it is `NULL`).

This can be fixed by adding, in `DTrans.php`
```php
    public static $DEFAULTS = array(
// ...
        'trans_id'=>0,
        // add
        'store_id'=>0
    );
```
and in `ShrinkTool.php`
```php
    public function post_upc_description_department_cost_price_qty_reason_handler()
    {
        // global
        global $FANNIE_TRANS_DB, $FANNIE_EMP_NO, $FANNIE_REGISTER_NO, $FANNIE_STORE_ID;
        $dbc = FannieDB::get($FANNIE_TRANS_DB);

        $record = DTrans::$DEFAULTS;
//...
        $record['trans_status'] = 'Z';
        // assignment
        $record['store_id'] = $FANNIE_STORE_ID;
```
It cannot be fixed by simply appending `$record['store_id']` because the later
`DTrans::parameterize($record, 'datetime', $dbc->now());`
validates `$record` keys against `Dtrans::$DEFAULT`

**Comment by gohanman** [comment]
I believe this works better long term. Managing store_id inside the DTrans class means the code making use of it will generate consistent records.
