### ISSUE TITLE
Support for line_item_discountable

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#620]
It would be convenient if `products.line_item_discountable` had:
* a `departments` default
* search in Advanced Search
* change in Advanced Search > Group Edit Items (EditItemsFromSearch.php)

**Comment by gohanman** [comment]
I think for consistency discount should have the same 4-option drop down on advanced search & group edit that it has on the regular item editor. I haven't done anything with ```departments``` yet.

**Comment by gohanman** [comment]
And that should cover the rest of it.
