### ISSUE TITLE
some bugs

### ISSUE THREAD

**Issue by jcharles15** [CORE-POS/IS4C#621]
While I was navigating through the interface, I found a few bugs that I thought I should bring to attention. Just a few developmental bugs I noticed.

1. When trying to create signage a "No layouts available" error message shows. Shelf tag layouts seem to be displaying OK. Also on the Fannie install page the Default signage drop down comes up blank.
Layouts work fine in version 8 and before. 

2. Vendor case breakdowns - HTTP 400 Bad request

3. Cashier performance report - Missing required directory C:\xampp\htdocs\core-pos\IS4C-master\fannie\reports\cash_report/image_area

**Comment by gohanman** [comment]
This may address the layout one: 19296fea515453004c9602b106ac743298bc41d3. I don't have a Windows installation immediately handy to verify it.

The other two are to be expected. Breakdowns has to be accessed via the vendor editor, and you do have to manually create (and set permissions for) the image directory for that particular report.

**Comment by jcharles15** [comment]
working now thanks.  For vendor case breakdowns, when I try to view/edit breakdown mapping, it says entry added if I enter the sku or upc but it doesn't add it to the data grid. Run breakdowns doesn't do anything. Is there something I ain't doing right?

**Comment by gohanman** [comment]
Not sure immediately off hand. Is the VendorBreakdowns table actually
empty? The queries log might shed light on what's happening.

**Comment by jcharles15** [comment]
Vendor Breakdowns I confirm is not empty, records are actually there. Where is the queries log exactly. Under Fannie logs. or through MySQL interface.

**Comment by gohanman** [comment]
The default would be debug_fannie.log. You may need to run the table update
to add a "units" column.
