### ISSUE TITLE
Hardcoded receipt fields

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#622]
I was surprised to see that both the “thank you - owner ####” and “Current IOU Balance: $#.##” messages seem to be essentially hard coded into the receipt code. (The former is in `ReceiptLib::memberFooter($receipt)`, the latter in `ReceiptLib::chargeBalance($receipt, $program="charge", $trans_num='')`, both of which are invariably called by `ReceiptLib::printReceipt($arg1, $ref, $second=False, $email=False)` whenever a full receipt is printed.

Maybe I’m alone in this, but ideally I’d like to be able to use a user setting to control whether these are printed — the vast majority of our customers have no IOU balance and it’s a waste of receipt paper! Is there any chance these two fields could made part of the modular scheme?

Related, is there any setting to change “TODAY YOU SAVED = ” to be differently capitalized, or a different font size, or to omit the equals sign?

**Comment by gohanman** [comment]
The IOU line should only print if someone has a balance (and/or IOU activity in the current transaction). Specifically, this condition: https://github.com/CORE-POS/IS4C/blob/master/pos/is4c-nf/lib/ReceiptLib.php#L595

For the member line, are you just looking for an on/off toggle or changing the text or formatting of the message?

There's a setting for TODAY YOU SAVED in that you can write your own class and then choose that class instead of DefaultReceiptSavings in the configuration. If it's reasonably generic it could go in lib/ReceiptBuilding/ReceiptSavings; if it's more store-specific then it would fit better in a plugin.

**Comment by scannerdarkly** [comment]
**Current IOU Balance: $#.##**:
Because `$num_rows` > 0, the `if` statement you referenced evaluates to `true`. `$num_rows` is the number of rows returned by query `SELECT trans_id FROM localtranstoday WHERE emp_no=9999 AND register_no=99 AND trans_no=10 AND (trans_subtype='MI' OR department IN (0))`, which in one typical case is 11 because every table record for that transaction has `department` 0 **except** the merch item itself. (Example line items with department 0: `BADSCAN`, `CARDNO IN NUMFLAG`, `** 15% Discount Applied **`, `15% Discount`, `Subtotal 1.49`, `Tax0.05 #8310`, `Cash`, `Change`, `Discount`, `Tax`, `UEZ`, `custdata`.)

**thank you - owner ####**:
My preferred end result would be having the message reading “Thank you, Andy!” but I imagine others might want to include last names too. Is there a way the string could be specified using a `"Thank you, {$first_name} {$last_name} (#{$member_id})!"` notation or something equivalent?

**Comment by scannerdarkly** [comment]
Are ReceiptBuilding plugins permitted to include ESC/POS formatting codes, or are they supposed return plaintext so they can be used for multiple output formats such as ESC/POS, emailed receipts, etc?

**Comment by gohanman** [comment]
Currently they should be plaintext.

Longer term it would make sense to pass a ```PrintHandler``` object into different modules so they can use its formatted methods without worrying about what the output device is. From a timing standpoint I'd like to hold off on those changes until I can wrap up the testing the next release.

**Comment by gohanman** [comment]
RE: IOU Balance: what's your setting for ```ArDepartments```? That ```IN (0)``` should not be happening.

RE: thank you - owner:
My inclination would be to just make the whole thing replaceable. It's less user-friendly than the templated approach in that you have to write a bit of code to get custom behavior, but it's substantially more flexible. Receipts seem to be an area where everyone has slightly different preferences and maximizing customizability is a good choice.

**Comment by scannerdarkly** [comment]
I totally dig the flexibility of having a full-fledged object as you describe, for the reasons you describe.

In the lane’s `parameters` table, `ArDepartments` has `param_value = 0` and `is_array = 1`.

**Comment by gohanman** [comment]
Looks like a configuration UI bug. Making the param_value blank or NULL or -1 should take care of it in the meantime.

**Comment by scannerdarkly** [comment]
NULL didn’t work, but blank did. Thanks! What does `ArDepartments` do, if you have time to explain?

**Comment by joelbrock** [comment]
In CORE, AR refers to Accounts Receivable, or more generally, charge accounts or "tabs".  So AR Departments is the department number of any depts. related to charging.   
ex. dept. CHARGE PAYMENTS would be where staff/owners can make payments into a charge account.

trans_subtype = 'MI' refers to the default tendercode for the CHARGE TENDER type.  Create a tender type with the code 'MI', assign it the StoreChargeTender type in the extras tab.  You can now use the MI Charge Tender to pay for groceries with member accounts that currently have a balance > 0 and custdata.ChargeOK = 1.  

Tip: BQ{ENTER} pulls up the balance inquiry at the lane.

**Comment by scannerdarkly** [comment]
Nice, thanks so much for explaining!

**Comment by gohanman** [comment]
The base class for swappable "Thank you" line(s) has been added into current master as well as injecting PrintHandlers into the different receipt modules to allow for formatting text.

**Comment by scannerdarkly** [comment]
`Thank you - owner Andy Theuninck`
:-)

**Comment by gohanman** [comment]
Is there anything left in this one that still needs to be addressed?

**Comment by scannerdarkly** [comment]
Nope, we good!
