### ISSUE TITLE
Tender reports blank

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#624]
If I use the MG shortcut to do a tender report, nothing prints — the printer just emits a cutting sound. I've already checked *everything* in Tender Mapping on the Extras install page. Am I missing something?

**Comment by gohanman** [comment]
The default tender report won't print anything if:

* None of the selected tenders have been used by that cashier that day (perhaps obvious)
* The lane cannot reach the server
* The lane is number 99
* The training cashier (9999) is logged in

The latter two are a consequence of how training/testing/dev transactions get filtered out of reporting in general.

**Comment by gohanman** [comment]
Did this ever get resolved?

**Comment by scannerdarkly** [comment]
Yes, I just got it working today in fact. Thanks!

**Comment by flathat** [comment]
> The default tender report won't print anything if:
>  + The lane cannot reach the server

Just FYI [WefcTorontoTenderReport] (https://github.com/CORE-POS/IS4C/blob/master/pos/is4c-nf/lib/ReceiptBuilding/TenderReports/WefcTorontoTenderReport.php) reports from a lane table if the server is inaccessible. (It also contains some "did the session end properly?" checks that may have been based on a misunderstanding of mine.)

**Comment by gohanman** [comment]
Whether that's a useful option depends a lot on operational assumptions. If tender reports are per-cashier and cashiers are allowed to switch lanes during the day, printing a partial, local report may not be terribly helpful.  When drawers are dropped & counted and when reports are printed will change what the report should/can balance against.

**Comment by flathat** [comment]
I should have mentioned that WEFC's reports are per-lane, not per-cashier, no mid-day cash drops, tills don't move.
