### ISSUE TITLE
products.multi.php discards diagnostic info

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#625]
Take a look at **IS4C/fannie/sync/special/products.multi.php**:
```php
exec($cmd, $output, $ret);
if ($ret > 0) {
    if (file_exists($tempfile . '.err')) {
        $output .= file_get_contents($tempfile . '.err');
        unlink($tempfile . '.err');
    }
    $report = implode($lineBreak, $output);
```
Note that in the event of an unsuccessful `exec`, `$output` is created as an array, then appended to as a string, and then its current value is subjected to `implode()` which takes an array argument. The net result is that `$report` discards the contents of the error file. I believe line 81 should read:
```
        $output[] = file_get_contents($tempfile . '.err');
```
or
```
        $output += file($tempfile . '.err');
```
Similar issues exist for **generic.mysql.php**.

Thoughts?

**Comment by gohanman** [comment]
It probably makes more sense to ignore $output entirely take out the implode part too. With both stdout and stderr redirected $output is always going to be empty.

**Comment by scannerdarkly** [comment]
So replace `$output .= file_get_contents($tempfile . '.err');` and `$report = implode($lineBreak, $output);` with `$report = file_get_contents($tempfile . '.err');`?

**Comment by gohanman** [comment]
As discussed.
