### ISSUE TITLE
Reason for suppressing apostrophe in brand

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#626]
What is the reason for ItemEditor `BaseItemModule.php` suppressing apostrophes (single quotes) in `products.brand`, `prodExtra.manufacturer` and other text fields?

```php
            $brand = FormLib::get('manufacturer');
            if (isset($brand[$i])) {
                $model->brand(str_replace("'", '', $brand[$i]));
            }
```
Quite a few of our brand names are possessives and others, especially in French, are contractions; they really don't look right on shelftags, etc. without the apostrophes. That module also suppresses them in `products.description` and `prodExtra.distributor` (vendor name), but not in `productUser.description`.

Shelf tags (`addShelfTag.php`) supports apostrophes as long as you fix the HTML `value="Bob's Red Mill"` coding:
```
<label>Brand</label>
    <input type='text' name='brand' maxlength=15
        class="form-control"
<?php
echo "value=\"".strtoupper($brand)."\"";
?>
>
// Instead of
echo "value='".strtoupper($brand)."'";
```
although that has been very recently overtaken in `master` by:
```php
<input type='text' name='brand' maxlength=15 
                class="form-control" value="<?php echo strtoupper($brand); ?>" />
```

Also no trouble in autocomplete or in the Brand Movement report.

**Comment by gohanman** [comment]
I think you've identified it. There are places where apostrophes will break things and I haven't sat down and searched the code to find all of them and make sure they've been fixed.

**Comment by scannerdarkly** [comment]
@flathat, in the short term could you use a [Unicode apostrophe](http://www.charbase.com/2019-unicode-right-single-quotation-mark)? It has the virtue of being a more correct apostrophe, typographically.

In the long run, it would bring me great joy to contribute to cleaning up the database code to permit use of arbitrary characters. PDO’s parameterized prepared statements make this rather easy.

**Comment by gohanman** [comment]
Database code should be by and large a non-issue. Prepared statements are used throughout the backend already for security reasons.  Syncing between lane and server should be ok but I'd have to check all the variants.

Whichever character(s) get used for html attribute delimiters need to be html escaped for display.



Andy

**Comment by gohanman** [comment]
Filters are gone, albeit only in master. If anything goes wrong that's why it's the dev branch.

**Comment by flathat** [comment]
I made a couple comments on the commit https://github.com/CORE-POS/IS4C/commit/8fec9d35e1bf4e5796a492bc468770ec0d0fe56c .

**Comment by flathat** [comment]
Apostrophes also do not cause trouble in lane syncing utilities such as Scheduled Tasks `lanesync.api.php` and `LaneSyncTask.php` when they use `mysqldump`, e.g. via symlinks to `sync/special/generic.mysql.php`.  I haven't tried syncing using the record-by-record `SQLManager->transfer()`.

**Comment by gohanman** [comment]
Forgot to put the issue number in the commit: 65c4f45420b1e9eef25013b27d89ab551205ec12

That was indeed a remaining problem w/ apostrophe handling.
