### ISSUE TITLE
Bugfix for TenderReport.php

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#627]
The default tender report was printing zeroes for both Amount Tendered and Change.

Turned out the base class implementation of `TenderReport::standardLine()` wasn’t using the `$amt` parameter passed to it. I fixed that. The Change amount isn’t passed as a parameter to `TenderReport::standardLine()`, making that number unavailable, so I replaced the zeroes it was printing with '-' to indicate an unknown amount.

Please see changes [here](https://github.com/GeorgeStreetCoop/CORE-POS/commit/0f3453ad5519706f0fb081847594b6b3faab6a0a). (Sorry, I'm still far from fluent in Git and couldn’t figure out how to do a pull request without bringing in a million unrelated bits.)

**Comment by gohanman** [comment]
The ```$amt``` bit was addressed here: a4eaa6ae7700bad0cade01936e5f8983bfdbd1cc. I've backported that into 1.9. The change zero doesn't bother me as it's consistent with [most? all?] past behavior.

**Comment by flathat** [comment]
> how to do a [git] pull request without bringing in a million unrelated bits

@scannerdarkly , if you can restrict the bits you want upstream to particular commits @gohanman  has been very good about pulling only those from a regular pull request.

**Comment by gohanman** [comment]
Git & pull requests & stuff:

Each branch is essentially just a long list of commits. If you take the starting state of the repo and apply all the changes in those commits in order you end up at the current state of the branch. If you have a pull request from branch A to branch B, it's going to look at both histories to find all the commits that *are* in branch A's history but *are not* in branch B's history. That set of commits is what gets sent in the pull request.

The other important piece is new branches don't [typically] start from scratch; they inherit another branch's history. So to a fine-tuned pull request, you would do:
```
git checkout -b pull-request upstream/master
```
That's going to create a new branch ```pull-request``` using the upstream ```master``` branch as a starting point. These branches currently have the exact same commit history. Then
```
git cherry-pick <sha>
```
Where ```<sha>``` is the hash of a commit you want to send. Now ```pull-request```'s history differs from ```master```'s history by this one commit so your pull request will include only that commit. Repeat as needed to send more than one.

**Comment by scannerdarkly** [comment]
Thank you so much! In much [frustrated] reading up on git, somehow I’ve never actually encountered the `cherry-pick` command before.
