### ISSUE TITLE
"NR" has no effect

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#628]
I understand that the `NR` command is supposed to [toggle receipt printing](https://github.com/CORE-POS/IS4C/wiki/Cashier-Handbook#the-lane-interface)?

Using version 1.9 on my system, `NR` doesn’t seem to have any effect. It doesn’t pop up an error message – which suggests to me that the system parser understands it but doesn’t correctly complete toggling flags.

Any ideas what might be happening?

**Comment by gohanman** [comment]
I'm honestly not sure how NR is supposed to work. It exists as a legacy command *prefix* that's been around forever. RP will also toggle printing as a standalone command (during a transaction; with nothing rung in RP goes to the reprint receipt screen).

**Comment by scannerdarkly** [comment]
RP is just fine for my current purposes then!

Has the group developed a procedure for identifying and removing unused code? I happen to love that kind of cleanup, so I’d be very happy to take part.

**Comment by gohanman** [comment]
"Unused" isn't easily quantifiable. I'm pretty sure there's no single store making use of every available feature, but I don't have any way of tracking exactly what's being used across all installs.

It looks to me like NR does actually work (both when used a prefix & when used alone but in the latter case it can't immediately update the receipt icon). I'd rather leave it for the sake of IS4C-compatibility. CORE's not an exact drop in replacement but every command that still works as expected is a plus.

**Comment by scannerdarkly** [comment]
Fair enough. I just figured there might be a way to check in with the client base and see what no longer needs maintaining. Trying to make your job easier @gohanman!

**Comment by gohanman** [comment]
It's an interesting idea. I've thought about some optional usage reporting (and version info reporting) on the back end but not for the lane. My main concerns would be overhead (lane machines tend to be weaker & slow downs are more noticeable) and sufficient anonymization so it's not leaking sales data or something. An any event, probably a separate subject.
