### ISSUE TITLE
"PO" has no effect

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#629]
I understand that the `PO` command is supposed to initiate a price override?

Using version 1.9 on my system, `PO` pops up a user authentication dialog, requests a new price from the user, and then returns the user to the main POS UI **with all the prices unchanged**. It doesn’t pop up an error message – which suggests to me that the system parser understands it but doesn’t correctly process it.

Any ideas what might be happening?

**Comment by gohanman** [comment]
This probably addresses it.

**Comment by scannerdarkly** [comment]
I made that change, and still no joy. I suspect it did help, though, because now I’m seeing a new pair of errors in the error log:
```
Undefined variable: row in /CORE-POS/pos/is4c-nf/gui-modules/priceOverride.php on line 92
Undefined variable: line_id in /CORE-POS/pos/is4c-nf/gui-modules/priceOverride.php on line 97
```
These are in `rePrice()`, and sure enough neither of those variables were passed to that method.

**Comment by scannerdarkly** [comment]
Alternatively: Is there another way that people currently do price overrides with this system?

**Comment by gohanman** [comment]
I'll backport that if it works correctly

**Comment by scannerdarkly** [comment]
I’ll test it now, thanks!

**Comment by scannerdarkly** [comment]
That works! Thanks so much. (Again.)

**Comment by gohanman** [comment]
RE: Another way:

I don't use price overrides at all. For better or worse features I don't use are much more likely to sneak through testing with bugs.

**Comment by scannerdarkly** [comment]
It's understandable.
