### ISSUE TITLE
How to do Payouts?

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#630]
Another aspect of George Street Co-op’s existing workflow that I’d like to know if it’s replicable in CORE-POS...

Our old registers have a Payout key for small petty cash payments. For example, we need to send someone to the 7-Eleven for some random sundry, we’ll ring in a small payout of say $5, hand them a fiver. The payout shows on the end of day report as a separate item (outside of any item sales), so we know why the drawer is short.

Does anyone do this within CORE-POS?

**Comment by gohanman** [comment]
We have a payouts department for this purpose. Anything in super department zero gets excluded from most sales reporting.

**Comment by scannerdarkly** [comment]
I’m confused, won’t this shift the end-of-shift tender report in the wrong direction? Or do you do all these as Refunds in that department?

**Comment by gohanman** [comment]
Yes, they'd be refunds.

**Comment by joelbrock** [comment]
FWIW:  I second Andy's solution.  This would be created as a department, in my installs its often "RECEIVED ON ACCOUNT" or similar.  And staff does a REFUND to this open department.
Usecases include:  writing checks for vendors that require payment on delivery.  Or an example where cash would go IN to this department (rather than out): the bookkeeper wants to run a check through the POS for bookkeeping purposes.
The kyboard command "CM" allows cashier to enter a "comment" that can be used to describe what the R/A was for.
Both of these work:
- CM[[TYPEYOURCOMMENT]]{ENTER}
- CM{ENTER}
  - [[TYPEYOURCOMMENT]]{ENTER}{ENTER}

**Comment by scannerdarkly** [comment]
Ah, okay. One more thing, and not a deal-breaker but it would be nice to have: Our old system doesn’t let you do payouts mixed in with any other transaction. Is there any similar mechanism possible with CORE-POS?

Again, just a nice-to-have.

**Comment by scannerdarkly** [comment]
And wow, that CM thing is cool!

**Comment by gohanman** [comment]
RE: payout department mixed into transactions:
You could probably write a ```SpecialDept``` that enforces the restriction and associate it with that particular department, but nothing exists out of the box.

RE: Comments
All input on the "main" screen gets converted to upper case (which simplifies parsing commands). So CM followed directly but the comment goes to uppercase. If you just enter CM, the dedicated comment-entry screen doesn't do any kind of conversion. That should add the comment to the transaction with casing exactly as typed.

**Comment by scannerdarkly** [comment]
> All input on the "main" screen gets converted to upper case (which simplifies parsing commands).

Ah, that makes sense. If I felt like turning the parser case-insensitive so as to preserve comment case, would anyone (including you @gohanman) object?

Any idea why the receipt lowercases the comment?

**Comment by gohanman** [comment]
Preserving comment case doesn't seem significant enough of an issue to justify changing input parsing behavior and every existing parser. As far as the receipts I doubt there's a reason beyond that's how the default receipt happens to format them.

**Comment by scannerdarkly** [comment]
It’s not that much of a change. If you stash the user’s original input (in AjaxParser.php)...
```
        CoreLocal::set('lastInput', trim(FormLib::get($in_field)));
```
...you can retrieve it in Comment.php...
```
            $comment = substr(CoreLocal::get('lastInput'),2);
```
...with no need to change any of the other parsers.

I just feel like our cashiers will like the system better if it preserves their mode of expression better.

**Comment by gohanman** [comment]
I'd guess ```RFCMTest``` doesn't do what you expect. It doesn't particularly matter in this case but throwing that variable into the session allows other mistakes where ignoring part of input processing does matter.

**Comment by scannerdarkly** [comment]
What is `RFCMTest`?

**Comment by gohanman** [comment]
It's a [non-sensical] POS command. It would currently result in the comment ```TEST```. With your change, it would result in the comment ```CMTest```.

The original input may be modified in the preparsing stage (in this case, removing the RF and setting a refund flag) before moving on to the parsing stage. If the comment parser assumes ```CoreLocal::get('lastInput')``` contains the same input it was given but merely in the original capitalization, it may well be wrong.

As I said, it doesn't particularly matter in this case. But the ```lastInput``` value may contain unexpected surprises. And unexpected surprises often means bugs.

**Comment by scannerdarkly** [comment]
Ah, okay. Since that check-in I’ve made it so `CM` is entered as a trailing string, which accords with a user’s natural behavior (type comment then hit a `COMMENT` key), and so the `RFCMTest` problem doesn’t occur here.

**Comment by gohanman** [comment]
FWIW, this is a type of change I'm very hesitant to incorporate upstream. I'm fairly unconvinced that there's an empirically more natural option and even if there is changing the order of a command is going to trip up existing users regardless.

As an aside, I'd suspect that if you've simply changed it to a suffix, `RFTestCM` will still be accepted as a command and result in the comment `RFTest` when using the `lastInput` idea.
