### ISSUE TITLE
Tender menu shortcut

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#632]
Is there a shortcut to pop up a list of all the tenders, letting a cashier choose one of the less-used ones without devoting a whole dedicated button to each of them?

**Comment by joelbrock** [comment]
"TT{ENTER}"

**Comment by scannerdarkly** [comment]
AWESOME! Okay, in this menu I see tenders which I’m not intending us to use. Is it okay to delete a tender, or are there places where the codes are also hardcoded and a deletion would leave the system to act in an undefined fashion? Alternatively, 

Related question: Is `CP` a generic code, of which `IC` is a type? Or is `CP` for manufacturer coupons?

**Comment by gohanman** [comment]
CP is indeed manufacturer coupons.

I think the following are required or mostly required:
* CA for cash. It's the default type for Change records if no other info is available.
* CP for manufacturer coupons
* IC for in-store coupons (if you're using them)
* Either FS or EF for SNAP/EBT. This related to exempting sales tax.
* MI for store charge (if you're using it). This relates to calculating balances.

I don't think there's anything else hard coded. Alternately, IMO it'd be reasonable to have the menu exclude tenders where ```TenderModule = 'DisabledTender'```.

**Comment by scannerdarkly** [comment]
That seems sound. How do you set a Tender’s `TenderModule` from the front end? (I do see it in the database.)

**Comment by gohanman** [comment]
It's on the Extra config page.

**Comment by scannerdarkly** [comment]
Great, thanks. Aside from the fact that the initial configuration would be different, would a QuickMenu with the tender list wind up functioning worse than the `TT` menu with the filters as you described? There’s probably some obvious difference that doesn’t occur to my newbie brain...

**Comment by gohanman** [comment]
I don't think so. Setting things to disabled is still not a bad idea just to prevent miskeys / accidental tenders.

**Comment by scannerdarkly** [comment]
Very good point! I'm confused though — you’re saying `DisabledTender` is fully implemented within the system, except for the `TT` menu?

**Comment by gohanman** [comment]
Yes, ```DisabledTender``` is one of the modules that can be mapped to a tender on the extras tab.

**Comment by scannerdarkly** [comment]
Got it. Implemented the change to `TT` per your suggestion. Also made the tender list auto-size to fit its contents (unless there’s more than 15 tenders, in which case it stays at 15 rows).

Committed [here](https://github.com/GeorgeStreetCoop/CORE-POS/commit/89d91d8c5c473a68a53a978f8b857095cc64a027).
