### ISSUE TITLE
How to enter multi-item deals?

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#633]
We have these great spinach pies that we normally sell for $1.25 each, but if you get a soup (any one of about a dozen kinds of soup) up to two spinach pies on the same purchase are discounted down to $1.00.

I’ve looked at the wiki and I don’t see how this is entered in CORE-POS, even though the database has some fields which would seem to support this. Is there some documentation I’m missing?

**Comment by joelbrock** [comment]
Dunno if this is documented in the wiki but it is in the Help text within Fannie.  If you go to the House/Store Coupon editor in Fannie you should be able to read up on the HouseCoupon params.  Also, here: https://github.com/CORE-POS/IS4C/blob/master/fannie/modules/plugins2.0/HouseCoupon/explainify.html

But sounds like you'd be looking to use the "mixed" minimum qualifier.  And require the soup PLUs.

**Comment by gohanman** [comment]
I think it would be more accurate to say "The interface to configure this type of pricing is missing, and the documentation for said interface is also missing".

https://github.com/CORE-POS/IS4C/wiki/Additional-Pricing-Methods

I don't think any of these actually cover your scenario. The split pricing options are close but the "up to two" piece is problematic.

**Comment by scannerdarkly** [comment]
No worries, we can just have two PLUs and keep this one manual. :)
