### ISSUE TITLE
Best way to clear out a lane for rollout?

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#636]
About to start parallel testing the lanes. Really excited here. :)

Is there a best way to get the old (fake) transaction data out of the system? I’m fine with truncating tables if that’s the best way...

Also, is there a particular set of cron tasks (or any other recurring tasks) that absolutely must be run nightly?

**Comment by joelbrock** [comment]
If you've assigned the testlane the dedicated lane number of 99, then there isn't any nec. steps to clean out data.  It will be ignored by all reports.  (dont forget to change the lane # before putting into production!)

In the interest of simply starting fresh, you could do this __on the lane__:
```sql
TRUNCATE translog.localtrans;
```

and __on the server__:
```sql
TRUNCATE core_trans.dtransactions;
TRUNCATE core_trans.transarchive;
TRUNCATE core_trans.dlog_15;
TRUNCATE trans_archive.bigArchive;
```
There may be more on the server depending on which nightly tasks had been running.

As for essential nightly tasks:
- Transaction Archiving
- Sales Batch Task
- Lane Data Sync
- Equity History

**Comment by scannerdarkly** [comment]
Great! Do any of these tasks depend on another task to precede them?

**Comment by joelbrock** [comment]
Most just need to be run after midnight. 
Obviously, schedule lane sync task to run AFTER sales batch task in order to ensure the latest sales data is on the registers for start of business.
More info here:  https://github.com/CORE-POS/IS4C/wiki/Scheduled-Tasks

**Comment by gohanman** [comment]
Joel covered most of it well. I expanded the wiki article to cover a few more broadly applicable ones. Table Snapshot is absolutely unnecessary but still not a bad idea. The others mentioned are somewhere on that scale - a report or other UI element won't return useful info without them.
