### ISSUE TITLE
Blank General Day Report

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#637]
I’m sure this is a simple configuration thing I’m missing.

In testing, it seemed the General Day Report was the best drop-in replacement for the end of day department reports we printed on our previous cash register.

Unfortunately, right now the General Day Report shows blank/zeroes. The `office_trans.dtransactions` has 698 records in it though. Why would the GDR be unable to see these transactions?

Related question, is there a different/better way to get daily summaries of department movement for QuickBooks purposes?

**Comment by gohanman** [comment]
If those records are register_no 99 or emp_no 9999 they'll be excluded from all reports (as training/testing/dev). Otherwise there's no reason for the report to show zeroes, especially across all the separate sections. Unless perhaps the backend if configured to use a different named database than office_trans.

**Comment by joelbrock** [comment]
also, if the data is in the `dtransactions` table then your nightly scripts havent run yet?  reports only look in `dtransactions` for "todays" data.  Any other date it is going to look in `dlog_15`, `dlog_90_view`, or `trans_archive.bigArchive` for historical data.

**Comment by gohanman** [comment]
Good point. That would also do it.

**Comment by scannerdarkly** [comment]
I finally had a chance to insert some tracing code into `fannie/reports/GeneralDay/GeneralDayReport.php`. Running reports today, February 5th:
* Running a report on 2/5/2016 sales, `$dlog` = “office_trans.dlog”, which doesn’t exist. (I do have a populated `office_trans.dtransactions`  table though, guess one of my backup processes isn’t working?)
* Running a report on 2/4/2016 sales, `$dlog` = “office_trans.dlog_15”, which exists but is empty.
* Running a report on 2/4/**2015** sales (one year ago), `$dlog` = “office_trans_archive.dlogBig”, which doesn’t exist. (I do have an empty `office_trans_archive.bigArchive` table though...)

I have the feeling there might be two separate issues here. Thoughts?

**Comment by gohanman** [comment]
The views in question are created directly by the install page rather than
any archiving process. It should show errors related to any tables or views
that could not be created.

**Comment by scannerdarkly** [comment]
Newbie mistake, I forgot to scout for views! Sorry for that boneheaded error. Both `office_trans.dlog` and `office_trans_archive.dlogBig` views exist, and are empty.

But `dlog_15` is also empty, and now I’m trying to figure out why. Am I right that `TransArchiveTask.php` is the main process that should be filling it?

If so, unfortunately `TransArchiveTask.php` is consistently failing at [this](https://github.com/CORE-POS/IS4C/blob/master/fannie/cron/tasks/TransArchiveTask.php#L178) point, when it calls through to [here](https://github.com/CORE-POS/IS4C/blob/master/fannie/cron/tasks/TransArchiveTask.php#L41), which dies [here](https://github.com/CORE-POS/IS4C/blob/master/common/SQLManager.php#L1087) because `$conn` = false instead of an object. (`$this->default_db` = “office_trans”, and `$this->connections` = `array('office_trans' => false)`).

Any idea how I should investigate this further?

**Comment by gohanman** [comment]
I'd say your really issue is here:
https://github.com/CORE-POS/IS4C/blob/master/fannie/cron/tasks/TransArchiveTask.php#L173

If FannieDB cannot connect to the database the task can't do anything. Virtually everything on the backend doesn't work if FannieDB cannot connect to the database. Does the install/config page show success for both databases in the Main Server section?

**Comment by scannerdarkly** [comment]
I think I’ve figured it out, but please check me on this.

The install/config page said both connections were good. It was all on one machine, with Server Database Host = `localhost`.

I threw in two debug lines to see what was coming back from line 173:
```
        $sql = FannieDB::get($FANNIE_TRANS_DB);
        var_export($FANNIE_TRANS_DB);
        var_export($sql);
```
and it output this:
```
'office_trans'
SQLManager::__set_state(array(
   'QUERY_LOG' => 
  FannieLogger::__set_state(array(
     'program_name' => 'fannie',
     'log_level_map' => 
    array (
      0 => 'emergency',
      1 => 'alert',
      2 => 'critical',
      3 => 'error',
      4 => 'warning',
      5 => 'notice',
      6 => 'info',
      7 => 'debug',
    ),
     'syslog_host' => false,
     'syslog_port' => 514,
     'syslog_protocol' => 'udp',
  )),
   'connections' => 
  array (
    'office_trans' => false,
  ),
   'default_db' => 'office_trans',
   'throw_on_fail' => false,
   'structure_cache' => 
  array (
  ),
   'last_connect_error' => 'Connection attempt failed: SQLSTATE[HY000] [2002] No such file or directory',
   'test_data' => 
  array (
  ),
   'test_counter' => 0,
   'test_mode' => false,
   'adapters' => 
  array (
  ),
   'adapter_map' => 
  array (
    'mysql' => 'COREPOS\\common\\sql\\MysqlAdapter',
    'mysqli' => 'COREPOS\\common\\sql\\MysqlAdapter',
    'pdo_mysql' => 'COREPOS\\common\\sql\\MysqlAdapter',
    'pdo' => 'COREPOS\\common\\sql\\MysqlAdapter',
    'mssql' => 'COREPOS\\common\\sql\\MssqlAdapter',
    'pgsql' => 'COREPOS\\common\\sql\\PgsqlAdapter',
    'sqlite3' => 'COREPOS\\common\\sql\\SqliteAdapter',
  ),
   'last_connection_error' => false,
))
```
Noting the `'Connection attempt failed: SQLSTATE[HY000] [2002] No such file or directory'`, I googled it and found [this](http://stackoverflow.com/questions/20723803/pdoexception-sqlstatehy000-2002-no-such-file-or-directory).

So I tried changing the Server Database Host from `localhost` to `127.0.0.1`, reran TransArchiveTask, and now it didn’t seem to report any errors. And I noticed `dtransactions` lost a lot of records (though not all), and `dlog_15` gained a lot.

Does this describe a working TransArchiveTask?

**Comment by scannerdarkly** [comment]
I should add that running it a second time, it said “TransArchiveTask: No data to rotate”, which sounds encouraging!

**Comment by gohanman** [comment]
The SO answers seem mostly right. I'm sure it does have to do with localhost getting mapped to a unix socket file. The other distinction is most likely that php-cli and mod_php5 (or php5-fpm) have separate ini files with different mysql-related settings.

TransArchiveTask is going to:
* Copy records excluding the current day from dtransactions to:
  * transarchive
  * bigArchive
* Reload dlog_15 entirely from dlog_90_view
* Remove the copied records from dtransactions
