### ISSUE TITLE
Drawer doesn’t open on CC transactions

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#638]
Is there a configuration option to make the cash drawer open at the conclusion of credit card transactions? We don’t have integrated credit cards, we run them on a separate machine (for now) and need to stash the signed receipts in the cash drawer.

**Comment by gohanman** [comment]
The selected Kicker controls this. There are a number of them in lib/Kickers/ or you can add your own.

**Comment by scannerdarkly** [comment]
Nice, thanks!

**Comment by scannerdarkly** [comment]
I wrote an AlwaysKick.php which is basically the exact opposite of NoKick.php. Any interest in having it in the standard codebase?

**Comment by gohanman** [comment]
Sure. I can probably make an identical one pretty easily if you don't feel like spending time on a pull request.

**Comment by scannerdarkly** [comment]
Well, if I do a pull request at one point in the history, does it force you to a pile of cherrypicking?

**Comment by scannerdarkly** [comment]
That’s it!
