### ISSUE TITLE
BUG: Printer port = “other” in extra_config.php

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#641]
This has happened several times over the past few days as I was trying to troubleshoot receipt issues:

At some point in all these configuration changes, the lane’s `printerPort` entry in `core_opdata.parameters` somehow gets changed to “other”. Once it does that, `extra_config.php` can’t seem to change it to any other value. I have to go into the database and manually set the value back to “/dev/ttyS1”, and then log out and back in, at which point the madness relents.

**Comment by gohanman** [comment]
That should work. I'm tempted to tear the whole thing out and replace it with an `InstallUtilities::installTextField`. The specialized form can't cover all the options anyway.

**Comment by scannerdarkly** [comment]
This seems to have fixed it perfectly. Thanks so much!
