### ISSUE TITLE
Hardcoded “magic” UPC in dlog view

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#644]
It seems that any `upc like '%00000000052'` is going to have its subtype overridden as “RR” in the `dlog` view.

As it happens, I do have an item defined with this PLU. Do I need to change the UPC, or is there a way to safely remove this sorcery?

**Comment by gohanman** [comment]
You can alter the view(s) of course. I'd have to look at old data more before trying to clean it up correctly.

**Comment by gohanman** [comment]
I changed the view structure. It's opt-in though; CORE won't drop the views itself but you can drop them and let CORE re-create them without the magic PLU.

**Comment by scannerdarkly** [comment]
Thanks!!!

**Comment by scannerdarkly** [comment]
I deleted `office_trans.dlog` and `office_trans.dlog_90_view`, and so far nothing seems to be recreating them. Which process does this?

**Comment by gohanman** [comment]
Viewing the install page

**Comment by scannerdarkly** [comment]
That’s what I thought, and attempted. Instead I’ve been getting something I can’t explain. See http://github.com/CORE-POS/IS4C/issues/663 as it seems to be a separate issue from this one.

**Comment by scannerdarkly** [comment]
Also, http://github.com/CORE-POS/IS4C/issues/664.
