### ISSUE TITLE
Guide to trans_type, trans_subtype, trans_status, charflag?

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#647]
In the interest of being able to better understand (and write) the codebase: Is there documentation which lists all the possible values for these fields in `dtransactions`, `dlog_15`, etc, along with their meanings?

**Comment by gohanman** [comment]
https://github.com/CORE-POS/IS4C/wiki/Office-Transaction-Database#dtransactions

**Comment by scannerdarkly** [comment]
Awesome, thanks!

**Comment by scannerdarkly** [comment]
Awesome, thanks!

In my investigation I noted a few unlisted types in my mostly-stock install. Should we add them to the documentation?
* `trans_type`:  `L` (log record?) `S` (savings?)
* `trans_subtype`: `NA`/`AD` (when `trans_type` = `I`; `AD` is “auto-deposit” for the bottles, I assume `NA` stands for “normal add”?)

**Comment by gohanman** [comment]
FWIW it's actually a code issue. The authoritative source is https://github.com/CORE-POS/IS4C/blob/master/fannie/classlib2.0/data/models/trans/DTransactionsModel.php#L661-L817; the models can emit markdown to fill in the wiki.

L is indeed log; S gets attached to upc=DISCOUNT records although I don't know any rhyme or reason for it other than it's been that way forever.

AD is auto deposit. NA is more like n/a - not available or unknown. SS is scanner-scale, KB is programmed key, HI is USB scanner. In the latter two cases the hardware would have to be programmed with an appropriate prefix. I don't know that anyone is actually using those. SS may have been wonky for a bit until 31d9a881f591332366db301f87313f0a54f83299.

**Comment by scannerdarkly** [comment]
Would it be appropriate for these other types to be added to `DTransactionsModel.php`?

**Comment by gohanman** [comment]
Sure

**Comment by scannerdarkly** [comment]
K, did my best. [scannerdarkly-patch-1](http://github.com/CORE-POS/IS4C/compare/master...scannerdarkly-patch-1)

**Comment by scannerdarkly** [comment]
Thanks!

**Comment by flathat** [comment]
Re `dtransactions.charflag` and also `numflag` in `products` and `dtransactions` , they now need a bit more than:
> numflag and charflag are generic status indicators. As far as I know, there's no uniform usage across implementations.

For `numflag`, something like: "`numflag` is used to hold bitwise flags for product characteristics as defined in `core_op.prodFlags`.  These can vary per co-op and may not be used at all.  For transaction records that are not for products it doesn't currently have a defined use."

For `charflag` it is less clear and usage is certainly still "not uniform".  The only values I could find in the `item/` and `plugins2.0/` code are:
+ `B2` from `PIKiller`
+ `PT` from `RecurringEquity`
+ `S` from `MobileLane`
+ `SO` from `WooSync`, likely meaning "Special Order", which `AdvanedItemSearch->filterMovement()` filters.

My own interest is in trying to distinguish some Correction-type transactions in a plugin for reporting purposes.  It (`charflag = 'FX'`) seems specialized enough not to get entangled with the above, but in other use cases it might not be so clear.  Is it practical to "register" these?

**Comment by gohanman** [comment]
It probably makes more sense to look at lane code in this case as that's mostly where the values get generated/written.

Charflag:
* `PW` marks a log recording a failed admin login attempt
* `PO` marks a record where price was overriden
* `HR` is a human-readable transaction identifier (HRI)
* `SR` is a record added after resuming a transaction referencing the original transaction
* `PT` a tender record from integrated transactions. In this case `numflag` contains the corresponding `paycardTransactionID`.
* It contains a number in upc=`MEMENTRY` records. `charflag` is `custdata.personNum` and `numflag` is `custdata.CardNo`
* `SO` is a CORE special order line item
* `RD` is a reduced, variably-priced item
* `IU` is a log record indicating an item sold while `inUse` is `0`
* `IC` is used with a customer number in `numflag` in the `WFC/LinkedCoupon` plugin
* `AnnualMeeting` plugin puts arbitrary letters in the column
* `B2` marks a invoice payment and `numflag` is the invoice number.
* `S` marks a suspended transaction to distinguish it from cancelled (and may overwrite most of the above)

I don't know where we would maintain some kind of registry. Duplicate usage in plugins is theoretically fine as long as you only need to use one of them.

**Comment by gohanman** [comment]
I thought it was the case, but didn't find it at a glance yesterday. This is not true:

>For numflag, something like: "numflag is used to hold bitwise flags for product characteristics as defined in core_op.prodFlags. These can vary per co-op and may not be used at all. For transaction records that are not for products it doesn't currently have a defined use."

On item records, `numflag` usually contains the value from `products.local` (via [here](https://github.com/CORE-POS/IS4C/blob/master/pos/is4c-nf/parser/parse/UPC.php#L358)). As far as I can recall this has always been the case.

Besides the usages mentioned above in conjunction with `charflag`, `numflag` will contain the tax rate ID on upc=`TAXLINEITEM` records and the shrink reason ID on shrink records.

**Comment by flathat** [comment]
> I thought it was the case, ... This is not true:

I should have checked before composing the statement.

But it seems an unfortunate loss of information to the transaction record.  I know there's been discussion about "local" being one of the bits in `numflag` instead of a field on its own.  It is used at most co-ops, or at least "localness" is important to them.  I don't remember why "organic" doesn't have the same status.  Changing the model to add a field for each feature that may turn out to be a fad is not a good idea. But if "local" had no `numflag` bit then it would be lost to transaction reporting.  I'm not aware of transaction reporting that uses the `numflag` bits, gets them from `products` during the reporting, but there may reports that rely on `dtrans.numflag = 1` meaning local.

Wasn't there a discussion at some point about the lowest eight or 16 bits having standard meanings and the rest being for per-installation values?  Or maybe that was another set of bits.  If there was then `UPC->handleItem()` could set the "standard local bit" and leave the others as they are in `products`.

**Comment by gohanman** [comment]
The intersection of `local` and `numflag` was discussed a while back (well, open to discuss; no one else commented): https://github.com/CORE-POS/IS4C/issues/833

It's the highest 16 bits that are [reserved](https://github.com/CORE-POS/IS4C/wiki/Change-Log#150-20150610). Sample data for `prodFlags` making bit 17 organic and bit 18 gluten free has been present for a while.

At present `local` supports multiple values. Reporting doesn't just rely on `dtrans.numflag = 1` meaning local. It allows that `dtrans.numflag = 2` or `dtrans.numflag=3` could indicate different types of local. There's not really a way to stick `local` into `numflag` as a binary setting without taking away current functionality.
