### ISSUE TITLE
Spring Cleaning

### ISSUE THREAD

**Issue by gohanman** [CORE-POS/IS4C#650]
I'd like to chop some old, possibly unused things out of the code base but I have to verify there's actually unused. It's a bit of a random list.

### Lane
Is pos/is4c-nf/parser-class-lib/parse/CoopCredCheck.php redundant? There's a similar but not identical parser in the plugin. If it's not redundant can it get moved into the plugin?

Does anyone use the `PD` command in `ItemPD.php`. It appears to take a number, e.g., `5PD`, and would presumably discount the selected item by the percentage. It doesn't appear to work though. It looks like someone (quite possibly me) copied Void.php and updated parts of it but never finished the job. If someone is using it I'd be interested to see a working version. The `LD` command in `LineItemDiscount.php` seems to do largely the same thing.

Is anyone using the `cdinvalid`, `cdStaffNA`, or `cdSSINA`? I'd like to drop them in the `WedgeStaffCharge` plugin which has become kind of a catch-all for very old and probably very store-specific original IS4C behavior. I think these are used in conjunction with a `CT` command.

### Office
Can I remove the various `_WEFC_Toronto.php` files in the `item` directory and/or move them into `legacy` where I park my own old code that still gets used occasionally but doesn't match the regular UI?

Is `members.update.from.CiviCRM.php` still used? Going strictly by the comments I'm guessing `members.sync.with.CiviCRM.php` gets used instead. It appears CiviCRM v3 is no longer being maintained.

**Comment by joelbrock** [comment]
> Does anyone use the PD command in ItemPD.php

This is the only one that stood out to me as something stores are still using in production.  At least, i have `PD` and `50PD` (for half-off) programmed into a couple of the keyboards i've deployed.  Which isnt to say they are using it i suppose.  But it should probably continue to work.  Or throw an informative error message onscreen.

**Comment by gohanman** [comment]
I should clarify: `PD` as a prefix does appear to work, e.g. `50PD[item UPC or scan]`. `50PD` as a standalone command does not seem to do anything. It currently says item not found and looking at the code if it *did* find the item it would void that item.

**Comment by joelbrock** [comment]
aha, good clarification.  In that case no one should be using the `PD` function as a standalone.  In no cases were my keyboards programmed to output `{ENTER}`, so they'd always be using a PLU/UPC.

**Comment by scannerdarkly** [comment]
Newbie question, is I hadn’t seen or heard of `PD`. It appears to be a percentage pricedown on a single line item. Is that correct, and is there anything else I need to know about it?

**Comment by gohanman** [comment]
Whether it's allowed is controlled by `products.line_item_discountable`

**Comment by scannerdarkly** [comment]
Nice. Thanks.
