### ISSUE TITLE
Esc/Pos Printer commands for TM-6000ii

### ISSUE THREAD

**Issue by jcharles15** [CORE-POS/IS4C#651]
Where can I find a good list of esc/pos commands for this printer?  There are a lot of guides out there and some don't list all the commands.

**Comment by gohanman** [comment]
Can't help you there. If it's not in ESCPOSPrintHandler I don't have any additional reference.
https://github.com/CORE-POS/IS4C/blob/master/pos/is4c-nf/lib/PrintHandlers/ESCPOSPrintHandler.php
