### ISSUE TITLE
Multiple * [item]PV

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#652]
If we’re ringing 3 avocados, and we know the PLU, we can do `3*94046<enter>` and CORE-POS does the right thing.

If we’re ringing 3 avocados, and we **don’t** know the PLU, we can do `avocadoPV` and CORE-POS finds the record. Once we’ve selected it, we can hit `RI` twice to get a total of 3.

Unfortunately `3*avocadoPV` doesn’t seem to work. Is there a way this could be made to work?

**Comment by gohanman** [comment]
That works in my testing.

Alternately, they could enter `*2` once instead of `RI` twice.
