### ISSUE TITLE
Aggressive/compatible modes

### ISSUE THREAD

**Issue by gohanman** [CORE-POS/IS4C#655]
(This is mostly a note for self to do this at some point).

CORE generally takes a conservative approach towards database changes. Scattered through the code you'll see checking to verify whether a table exists or whether a column exists or whether some structure is currently a table or a view. These checks aren't super expensive but they aren't free.

I was fiddling with a lane today that was perceived to be a little slow and managed to cut execution time of `login2.php` in half by stripping out these compatibility checks. Half in this case means it went from about a half a second to about a quarter of a second. That's not a huge amount of time but it is noticeable.

I don't want to do away with the compatibility checking entirely. Preventing errors and crashes is a good thing. But I'd like to add an opt-in setting that can disable these kind of checks to gain a little extra performance.

**Comment by joelbrock** [comment]
:+1: for this.
I could envision this being a part of an overall set of features that we could simply call "Development Mode" and "Production Mode"

"Development Mode" could include settings such as this strict table checking, as well as different logging levels, displaying PHP errors, etc...

**Comment by scannerdarkly** [comment]
I’d be in favor of this as well. It expose some gaps in error reporting functionality; if that happens I’m happy to help with error reporting code.

**Comment by gohanman** [comment]
I don't see any way that this would relate to error reporting.

**Comment by scannerdarkly** [comment]
Currently CORE-POS checks for something to exist before using it.

The change you’re describing would do away with those checks. That’s a good move in production code. However, if something doesn’t exist, there will likely be an error when CORE-POS attempts to use it.

I have found many internal CORE-POS errors go completely unreported to the UI or to any error log. (In just the last three weeks, for example, I’ve reported https://github.com/CORE-POS/IS4C/issues/637, https://github.com/CORE-POS/IS4C/issues/663, and https://github.com/CORE-POS/IS4C/issues/664, none of which left a trace to the front end or the error logs.) I’d suggest that if we’re doing away with proactive checks as you suggest, we might want to make sure that errors that *do* occur will definitely be reported. Somewhere, anywhere!

**Comment by gohanman** [comment]
I'm not really sure how to help you with that. If I drop the dlog_90_view and reintroduce the error mentioned in #663, I get the CREATE VIEW query logged in debug_fannie.log along with the reason why it failed. Ditto with #664 (although the NOTICES in debug_fannie.log don't make it as immediately obvious what the issue is). If I recreate #637 by immediately severing the database connection, it crashes in the place reported with the error message logged in both fannie.log and STDERR (when run via cron the latter would trigger an email if an email address is associated with cron).

I don't think it's possible to *guarantee* errors are reported - logging that an error occurred attempting to write to the log being the biggest problem - but all the issues mentioned should at least attempt to write logs.
