### ISSUE TITLE
Install page isn’t creating views

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#663]
This is crazy. On the install page, `create_trans_dbs($con, $trans_db_name, $op_db_name)` isn’t creating `dlog` or `dlog_90_view`. Nor can I find a sensible reason why.

I added two bits of tracing code to the stock `BasicModel.php`:
```
    public function create()
    {
echo "...create(): {$this->fq_name}<br>\n";
        if ($this->connection->tableExists($this->fq_name)) {
            return true;
        }
```
and
```
    public function createIfNeeded($db_name)
    {
        $this->fq_name = $db_name . $this->connection->sep() . $this->name;
        $ret = array('db'=>$db_name,'struct'=>$this->name,'error'=>0,'error_msg'=>'');
echo "createIfNeeded('{$db_name}'): {$this->name}<br>\n";
        if (!$this->create()) {
            $ret['error'] = 3;
            $ret['error_msg'] = $this->connection->error($db_name);
        }
```
Running the install page, I get output like the following for all the tables...
```
createIfNeeded('office_trans'): dtransactions
...create(): office_trans.dtransactions
createIfNeeded('office_trans'): transarchive
...create(): office_trans.transarchive
createIfNeeded('office_trans'): suspended
...create(): office_trans.suspended
createIfNeeded('office_trans'): dlog_15
...create(): office_trans.dlog_15
```
...which is perfect. But when it gets to the views, `create()` never seems to get called:
```
createIfNeeded('office_trans'): dlog
createIfNeeded('office_trans'): dlog_90_view
createIfNeeded('office_trans'): ar_history_today
createIfNeeded('office_trans'): ar_history_today_sum
createIfNeeded('office_trans'): CcReceiptView
```
This defies my understanding of program flow: Somehow `create()` is not getting called when it would be creating a view, even though there is literally no other place for the program flow to go.

The error and query logs are silent as well.

Do I need an exorcist?

**Comment by gohanman** [comment]
You may want to look at ViewModel::create rather than BasicModel::create since they're both views

**Comment by scannerdarkly** [comment]
Haha inheritance! Okay!

**Comment by scannerdarkly** [comment]
The installation failure turned out to be because I hadn’t picked up 364f9014edcf8fadd99d612bdf0651cab283d548. The error reporting didn’t report the resulting `CREATE VIEW` syntax error; would I have your permission to attempt to get that error reported back to the install page?

**Comment by gohanman** [comment]
It's the same correction as reported in #664 2ac179303bdbb2492447a0e8c20cfd9934809839

**Comment by scannerdarkly** [comment]
Awesome, thanks! (Sorry I didn’t see https://github.com/CORE-POS/IS4C/commit/2ac179303bdbb2492447a0e8c20cfd9934809839.)
