### ISSUE TITLE
No way to lower discount

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#667]
If a member is listed in the database with a too-high discount, the manual discount feature (`##DA`) doesn’t lower it. Is there anything we can do to permit a true discount override?

**Comment by gohanman** [comment]
Can you elaborate on the sequence of steps? `##DA` works exactly as expected for me and does override the current member discount.

**Comment by scannerdarkly** [comment]
Sure thing:
* I scan an item which costs $9.99.
* I enter my member ID followed by `ID`; the bottom row of the screen now shows “You Saved 1.50” and “15% Discount 1.50” and “Amount Due 8.49” (the latter in red). That’s exactly what I’d expect, as my membership type has a 15% discount.
* I type `5da`; the bottom row now *still* shows “You Saved 1.50” and “15% Discount 1.50” and “Amount Due 8.49” (the latter in red).

**Comment by gohanman** [comment]
Not sure what I couldn't reproduce this before but now I see what you mean.

**Comment by scannerdarkly** [comment]
Perfect, thanks!
