### ISSUE TITLE
Error “no change allowed - max tender”

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#669]
When I enter a $2.25 taxed item, and a $1.45 non-taxed item, the total (including $0.08 tax from 3.5% sales tax) is $3.78 for someone with no discount. If I attempt to enter this amount from credit card (`378CC`), the system says “no change allowed - max tender is 3.78”.

Rounding error? Can something be done?

There’s a workaround; I can do `377CC` and then `1CC`, but this is obviously not ideal.

**Comment by gohanman** [comment]
Using within 0.005 as "probably equal" is the standard fix for this kind of thing

**Comment by scannerdarkly** [comment]
Thanks!
