### ISSUE TITLE
Slightly deceptive price override UI

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#672]
Doing a price override on bulk, the new price is interpreted as a new price *per pound*, which is exactly what we want at George Street Co-op.

What’s weird is that the previous price shown as the person is typing the override isn’t the price per pound, it’s the net price. Our cashiers find this confusing — they generally expect the previous price per pound to be shown.

Any chance this could be changed? I’m happy to give it a whirl if it’s a desirable change but nobody else has the time.

**Comment by gohanman** [comment]
Seems sensible enough. I appended either an "each" or "/lb" after the displayed price for clarification.

**Comment by scannerdarkly** [comment]
Looks good, though I had two questions which I put in the comments for the [code change itself](https://github.com/CORE-POS/IS4C/commit/f00385ccf66c8aaf77e54ef834198c59632d7600).
