### ISSUE TITLE
Adapt Shelf Audit original scan page to a different scanner

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#676]
The hand scanner that I use successfully in most CORE applications is not suitable for the `ShelfAudit` plugin's `SaScanningPage.php` (the original scanning interface) because it doesn't read the checkdigit (12th digit of the barcode) and because it appends  `<CR>` to the digits it sends to the application.  The latter causes the application to submit the page before the quantity can be entered. If the submission is suppressed, the 11-character string of digits is not long enough to fire the automatic moving of the cursor to the quantity field, which requires 12.

I added `id="minput"` to `<input name="minput" id ="minput" type="text" value=""/>` in the form and then, to defeat the submit from that field:
```javascript
        <script type="text/javascript" 
        src="/IS4C/fannie/src/javascript/composer-components/jquery/jquery.min.js">
        </script>
        <script type="text/javascript">
        $(document).ready(function() {
              $("#minput").keydown(function(event){
                      if(event.keyCode == 13) {
                                event.preventDefault();
                                      return false;
                                    }
                });
    });
    </script>
</body>
```
And changed the `inputvalue.length` test to make the jump to the quantity input fire without a checkdigit:
```javascript
function readinput() {
    if (document.forms[0]) {
        var inputvalue = document.forms[0].minput.value;

        /* Changed from 12 to 11 */
        if (inputvalue.length == 11) {
        ...
```

The first change defeats entering shorter-than 11-char codes, but that might be gotten around with a special terminator, such as the `z` that can be used to terminate quantities instead of `<Enter>` or the "enter" button.

The submission-suppression option and upc-length could be handled as plugin parameters.

**Comment by gohanman** [comment]
It's possible that SaHandheldPage will just work. Enter sends to cursor from the UPC field to the quantity field. I'd consider doing the same w/ your keydown function. If the user presses enter for any reason, whether via the scanner or manually (say keying in PLUs) they're probably done with the UPC and ready to enter a quantity.

**Comment by flathat** [comment]
> It's possible that SaHandheldPage will just work.

Yes, it does.  With it, submit is the right thing to happen after entering the upc.
> I'd consider doing the same w/ your keydown function. If the user presses enter for any reason, whether via the scanner or manually (say keying in PLUs) they're probably done with the UPC and ready to enter a quantity.

Sounds like a good idea.
