### ISSUE TITLE
BUG: Voiding items with price overrides

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#677]
This is one of those super rare edge cases — I feel like a jerk just for posting it, but I did encounter it in the field, so I have to suppose it’s a legit concern.
1. Scan an item.
2. Hit `RP` twice to make it three identical line items.
3. Do a price override on *one* of the identical items.
4. Void the item with overridden price.
5. Void it again. *The system shouldn’t let you, but it does.*

I imagine the void pre-check code would ideally check not just for how many item instances there are, but how many at that exact price.

**Comment by gohanman** [comment]
Yeah that's weird. It definitely should be locating the next voidable item differently.

**Comment by gohanman** [comment]
Long version is in the commit; short version is void's behavior predates the existence of a price override function.
