### ISSUE TITLE
Release Candidate Branches

### ISSUE THREAD

**Issue by gohanman** [CORE-POS/IS4C#679]
Now that I'm no longer running Office in single store mode in production there's an increased chance that bugs and regressions aren't going to be caught by me. With that in mind, I think it would be nice to have someone (or even a couple people) run proposed releases in a single store environment to check for issues.

Instead of just putting out a new version branch, I'd put out a release candidate branch, some early adopters would deploy (or merge) that branch and report back any problems they discover. When everyone says no-more-problems, a proper version would branch off the release candidate.

The catch is I can't do this myself. So anyone running the release candidates would need to be comfortable dealing with discovered problems - either by going into the code and fixing them or by using git to revert everything back until problems are addressed upstream. I think the latter would be best managed by branching although in a pinch reset could probably get back to a known-good commit.

**Comment by scannerdarkly** [comment]
I’d offer for George Street Co-op to fill this role, but I don’t feel we’re quite ready. But if nobody else offers to step up, I guess let me know. :)

**Comment by gohanman** [comment]
I appreciate the offer but definitely don't want to push anyone into an uncomfortable situation. It's totally understandable that this sort of thing will take a back seat to day-to-day business operations.
