### ISSUE TITLE
0% member discount override?

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#680]
When a member doesn’t wish to take their discount, at the moment CORE-POS doesn’t seem to permit a 0% discount override. We *could* put do this as a non-member transaction, but that would be non-ideal for patronage reports. Any way CORE-POS could support `0da` functionality?

**Comment by gohanman** [comment]
Odd request but I don't see any harm.

**Comment by scannerdarkly** [comment]
“Odd request but I don't see any harm.” — story of my life! :)
