### ISSUE TITLE
Membership modules in a particular order

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#681]
Would be great to fix the issue seen in recent installs and upgrades that causes destruction of secondary/household members data if the HouseholdMembers module is not in the proper order.

Private repos, but for developer reference:
https://github.com/CORESupport/Alberta/issues/23
https://github.com/CORESupport/ELFCO/issues/14

Going to label as a bug since it kinda is.

**Comment by gohanman** [comment]
I think in essence the entire save structure needs to be overhauled. Right now each module's `saveFormData` is responsible for writing its fields to the database. What **should** happen is each module's `saveFormData` should take a `MemberREST` structure as an argument, make any necessary modifications to that structure, and return it. That way changes will be carried over to the next module's save method.

**Comment by gohanman** [comment]
As discussed. I still think there's going to be a conflict between `MemType` and `HouseholdSeparateDiscounts`. On save `MemType` wants to normalize all customers' discount (reasonable, IMO) and `HouseholdSeparateDiscounts` wants to be able un-normalize those discounts. I don't see any particularly straightforward way to fix that. `HouseholdSeparateDiscounts` still has to come after `MemType`. But AFAIK this will address any other problem where display order messes with saving data.It's probably a touch faster, too, to just post all the changes in one call.
