### ISSUE TITLE
Implementing PCI DSS network segmentation

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#686]
This is copied from another forum in which I asked about changing network organization (separating office and POS networks) at my co-op to support integrated credit card processing in CORE.

Re Payment Card Industry (PCI) [Data Security Standard] (https://www.pcisecuritystandards.org/pci_security/how) (DSS) see the link.

@gohanman wrote:
The goal of segmentation is to reduce scope. In a nutshell any machine that can ping one of your lanes is in PCI scope. You want as few machines in scope as possible so you want to have two separate networks - for example all the regular users might have 192.168.1.x IPs and all the POS stuff might have 192.168.2.x IPs. Your router (or from a marketing/branding standpoint more likely "firewall") needs to support multiple networks and be able to restrict traffic between them.

I have one of these [Dell SonicWALL SOHO Gen 6 Firewall appliance] (http://www.neweggbusiness.com/Product/Product.aspx?Item=9B-33-376-633)  at the new store and similar, previous gen device at the old store. I've generally been happy with them and find them easy to manage although soicwall does not have the greatest reputation. Something that annoys me about the sonicwall is it doesn't do DNS. It'll relay ISP DNS server(s) through to clients just fine but if you want to define your own names you can't (stuff like lane1.wefc or copier.wefc)

I've heard great things about [Fortinet] (http://www.fortinet.com/). They're way more liberal with the # of VPN licenses include w/o adding extra licensing fees and have a free, smartphone-based 2-factor auth app which is required by PCI if you're using it for remote access (you can do it w/ sonicwall if you know how to set up your own RADIUS server and manage RSA tokens but I'm guessing basically no one working at our size of business deals with those things). 

Cisco makes great devices with a very steep learning curve to manage them. [Meraki] (https://meraki.cisco.com/technologies/next-gen-firewall) has a fantastic reputation as "Cisco, but easy!". The catch is Meraki is subscription based so you're looking at a monthly fee for the entire life of the device.
![screenshot_041216_030413_am](https://cloud.githubusercontent.com/assets/1131922/14452267/818e9418-005b-11e6-9b9f-df796fb3f0fc.jpg)

**Comment by flathat** [comment]
@jdpurdyvi followed up on the SonicWALL DNS issue with:
We've been under the impression that running DNS on an external facing device is considered bad practice. Maybe that's related to sonicwall not doing it?
But yeah, as @gohanman said, "The goal of segmentation is to reduce scope." Putting the POS on a separate subnet is a very good thing to do. It's convenient, and not wrong, to use the Fannie server as the gateway that spans the two subnets. At the Wedge we've done it all with generic linux boxes with multiple NICs. You should then setup any routes/rules that you expect the POS to need and then block everything else. For the Wedge (and WFC I presume) that means only allowing traffic to Mercury's processing servers from the POS subnet. For Fannie you can allow that traffic as it originates from the same subnet.

@gohanman responds
There's already a clear distinction between internal and external facing services - e.g., by default you can only pull up the admin web interface via the internal IP not the external IP. Presumably it would be possible to only respond to DNS requests on the internal IP.

**Comment by gohanman** [comment]
I'd like to add a couple additional notes for the public version of the discussion:

1) As far as I know, no one involved in the discussion has any kind of formal PCI DSS accreditation. This is advice from peers, not authoritative statements on how one should interpret the standard.

2) None of this is really particular to CORE-POS.

**Comment by gohanman** [comment]
(I changed the title because it was bugging me)
