### ISSUE TITLE
Add checkbox / batch delete option to SKUtoPLU edit

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#692]
I suggest changing, or adding to, the current one-by-one deletion of SKUtoPLU mappings `item/vendors/SkuMapPage.php` to have a checkbox for each item and a delete-all-ticked option.  Or else a delete-in-place.  It's the re-generating of a big list after each deletion, not the pop-up confirmation, that slows the work.

**Comment by gohanman** [comment]
As a temporary workaround, the upload option clears & reloads the whole list. I'm not sure what uploading an empty file would do but a file w/ one SKU+PLU pair would get close to starting from scratch.

**Comment by gohanman** [comment]
Implemented as delete-in-place.

**Comment by flathat** [comment]
Thanks much for this.

**Comment by flathat** [comment]
On closer examination the deletions aren't actually happening.

Can you advise on debugging where the `confirm()` in this has the plu value:
```javascript
// skuMap.js
var skuMap = (function($) {

    var mod = {};

    mod.deleteRow = function(id, sku, plu, elem) {
        if (window.confirm('Delete entry for PLU #' + plu + '?')) {
            $.ajax({
                type: 'delete',
                data: 'id='+id+'&sku='+sku+'&plu='+plu,
                dataType: 'json'
            }).done(function (resp) {
                if (resp.error) {
                    window.alert('Error deleting PLU #' + plu);
                } else {
                    $(elem).closest('tr').remove();
                }
            }).fail(function (resp) {
                window.alert('Error deleting PLU #' + plu);
            });
        }

        return false;
    };

    return mod;

}(jQuery));
```
but `plu` and `sku` are empty or don't exist in:
```php
// SkuMap.php
    public function delete_id_handler()
    {
        $sku = FormLib::get('sku','NoSKU');
        $plu = BarcodeLib::padUPC(FormLib::get('plu','NoPLU'));
// Both get the 'No' default rather than the value
```
No PHP or MySQL error is reported.
There is a JS error when the `confirm()` is responded to: `Empty string passed to GetElementById`, but it is the same for either `OK` or `Cancel`

I hacked the changes to `SkuMap.php` into the `CORE 1.6` code at this site rather the copying the whole revised listing so it is possible something is missing.

**Comment by gohanman** [comment]
That's weird. It definitely works upstream. PLU and SKU are simply passed in (https://github.com/CORE-POS/IS4C/blob/master/fannie/item/vendors/SkuMapPage.php#L249). It's identical to how the old link `_method=delete` link was constructed so if they weren't empty there they shouldn't be empty here.

What source file does it list for the `GetElementById` error? What does the AJAX request & response look like in your browser console?

**Comment by flathat** [comment]
The file on the same line as the `GetElementById` is `jquery.min.js`.
The request on the line following that error is:
`DELETE XHR http://10.5.0.1/RVM-CORE/item/vendors/SkuMapPage.php?id=1`
Does that mean the `id` assignment is succeeding but the `sku` and `plu` aren't? That everything after `+id` in: 
`data: 'id='+id+'&sku='+sku+'&plu='+plu` 
doesn't happen?
If, in `SkuMap::delete_id_handler()` I get `id` from the form instead of from the class it is successful:
```php
$form_id = FormLib::get('id',-1);
$sku = FormLib::get('sku','NoSKU');
$plu = BarcodeLib::padUPC(FormLib::get('plu','NoPLU'));
$args = array($form_id, $sku, $plu);
// Instead of: $args = array($this->id, $sku, $plu);
// print_r($args)
Array
(
    [0] => 1
    [1] => NoSKU
    [2] => 00000000NoPLU
)
```

**Comment by flathat** [comment]
> `DELETE XHR http://10.5.0.1/RVM-CORE/item/vendors/SkuMapPage.php?id=1`
Does that mean the id assignment is succeeding but the sku and plu aren't? 

Apparently not. That URL is the original, not the one with `data:` composed in the `.ajax` statement.

> What does the AJAX request & response look like in your browser console?

AFAICT everything in the browser (FF) console is set to display but maybe something I don't know.

**Comment by gohanman** [comment]
ed155f1e53354c2142cf88c5be7ee7af80317959

A `HTTP DELETE` technically doesn't support parameters in the request body. Where things get goofy is that when omitted the URL defaults to the current page.

If you just pull up the page you'll be at `/item/vendors/SkuMapPage.php?id=1`. A `DELETE` fails since the only data included is the URL, `id`. If you **add a new mapping** you'll end up at `/item/vendors/SkuMap.Page.php?id=1&sku=foo&plu=bar`. Now `DELETE` will succeed for that particular pair since the URL has all the data. Not having any bad data that needed to be deleted, this was exactly my test case: create a new mapping, then delete it. The `data` part of `$.ajax` is ignored either way.

`FormLib::get('id')` and `$this->id` are exactly identical so I imagine the fact that "it worked" is somehow related to the order-of-operations coincidence above.

**Comment by flathat** [comment]
It's working at the site now.
```javascript
// revised skuMap.js
            $.ajax({
                type: 'get',
                data: '_method=delete&id='+id+'&sku='+sku+'&plu='+plu,
                dataType: 'json'
            })
```
