### ISSUE TITLE
BUG: CustPreferencesModel.php

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#699]
Version 1.9.
`CORE-POS/fannie/install/InstallUpdatesPage.php` notices that `custPreferences`.`custPrefenceID` should be `custPreferenceID`, but can’t automatically correct the error. I had to go into the database and correct the field name manually in order to get the nag message to stop showing up.

**Comment by gohanman** [comment]
This is already fixed in the version-1.9 branch: 0805a25f548d4529ec281919d7860276e5382a12

**Comment by scannerdarkly** [comment]
Not exactly. If the table is created from scratch, the fix you posted creates the fields with no misspellings. BUT if the table was created incorrectly in the first place, the office Updates page doesn’t know how to correct it — probably because the misspelled field name is part of the primary key. As it stands now, the code just reports the error and can’t correct it. *That’s* a bug, and that’s what I’m reporting!

**Comment by gohanman** [comment]
I guess if you want to quibble then it's a WONTFIX. As a rule the update mechanism doesn't drop columns (manually add more columns to the table if you like and it'll do the same thing; just report them as unknown columns). I don't think it's likely in this particular case that anyone is relying on that data, but better safe than sorry. I believe the message even says `delete manually if desired`.

I'm don't think changing this would be a good idea. Warning messages just aren't that effective. Requiring some basic SQL knowledge to get rid of data helps ensure the person doing so is qualified to make that decision.

**Comment by scannerdarkly** [comment]
I never *want* to quibble. But if this is a WONTFIX, then I’m glad that’s been made explicit!
