### ISSUE TITLE
BUG: DTransactionsModel.php

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#700]
CORE-POS/fannie/install/InstallUpdatesPage.php reports an error but can’t correct it.
```
==========================================
Checking table office_trans.dtransactions
==========================================
==========================================
Check complete. Need to adjust 0 columns  0 indexes.
==========================================

==========================================
Checking table office_trans.transarchive
==========================================
==========================================
Check complete. Need to adjust 0 columns  0 indexes.
==========================================

==========================================
Checking table office_trans.suspended
==========================================
==========================================
Check complete. Need to adjust 0 columns  0 indexes.
==========================================

==========================================
Checking table office_trans_archive.bigArchive
==========================================
==========================================
Check complete. Need to adjust 0 columns  0 indexes.
==========================================

==========================================
Checking table office_trans.dlog_15
==========================================
==========================================
Check complete. Need to adjust 0 columns  0 indexes.
==========================================

Would recreate view: dlog (of table dtransactions)
Would recreate view: dlog_90_view (of table transarchive)
Would recreate view: dlogBig (of table bigArchive)
```
`dlog` and `dlog_90_view` are currently tables, not views. Perhaps this is the problem?

**Comment by gohanman** [comment]
If you're referring to #699, then no it's not related in any way.

I'm not sure how you wound up with `dlog` and `dlog_90_view` as tables. They've been views for the entire history of CORE (and earlier versions of IS4C too for that matter) and there's never been any mechanism to create them as tables.

**Comment by scannerdarkly** [comment]
Weird. I never tried to make them as tables. I’ll try to fix this manually.

I knew #699 and this one weren’t related, except inasmuch as they showed up in the same screen.

**Comment by gohanman** [comment]
Dropping them (if they don't have import data; I'd expect them to be empty though) and letting `fannie/install/` recreate is probably the easiest approach.

Per #644 and #663 it seems they were views at some point. One way they could become tables is via `mysqldump` and restore crashing part way through. If you look at one in detail, it first recreates views as tables with identical columns then makes a second pass replacing these tables with the actual views (I'd guess this is so it can restore views that reference other views without worrying about what order they're restored in).

**Comment by scannerdarkly** [comment]
They were in `office_trans_archive` as tables, not `office_trans`. I wound up deleting:
- *.`dlog`
- *.`dlog_90_view`
- `office_trans_archive`.`dlogbig`
and rerunning both `http://localhost/CORE-POS/fannie/install/InstallUpdatesPage.php?mupdate=DTransactionsModel` and `php CORE-POS/fannie/classlib2.0/data/models/BasicModel.php --update office_trans CORE-POS/fannie/classlib2.0/data/models/trans/DTransactionsModel.php`. Even after doing all that, CORE-POS/fannie/install/InstallUpdatesPage.php still reports that updates are needed.

Is this a false error report?

**Comment by gohanman** [comment]
It's hard to tell. It  implies a column discrepancy of some kind in your views but isn't too helpful beyond that. Replacing one of these (https://github.com/CORE-POS/IS4C/blob/master/fannie/classlib2.0/data/models/trans/DTransactionsModel.php#L164) w/ `echo ob_get_clean()` might shed some light on it. The output won't be entirely accurate for a view but should at least point to the column(s) it's flagging.

**Comment by scannerdarkly** [comment]
I think I’ve figured out this issue. Tracing the code path, [here](https://github.com/CORE-POS/IS4C/blob/version-1.9/fannie/classlib2.0/data/models/BasicModel.php#L875)’s the code that causes the install page to complain that updates are still needed. Basically, because DTransactionsModel inherits from BasicModel, the code thinks `dlog`, `dlog_9_view`, and `dlogbig` are actually supposed to be tables.

If we change DTransactionsModel to inherit from ViewModel instead, the install page stops complaining about `dlog`, `dlog_9_view`, and `dlogbig` — but then it complains that `dtransactions`, `transarchive`, `suspended`, `bigArchive`, and `dlog_15` are actually supposed to be views instead of tables!

Perhaps some refactoring of models is needed?

**Comment by gohanman** [comment]
Sorry, but that's absolutely not the case. At no point does `BasicModel` check whether a structure is a table or a view. It's just checking for missing or differently formatted columns. Showing or disabling the output buffering above would clarify what columns it's complaining about.

Part of the problem may be that it's trying to correct the situation by dropping & recreating the view but `DROP VIEW dlog` will fail if it isn't a view. Especially in this case I think it's important that dropping that table is a carefully considered manual decision. Without knowing either how that structure wound up as a table or how data got into it, it's impossible to guess whether that data is important.

Just related to the general subject if you haven't come across it: https://github.com/CORE-POS/IS4C/wiki/Scheduled-Tasks#the-transaction-shuffle

**Comment by scannerdarkly** [comment]
> At no point does BasicModel check whether a structure is a table or a view.

I’m confused, this seems to be precisely the check that’s going on here:
https://github.com/CORE-POS/IS4C/blob/version-1.9/fannie/classlib2.0/data/models/BasicModel.php#L873

What am I missing?

**Comment by gohanman** [comment]
Sorry, you're correct; I was looking at up to date code for managing models instead of 1.9.

Workaround: f15b77e4b64e8ba207bacd6845256e3bb6bf459d

For what it's worth, this is about the scope of what fixes to version branches will normally look like. Large scale changes strictly happen on the master branch for inclusion in future versions.

**Comment by scannerdarkly** [comment]
Thanks for coding the workaround! I get what you’re saying about keeping the changes low-key for version branches. Makes sense to me.
