### ISSUE TITLE
InstallStoresPage.php makes new store #

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#701]
George Street Co-op is just one store. Nothing fancy. As far as I know, `office_opdata`.`Stores` just needs one record with storeID = 1.

Every time I load http://localhost/CORE-POS/fannie/install/InstallStoresPage.php, it says “No entry found for this store. Adding one automatically...” and adds a second record to `office_opdata`.`Stores` (with an auto-incremented `storeID`).

If I delete that new record and hit Save, it adds a record with the next number higher, and so on.

Ideally, I would like to be able to navigate to this page without it adding new records like that. Any clues what I need to change?

**Comment by gohanman** [comment]
The entire behavior is gone in the latest release, but it's attempting to find a database server host (https://github.com/CORE-POS/IS4C/blob/version-1.9/fannie/install/InstallStoresPage.php#L187-L192). If you have a store entry for "localhost" but Office is configured to use "127.0.0.1" or vice versa that would cause this. If that's the case, changing either so they match would work.

**Comment by scannerdarkly** [comment]
You were 100% correct about the cause. Changing everything to “localhost” (and fixing the socket config which had made “localhost” originally not work) fixed everything.
