### ISSUE TITLE
GitHub issue? Unexplained changes to forked repo

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#710]
While checking out @gohanman’s references on [this issue](https://github.com/CORE-POS/IS4C/issues/701), I noticed that despite George Street Co-op’s repository originally being forked from [Version 1.9](https://github.com/CORE-POS/IS4C/blob/version-1.9/fannie/install/InstallStoresPage.php), it currently [shows a bunch of code changes](https://github.com/GeorgeStreetCoop/CORE-POS/commits/master/fannie/install/InstallStoresPage.php) introduced on CORE-POS’s *master* branch, and subsequent to the date we forked it.

I was under the (perhaps naive) impression that once you fork a new repository from a labelled branch, it shouldn’t automatically include upstream code changes from a different branch.

I’ve used `git cherry-pick` on a few occasions, but had believed that `cherry-pick` only introduced the changes shown in the diff page for that commit. I haven’t had a chance to check every detail, but I didn’t think I’d cherry-picked any changes to `InstallStoresPage.php`. (The way git stores cherry-pick history seems to obscure the fact that the cherry-pick method had even been used — so it’s hard to be sure.) 

Can anyone give some clues as to which of my assumptions are incorrect?

Sorry for what’s probably a newbie question!

**Comment by gohanman** [comment]
Once you fork a repo, nothing from any upstream branch flows to your fork automatically. It's strictly controlled by you.

Git remote will show info about which remote branch a local branch follows if you do a git pull w/o specifying a remote branch. But I'm fairly sure nothing will default to upstream rather than your own fork in github
