### ISSUE TITLE
Product aliases?

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#711]
There are items (e.g. cauliflower) which come in with different brands and UPC codes, but they’re functionally identical; neither we nor the customers really care whether it’s Earthbound Farm, Joseph’s Organics, or Bonipak. For reporting purposes we’d like to treat these items as one.

I’m wondering if that functionality currently exists in CORE-POS or Office, or could be approximated somehow.

Such functionality might also help with a couple other issues:

1. **Produce labelled with both a UPC and a 5-digit PLU.** Technically the UPC is supposed to be used *only* when those items are sold by count, and the 5-digit PLU is supposed to be used *only* when sold by weight. But this a hard point to train cashiers on (this restriction is nonsensical to anyone but data geeks); and when the UPC gets wrinkled or the customer wraps the kale in a plastic bag, the only efficient entry method remaining is the 5-digit PLU. George Street Co-op currently inputs *both* codes into CORE-POS and let cashiers use whichever one they like, but just like with the case above, we’d like to be able to consolidate reporting on these items into just one number.

2. **Produce items with an inaccurate 5-digit PLU on the invoice.** The electronic invoice (which we import directly into the POS) says Bananas 94011, but the bananas arrived with “94231” stickers on them. The invoice says Grapes 94023, but the grapes arrived with “94635” stickers. This happens every week, and since it’s a big vendor, I doubt we can change their behavior. Fortunately the *specific* mis-labelings are rather consistent, so a mapping could occur. **George Street Co-op could do this on the import side**, but if CORE-POS had this functionality it might help other co-ops down the road.

**Comment by gohanman** [comment]
We use like codes heavily with produce. These are probably a better fit for case one where on both the front and back end you want to treat two (or more) separate items as logically identical. 

Depending what you're doing with the invoice info in case two, you may want to look at vendor SKU mapping (https://github.com/CORE-POS/IS4C/wiki/Products-and-Vendors#intra-vendor-item-mapping). We use this more often with bulk - a 25# sack of flour has a UPC that differs from the PLU we sell it under - but the same idea could apply if you're using the invoices to update costs and generate pricing.

**Comment by scannerdarkly** [comment]
Ah, *now* I remember hearing about like codes!

I’ve created LC 1 for Cauliflower, and the in-program help says “Use the item editor to assign a particular item to a like code”. But I don’t see where to assign a like code in the item editor (ItemEditorPage.php). Clue me in?

**Comment by joelbrock** [comment]
Check out the Fannie Installer > Products tab.   Make suer the LikeCode module is enabled.

**Comment by scannerdarkly** [comment]
Okay, enabled the module, and now there’s a “Likecode” button in the product editor. I’ve set up four types of cauliflower under one code. Unfortunately, DepartmentMovementReport.php seems to be unchanged — the cauliflowers are still listed individually.

I do see the “Likecode Sales History” link in the item editor.

Is that the extent of Likecode’ inclusion in the reporting structure? Or is there more I’m missing?

**Comment by gohanman** [comment]
How like codes are treated is a per-report thing. It's not always a given that someone would want them rolled together into a single result (e.g. someone might decide to likecode all their Clif bars together but still want to see popularity of flavors)

https://github.com/CORE-POS/IS4C/blob/master/fannie/reports/LikeCodeMovement/LikeCodeMovementReport.php

https://github.com/CORE-POS/IS4C/blob/master/fannie/reports/DepartmentMovement/SmartMovementReport.php

**Comment by scannerdarkly** [comment]
Has there been thought given to the idea of having per-likecode settings for:
1. Update prices as one (seems to be implemented).
2. Treat these as one UPC/PLU in most movement reports (unimplemented, apparently).
3. Treat these as one UPC/PLU for order generation (unimplemented, I imagine).

**Comment by gohanman** [comment]
No.

The primary purpose of like codes is to edit items as one. If prices aren't updated as one something is probably broken in your own code base. This has been the behavior of like codes literally forever.

As far as reports, like codes are likely going to remain a special case with their own reporting. It's an added layer of complexity in lots of places and it's not a given that people will always want totals rolled up together (even for the same like code depending on situation or context). And I don't think layering more knobs and switches onto reports to control like code behavior is necessarily helpful. A separate report with different, simple choices can be easier for a user who knows nothing about the underlying data.

I think three is literally impossible.

**Comment by scannerdarkly** [comment]
Okay, fair enough. Are prices the only product attribute which gets automatically updated across all likecode “participants”?

Can you clue me where (in the 1.9 codebase) the price is supposed to get auto-updated? It’ll help me figure out what’s failing to happen in my 1.9-like system.

**Comment by gohanman** [comment]
https://github.com/CORE-POS/IS4C/blob/version-1.9/fannie/item/modules/LikeCodeModule.php#L146-L168

**Comment by scannerdarkly** [comment]
> The primary purpose of like codes is to edit items as one. If prices aren't updated as one something is probably broken in your own code base. This has been the behavior of like codes literally forever.

Unfortunately, there seems to be a bug, in the main repo’s [version 1.9](https://github.com/CORE-POS/IS4C/tree/version-1.9) at least. What happens when I update a product in 1.9 is that all of the same-likecoded products get the *old* values for the product I was editing; then the new values are saved for *just the one UPC I was editing*.

When using George Street Co-op’s fork of 1.9, I got the same behavior. I originally misinterpreted it as no update happening at all. *An update is happening*, it’s just the update is with the incorrect data. And the behavior is identical in the main repo’s 1.9 version.

Please consider fixing this behavior in 1.9. Thanks!

**Comment by gohanman** [comment]
I cannot reproduce the behavior you're describing. I've tried installing the version-1.9 branch from scratch in a new VM and verified that like codes behave correctly.

**Comment by scannerdarkly** [comment]
Oy. Okay, I’ll try 1.9 again in a true “from scratch” environment and report back — it might be a bit before I have a chance to do this. (My tests yesterday were from a `git checkout` on `version-1.9` in my existing environment. `git status` showed no differences from 1.9, but of course there’s a few items configured to be ignored, plus of course potential issues from the database being in a non-default state.

Thanks so much for attempting to reproduce the behavior!
