### ISSUE TITLE
New Vendor creation fails

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#712]
Slightly modified Version 1.9, as seen in [George Street Co-op’s repo](https://github.com/GeorgeStreetCoop/CORE-POS).

In VendorIndexPage.php, selecting “New vendor...” inputting a vendor name (“UNFI” if it matters, but others have the same result), clicking “Create vendor” takes me to a page with the URL:
`http://localhost/CORE-POS/fannie/item/vendors/VendorIndexPage.php?vid=<html><head><title>HTTP 400 - Bad Request</title>            <body><h1>HTTP 400 - Bad Request</body></html>`

Not surprisingly, since the vendor ID is bad in the URL, saving from this page fails to save a record in the database.

Does this happen on a clean 1.9 install?

**Comment by scannerdarkly** [comment]
I should add that if I manually correct the entry URL to `http://localhost/CORE-POS/fannie/item/vendors/VendorIndexPage.php?vid=UNFI`, enter all the data, and click “Save Vendor Contact Info”, it *still* doesn’t add a vendor entry to the dropdown or the database’s `vendorContact` table.

**Comment by gohanman** [comment]
There's definitely a bug there although it was introduced in this 1.10 era commit (02b80a6c0b07bab2e17e45e78bbf6a9453da6eb6). I saw slightly different behavior though. The new vendor form just did nothing rather than proceeding to the 400 page. If the browser continues to that 400 page there's probably a javascript crash happening in yours.

**Comment by scannerdarkly** [comment]
I can create vendors now, thanks!

I don’t seem to be able to save info about their delivery schedules though. Should I open a new issue for that?

**Comment by gohanman** [comment]
Fixed, although it's mostly a dead-end feature. Movement variation on a per-SKU basis is too high to forecast daily inventory levels with any accuracy, and even if it did there's no accounting for physical storage space availability, product shelf life, turnaround time on orders, etc. Having a human pick a par value at least to start with makes more sense than trying to feed in all the info the system would need to try and make an intelligent choice.

**Comment by scannerdarkly** [comment]
Yup, that fixes it, thanks! I wasn’t sure what the schedule was used for, just assumed it must be used for *something*. It’s potentially handy to know it won’t be a focus for further development.
