### ISSUE TITLE
Referring to Fannie config

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#718]
The SiteMap trouble I mentioned in #683 had partly to do with my attempt to add coop-specific `helpContent()` blocked using `if ($this->config->get('COOP_ID') == 'WEFC_Toronto') { ... }`, which works fine in the page but does not when `SiteMap.php` calls `helpContent()` because `$this->config` isn't set up in that context (`Call to a member function get() on a non-object`).

I've gotten around this using `if (FannieConfig::config('COOP_ID', '') == 'WEFC_Toronto') { ... }` instead, and could also have used the old:
```php
public function helpContent() {
    global $FANNIE_COOP_ID;
    if (isset($FANNIE_COOP_ID) && $FANNIE_COOP_ID == 'WEFC_Toronto') { ... }
}
```
Could you say a bit about the contexts in which `FannieConfig::config()` and `$this->config->get()` are designed to be used?  Could `SiteMap.php` support `$this->config->get()`?

**Comment by gohanman** [comment]
I think as a basic rule of thumb `$this->config->get()` should be used whenever possible and `FannieConfig::config` should be used when flaws in my architectural design make the first option impossible.

From a higher level design standpoint, it's [Inversion of Control](https://en.wikipedia.org/wiki/Inversion_of_control) via [Dependency Injection](https://en.wikipedia.org/wiki/Dependency_injection) (and the problem with SiteMap is it doesn't call the necessary DI setters). Code that uses `$this->config->get()` isn't tightly coupled to `FannieConfig`.

Solving the immediate issue would be something like this (d10c27dc766a64961b6acb198e38bbb362aadc9e). Although I think the bigger problem is SiteMap shouldn't be calling methods like `helpContent` at all. Collecting developer-oriented information about whether pages implement different features increases the potential for problems, such as this one, and that info has no value for end users.
