### ISSUE TITLE
Special chars in Product list tool

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#719]
This one comes courtesy of a real live end-user:
>Just wanted to let you know about a little glitch that I ran into in Office. In the Product List Tool page, when renaming an item with a special character (in my case '&') most/all of the characters after the special character and the special character itself are erased upon saving. Not a serious glitch or anything, but I thought I'd bring it to your attention.

I have not tested but wanted to post it up so it could get addressed, if it is in fact a bug.

**Comment by gohanman** [comment]
Looks like a bug to me. abc1f4d8c9e97a586d4a2da6a743a590f28d1dd7

**Comment by gohanman** [comment]
Fixed in 2.1
