### ISSUE TITLE
Member Search Page finds bupkis

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#726]
Version 1.9 with minor tweaks. Office’s `mem/MemberSearchPage.php`:

I’m trying to find member Matt Smith, I start typing “Smi” into the Last Name field, and sure enough “Smith” shows in the dropdown. I click the word to fill out the rest of the field, then click the “Search” button. All-blank form comes up for “Member 0”. If I then click “Next”, what comes up is the member data for member #2 (our lowest-numbered member). Clicking “Next” again shows the *next* higher-numbered member’s data, etc.

The same exact behavior occurs no matter what last name I’m searching for. At no point does the search engine seem to narrow the results list.

Any ideas what’s happening?

**Comment by gohanman** [comment]
This maybe 1caa3fb2d8567b2323ace93328fb4fadd39958a6?

**Comment by scannerdarkly** [comment]
Yup, that’s the magic. Thanks!
