### ISSUE TITLE
How to set up AR charges?

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#727]
I’d like to get member tabs (AR charges) working.

But how are they designed to work in CORE-POS? What do I need to install/configure, and what tasks need to be added to the nightly batch?

**Comment by gohanman** [comment]
https://github.com/CORE-POS/IS4C/wiki/Charge-Accounts

**Comment by scannerdarkly** [comment]
Nice instructions — thanks for creating them! I think I’ve followed directions pretty correctly, but the cron job which updates the lanes with customers’ charge balances is failing and reporting:
`./LanePush/UpdateCustBalance.php: Failed: SELECT CardNo, balance FROM memChargeBalance WHERE mark=1`

This seems to be due to:
`#1146 - Table 'office_opdata.memchargebalance' doesn't exist`

Any idea why that table wouldn’t have been created?

**Comment by gohanman** [comment]
Not off hand, no. The name listed seems a little odd but that could be purely coincidence. `memChargeBalance` is created in the transaction database (default name `core_trans`) but there's nothing in the cron script between connecting to the server and issuing the query that could change the selected database.

**Comment by scannerdarkly** [comment]
Oops, my bad, I made an invalid assumption, running that query on office’s *operational* database. Running it on the transaction database still fails, however:
`#1054 - Unknown column 'CardNo' in 'field list'`
and that’s because `office_trans.memchargebalance` is currently defined as:
``select 1 AS `columnName` ``

This is very weird.

What process creates `memchargebalance`?

**Comment by gohanman** [comment]
The primary install/configuration page. It's defined here: https://github.com/CORE-POS/IS4C/blob/master/fannie/classlib2.0/data/models/trans/MemChargeBalanceModel.php. 

That definition would imply it's having trouble locating the `custdata` table. That's probably an issue somewhere in the SQL stack that isn't understanding fully qualified names (i.e., `databaseName.tableName`). If you have ADOdb installed from composer I'd just get rid of it to eliminate one variable. Which MySQL driver are you using?

**Comment by scannerdarkly** [comment]
I just deleted the view, and the install page re-made it correctly. Everything seems good now, with the totally minor quibble that office’s AR History report doesn’t show today’s charges.

(I’m using the PDO driver, and no composer.)

**Comment by scannerdarkly** [comment]
Thanks for fixing the quibble too! AR is working well.
