### ISSUE TITLE
Correcting past costs

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#729]
Until recently, we had a costing process that gave wrong item costs for a significant number of items. As a result, `dlog_15`, `transarchive`, and `bigarchive` all have a bunch of records with incorrect values in the `cost` field.

Obviously we’d like to get these corrected for reporting purposes. Has anyone written a batch cost correction process at any point?

**Comment by gohanman** [comment]
I haven't. As more of a general rule I never change transaction data.

If you have a list of items w/ costs that you want to change that you can put into a table, it'd presumably be something like this:
```php
include('config.php');
include('classlib2.0/FannieAPI.php');

$dbc = FannieDB::get($FANNIE_OP_DB);

$p1 = $dbc->prepare("UPDATE $FANNIE_TRANS_DB.dlog_15 SET cost=? WHERE upc=?");
$p2 = $dbc->prepare("UPDATE $FANNIE_TRANS_DB.transarchive SET cost=? WHERE upc=?");
$p3 = $dbc->prepare("UPDATE $FANNIE_ARCHIVE_DB.bigArchive SET cost=? WHERE upc=?");

$res = $dbc->query("SELECT upc, cost FROM BadCostItems");
while ($row = $dbc->fetchRow($res)) {
    $dbc->execute($p1, array($row['cost'], $row['upc']);
    $dbc->execute($p2, array($row['cost'], $row['upc']);
    $dbc->execute($p3, array($row['cost'], $row['upc']);
}

**Comment by scannerdarkly** [comment]
That looks good. Are there any other transaction tables with cost data?
