### ISSUE TITLE
pos.exe compilation trouble

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#730]
I've upgraded a lane to Ubuntu 14.04.4 LTS and am getting these errors from trying to compile the driver.  The sources date from about CORE 1.8.

```
NewMagellan$ mcs --version
Mono C# compiler version 3.2.8.0
NewMagellan$ make
mcs -target:library /r:System.Drawing.dll /r:System.Core.dll -out:DelegateForm.dll DelegateForm.cs
error CS0006: Metadata file `System.Drawing.dll' could not be found
Compilation failed: 1 error(s), 0 warnings
make: *** [DelegateForm.dll] Error 1
```
How to find `System.Drawing.dll` and where to put it?
It may be that only the Ingenico needs it in which case I can do without but don't know how to remove all of Ingenico's requests for it.

Trying the `xbuild` approach after installing `mono-xbuild`
```
NewMagellan$ xbuild
XBuild Engine Version 12.0
Mono, Version 3.2.8.0
Copyright (C) 2005-2013 Various Mono authors

Build started 2016-05-19 4:31:49 PM.
__________________________________________________
Project "/var/www/IS4C/pos/is4c-nf/scale-drivers/drivers/NewMagellan/NewMagellan.csproj" (default target(s)):
        Target DelegateFormLibrary:
: error : Error initializing task Csc: Could not load file or assembly 'Microsoft.Build.Tasks.v4.0' or one of its dependencies. The system cannot find the file specified.
        Task "Csc" execution -- FAILED
        Done building target "DelegateFormLibrary" in project "/var/www/IS4C/pos/is4c-nf/scale-drivers/drivers/NewMagellan/NewMagellan.csproj".-- FAILED
Done building project "/var/www/IS4C/pos/is4c-nf/scale-drivers/drivers/NewMagellan/NewMagellan.csproj".-- FAILED

Build FAILED.
Errors:

/var/www/IS4C/pos/is4c-nf/scale-drivers/drivers/NewMagellan/NewMagellan.csproj (default targets) ->
(DelegateFormLibrary target) ->

        : error : Error initializing task Csc: Could not load file or assembly 'Microsoft.Build.Tasks.v4.0' or one of its dependencies. The system cannot find the file specified.

         0 Warning(s)
         1 Error(s)
```

**Comment by gohanman** [comment]
Using `make` probably doesn't work well. This is everything I needed installed to compile w/ `xbuild` on 14.04:
https://github.com/CORE-POS/IS4C/wiki/New-Magellan#building-on-ubuntu-1404lts

`libmono-system-drawing4.0` and `libmono-microsoft-build-tasks-v4.0` would resolve the current issues but you may bump into additional ones if other things on the list are missing.

**Comment by flathat** [comment]
I had a completed compilation after installing the packages listed below.
The resulting `pos.exe` is working, that is files of scan and scale data are being placed in `ss-output/`.
```
# Each of these
$ sudo apt-get install
mono-xbuild
libmono-data-tds4.0-cil
libmono-microsoft-build-tasks-v4.0-4.0-cil
libmono-system-data-linq4.0-cil
libmono-system-drawing4.0-cil
libmono-system-numerics4.0-cil
```
The set of `*mono*` packages I have is:
```
$ dpkg -l | grep mono | cut -c5-58
fonts-tlwg-mono
libmono-corlib2.0-cil
libmono-corlib4.5-cil
libmono-csharp4.0c-cil
libmono-data-tds4.0-cil
libmono-i18n-west2.0-cil
libmono-i18n-west4.0-cil
libmono-i18n4.0-cil
libmono-microsoft-build-engine4.0-cil
libmono-microsoft-build-framework4.0-cil
libmono-microsoft-build-tasks-v4.0-4.0-cil
libmono-microsoft-build-utilities-v4.0-4.0-cil
libmono-microsoft-build2.0-cil
libmono-microsoft-csharp4.0-cil
libmono-posix2.0-cil
libmono-posix4.0-cil
libmono-security2.0-cil
libmono-security4.0-cil
libmono-system-configuration4.0-cil
libmono-system-core4.0-cil
libmono-system-data-linq4.0-cil
libmono-system-data4.0-cil
libmono-system-drawing4.0-cil
libmono-system-enterpriseservices4.0-cil
libmono-system-numerics4.0-cil
libmono-system-runtime-serialization4.0-cil
libmono-system-security4.0-cil
libmono-system-transactions4.0-cil
libmono-system-xml4.0-cil
libmono-system2.0-cil
libmono-system4.0-cil
libmono-xbuild-tasks2.0-cil
libmono-xbuild-tasks4.0-cil
mono-4.0-gac
mono-gac
mono-gmcs
mono-mcs
mono-runtime
mono-runtime-common
mono-runtime-sgen
mono-xbuild
ubuntu-mono
```
Something about either what to install or what libraries are needed for an `xbuild` should probably be added to the NewMagellan/README` since the current:
```
    * Non-Windows
        * Install mono and related development packages,
          e.g. mono-devel. If "dmcs --version" returns
          3.2.8+, you're probably fine.
```
is not quite detailed enough for a successful `xbuild`.

I haven't tried the `make` approach again since the new installs.

**Comment by gohanman** [comment]
> Something about either what to install or what libraries are needed for an xbuild should probably be added to the NewMagellan/README` since the current:

Unfortunately that's not really possible. There are no detailed instructions that are applicable to all non-windows environments because package naming conventions and subdivisions aren't remotely consistent across different distributions. The set for Ubuntu 14.04 is documented, as linked, but that's not necessarily useful information in any other setup.
