### ISSUE TITLE
Uniqueness in product table

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#731]
I notice the stock `products` table has no constraint to prevent multiple records with the same UPC/PLU. Perhaps naively, I’d imagined there would be.

Is there a reason a store would want multiple records with the same UPC or PLU? Is CORE-POS’s behavior defined in situations where a duplicated UPC or PLU is scanned/entered at the lane?

**Comment by gohanman** [comment]
In a multi store setup there's expected to be one record per store - i.e., the uniqueness constraint would be `(upc, store_id)`. It's not enforced at the table level mostly to avoid creating headaches for downstream users that don't have (or need) well defined Store entities. You're correct that lane behavior isn't defined with multiple UPCs - it'll use whichever record comes back first. There's a different sync option to handle that (https://github.com/CORE-POS/IS4C/blob/master/fannie/sync/special/products.multi.php#L64).

You can certainly manually add a uniqueness constraint on `upc` if you like.
