### ISSUE TITLE
Why ss-output is not being read

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#732]
I have an upgrade to Ubuntu 14.04.4 and an xbuild of pos.exe that is writing both scans and weights to  to ss-output but not displayed in the POS  The files are accumulating in `ss-output/` suggesting they are not being read (and deleted) by `NewMagellan->ReadFromScale()`.  `pos2.exe` has `CoreLocal::get("scaleDriver")` as `NewMagellan`.  I installed [Mixed up scale display ajax vs scale polling ajax] (e609ae62bd5d7d88769cfd53b49133e0f125e0ba).

I'm using the Chromium browser because its JS display is easier to read than Firefox's.  It shows requests to ajax-parser.js, CustomerDisplay.js and poll-scale.js when `pos.2` is displayed but not additional requests when an item is scanned or weighed.  It does not show errors.

I need help in the approach to debugging this.

**Comment by gohanman** [comment]
If files exist in `ss-output`, it stands to reason the new driver build has nothing to do with your issue.

There aren't requests specifically when an item is scanned or weighed and never have been. You should be seeing a constant stream of ajax requests from here (https://github.com/CORE-POS/IS4C/blob/master/pos/is4c-nf/js/poll-scale.js#L7-L11) - i.e., polling.

**Comment by flathat** [comment]
Note: Debugging at this level is new to me.  Some of the below is not written to the maintainer of this project but rather for the benefit of others who might be interested and need to get up to speed on it as I am trying to.

This concerns getting scan and weigh values from files in `NewMagellan/ss-output/` to the POS screen.  It is the implementation of the description in the [Hardware Driver](https://github.com/CORE-POS/IS4C/wiki/Hardware-Driver)
> POS constantly runs AJAX requests in the background that check for new files in ss-output and read their contents.

I've now been able to compare `pos2.php` JS activity on a lane which is reading the files and on one that isn't.  I used the Firefox [Browser Toolbox](https://developer.mozilla.org/en-US/docs/Mozilla/Debugging/Debugging_JavaScript) Console tab which is quite similar to the Browser Console (FF Menu > Developer > Browser Console), and the BT Network tab.

When `pos2.php` loads it calls `pollScale('../')` from `poll-scale.js` which is then called repeatedly at a certain interval. `pollScale()` submits `ajax-poll-scale.php`. (I hope I've understood this correctly. It is based on reading the composed request `pos2.php` from the BT > Network rather than the listing on the lane.)

In the Browser Toolbox, Console tab I've ticked Net > Log, which, in the lane that is reading scans and weighs successfully, begins to display:
```POST http://localhost/.../ajax-callbacks/ajax-poll-scale.php```
several times per second.  I think this is what @gohanman is referring to above when he says:
> You should be seeing a constant stream of ajax requests

The Browser Toolbox also has a Network tab which seems to be dedicated to request data and also displays the `ajax-poll-scale.php` requests.

On the lane that is NOT reading the scans and weighs, in the Browser Toolbox I ticked the Console > JS > Errors and Warning items. When `poll-scale.js` loaded for `pos2.php` no problem was reported. The last request when I start `pos2.php` is
```GET is4c.gif```
There is no request for `ajax-poll-scale.php` so I conclude at this point that the JS `pollScale()` is called but there are no requests for `ajax-poll-scale.php` because `pollScale()` doesn't execute the `$.ajax()` because `isNodeWebKit()` returns `true`.  At this point I don't know why that should be so or what it means.
```
var SCALE_REL_PRE = "";
function pollScale(rel_prefix)
{
    if (typeof isNodeWebKit === 'function' && !isNodeWebKit()) {
        SCALE_REL_PRE = rel_prefix;
        $.ajax({url: SCALE_REL_PRE+'ajax-callbacks/ajax-poll-scale.php',
            type: 'post',
            cache: false,
            dataType: 'json',
            error: scalePollError,
            success: scalePollSuccess
        });
    }
}
// ...
function isNodeWebkit()
{
    var isNode = (typeof process !== "undefined" && typeof require !== "undefined");
    if (isNode) {
        try {
            return (typeof require('nw.gui') !== "undefined");
        } catch(e) {
            return false;
        }
    }
}
```

**Comment by flathat** [comment]
The problem is a capitalization in the function name, `isNodeWebkit()` should be `isNodeWebKit()` to agree with the reference to it. Previously fixed in [Misnamed funciton isNodeWebKit] (https://github.com/CORE-POS/IS4C/commit/fe45e17cc2ed529b43ad7adfe921e9458b122edb) - Gotta love that name for a typo fix.

**Comment by gohanman** [comment]
It looks like you're running into this (fe45e17cc2ed529b43ad7adfe921e9458b122edb).

I feel obligated to point out that EVERYTHING related to this occurred between the 1.8 and 1.9 releases. Merging up to a random point in the development cycle and then stopping is a recipe for disaster. The master branch is not stable between releases nor is it intended to be. This bug was of course noticed when the code was put into production use for testing prior to the 1.9 release. By not catching up to at least the 1.9 tag you're repeating the same test cycle to find and fix the same bugs.

**Comment by flathat** [comment]
At the time I wanted some features that were new and needed to do the upgrading at that moment.  Tagged releases haven't been immune from bugs. Also, at that time I was more under the impression that critical lane-side code in master had had at least some testing.

**Comment by gohanman** [comment]
Nothing is every going to be immune from bugs, but your impression is definitely wrong.

What's frustrating here is that from my perspective this was ideally managed. New development introduced a bug, then pre-release testing found and fixed the bug which prevented it from appearing in anything described as stable.

I realize merges aren't always clean and take some amount of time to deal with, but it's been 6+ months. I don't see an upstream issue here at all.
