### ISSUE TITLE
integrating with eCommerce website

### ISSUE THREAD

**Issue by brody182** [CORE-POS/IS4C#759]
can this be integrated with shopify, magento, woocommerce?

**Comment by gohanman** [comment]
Integrated in the sense that items in CORE-POS could be exported to shopify et al or imported from shopify et al? There's no such link now but I doubt it would be all that difficult. If you want something completely seamless that doesn't involve a person dealing with exporting and importing files then the details would depend on which software has direct access to which databases.

**Comment by brody182** [comment]
I'm looking for a seamless option,  like if someone makes a purchase in the pos then it would register in wooCommerce, they need to be connected in some way.  Not sure what kind of api capabilities the core Pos has.

**Comment by gohanman** [comment]
>  like if someone makes a purchase in the pos then it would register in wooCommerce

Not being particularly familiar with wooCommerce I'm not sure exactly what this means, but I think this would really have more to do with what kind of API woo offers. Following the purchase POS would have to either call some API provided by woo to register a purchase or it'd have to connect directly to woo's database to add information about the purchase.

**Comment by brody182** [comment]
woocommerce has the api for this https://docs.woothemes.com/wc-apidocs/

**Comment by brody182** [comment]
I'm just not sure if core pos would be able to tie in to this

**Comment by gohanman** [comment]
I may be missing something, but that just looks like a class API. I was thinking of an HTTP API (REST, SOAP, etc) that would let POS submit changes to woo via HTTP. You could instantiate woo classes from somewhere within CORE provided the files are installed somewhere on the system but that wouldn't get any information from one place to another. In other words you could create a `WC_Product` in CORE but saving it wouldn't get the information to your ecommerce site unless the system running CORE is able to connect to the ecommerce site's database.

**Comment by gohanman** [comment]
Couple follow-up thoughts: I think this is a really interesting idea. The key piece to figure out in the architecture would be figuring out communication channels and data flows. From a practical standpoint it'd almost have to be going POS => eCommerce site. Going in the other direction would either have serious PCI implications or would be a lot harder to set up with HTTPS certificates on both ends or a private point-to-point channel (VPN, SSH tunnel, etc). Most of that latter stuff would be difficult or impossible to set up for folk running their eCommerce site on a shared hosting setup.

From a design standpoint it might be best to stand up a 3rd app running a REST service on the same infrastructure as the eCommerce site. POS (any POS, not just CORE-POS) could communicate with the REST service and the REST service could then talk to the eCommerce site (or its database). A service that bridges multiple POS systems with multiple eCommerce systems would be more useful than a service tied to two specific products, e.g. CORE => woo.

**Comment by brody182** [comment]
I think this is what you are looking for http://woothemes.github.io/woocommerce-rest-api-docs/#introduction

**Comment by gohanman** [comment]
That's just a couple basic cron tasks to submit all CORE's items & customers to WooCommerce. There would probably be some efficiency gains in creating tables for the plugin to keep track of woo's entity IDs.

I didn't touch orders. CORE's primary real world usage is in grocery store's and woo's data model isn't equipped to handle items that are sold by weight. It's not clear to me what the best thing to do would be in that case - don't send the order at all, send the order with by-weight items excluded, or send the order with all the items but incorrect quantity/price.

**Comment by gohanman** [comment]
Sync plugin included in 2.2
