### ISSUE TITLE
Reports: Subdepartments inconsistently applied

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#777]
In many reports the use of subdepartments is inconsistently applied and/or broken.  There seem to be 2 ways that this manifests:

1. the submit form includes a field to select subdepartments, but the resulting report doesn’t have a subdept. column.  Further, the report results don't actually filter on the selected subdepartments.  Can be seen on the Non-Movement and Margin movement reports
Or,
2. there IS a subdept. column, but the data it contains is wrong.  ex.   A Department Movement Report on Produce will show the number 3 in the subdept column for all items.  The "3" seems pretty arbitrary too, does not correspond to a dept#, subdept#, etc.

These issues can be found in the following reports:

- Department Movement
- Margin Movement
- Price Movement
- Non-Movement
- New Item
- Vendor Sales
- Department Transactions

An added bonus would be to find a way to include the subdept name in the report results, rather than the ID, as that would be more user-friendly.

**Comment by gohanman** [comment]
The 3 isn't arbitrary, for what it's worth (which is not to say it shouldn't be fixed). It's a mislabeled super department number. This really dates back to before CORE when subdepts were being used in different incompatible ways.

Most of these are straightforward to fix but I'm not sure what the right approach is to department movement and transactions. Both include open rings and those don't map to any subdepartment. If you run a report on a department then run reports on several sets of subdepartments, the totals won't match. The set of subdept reports will come out lower if open rings are excluded or higher if they're included.
