### ISSUE TITLE
BUGS: Install / extra_config.php 

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#786]
s/b `paramSave()` - https://github.com/CORE-POS/IS4C/blob/master/pos/is4c-nf/install/extra_config.php#L208

s/b `echo $this->selectField('fntlDefault', $ebtOpts, 1);`  - https://github.com/CORE-POS/IS4C/blob/master/pos/is4c-nf/install/extra_config.php#L372

**Comment by gohanman** [comment]
Fixed in master and version-2.2 branches, tagged as release 2.2.2
