### ISSUE TITLE
Cleaning up Translookup receipt output

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#787]
Can we remove CARDNO IN NUMFLAG and BADSCAN from the rendered receipts?

Unless there's a reason why these appear hear.

But many stores reprint these for customers and these changes would pretty up the reprinted rcpts.

<img width="439" alt="reprint_receipt" src="https://cloud.githubusercontent.com/assets/52835/17222363/800cda6c-54bd-11e6-9792-56d855132a7e.png">

**Comment by gohanman** [comment]
I don't see any major problem with removing them, although I've never had a customer ask about extra noise lines on these. My only concern is setting the expectation that this is supposed to produce a "pretty" receipt. There's a potentially endless rabbithole of requests to make the backend transaction view prettier (and probably for different and mutually incompatible opinions of what that means).

**Comment by joelbrock** [comment]
I think the feedback i've heard **most** often about this is that the backend receipts dont look like the frontend receipts.  Not in terms of the headers/footers and such, just strictly the transaction list.

**Comment by gohanman** [comment]
I'm not particularly gung-ho about trying to make them match **and** allowing a customizable transaction list on the frontend receipts. It doubles the amount of work involved in any receipt change.

**Comment by joelbrock** [comment]
i agree on that count.

**Comment by gohanman** [comment]
Closing 'cause the lines in question are indeed filtered now
