### ISSUE TITLE
Quick Key/Menu Editor Error when adding first Menu Entry

### ISSUE THREAD

**Issue by danry25** [CORE-POS/IS4C#789]
When the initial menu entry is added in the Quick Key/Menu Editor, the user gets HTTP 400 - Bad Request after pressing Add Entry, but if the page is refreshed the new entry is there.

This only happens when adding the first entry to Quick Key/Menu Editor in Fannie.

**Comment by gohanman** [comment]
Clicking "Add" submits the form to avoid losing any changes when reloading the page, but when adding the first record that form submission is empty and there's no request handler for a `POST` without any data. In that case it's safe to just refresh the page. The will address the same issue with a few other pages that use `FannieCRUDPage` to edit a table.
