### ISSUE TITLE
On streamlined (or automated) updates

### ISSUE THREAD

**Issue by gohanman** [CORE-POS/IS4C#802]
I'm thinking more about updates lately as one of the biggest unresolved problems with the project. But unlike a lot of problems this one is community driven and needs a democratic(ish) solution.
## Current Status

Updates, when they occur, happen via git. Some combination of `pull/merge/rebase`, depending on personal preference, can bring changes into a deployed instance of CORE. Using version control as a deployment mechanism is theoretically really powerful but it can quickly get really technical, too. Something has to change to improve updating.
## Copying Existing Wheels

I think it's helpful to look at how large projects do this. We don't have to take this approach but it illustrates some of the more glaring sticking points. In many large projects, there's a clear distinction about where customization can and cannot happen downstream. There's a configuration file that belongs to the user and directories like 'themes' or 'modules' or 'plugins' that belong to that individual deployment, but everything else belongs to the upstream project. If you're editing files in `wp-includes` in a Wordpress installation, the next update will just pave over those changes with the "correct" versions of the files.

Now, the way that CORE has actually been deployed in practice it'd be downright user-hostile to adopt this approach without a lot of upfront planning and migration. But there are good reasons that bigger projects take this approach. It goes a long way toward ensuring consistency in deployments and nudges developer users toward active participation upstream. If you have an idea or problem and what it implemented permanently, you have to share that information.
## Streamlining the Current Approach

I think there are a couple major stumbling blocks to making `pull/merge/rebase` updates work smoothly. Documentation or scripting can overcome needing to know arcane git commands but if downstream changes can happen anywhere in the code base then merge conflicts are inevitable. This stops automated updates in its tracks. _At best_, the system could periodically attempt updates and notify an administrator that there are conflicts that must be manually resolved. Human nature being what it is I expect this will often lead to procrastination. But even if downstream installs are diligently resolving conflicts there's no way to guarantee they've all resolved them in the same way. So codebases will still diverge in the long term and likely create new headaches for everyone involved.
## So What Next?

Other suggestions are, of course, welcome but I think #778 is a good place for making a clean starting point. It's an opportunity to sort out which downstream features that people need haven't made it into the upstream codebase, incorporate those features, and move those projects forward with a well-defined safe spaces for downstream customization. I'd lean toward keeping git involved in the process and manage updates by checking out tags. This could be fully automated if desired but also would be quite easy to revert to a previous version in a pinch.

To really make this work I believe it'll be necessary to incorporate downstream changes **quickly**. A lot of real life customization happens under the general heading of "I need this & I need it right now". Upstream's commitment would be if someone posts an issue with changes they've made those changes will make it into the next release so an automated update process isn't destructive.

**Comment by joelbrock** [comment]
wondering what you think the timeline is for bigger changes like this and like #778.
Are you thinking like version 2.3?  Or more like version 3.0?

**Comment by gohanman** [comment]
I don't know. It's largely dependent on what existing downstream deployments want to do. I can't (or at least shouldn't) do anything unilaterally on this.

#778 doesn't have to be involved in the discussion but it strikes me as sort of an "opt-in" approach. If rules for what kind of development happens where are more formally structured on the separate repos, people can choose if/when they want to opt into that change.

I think the ongoing piece is actually relatively easy and just involves laying out some minimal expectations. If downstream needs to change something outside plugins, great. That's an advantage of an open system. But at some point after the immediate issue is solved, the expectation is you post a link to your commit(s). At that point it's upstream's responsibility to incorporate those changes before the next update rolls out.

I don't see any major issue in keeping this combined repo as sort of a free-for-all where you can do whatever you want and deal with merge messes yourself while having separate Office & Lane repos that have slightly more rules for developers to enable easy/automated updates. This all depends of course how much people *want* easier or automated updates. I just don't see a way to do that without some consensus on what/where/how different developers communicate changes.

**Comment by gohanman** [comment]
I don't think this is really a solvable issue. If there are local edits to tracked files there's no way to guarantee those changes are preserved through an update w/o involving the person who made the local edits. Which rules out "automated" entirely. Automated updates has to go hand-in-hand with banning local edits and that's not a simple transition.
