### ISSUE TITLE
Price Rules

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#806]
Can you explain what Price Rules are, or might be, used for?

What does `products.price_rule_id == 1` imply about the price values in the record?

**Comment by gohanman** [comment]
The specific value `1` is equivalent to setting `prodExtra.variable_pricing=1` for backward compatibility. This simply means the item doesn't isn't priced based on cost and margin.

More generally, price rules are intended to deprecate this `prodExtra` field while providing more detail about **why**  the item doesn't follow margin pricing. In hindsight they may be more detailed than necessary. I end up referencing a price rule's type more often than any other detail but "wasting" a few hundred records isn't that big a deal. My price rule types are things like "loss leader", "competitor price match", "NCG basics", etc.

Crucially, price rules are intended to be exceptions to the norm. Margin settings allow the system to calculate and suggest retail pricing. Price rules on the other hand give context to human-chosen prices. IMO the pareto principle applies here and if more than 20% of items have price rules then too much time is being wasted on manual pricing decisions.
