### ISSUE TITLE
Different pricing by time of day?

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#816]
I'd like to set up a promo where certain items are discounted between say 8am and 10am. Is there any functionality in CORE-POS to automate a discount based on time of day?

**Comment by gohanman** [comment]
No, there isn't.

It seems like something that should be grafted onto batches, but backwards compatibility is a bit of a headache. The hour portion of the end date has never mattered before, e.g. a sale with end date `2016-12-31 00:00:00` actually runs through `2016-12-31 23:59:59` but making every batch specify an end date with that level of precision seems like a UI step backwards. I'd also be sort of concerned about start/stop task performance. It'd essentially have to run completely including pushing updates to the lanes in under a minute, so having some kind of flag marking hourly/high-precision batches and a separate start/stop task that only looks at those items seems optimal.

I could see a couple ways to go about this. Tacking a boolean `exactTime` column onto `batches` would be sufficient and minimalist, but if you want to do something like 8am to 10am *every Monday* then there's a whole recurrence piece that would have to be bolted on as [most likely] separate table(s). In that case it'd probably make more sense to have a separate interface for creating & managing the batches' attributes but it could probably share `EditBatchPage.php` for adding/removing items.

That's quite the undertaking though. The easier, not generic way would be to write put a `TotalAction` in a plugin that rewrites pricing based on time and hardcode the items that it applies to somewhere. Depending how often these deals change that might be perfectly acceptable.
