### ISSUE TITLE
Sources for margin in Standard Retail Pricing

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#828]
I want to confirm that there are meant to be three potential sources for margin in the Standard Retail Pricing (SRP) scheme and that the margin should be chosen in this priority (the first one that exists and is not zero):
1. Vendor Subcategory (vendorItems.vendorDept and vendorDepartments.margin)
1. Vendor-Specific margin for store Department (VendorSpecificMargins.margin)
1. Store Department margin (Departments.margin)

**Comment by gohanman** [comment]
Priority is:

1. Vendor-Specific margin for store Department (VendorSpecificMargins.margin)
2. Vendor Subcategory (vendorItems.vendorDept and vendorDepartments.margin)
3. Store Department margin (Departments.margin)

I kind of wish my own store would stop using (1). In a sense you can think of the priorities in reverse, too. (3) is the baseline and should be defined for all departments, (2) defines exceptions to the baseline, and (1) are exceptions to those exceptions. I think that exception-to-an-exception situation would be handled better with `PricingRules` that can express a more explicit intent.
