### ISSUE TITLE
NJ sales tax change

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#834]
NJ has changed its sales tax rate from 7% to 6.875%. In a year, it will change again to 6.625%.

Is it smarter to *change* the amount of the existing tax rate record entry in the POS setup, or to create a *new* tax rate record and switch all the existing departments to use the new record?

I could imagine that the latter approach, while involving more work, might work better for archived data; but if CORE-POS already archives everything it needs to know about tax rates, I’d guess the extra work isn’t needed.

**Comment by gohanman** [comment]
I would just change the existing tax rate. Rates are archived although I don't think any reporting utilizes that directly. As a practical issue running old sales tax reporting has never come up.

In any event, tax reporting should start with actual sales tax collected and then extrapolate back to determine what taxable sales were (the alternative, walking through every individual transaction to account for % discounts and EBT purchases on taxable items, is quite slow). It's pretty straightforward to take total tax collected and manually substitute an old rate if needed.

**Comment by scannerdarkly** [comment]
Excellent — thanks for answering quickly and decisively, this definitely puts us at ease.

**Comment by scannerdarkly** [comment]
We are now going to be selling stuff at two different sales tax rates. (NJ has a special Urban Enterprise Zone tax rate that only applies to certain items.)

Looking at the `taxrate` table, I see a field called `salesCode`. What is this used for, and do I need to set it to any particular value?

**Comment by gohanman** [comment]
It's used for the same thing as `departments.salesCode` (and `tenders.SalesCode`): mapping transaction data to financial software's chart of accounts. It's a wholly optional piece of reporting info. The lane side of things doesn't care about it or even need it.

As far as multiple tax rates, a given item can only have one rate so depending how things align you might actually need three:
* NJ sales tax only
* NJ & UEZ tax
* UEZ tax only

Also for `taxrates.id >= 2`, the first letter of the description gets used as an on-screen indicator (the first tax rate is always "T"). Picking descriptions with different first letters will make it more obvious what rate applies to a given item.

**Comment by scannerdarkly** [comment]
Nice, thanks for all that information!
