### ISSUE TITLE
Counting inconsistencies among reports

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#835]
Passing along input from a user:

> I was reviewing Margin Report, it seems its polling items that are scanned but voided.  So instead of showing 1 sale for an item, it shows 2 because it was scanned twice (in error) and voided once.  I am believing that's what's happening because when you do an item movement it shows less rings than what the [margin] report is showing.  This makes it difficult to define margin errors and/or discount abuse.

*Sounds* like potential inconsistent counting methods when reporting on units sold?  But i havent gotten as far as examining the relevant queries on these 2 reports to see if/how they differ.

**Comment by gohanman** [comment]
If it's this [Margin Report](https://github.com/CORE-POS/IS4C/blob/master/fannie/reports/MarginMovement/MarginMovementReport.php#L104-L133) and this [Item Movement](https://github.com/CORE-POS/IS4C/blob/master/fannie/reports/ProductMovement/ProductMovementModular.php#L83-L103) then the counting method is literally identical. They're both using `DTrans::sumQuantity`.

If the $ total also differs that a `JOIN` on the margin report isn't one-to-one as expected. But I don't see any way that the $ total could match but quantity differ.

**Comment by joelbrock** [comment]
thanks, would have seen that if i'd slowed down to look at the code before posting.
I'll try and get more specifics from the user....

**Comment by gohanman** [comment]
If they're looking at Department Movement - AFAIK the only report with a column named "rings" - that's counting the number of times something passed the scanner scale. If you enter 5* and scan an item that's one ring. If you put a 2lb melon on the scale that's one ring. If you put a 0.01lb bay leaf on the scale that's one ring.

The intention was to get a better handle on how times by-weight items are getting purchased (both weighed at POS and service-scale labeled). Differences between rings and quantity for plain old barcoded items are just random noise from how cashiers choose to use the multiplier key.

**Comment by joelbrock** [comment]
OK, i think it's this:
![localhost_8888_reports_marginmovement_marginmovementreport_php_buyer_1_deptstart_143_deptend_143_date1_2017-01-29_date2_2017-02-04_other_dates_on](https://cloud.githubusercontent.com/assets/52835/22519008/aa207ba8-e863-11e6-8325-d6e43e838d71.png)

For this item, the Tlogs show it was rung up 2x.  And then 1 was VOIDed.  So, 1 sold in total.  The Sales column reflects this.  The Cost column is summing all 3 records.

```sql
mysql> SELECT tdate, upc, description , cost, ItemQtty, total, trans_status, voided FROM dlog_15 where upc = 0004227200504 and tdate > '2017-01-29 00:00:00';
+---------------------+---------------+----------------------------+------+----------+-------+--------------+--------+
| tdate               | upc           | description                | cost | ItemQtty | total | trans_status | voided |
+---------------------+---------------+----------------------------+------+----------+-------+--------------+--------+
| 2017-02-01 09:24:14 | 0004227200504 | Soup, Black Bean Vegetable | 2.41 |        1 |  3.59 |              |      0 |
| 2017-02-01 09:24:15 | 0004227200504 | Soup, Black Bean Vegetable | 2.41 |        1 |  3.59 |              |      1 |
| 2017-02-01 09:24:16 | 0004227200504 | Soup, Black Bean Vegetable | 2.41 |       -1 | -3.59 | V            |      1 |
+---------------------+---------------+----------------------------+------+----------+-------+--------------+--------+
3 rows in set, 13584 warnings (0.04 sec)
```

**Comment by gohanman** [comment]
OK, yeah. That's [this](https://github.com/CORE-POS/IS4C/blob/master/fannie/reports/MarginMovement/MarginMovementReport.php#L110-L115). 2.4 is the only release the includes the fix.

From a logical standpoint point cost really ought to be negative on a void (and is in 2.4+) but to cope with historical data this is forcing cost to be negative when total is negative and positive when total is positive.

**Comment by gohanman** [comment]
As far as I can tell this is fixed.
