### ISSUE TITLE
Diagnosing computer power issue

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#849]
One of my lane computers has apparently lost electrical power.  The usual light that goes on when it is plugged in and turned on is off, the disk doesn't turn, but there is a small LED on the motherboard that does go on.  The computer is an ITX format. It has an external AC/DC adapter and an internal DC/DC power supply on a small separate board (PSU). I swapped in a PSU from a working computer of the same type but still no power-light, disk doesn't turn.  I tested the voltages at the power connector both on the motherboard and on the known-good PSU.  The 3.3 and red 5 volt leads are higher than tolerance on the motherboard and lower, but still higher than tolerance on the PSU. 12 volt are nearly the same and within tolerance on both. Voltages are the same on all instances of each type. (The motherboard voltages using the PSU from the non-working computer were similar.) I also replaced the CMOS battery, but only in combination with the original PSU.

Any suggestion on something else fairly simple to try?  My hardware skills are quite limited.

It is getting hard to find pre-built ITX systems with the "traditional" parallel, VGA and serial ports.  Is it likely an ITX board such as [Q1900B-ITX](https://www.amazon.com/dp/B00J2CCCJE/ref=psdc_1048424_t2_B00JQHUE3G) or [N3150B-ITX](http://www.asrock.com/mb/Intel/N3150B-ITX/), which have them, could be swapped in so I could use the existing disk (assuming it is OK, which I don't know for sure at this point)?

**Comment by joelbrock** [comment]
One _possible_ thing to try is to reset CMOS.  Usually involves removing or repositioning a jumper on the motherboard.  The docs for your MoBo should have instructions on this.

**Comment by gohanman** [comment]
> Any suggestion on something else fairly simple to try? My hardware skills are quite limited.

I'd call testing voltages advanced hardware skills myself.

The motherboard LED would suggest to me that the motherboard is getting power. There should be a wire leading from the physical power switch to a 9-pin block somewhere on the motherboard. That block includes pairs of pins for the power switch, reset switch, power LED, and harddrive status LED. That might be loose or something could be wrong with the physical power switch such that pressing it doesn't connect the corresponding pair of pins. I'm pretty sure in theory you can power on the motherboard by jumpering those two pins briefly but I've never tried it myself.

**Comment by joelbrock** [comment]
> I'm pretty sure in theory you can power on the motherboard by jumpering those two pins briefly but I've never tried it myself.

Haha, i've tried this before by bridging the POWER pins with a screwdriver.  It does work, though i can't attest to whether or not this is a good idea.
