### ISSUE TITLE
Perpetual Inventory Discussion Issue

### ISSUE THREAD

**Issue by gohanman** [CORE-POS/IS4C#850]
By request here's an issue thread to talk about perpetual inventory. I believe everything in the [documentation](https://github.com/CORE-POS/IS4C/wiki/Tracking-Inventory) is still accurate.

### Basics
Inventory can be run on one item, all items, or any subset in between. To add an item to inventory tracking that item **must** be assigned to a vendor. An item is added to inventory by assigning it a **count** and optionally a **par**. 

The **count** is how many units are currently present. At any given moment the inventory on hand is the most recent count plus orders minus sales minus shrink. Counts and inventory levels are measured in whatever unit is used for sales to keep the "minus sales" piece of the equation completely automated.

The **par** is the quantity the store wants to keep on hand. The **par** quantity controls order automation steps. An item with a par of zero will never be included in automatically generated orders. It's important that case sizes are entered correctly for order automation to work reliably.

### Orders
Orders, or POs, and found in **Purchase Orders** under **Item Maintenance**. A PO is a list of items, quantities, and costs. The PO lifecycle involves three stages: pending, placed, and received.

When a PO is created, either automatically or manually, it starts out in the **pending** stage. A pending PO does not alter inventory and may still be edited or deleted. When an order is submitted to the vendor the corresponding PO should be changed to **placed** status. At this point inventory levels will increase even though the items likely are not physically present yet. This is to avoid repeated automated orders while goods are in transit. Finally when the order arrives the PO should be received by entering the quantities that were actually delivered which may differ from the quantities that were originally ordered. Any receiving adjustment will adjust inventory levels accordingly.

### Sales and Shrink
Tracking sales should not require any manual intervention. Mistakes like miskeys or open rings will skew inventory levels but these are largely unavoidable. Periodically entering fresh counts will be necessary; the frequency of that depends entirely on the store's tolerance for skew.

Shrink can be entered via `DDD` at the front end or using backend shrink entry tools. No special steps are required for items that are included in inventory tracking.

### Edge Cases and Details
Inventory does not aim to cover every conceivable scenario. Some situations might require extra data entry legwork or just might be a poor fit for inventory. Two notable cases are:
* Items sold multiple ways. If for example a soda is sold both as six packs and single cans/bottles, inventory only provides for one count and par that would be given in single cans/bottles. To track them separately would require some kind of formal step where the store converts six packs to singles on the backend.
* Items purchased multiple ways. If an item can be purchased in several colors or flavors but are all sold under the same PLU or UPC, there's no practical way to keep separate inventory levels for the individual colors/flavors.

Returns are **not** currently added back to inventory. This likely has to be dealt with on a case-by-case basis.

A par of one has special meaning. Automated ordering will order a par one item when inventory levels are **at or below** par. In all other cases ordering is only triggered when inventory levels are below par.

### Future Work
Allowing order **submission** from directly within POS would be nice. To the extent that his is possible it probably means "via email". To whatever extent possible co-ops should use their size relative to smaller suppliers to dictate how ordering will work rather than adding bespoke variations for each vendor.

Ordering needs to be aware of promotional sales. Movement changes significantly in those cases. Adjusting pars up and down is possible but would quickly get tedious. The order view should flag items that are on sale somehow so they're easy to recognize.

This is intended as a catch-all for anything inventory related.

**Comment by gohanman** [comment]
I made some revisions to [documentation](https://github.com/CORE-POS/IS4C/wiki/Purchase-Orders-and-Invoices) on purchase orders to bring it more in line with current functionality.

**Comment by gohanman** [comment]
A couple updates:

> Allowing order submission from directly within POS would be nice. To the extent that his is possible it probably means "via email". To whatever extent possible co-ops should use their size relative to smaller suppliers to dictate how ordering will work rather than adding bespoke variations for each vendor.

This is essentially done and will be enabled in the next release. The main things to keep in mind will be:
* `Users` gets widened to include an email address column. This lets the order be sent as "From" the correct person & also CCes that person on the order so they can see what was sent.
* Email will have to be configured correctly on the server running Office. That includes avoiding the more obvious spam filters (relaying is probably easiest) and making sure bounces get back to a person (ideally the person who sent the order).
* CSV export formats work better. It's feasible to re-parse the export and give the email a body with the same information as the attachment. That's convenient for the recipient and having a message body probably cuts down on the chances of getting spam filtered.

> Ordering needs to be aware of promotional sales. Movement changes significantly in those cases. Adjusting pars up and down is possible but would quickly get tedious. The order view should flag items that are on sale somehow so they're easy to recognize.

This is done and will be in the next release. Sale items get "info" flagged (default light blue) and show the name of the batch on hover.

**Comment by gohanman** [comment]
By request, here's a bit about how perpetual inventory has been used at Whole Foods Co-op and some takeaways. There'll be a bit of editorializing.

First, this is more of a people issue than a technical one. There's some features and functionality that has to exist, but *using* those features fundamentally means disrupting and changing existing workflows. To that end I think there has to be a goal. No one's going to be gung ho about spending extra time electronically receiving orders if it's just for the sake of having perpetual inventory. Perpetual inventory has to be a stepping stone to accomplish something else. Now that we have these live on-hand counts we can do X. For us that goal was to streamline ordering.

The niche perpetual inventory fills right now - and it's very much still a niche - is smaller vendors with packaged products and mostly just non-perishables. Ordering from lots of small vendors that each only provide a handful of products is time consuming in a way that's not really proportional to those products' sales. By setting pars for these items we can use the on-hand information provided by perpetual inventory to generate purchase orders for those vendors.

In-aisle ordering remains the norm for big vendors. At a larger scale it's less clear if there's a time efficiency to be had. Perpetual inventory could co-exist with in-aisle order creation but there would have to be a compelling use case for what to do with that data beyond generating orders to justify the time spent gathering said data.

**Comment by flathat** [comment]
A user at another CORE-POS-using co-op passed on these remarks:
> I have some limited experience with perpetual inventory from larger organizations, and believe that the costs of implementation might outweigh the benefits of the system considering our small store format, depending on the levels of functionality the support coop [i.e. the Tech Support Co-op, which supports CORE-POS] is intending. That's not to shut down the idea, but just share my opinion that we would lose more than we would gain at this point in our evolution.

> I believe it would be extremely challenging for us to implement perpetual inventory without hiring a dedicated receiver (plus someone to cover their two days off), as all invoices would need to be uploaded to whatever system was created. Not only would those invoices need to be electronically uploaded, but all products must be checked in to a much higher level. Like, if UNFI doesn't send an item, perpetual inventory will be off.  If a wine company changes a price but it hasn't been changed in our system, we couldn't receive it, etc.  Again, this is based on my limited experience, and perhaps the support coop has a different system in mind.  It's hard to imagine that they [i.e. CORE-POS] are going to come up with a better system than say a multi-billion dollar Whole Foods Market system, as they have the resources to provide whatever system they think is best.

> At minimum, once full implementation has been achieved, assuming that some costs to bookkeeping would be cut (which is a big assumption - there might be more bookkeeping paperwork to do than originally thought), we would probably still look at a minimum of 40 additional hours of labor per week on top of what we may save on that end. That's also not piecing in some other (assumed) costs- technology (hand held scan guns, a new printer/computer/work space, etc), training, etc. I'm not sure that where we're at with declining sales that investing labor into a position/s that are administrative instead of retail help would be prudent.

> If we were wanting to move forward on making a decision to implement/not implement, it would be prudent to gain full consent from finance and the buyers team. This would affect every department including produce and bulk. In reality, it would also have somewhat of an impact on FE [Front End], as every item would need to be scanned very accurately. SPO's [Special Orders] are one thing that jumps to mind as an area with which we have minimal accuracy at this time.

**Comment by flathat** [comment]
At my own co-op, West End Food Co-op in Toronto, we have begun to implement loading digital cost data from some of our vendors, which is one of the foundations for perpetual inventory, and expect to place our first CORE-generated orders soon.

Our ambitions for perpetual inventory include:

+ monitoring shrink, especially theft
+ tracking turnover, the rate at which products move

**Comment by gohanman** [comment]
IMO that's an insightful comment. Any level of perpetual inventory inevitably adds some labor to receiving and that needs to be justifiable. There are some potential accounting savings but those largely involve shifting. At some point information about purchases has to be digitized and moving that process from accounting to buyers doesn't necessarily save any hours overall. The most straightforward saving is where ordering can be automated. The advantages of having real time margin information are harder to quantify. We see some advantages in being able to "check" backstock without physically going and looking but store size/layout is a massive factor in how important that is.

I do think there's a Pareto-principle-esque factor with stores working with a larger number of suppliers. Running perpetual inventory on small, local suppliers to eliminate ordering labor can have gains without trying to run perpetual inventory on everything. Co-ops' tendency to work with dozens (or hundreds) of independent suppliers is fundamentally labor intensive.

I don't follow what perpetual inventory has to do with tracking movement. That shouldn't require any extra effort unless the checkout process is generating bad sales data - and perpetual inventory is going to be a mess without good sales data. Keeping accurate costs on file is of course a good idea but I'm not sure this requires perpetual inventory either. Spot-checking invoices on an item at least monthly or quarterly may require less work than checking in every invoice without a significant gain in cost accuracy.

**Comment by gohanman** [comment]
Expanded docs:

https://github.com/CORE-POS/IS4C/wiki/Base-Counts
https://github.com/CORE-POS/IS4C/wiki/Purchase-Orders
