### ISSUE TITLE
Composer install problems with new installation

### ISSUE THREAD

**Issue by cnakamoto** [CORE-POS/IS4C#851]
Hi, I am sorry if this problem is not related to the Core code.  I just installed the latest branch of CORE-POS and I was walking through the installation and when I get to the point where I run the 'composer install' command, I get the following:

```
[coremusk@storm30 IS4C]$ composer install
Loading composer repositories with package information
Reading composer.json of adodb/adodb-php (psr4)                
Skipped branch psr4, "1fb7e26478b7ab8a98afe5b2a2dd059394368948:composer.json" does not contain valid JSON
Parse error on line 36:
...adict/"            "ADOdb\\drivers\\" :
---------------------^
Expected one of: 'EOF', '}', ':', ',', ']'

Updating dependencies (including require-dev)                        
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for codeclimate/php-test-reporter ^0.2.0 -> satisfiable by codeclimate/php-test-reporter[v0.2.0].
    - codeclimate/php-test-reporter v0.2.0 requires satooshi/php-coveralls 0.6.* -> satisfiable by satooshi/php-coveralls[v0.6.0, v0.6.1].
    - satooshi/php-coveralls v0.6.0 requires psr/log 1.0.0 -> satisfiable by psr/log[1.0.0].
    - satooshi/php-coveralls v0.6.1 requires psr/log 1.0.0 -> satisfiable by psr/log[1.0.0].
    - Conclusion: don't install psr/log 1.0.0

[coremusk@storm30 IS4C]$
```

I have tried to trace this error back but I can't even figure out which file is causing the error.

Any help would be appreciated - thanks!

Craig

**Comment by gohanman** [comment]
What version branch are you on? The composer.json for 2.5 requests a different version of `codeclimate/php-test-reporter` and doesn't have a reference to `adodb` anymore (plus it has a lock file that should prevent these kind of issues).

The top level VERSION file should say what you're working with.

**Comment by cnakamoto** [comment]
That was the problem.  I just checked out master and it is working fine.  I am now on 2.6.0-dev - which is probably fine since I am just testing the software right now to see if we will be able to use it for our new store.  Thanks!
