### ISSUE TITLE
Partial Day Promotional Pricing

### ISSUE THREAD

**Issue by gohanman** [CORE-POS/IS4C#869]
The purpose of this issue is to spec out a design for pricing that applies for some limited portion of a day. Pretty much everything's open to debate or suggestions.

### Considerations
* I think recurrence has to be included in the design. In practice I expect many or most of these kind of pricing schemes will recur and planning for that will make the result cleaner.
* There's going to be tension here between flexibility and complexity. A scheduler that can run something on the 3rd Thursday of every other month is useless if the configuration UI is a nightmare no one understands.
* An item's base retail might change between recurrences
* An item might already be on sale when an hourly pricing scheme kicks in
* An hourly pricing scheme might start or stop in the middle of a transaction
* The precision of start and stop times is going to depend on how frequently a background task to start and stop hourly pricing runs.

### Design Sketch
* This can be built on top of `batches`. Nothing in `batches` needs to change meaning. Existing start and end dates can put outer limits on recurrences. For example, to run a summer weekend special "summer" would be from `batches.startDate` to `batches.endDate`.
* `batchType.editorUI` can route these to a slightly or radically different UI depending what's needed
* We'll need a supplementary table to store more information about scheduling
  * This would definitely have a `batchID`, start time, and stop time.
  * A padding or tolerance in minutes that extends the stop time might be nice to have. The goal would be to minimize customers who are upset they didn't get the price because their purchase was slightly after the advertised end time. You could do the same thing by setting the stop time differently from what's publicly advertised but having a separate field makes intent clearer.
  * IMO there should be a simple yes/no toggle for whether a time-based sale applies if an item is already on sale. I think you either draw the line here or open the floodgates to lots and lots of permutations and the latter isn't worth the confusion or potential for mistakes.
  * I think scheduling should be be a fixed list of options, not a combination of text date/time descriptors and numbers defining frequency of cycles. A fixed list is easier to understand (and implement). If it means you occasionally need a couple identical batches with slightly different schedules that's fine. I'd rather have a "clone batch" function than a complex scheduler. I'd propose starting with:
    * Daily
    * Weekdays
    * Short Weekends (Sat-Sun)
    * Long Weekends (Fri-Sat-Sun)
    * And then 7 more options for the individual weekdays
* A specialized batch task would **only** start and stop batches that have an entry in the supplementary scheduling table. The regular batch task would also need to check for these entries and skip over such batches.
* Letting the user define pricing as $X.XX off or X% off would let long running batches adjust automatically to changes in retail (and/or non-timed-sale) price but again at the cost of some complexity.

### Implementation
* Need a table or tables to hold additional necessary information
* Need a user interface to manage data in the table/tables
* Need a task that can start/stop these sales

**Comment by flathat** [comment]
Long weekends in Canada are almost always Sat-Sun-Mon.

**Comment by gohanman** [comment]
That's mostly the case in the states, too, at least with holidays. My thinking is that if someone's going to run a "weekend" deal year round (instead of just on Labor Day or Memorial Day or whatever) it'd likely be Fri-Sat-Sun or Sat-Sun. Friday evening is commonly viewed as part of the weekend. No part of Monday is outside of special occasions.

**Comment by gohanman** [comment]
As implemented:

This will require adding a new **batch type** and assigning it the UI **Partial**. When a batch has a type with the Partial UI the batch editor includes fields for start and stop time, whether or not to override existing sales, and recurrence options. This will also require enabling the Partial Batch task. Start and stop times are relative to the timing of the task. If the task runs every 5 minutes and you set a partial batch to start at 13:03 it will actually start at 13:05 (or maybe 13:05:01 or so).

The partial batch task does not support the full array of sale pricing options e.g. X for $Y. It'll set a sale price for one item and that's it. It also doesn't log changes to `products` to `prodUpdate` like normally happens with changes. Both these compromises are intended to keep overhead low and start-to-finish execution time as fast as possible. In theory someone might want to schedule the task to run every minute.

Not overwriting existing sales is probably the safest option. The current limitations of the management task means the item isn't going to revert to the previous sale price with the partial batch ends. One exception would be a partial batch that runs "until close". In that case the normal sales batch management task will sort everything out again overnight.

This requires an up-to-date enough `products` schema to have a `products.batchID` column. If another batch is forced while a partial batch is in effect, the partial batches task will not make further changes to any affected items. The forced batch is interpreted as an intentional override. If that's not the case the partial batch can itself be forced to put the partial batch system "in charge" of those items again.

**Comment by joelbrock** [comment]
Based on our field testing of this new feature here's some feedback:
+ Some typos: 4e74ab911f2ec3260145500ff519c7b3130159d6
+ Besides that it actually seemed to work great with one flaw:  As it stands now, the prices do go into effect at roughly the designated time, and we can see their sale status in Fannie > Item Maint..  But the process still require a manual Procucts sync to update the lane.  How to trigger a products sync AFTER the cron task updates a partialBatch?  Ideally how to sync ONLY those items in the batch that were updated?

**Comment by gohanman** [comment]
81093574f541f8f270c9ea82cbc12feb14469111

I semi-remembered this was necessary since I built the `$changedUPCs` list; I just forgot the actual sync.

**Comment by joelbrock** [comment]
Field test round 2 including the latest fixes:
>Partial day batches seem to work. 
 🍾 👏 😀  !!!

>One minor issue is that the item editor ui in Fannie shows an end date of 0000-00-00 while the batch is active.
