### ISSUE TITLE
Could Install > Updates handle plugin model changes?

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#872]
2.6 doesn't  for `OverShortTools/models`.

**Comment by gohanman** [comment]
Yes, generally. If the database name is a plugin setting it needs to be specified [like this](https://github.com/CORE-POS/IS4C/blob/master/fannie/modules/plugins2.0/ScheduledEmails/models/ScheduledEmailQueueModel.php#L30) so the updates page knows where to find the table.

**Comment by gohanman** [comment]
I think that covers it.
