### ISSUE TITLE
How to clean out lane databases

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#873]
How does one properly clear out the lane databases to prevent them filling up with archived data?

I believe this has been answered before, but I don’t know where to find the answer.

**Comment by gohanman** [comment]
Meaning `translog.localtrans`?

Either the newer `Trim Lane History` scheduled task or the older `lanes clean`. The former was added in 1.10 but 1.10-dev effectively means "some point between 1.09 and 1.10".

`translog.localtrans_today` and/or `translog.localtranstoday` should take care of themselves. I don't think anything else accumulates meaningful data over time.

**Comment by scannerdarkly** [comment]
It seems these tasks are designed to be run from the office backend. On our lanes (where the data is accumulating), we never ran the office setup even once, and so there’s no config.php is needed by LaneTrimTask; was it a mistake on our part to not have set up office on our lanes?

Or am I completely misunderstanding the issue, and the office backend can remotely instruct the lanes to delete their old data?

**Comment by gohanman** [comment]
> the office backend can remotely instruct the lanes to delete their old data?

This. The office backend has access to the lane databases and can add data (e.g., products) or in this case delete data.

**Comment by scannerdarkly** [comment]
So we’d just run LaneTrimTask from the backend?

**Comment by gohanman** [comment]
Yep
