### ISSUE TITLE
In-Aisle Price Check Scanners Software

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#876]
As a couple CORE-POS users are in a state which requires there to be in-aisle price check scanners made available, i'm looking to try and see if we can offer an easily deployable (and more affordable) solution to this need.

Inspired by @gohanman's tinkering with a Raspberry Pi approach i'm interested in developing something that has all the nec. features to meet the statutory requirements.  I know there is already a price lookup page for this purpose included in the code.

I have specced out a Raspberry Pi w/ a 7" touchscreen and barcode scanner.

The added features that would make this a homerun would be:
+ an onscreen number pad, for punching in bulk PLUs
+ a print button - i will find out what info is required to be on the printout, but date+time, the UPC/PLU, and the current retail and/or sale price would be a good start

I'm looking at thermal printers that could interface with the Raspberry Pis, [this one](https://www.amazon.com/dp/B06XFKNPG5/_encoding=UTF8?coliid=I1CH8POQV0EYSZ&colid=8JH2BUWW8QCZ) looks promising w/ support for ESC/POS and bluetooth connectivity.

I'm interested to know what design challenges other foresee?  Technical hurdles? Thoughts in general?  etc.

**Comment by gohanman** [comment]
This is the page in question that essentially just keeps the cursor in place and assumes the barcode scanner will behave HID-ily: https://github.com/CORE-POS/IS4C/blob/master/fannie/item/PriceCheck/PriceCheckPage.php

From a security standpoint such devices should probably have their own backend installation & database. I don't think that's a compute problem for the Pi but implies some kind of periodic sync. A browser with a strong kiosk would be a good starting point but since it's a fully functional PC it should be isolated such that if someone gains control of that PC they can't [easily] proceed deeper into the network.

**Comment by joelbrock** [comment]
>  such devices should probably have their own backend installation & database
Here you mean having the RPi accessing a page hosted on a local LAMP stack, as opposed to a page being served from the POS server, for example?

One of the biggest design challenges i see is encasing the entire rig in a secure fashion.  I've picked up a secure RPi case that blocks open ports.  But something that encloses ALL the hardware in an ergonomic and compact fashion and provides flexible mounting options and tamper-proof-ness might need to be a custom job.  Is it time for me to buy a 3-D printer?  (oh please say yes!)

**Comment by gohanman** [comment]
Well just having the touchscreen means an input device is available. IMO you should assume someone will figure out how to close the browser and make sure they still can't reach anywhere valuable on the network from that PC.

**Comment by joelbrock** [comment]
RPI w/ 7" touchscreen and the existing PriceCheckPage.php
Has been more or less plug'n'play so far.
![2017-06-21 20 27 35](https://user-images.githubusercontent.com/52835/27416152-7277f3fe-56c0-11e7-8e9e-bf61b2874382.jpg)
![2017-06-21 20 27 09](https://user-images.githubusercontent.com/52835/27416153-72781884-56c0-11e7-910c-205d7afd4d6f.jpg)
