### ISSUE TITLE
Basic Item Search inUse not working

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#881]
>Currently, in Item Search, when we search for a product WITHOUT selecting the "Include not inUse" box, the search still includes not-in-use items. If we perform an item search without selecting the "Include not inUse" box, we need the results to return ONLY in-use items and exclude not-in-use items. 

In my own testing on 2 production systems i could not see that the inUse checkbox on ItemEditorPage had any effect at all.  
Further, some Items presented in the search results had a "Create this item" button in their editor....

**Comment by gohanman** [comment]
^ That's the issue with the inUse checkbox.

The first thing that stands out on `Create Item` is a mis-sized UPC. That'd show up in the search results but on selecting the individual item it'd pad the UPC out to a proper 13 digits - and would in fact create a new `products` record with the correct width UPC. If there's tooling in CORE that lets you create mis-sized UPCs I'd consider that a bug; trying to cope with unexpected, existing malformed data is an endless rabbit hole though.
