### ISSUE TITLE
Data models for email columns are too restrictive

### ISSUE THREAD

**Issue by jdpurdyvi** [CORE-POS/IS4C#882]
Default models are varchar(50). Suggest we bump that up to 75 or 100.

**Comment by gohanman** [comment]
Fine by me; I've just never run into an issue with it before. I just checked and 42 is the longest I have on file. 0.06% of addresses are 40 characters or more.

N.B. `meminfo.email_2` gets used in practice as an alternate phone number. That really ought to get renamed now that models have a mechanism for renaming columns.

**Comment by gohanman** [comment]
^ That's just the field widening. I didn't touch `email_2` although ugliness of `MemberREST`'s internals notwithstanding the scope of that potential change is smaller than I would have expected. Relatively few things touch the column directly.

**Comment by gohanman** [comment]
On 2nd examination there's a bunch of references to `email_2` in CiviCRM scripts. I don't know enough about how those are supposed to work to confidently revise them around column name changes so I think I'm just going to leave it mis-named for now.
