### ISSUE TITLE
Open Ticket functionality

### ISSUE THREAD

**Issue by otc-narendra** [CORE-POS/IS4C#884]
A common feature in restaurant/bar POS systems is "Open Tickets" or "Open bar tab" - the ability for multiple simultaneous open transactions which can be edited as customers add items to their order with payment made one time at the end of the customer's visit. The key features necessary for this type of functionality to work properly are:
1) Ability to suspend or resume a transaction from any lane (i.e. global list of pending transactions)
2) Ability to attach a simple human-readable transaction identifier like a table number or customer name to a transaction so that staff can easily pull up a suspended transaction for editing
3) Remote printing of food items for the kitchen (under development - https://github.com/CORE-POS/IS4C/issues/870)

CORE already has most of this built-in and we have been using it with some success with the following workflow:
1. Customer walks up to register, orders some items and hands cashier their credit card to start a tab (or place a one-time transaction).
2. Cashier hands customer a table number which they keep through the night and display on their table; adds a comment to the transaction like "Table number <xx>"; rings up the items; adds any other comments like "no onions"; suspends the transaction; wraps credit card in printed suspend receipt and writes table number on it; and files away the card in a box. If this is a one time transaction, the cashier does not suspend the transaction but closes it out and accepts payment. The kitchen remote printing feature (once fully functional) prints a kitchen ticket along with all the comments.
3) When the food is ready, the kitchen sends it out with the server using the table number as a way to identify the customer.
4) Customer wants to add items to their order so they walk up to the counter and place their order using their table number to identify themselves. The cashier finds the customer's credit card and suspended receipt(s) using the table number; looks up the CORE transaction number from the receipt; resumes the transaction; adds a comment like "Table number <xx>"; adds items; and then suspends again. The kitchen remote printing prints out a kitchen ticket with only the new items and any new comments.
5) Customer wants to close their transaction and pay their bill. Cashier uses table number to locate transaction number; resumes the transaction; takes payment.

It should be noted that unlike most restaurants, we do not have table service (i.e. customers must walk up to the counter to place an order) or fixed seating (i.e. customers can pick any table they want and even move around during their stay). This is why it is necessary for them to be assigned a unique "table number" which they hold on to during their stay. If a customer does not have an open tab then they are assigned a different style of table number so that when their food is delivered, the staff can take their number back.

Note that the ability to suspend/resume from any of multiple lanes is critical and already works as expected.

All of this works but there are a few speed-bumps that make it difficult for staff:
1) The mapping between table number (easily human readable id) and CORE transaction number has to be done manually although the comment features help. However, the table number comment needs to be entered at each suspend in order to ensure that it is printed on the kitchen remote receipt.
2) Suspend/Resume require multiple keystrokes.

To make some of this easier, I have created a custom key on our keyboard which maps to "CMTable Number: " so that cashiers have to push that key and then just enter the table number in order to quickly put that identifier into the transaction. This is better but doesn't completely resolve the issue. Ideally we would have:

1) Single button suspend/resume
2) Upon suspend one would be able to enter a user-defined identifier (unique to the current set of suspended transactions only since table can be re-used throughout the day) 
3) Upon resume a list of pending transactions showing the user-defined identifier (instead of the current transaction number)

The other issue that comes up is tipping of staff. Currently we limit people to cash tips but are constantly being asked to accept credit card tips. Since we use integrated card processing, cc tips would need to be added to the transaction so we are considering an open PLU. However this has the disadvantage of forcing customers to specify a tip amount (and potentially do some math in their heads) while under the steely gaze of their cashier!! Not a huge problem but thought I'd mention it here in case there are some clever solutions...

- Narendra

**Comment by gohanman** [comment]
It seems to me like much of this revolves around having that human defined, human-readable identifier (HRI) available. This could still functionally be a comment but it needs to be flagged specially so the system can reliably locate the HRI and display it in suspended receipts, handle it differently in remote printing, etc. Ideally on suspend the system could then detect whether an HRI is present and only prompt for it when actually necessary. Combining this will single-button suspend might get tricky but single-button resume ought to be fairly straightforward.

Tipping is distant enough that I'd rather treat it separately #885. Doing it correctly is a larger undertaking.

**Comment by otc-narendra** [comment]
I like where you're going with the HRI... We certainly can live without single-button suspend.

**Comment by otc-narendra** [comment]
Andy can you provide some more information on why single button SUSPEND is "tricky"? That seems to be the only remaining hiccup to what would otherwise be a super smooth workflow for the cashier.

**Comment by gohanman** [comment]
It's easier with a non-mandatory HRI for sure. There's also an optional security setting requiring a manager approval for suspend/resume that wouldn't play nice with a single button suspend. I don't think this would matter much in practice - requiring manager approval is the polar opposite of trying to make suspend fast & easy - but I'd like to avoid the subtle hidden surprise.

**Comment by gohanman** [comment]
RE: Single-button suspend:

The problem is [here](https://github.com/CORE-POS/IS4C/blob/master/pos/is4c-nf/gui-modules/adminlist.php#L43). The default suspend/resume/tender report page embeds a random token in the form. If a request is sent that includes form data but *does not* have the correct token the whole request is just ignored. So the blank white screen here actually doesn't indicate a PHP error.

If the single-button suspend command generates a valid token first and sends it with the request then it works mostly as expected. The suspend/resume/tender menu does appear briefly while background tasks close out the transaction and print a receipt but once that's done it kicks back over to the main screen automatically.
