### ISSUE TITLE
Bad JSON in EditOnePurchaseOrder ItemSearch

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#892]
* Version of CORE? 1.8 + 2.7 (yikes!)

* Issue with Office, Lane, or both? Office

* Is this [mostly] a bug report, feature request, or question? bug, problem

I'm a bit hesitant to ask for help on this because of the somewhat unholy version of Office it is running on, which is 1.8 with all the code and database parts of 2.7 that are needed to make Purchase Orders and Inventory run without errors, including `$SRC/javascript` and `$SRC/css` from 2.7

The only problem I have is with the Item Search part of `EditOnePurchaseOrder.php`.  It finds the item and adds it to the `PurchaseOrderItems` with `.quantity = 1.00` but does not display the form for changing `quantity` and does not add the item or quantity change to the ItemList tab.  This is because `.ajax().done()` in `editone.js itemSearch()` doesn't run because of an error:
```javascript
  var jqXHR = $.ajax({
    url: 'EditOnePurchaseOrder.php?'+dstr,
    method: 'get',
    dataType: 'json'
    }).done(function(data){
...});
 jqXHR.always(function(jqXHR, textStatus, errorThrown) {
           alert( "jqXHR always textStatus: " + textStatus );
           alert( "jqXHR always errorThrown: " + errorThrown );
            });
```
reports `textStatus: parsererror`    
`errorThrown: SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 156 of the JSON data`    
`data` exists but is empty.

That report was for a simplified JSON chunk that doesn't include the table of existing items in the order:    
`[{"sku":"0006135433333","title":"Carina Organics - Citrus Conditioner","unitSize":"360 ml","caseSize":"1","unitCost":"10.99","caseCost":"10.99","cases":1}]`    
which was composed by `json_encode($ret)`, where `$ret` is a one-item array.
but the errors for the regular results are the same.

The JSON above is 155 characters, and is 155 characters when it's sent from `EditOnePurchaseOrder->get_id_search_handler()`. The error is on a character, at position 156, that is somehow appended to that.

A bit of googling    
syntaxerror json.parse unexpected non-whitespace character after json data    
suggests `JSON.parse` may be having trouble with the original JSON chunk string being an array when it shouldn't be.  But I'm out of my depth on this, looking for a suggestion to either fix or find pertinent debugging information to guide next steps.

Things that do work in this 1.8/2.7 environment:

* The similar Item Search in `EditManyPurchaseOrders` that displays a quantity-input form.
* All other JS and `.ajax()` functionality that I'm aware of in Purchase Orders.
* The 1.8 version of Item Search in`EditOnePurchaseOrder` and `editone.js`, using the 2.7 `$SRC/javascript` and `$SRC\css`
	* But it doesn't populate ItemList, which was, I think, a known issue, and the thing that drove my wanting to upgrade since the context it provides is important.

I tried grafting 1.8 `EditOnePurchaseOrder->get_id_search_handler()` and `editone::itemSearch()` into 2.7 listings, with the minimal changes to allow them to run, but the result is still same `JSON.parse: unexpected non-whitespace character` error.

If the only way to get a firm starting place is doing a full 2.7 upgrade then I'll have to set this aside do that, but other ideas are very welcome at this point.

This issue aside, I now have all the parts of Perpetual Inventory running at least in trial mode, and that is no small thing.

**Comment by gohanman** [comment]
The first thing I'd do is `alert` (or better `console.log`) `jqXHR.responseText`. If the response includes something else beyond the 155 characters you're expecting that could cause the error.

The major changes between 1.8 and 2.7 (or really 2.6) in `EditOnePurchaseOrder` are:
* The search implicitly adds one to quantity on each run. In a handheld context this is similar to other ordering apps I've seen where you can order two cases by scanning an item twice.
* The response is a JSON object with keys `items` and `table`. It used to be just an array of object, similar to what you've posted, and that's what should be under the `items` key but the additional `table` key facilitates updating the Item List tab.

**Comment by flathat** [comment]
Yes, that exposed the problem. For the sake of others who might need to do this:
```javascript
var jqXHR = $.ajax({
    /* ... */
});
/* This makes responseText available. */
jqXHR.always(function(jqXHR, textStatus, errorThrown, responseText) {
    alert( "jqXHR always textStatus: " + textStatus );
    alert( "jqXHR always errorThrown: " + errorThrown );
    /* Two ways of showing it. */
    alert( "jqXHR always responseText: " + jqXHR.responseText );
    console.log("responseText: " + jqXHR.responseText);
    });
```
It showed that the JS for the linea scanner was being appended to the JSON string. This was being done by `FanniePage->postFlight()`:
```php
    public function postFlight()
    {
        if ($this->enable_linea) {
            echo '<script type="text/javascript">';
            echo $this->lineaJS();
            echo '</script>';
        }
    }
```
In `2.7` this is done differently so the issue wouldn't arise in a complete upgrade.

Since we don't have Lineas I just disabled it in `EditOnePurchaseOrder.php->preprocess()` pending the rest of the upgrade:
```php
        if ($this->config->get('COOP_ID') == 'WEFC_Toronto') {
            $this->enable_linea = false;
        }
```
