### ISSUE TITLE
EditManyPO Search replaces current quantity with new

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#901]
* Version of CORE? 1.8 + 2.7

* Issue with Office, Lane, or both? Office

* Is this [mostly] a bug report, feature request, or question? Bug, to me anyway.

In `EditManyPurchaseOrders.php` if you Search for an item that is already in a purchase order the "Order _N_ Cases" input value is 1 and can be increased or decreased.  On "Confirm" the quantity in the current purchase order is replaced by that value.  Since you can't tell from the page whether the item is already in the order this can result in unexpected changes.

It would seem better to populate "Order _N_ Cases" with the quantity currently in the PO, initially 0. However this would require always entering something.  If _N_ were 0 for new items and "Confirm" defaulted to 1 then you couldn't use 0 to remove an item, which you can now.  Removing with 0 may not be done very often and -1 could be used by convention to set quantity to 0.

Or else display the current quantity in the description above the input and change the text around the input to "Add  _N_ Cases to the order", and change the behaviour to increment rather than replace.

Currently, entering negative values in the Search puts a negative in the Order.  Is that meaningless or is it a convention for returns?

**Comment by gohanman** [comment]
It seems to me the best solution is going to start with the search results to include the current quantity. For items in the order Order N Cases should have the actual current quantity. For items that are not in the order I can see at least two options:

* Set Order N Cases to zero. What I like about this is the field behavior is consistent; it always tells you the current quantity. What I dislike is you'd always have to enter a number then confirm which is going to make adding items slower. I suppose we could remove the Confirm button and save the input quantity `onchange`. This would keep adding an item a one-click operation.
* Set Order N Cases to one and put in an extra disclaimer row in the UI saying "Item not currently in order". This takes a little extra screen space which is mostly a mobile concern but keep search, confirm, search, confim, etc as a fast workflow.

I don't like the idea of changing the behavior of saving zero. Using a magic value for delete is REALLY unintuitive. In either option I'm expecting zero still means "don't order this item".

**Comment by flathat** [comment]
> For items in the order Order N Cases should have the actual current quantity.

Yes, this is consistent with what `EditOnePurchaseOrder` does now.

**Comment by gohanman** [comment]
I went with showing the current quantity, including zero for items not yet in the order, as the simplest step forward. My instinct is bringing the search result UI further in line with `EditOnePurchaseOrder` would be best. The recent order history is useful information to have although in this context there are a couple options for what that means (order history for the item in general or order history for the item from a particular vendor).
