### ISSUE TITLE
Help plugin find Class

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#922]
* Version of CORE? Upgrading to 2.7

* Issue with Office, Lane, or both? Lane

* Is this [mostly] a bug report, feature request, or question? Question.

What do I need to add to `CoopCredLib.php` to help it find this Class?
`(debug) Class 'CCredProgramsModel' not found Line 108, /var/www/IS4C/pos/is4c-nf/plugins/CoopCred/CoopCredLib.php`
`CCredProgramsModel.php` is in `$LANE_PLUGINS/CoopCred/models`.

**Comment by gohanman** [comment]
I wouldn't think anything. If the file name matches the class name it should be mapped by `AutoLoader::loadMap`.

**Comment by flathat** [comment]
It does:
```
$ grep "class CCredProgramsModel" *.php
CCredProgramsModel.php:  @class CCredProgramsModel
CCredProgramsModel.php:class CCredProgramsModel extends BasicModel
```
Any idea what other factor might be in play?  This plugin hasn't changed recently except for the addition of `use` and `namespace`, of which my understanding is rather limited at this point
```
use COREPOS\pos\lib\ReceiptLib;

/**
  @class CoopCredLib
  Functions for the Coop Cred plugin.
*/
class CoopCredLib {
```

```
namespace COREPOS\pos\lib\models\op;
use COREPOS\pos\lib\models\BasicModel;

/**
  @class CCredProgramsModel
*/
class CCredProgramsModel extends BasicModel
{

    // The actual name of the table.
    protected $name = 'CCredPrograms';

    protected $preferred_db = 'plugin:CoopCredLaneDatabase';
```

**Comment by gohanman** [comment]
Ah. The namespace you've added means that file **doesn't** contain `CCredProgramsModel`, it contains `COREPOS\pos\lib\models\op\CCredProgramsModel`. And the autoloader is expecting to find it in `pos/is4c-nf/lib/models/op/`.

You probably want to not use a namespace statement in that file at all or use the namespace that corresponds to that location `COREPOS\pos\plugins\CoopCred\models`.

**Comment by flathat** [comment]
Thank you. `CCredLib.php` needs:
```PHP
use COREPOS\pos\lib\ReceiptLib;
use COREPOS\pos\plugins\CoopCred\models\CCredProgramsModel;
```
for `$ccpModel = new CCredProgramsModel($conn);`
and
`models/CCredProgramsModel.php` needs (`namespace` is not optional):
```PHP
namespace COREPOS\pos\plugins\CoopCred\models;
use COREPOS\pos\lib\models\BasicModel;
```
