### ISSUE TITLE
patch  housekeeping

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#923]
* Version of CORE? n/a

* Issue with Office, Lane, or both? n/a

* Is this [mostly] a bug report, feature request, or question? Question -- Housekeeping

Since `flathat-patch-4` has been merged is it my responsibility to delete the patch?  Did `flathat-patch-3`, which was also merged earlier today, disappear by itself or was it removed manually?

**Comment by gohanman** [comment]
I noticed a little indicator on the 2nd merge saying "you can delete this branch now" and clicked it. I probably just missed it the other time. I'm not super concerned about pruning branches after merges. I should probably consistently delete them on merge but there's not a giant mess of need-to-be-deleted branches at present.
