### ISSUE TITLE
Trouble understanding AutoLoader include error

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#924]
* Version of CORE? upgrading to 2.7

* Issue with Office, Lane, or both? Lane

* Is this [mostly] a bug report, feature request, or question? question

I'm having trouble understanding what this error is about, what I should be looking at. How did that wrong-looking path get built?

Sep 13 17:28:16 x.y.coop corepos[30070]: (debug) include_once(): Failed opening '/var/www/IS4C/pos/is4c-nf/lib/../lib/ReceiptBuilding/ThankYou/COREPOS/pos/lib/ReceiptBuilding/ThankYou/DefaultReceiptThanks.php' for inclusion (include_path='/var/www/IS4C/vendor/phpunit/php-file-iterator:.:/usr/share/php:/usr/share/pear') Line 100, /var/www/IS4C/pos/is4c-nf/lib/AutoLoader.php
```PHP
// AutoLoader.php
        if (isset($map[$name]) && !class_exists($name,false)) {
            $included = include_once($map[$name]);  //L#100
            if ($included === false) {
                unset($map[$name]);
                CoreLocal::set('ClassLookup', $map);
            }
        }
```
`lib/ReceiptBuilding/ThankYou/DefaultReceiptThanks.php` exists:
```PHP
namespace COREPOS\pos\lib\ReceiptBuilding\ThankYou;
use \CoreLocal;

/**
  @class DefaultReceiptThanks
  Prints thank you line(s)
*/
class DefaultReceiptThanks

```

**Comment by gohanman** [comment]
a26c785ca9f079e95192c3e2cc131579f238b16d

In the interest of backward compatibility, a namespace gets appended to an existing config setting like `DefaultThankYou` translating it to the correct `COREPOS\pos\lib\ReceiptBuilding\ThankYou\DefaultThankYou`. This really needs to check whether the config setting has itself been updated to include a namespace. Appending one then produces a lengthy `COREPOS\pos\lib\ReceiptBuilding\ThankYou\COREPOS\pos\lib\ReceiptBuilding\ThankYou\DefaultThankYou`. This results in an attempt to include a non-existent file.

AFAIK this just causes the warning & extra file system op. It'll still locate & load the class specified w/ namespace in the config setting.
