### ISSUE TITLE
Constructor cannot be static

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#927]
* Version of CORE? upgrading to 2.7

* Issue with Office, Lane, or both? Both

* Is this [mostly] a bug report, feature request, or question? Question.

I've upgraded my development server which uses `PHP 5.4.39` but in taking the code to the production server which uses `PHP 5.3.2` I find that `common/ErrorHandler.php` won't pass `php -l`:
 Constructor COREPOS\common\ErrorHandler::errorHandler() cannot be static in /var/www/IS4C/common/ErrorHandler.php on line *n* (end of class)

I've read that it may be possible to work around this, possibly by using a `__construct` or changing the name of `errorHandler()` to not match the `class` name.  I tried something I thought might be like that but get an error:   
` Non-static method COREPOS\\common\\ErrorHandler::errorHandler() cannot be called statically`  
pointing to `set_error_handler(array($class,'errorHandler'));`, which I don't understand.

Might there be more trouble with this old `PHP`?  I don't know whether it can be upgraded in the version of `Ubuntu` on this server.  I have to put things back together for the work day now.

**Comment by gohanman** [comment]
Sounds like yes, the old version is a problem. PHP's general documentation on constructors says
>As of PHP 5.3.3, methods with the same name as the last element of a namespaced class name will no longer be treated as constructor. This change doesn't affect non-namespaced classes.

I know [this](https://launchpad.net/~ondrej/+archive/ubuntu/php) is the general source for "newer than Ubuntu-packaged PHP" versions. I don't know off hand if 10.04 packages are even in the repo anymore though.

**Comment by flathat** [comment]
I was able to get PHP 5.3.3 from [chris-lea](https://launchpad.net/~chris-lea/+archive/ubuntu/php5.3.3); that site also has a `PHP 5.3.6` which I haven't tried, but not `PHP 5.4`.

After adding `deb http://ppa.launchpad.net/chris-lea/php5.3.3/ubuntu lucid main` to the top of `/etc/apt/sources.list` 
the `sudo apt-get update` and `sudo apt-get upgrade` sequence went without error but the new version wasn't installed as I expected it to be.

I found this page about [upgrading a single package](https://askubuntu.com/questions/44122/how-to-upgrade-a-single-package-using-apt-get) pertinent (`apt-get install` does an upgrade if another version of the package is already installed) and following that:

```
$ sudo apt-cache policy php5
php5:
  Installed: 5.3.2-1ubuntu4.28
  Candidate: 5.3.3-8ubuntu12~lucid1
  Version table:
     5.3.3-8ubuntu12~lucid1 0
        500 http://ppa.launchpad.net/chris-lea/php5.3.3/ubuntu/ lucid/main Packages
     5.3.2-1ubuntu4.30 0
        500 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ lucid-updates/main Packages
...

$ sudo apt-get install php5=5.3.3-8ubuntu12~lucid1

# and now
$ php --version
PHP 5.3.3-8ubuntu12~lucid1 with Suhosin-Patch (cli) (built: Jan 26 2011 20:50:36)
```
So yes I never should have allowed Ubuntu to get so out of date, but I'm over the static constructor hump and on to testing my `CORE 2.7`, so far going fairly well.
