### ISSUE TITLE
PHP Version Minimum, Part II

### ISSUE THREAD

**Issue by gohanman** [CORE-POS/IS4C#928]
* Version of CORE?
2.7

* Issue with Office, Lane, or both?
both

* Is this [mostly] a bug report, feature request, or question?
Question / Discussion

It's been a bit over a year since the project called PHP 5.5 [minimum supported version](https://github.com/CORE-POS/IS4C/wiki/Supported-PHP-Versions) and probably about time for some planning again. End of life for Ubuntu 14.04 LTS, the only major distro I know of on 5.5.x,  is coming in April 2019 which is still a ways off but not **that far** off.

PHP 5.6.x is losing support from PHP itself a bit earlier in December 2018. Some long-term-stable oriented distros will surely support it longer but maybe not lots longer. The latest Ubuntu LTS (16.04) and Debian stable (stretch) have both moved on to 7.0. My sense is that the traditional backporting of security fixes approach is going to be more difficult given significant differences between 5.6 and 7+. Folks on 5.6 going into 2019 will probably be in a bit less than ideal security situation.

This isn't super pressing yet but in the next year or so we should be ready to jump to 7.0 or higher. I don't think this is going to be terribly difficult from a code standpoint. I have a few lanes running on 7.1 without issue. But based on last time around migration strategies are going to be important.

----

Upgrading an entire distro can be a pain in the neck and while that will inevitably be necessary there are some ways to streamline.

#### Don't use mod_php; use fpm, fcgi, fastcgi, etc
With Apache `mod_php` is still often the out-of-the-box default. While this mostly works fine one thing you **cannot** do with `mod_php` is have multiple versions of PHP installed easily. With all the CGI variants where PHP runs as a separate service you can have several PHP services and point the Apache (or Nginx) configuration at whichever one you want to use. This provides more flexibility to install 3rd-party PHP builds or build a newer version yourself while still being able to go back to the distro-provided default version is everything goes awry.

One thing here that's specific to CORE if you use a 3rd party distro or compile your own PHP binary from source is that cron has a limited and often different shell. CORE's tasks by default just say `php script.php`. If your latest & greatest binary is `/usr/local/bin/php` or `/usr/bin/php-7` cron might very well use `/usr/bin/php` instead. This is easy to fix with `crontab -e` and a quick find & replace but using the built-in web UI from managing tasks will have some hiccups and reversals. In practice tasks don't get changed that often after install so if the previous paragraph didn't scare you off this part should be entirely manageable.

#### Put MySQL and the web server on separate machines, physically or virtually
With this setup, you have more flexibility to add another machine, again physically or virtually, with a newer OS and PHP version. This provides for a smooth transition from one OS version to the next without downtime and again with the ability to go back if the new OS proves problematic.

This is not necessarily a simple thing to do on an existing monolithic setup. Given enough spare disk space (I'd guess 20GB or so is sufficient) it'd probably be possible to install KVM (or maybe Xen; haven't tried it), create a virtual machine, and set up the VM as just a web server. I don't think there's necessarily much value in trying to lift MySQL off the bare metal and into a separate VM. But adding a 2nd VM at a later date to test a newer web server OS would be possible.

#### Pick a distro that supports in-place upgrades
This is a little scarier since there's always the possibility something goes horribly wrong, but the mainstream distros are thoroughly tested enough that the odds of catastrophe are pretty low. In any event it's a better place to be than stuck on a distro that can't upgrade in place.

**Comment by roberski** [comment]
As of 2/26/18 I am running CORE at both stores.
With the fresh install at my main store I just went with all the default Ubuntu 16.04 versions of everything I'm running the Office on php 7.0 and have seen no issue from that aside from having to figure out all the new config files and having to manually install curl and the sqlite3 extensions for php7 manually.

To get replication working I had to upgrade my older server from ubuntu 12.04 to 16.04 mostly so I could run mysql 5.7 because I guess mysql doesn't like replication between large version differences.
The upgrade went almost as well as the fresh install again with a few config errors, mostly around extensions.

Overall the mysql upgrade was worse but not too awful.

My lanes are all still on php5.6 and  I wish I had gone with 7. If I was faced with upgrading my lanes I would probably just dump the databases and do a totally fresh install with php7.

**Comment by gohanman** [comment]
Thanks for passing that along. I haven't run anything on 7.0 specifically; just some lanes on 7.1.

**Comment by gohanman** [comment]
Update: I've got a backend running on 7.0 now too. The switch was entirely uneventful.

**Comment by gohanman** [comment]
I updated the requirement on the wiki to 7+. Everything front end and back end definitely works on PHP7 at this point. I'd guess everything still works in 5.6 or probably even 5.3 but the documented advice should definitely be 7+ now.
