### ISSUE TITLE
class PartialBatchesModel extends \COREPOS\common\BasicModel fails

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#931]
* Version of CORE? 2.7

* Issue with Office, Lane, or both? Office

* Is this [mostly] a bug report, feature request, or question? bug and/or question

If `models/op/PartialBatchesModel.php` has `class PartialBatchesModel extends \COREPOS\common\BasicModel`
```
$ php ./BasicModel.php --update core_op op/PartialBatchesModel.php
PHP Fatal error:  Call to a member function isConnected() on a non-object in /var/www/IS4C/common/BasicModel.php on line 868
ubuntu@pos:/var/www/IS4C/fannie/classlib2.0/data/models$ vi op/PartialBatchesModel.php
```
but OK if ` ... extends BasicModel` like all of the other `op/*Model.php`s.

(I wish I understood namespaces well enough to know why this is so.)

**Comment by gohanman** [comment]
It's really not specific to namespaces. If `COREPOS\common\BasicModel` was instead named `ParentModel` the issue would be the same. The parent class doesn't know anything about Fannie or Lane specific functions needed to actually establish a database connection.
