### ISSUE TITLE
Office Install doesn't create databases

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#936]
* Version of CORE? 2.7.0

* Issue with Office, Lane, or both? Office

* Is this [mostly] a bug report, feature request, or question? Question at this point.

In `InstallIndexPage.php` after entering host and MySQL user and password, saving configuration, and then saving configuration again, for all of `core_op`, `core_trans` and `trans_archive` it reports `DB connection failed`. `USER_PRIVILEGES` shows the user at the connection having the `CREATE` privilege. If I use phpMyAdmin as the same user I can create those databases, and after I do then `InstallIndexPage` creates the tables.  The only error reported, twice for each database is:
`[2017-10-13 02:12:00] fannie.DEBUG: mysqli_real_connect(): (HY000/1049): Unknown database 'core_trans' Line 124, /var/www/IS4C/common/adodb5/drivers/adodb-mysqli.inc.php [] []`

It seems that the call to `db_test_connect(...$FANNIE_X_DB...)` in `InstallIndexPage` should eventually execute `SQLManager->connectAndCreate(...$database...)`. (It would be helpful to have a comment at `db_test_connect()` if that is what is supposed to happen.)

What might be missing in the way this is set up?

**Comment by gohanman** [comment]
It strikes me as more of a bug that `connectAndCreate` doesn't do what it says.
