### ISSUE TITLE
Gift cards

### ISSUE THREAD

**Issue by otc-narendra** [CORE-POS/IS4C#939]
* Version of CORE? 2.7

* Issue with Office, Lane, or both? Lane

* Is this [mostly] a bug report, feature request, or question? Question

Wondering if anyone has had any experience with a gift card system well integrated with CORE. Ideally I'm looking for something where I can issue a physical or electronic gift card with integrated processing in the POS checkout process. We use Vantiv for our integrated card processing.

**Comment by gohanman** [comment]
Vantiv does physical gift cards. I imagine you can just call them and order an initial batch of cards. I've never been directly involved with that piece but the gift cards do work fine with CORE.
