### ISSUE TITLE
Default db in spanning view definitions

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#942]
* Version of CORE? 2.7

* Issue with Office, Lane, or both? Office

* Is this [mostly] a bug report, feature request, or question? Bug, or problem, at least in some situations.

It seems that in at least some situations, perhaps an old MySQL version such `5.1.73` in my case, when a spanning view such as `core_trans`.`ar_live_balance` is created, tables or views referred to _after_ a table or view in the "other" database is referred to are assumed to be in the "other" database, thus in `ArLiveBalanceModel` `CREATE VIEW AS`:
```
            SELECT   
                c.CardNo AS card_no,
                (CASE WHEN a.charges IS NULL THEN 0 ELSE a.charges END)
                    + (CASE WHEN t.charges IS NULL THEN 0 ELSE t.charges END)
                    AS totcharges,
                (CASE WHEN a.payments IS NULL THEN 0 ELSE a.payments END)
                    + (CASE WHEN t.payments IS NULL THEN 0 ELSE t.payments END)
                    AS totpayments,
                (CASE WHEN a.balance IS NULL THEN 0 ELSE a.balance END)
                    + (CASE WHEN t.balance IS NULL THEN 0 ELSE t.balance END)
                    AS balance,
                (CASE WHEN t.card_no IS NULL THEN 0 ELSE 1 END) AS mark
            FROM ' . $custdata . ' AS c
                LEFT JOIN ar_history_sum AS a ON c.CardNo=a.card_no AND c.personNum=1
                LEFT JOIN ar_history_today_sum AS t ON c.CardNo = t.card_no AND c.personNum=1
            WHERE c.personNum=1
```
if `$custdata` is `core_op.custdata` the `JOIN` on `ar_history_sum` fails because MySQL is looking for it in `core_op` instead of `core_trans` and the `VIEW` isn't created.

It would be safer if the "later" table and view names were qualified with the db name.

(An aggravating factor is that `InstallMembershipPage.php` runs into this just by displaying the page, not submitting changes, so one isn't on the lookout for problems.  I don't recall seeing the error reported on the page, although it is logged.)

I ran into the problem working on an upgrade, but it seemed not to happen any more in later uses of the page, so I don't have a clear way to reproduce it.  It did apparently happen again after the upgrade was ported to another server and someone used `InstallMembershipPage`.

**Comment by gohanman** [comment]
> It seems that in at least some situations, perhaps an old MySQL version such 5.1.73 in my case, when a spanning view such as core_trans.ar_live_balance is created, tables or views referred to after a table or view in the "other" database is referred to are assumed to be in the "other" database, thus in 

To the best of my knowledge this is simply not the case in any realistic version of MySQL. A bare table or view name is assumed to be in the current connection default database as specified by the last `USE` statement. MySQL's documentation is consistent on this back to 4.1 which is the oldest version I can find docs for. It's since something, somewhere, called `USE core_op` prior to that query. Since the connection state is effectively global it's difficult to speculate what exactly without a way to reproduce it.

> (An aggravating factor is that InstallMembershipPage.php runs into this just by displaying the page, not submitting changes, so one isn't on the lookout for problems. I don't recall seeing the error reported on the page, although it is logged.)

It definitely ought to be reported. The views get rebuilt whenever the page loads because the configured AR and/or equity departments might have changed. Theoretically this could happen outside the UI on that page. Breaking on submitted changes only isn't really much better IMO. It needs to work correctly either way.

**Comment by flathat** [comment]
Running `InstallMembershipPage.php` now does not fail, but this is what was logged when it did, with context of the run of `InstallMembershipPage.php`.  

Note that the `DROP VIEW ar_live_balance` that precedes the `CREATE` is not reported as failing, which suggests the current db was correct at that moment, whereas the next instruction `DROP VIEW stock_sum_today` does fail, although it doesn't say in which db it assumes it is.:
```
Sep 18 03:52:09 ip-10-245-226-26 fannie[26046]: (debug) Declaration of EquityRefund::SaveFormData() should be compatible with that of COREPOS\Fannie\API\member\MemberModule::saveFormData() Line 187, /var/www/IS4C/fannie/mem/modules/EquityRefund.php
Sep 18 03:52:09 ip-10-245-226-26 fannie[26046]: (debug) Declaration of Prepay::SaveFormData() should be compatible with that of COREPOS\Fannie\API\member\MemberModule::saveFormData() Line 187, /var/www/IS4C/fannie/mem/modules/Prepay.php
Sep 18 03:52:09 ip-10-245-226-26 fannie[26046]: (debug) Declaration of StoreCharge::SaveFormData() should be compatible with that of COREPOS\Fannie\API\member\MemberModule::saveFormData() Line 299, /var/www/IS4C/fannie/mem/modules/StoreCharge.php
Sep 18 03:52:09 ip-10-245-226-26 fannie[26046]: (debug) Declaration of AR_newer::SaveFormData() should be compatible with that of COREPOS\Fannie\API\member\MemberModule::saveFormData() Line 99, /var/www/IS4C/fannie/mem/modules/AR_newer.php
Sep 18 03:52:09 ip-10-245-226-26 fannie[26046]: (debug) Failed Query on /IS4C/fannie/install/InstallMembershipPage.php
CREATE VIEW `ar_live_balance` AS
            SELECT
                c.CardNo AS card_no,
                (CASE WHEN a.charges IS NULL THEN 0 ELSE a.charges END)
                    + (CASE WHEN t.charges IS NULL THEN 0 ELSE t.charges END)
                    AS totcharges,
                (CASE WHEN a.payments IS NULL THEN 0 ELSE a.payments END)
                    + (CASE WHEN t.payments IS NULL THEN 0 ELSE t.payments END)
                    AS totpayments,
                (CASE WHEN a.balance IS NULL THEN 0 ELSE a.balance END)
                    + (CASE WHEN t.balance IS NULL THEN 0 ELSE t.balance END)
                    AS balance,
                (CASE WHEN t.card_no IS NULL THEN 0 ELSE 1 END) AS mark
            FROM core_op.custdata AS c
                LEFT JOIN ar_history_sum AS a ON c.CardNo=a.card_no AND c.personNum=1
                LEFT JOIN ar_history_today_sum AS t ON c.CardNo = t.card_no AND c.personNum=1
            WHERE c.personNum=1

Table 'core_op.ar_history_sum' doesn't exist

Sep 18 03:52:09 ip-10-245-226-26 fannie[26046]: (debug) Failed Query on /IS4C/fannie/install/InstallMembershipPage.php
DROP VIEW stockSumToday
Unknown table 'stockSumToday'

Sep 18 03:52:09 ip-10-245-226-26 fannie[26046]: (debug) Failed Query on /IS4C/fannie/install/InstallMembershipPage.php
CREATE VIEW `equity_live_balance` AS
            SELECT
                m.card_no AS memnum,
                CASE
                    WHEN a.card_no IS NOT NULL AND b.card_no IS NOT NULL
                    THEN a.payments + b.totPayments
                    WHEN a.card_no IS NOT NULL
                    THEN a.payments
                    WHEN b.card_no IS NOT NULL
                    THEN b.totPayments
                END AS payments,
                CASE WHEN a.startdate IS NULL THEN b.startdate
                    ELSE a.startdate END AS startdate
            FROM core_op.meminfo AS m
                LEFT JOIN equity_history_sum AS a ON a.card_no=m.card_no
                LEFT JOIN stockSumToday AS b ON m.card_no=b.card_no
            WHERE a.card_no IS NOT NULL
                OR b.card_no IS NOT NULL

Table 'core_op.equity_history_sum' doesn't exist
```

**Comment by gohanman** [comment]
It'd guess that something switched the connection to core_op. If it did you probably have a `stockSumToday` view in core_op. The `DROP` failed but the `CREATE` should still have worked.

Calling `$dbc->tableExists('core_op.custdata')` is going to alter the connection state. What ADOdb will actually do is:
```sql
USE core_op;
SHOW COLUMNS FROM custdata;
USE core_trans;
```

I haven't been able to reproduce the problem, but something going wrong in this SQL sequence seems like the most likely candidate to have altered the connection state. Is this happening with mysql, mysqli, or pdo?

**Comment by flathat** [comment]
On my test server, where `ar_live_balance` was being `CREATEd`, `$FANNIE_SERVER_DBMS = 'MYSQL';`.  The production server has `MYSQLI`.  Changing test to `MYSQLI` made it fail, and restoring to `MYSQL` made it succeed again.  It also fails on the test server with `PDO_MYSQL`, same error.

**Comment by gohanman** [comment]
That's odd. It succeeds on my own servers using both `MYSQLI` and `PDO_MYSQL`. It also consistently succeeds in the CI test environment with both those drivers.

Do you have a `vendor/adodb` folder? That could be the culprit.

**Comment by flathat** [comment]
Yes, `IS4C/vendor/adodb/` on both servers. Files in it date from April, 2015.

**Comment by gohanman** [comment]
Aha. That's probably it then. That was removed 507474640f3800a9bb732581e184d57569033716 from the required packages but I don't think I have a way to force anyone else to uninstall it. I **think** running `composer install` will remove it.

**Comment by flathat** [comment]
`"adodb/adodb-php": "^5.20"` and `"everyman/neo4jphp": "dev-master"` were not in `composer.json`.
```
$ install composer
ubuntu@posdev:IS4C$ composer install
Warning: This development build of composer is over 60 days old. It is recommended to update it by running "/usr/local/bin/composer self-update" to get the latest version.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for itgalaxy/bmp2image 2.0.0 -> satisfiable by itgalaxy/bmp2image[2.0.0].
    - itgalaxy/bmp2image 2.0.0 requires php ^5.6 || ^7.0 -> your PHP version (5.4.39-1+deb.sury.org~lucid+2) or "config.platform.php" value does not satisfy that requirement.
  Problem 2
    - Installation request for symfony/config v3.1.5 -> satisfiable by symfony/config[v3.1.5].
    - symfony/config v3.1.5 requires php >=5.5.9 -> your PHP version (5.4.39-1+deb.sury.org~lucid+2) or "config.platform.php" value does not satisfy that requirement.
 [... and five more similar Problems with symfony modules]
```
Under this version of Ubuntu I can't upgrade PHP beyond what it is.  Are those `symfony` modules needed?

Might the recommended `composer self-update` make things still worse?

**Comment by gohanman** [comment]
I don't know if self-update would make things worse but I doubt it'll help make anything better. The PHP version still isn't going to be supported by those packages.

You could try running `composer dump-autoload`. That might regenerate the autoload info **without** any version checks. Or you could manually excise the adodb reference from `vendor/composer/autoload_files.php`.

**Comment by flathat** [comment]
I did the latter:
```php
<?php
// autoload_files.php @generated by Composer
$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);
return array(
    $vendorDir . '/kriswallsmith/assetic/src/functions.php',
//    $vendorDir . '/adodb/adodb-php/adodb.inc.php',
);
```
and now the re-generation of `ar_live_balance` and `equity_live_balance` by `InstallMembershipPage.php` are OK.
