### ISSUE TITLE
Scanner/scale ESC/POS dialects, other gotchas?

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#958]
Continuing to think about the current [supported hardware list](https://github.com/CORE-POS/IS4C/wiki/Supported-Hardware)...

Who out there is using the Magellan SL384? Who’s using the 8100? The 8300? The 8500?

Do they speak the same dialects of ESC/POS, or are there translation issues when one switches scanner/scale models?

I’m most interested in differences between the SL384 and later models — but any and all experiences would be informative!

* Version of CORE?
All

* Issue with Office, Lane, or both?
Lane

* Is this [mostly] a bug report, feature request, or question?
Question

**Comment by gohanman** [comment]
I've personally only worked with 8500s and 8400s but the communication protocol is byte-for-byte identical. I've seen documentation strongly implying that NCR scanner-scales can be configured to use the same protocol, too, but I've never had access to hardware to verify it. Based on the product manual the newer 9800i appears to support the same protocol, too.

It's not ESC/POS though. That's Epson's printer control language.

**Comment by flathat** [comment]
West End Food Co-op uses one SL384 and one 8400, with the 8400 having been moved between lanes, and there has been no difference in scanning or weighing behaviour, no need or desire to tweak communication with the s/s.

**Comment by joelbrock** [comment]
I've never had any issues with any Magellan model.  Includes: SL series,
8100, 8200, 8400, 8500, and 8500xt.
Specifically i've not had any issue when replacing failing SL384s with
newer 8X00s.  So long as the new scales are programmed properly before
making the switch.

**Comment by scannerdarkly** [comment]
Sorry @gohanman, you’re right of course that it’s not ESC/POS!

It’s very encouraging that y’all have experience with this and that they’re so swappable. Are there any **other** types of gotchas when swapping scanner/scale models? Other than dimensional differences, of course...

**Comment by gohanman** [comment]
I don't think so. Making sure they're configured for RS-232 single cable and appropriate STX, ETX, etc is necessary but it's theoretically necessary with two identical-model scales, too.
