### ISSUE TITLE
Upgrades: Major versions? Skipping versions?

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#961]
Is upgrading major versions (e.g. 1.10 → 2.0) any more perilous than minor versions? Any additional precautions one should take when the first digit is changing?

Also, is skipping versions (e.g. 2.0 straight to 2.7) a very good idea, a very bad idea, or somewhere in between?

* Version of CORE?
all

* Issue with Office, Lane, or both?
both

* Is this [mostly] a bug report, feature request, or question?
question

**Comment by gohanman** [comment]
> Is upgrading major versions (e.g. 1.10 → 2.0) any more perilous than minor versions? Any additional precautions one should take when the first digit is changing?

Not particularly. The "big" change in 2.0 is support for multiple stores but it's an optional addition.

> Also, is skipping versions (e.g. 2.0 straight to 2.7) a very good idea, a very bad idea, or somewhere in between?

Skipping is probably easier. Fixes that are backported into version branches could turn into conflicts trying to merge them sequentially.

**Comment by scannerdarkly** [comment]
So 1.10 → 2.8 wouldn’t actually be a bad upgrade path?
