### ISSUE TITLE
Versions: What’s everyone using right now?

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#962]
* Version of CORE?
all

* Issue with Office, Lane, or both?
both

* Is this [mostly] a bug report, feature request, or question?
question

**Comment by gohanman** [comment]
2.8-dev (or within a couple commits of `HEAD` at any given moment).

**Comment by joelbrock** [comment]
Currently supporting CORE-POS installations that range from 1.8 up to 2.7

**Comment by scannerdarkly** [comment]
@joelbrock, is there a median version to this spread of versions you’re supporting? One that’s significantly more prevalent than the others (which I guess would actually make it the “mode”, statistically speaking...)?

**Comment by joelbrock** [comment]
Hrm.  I'd say the mid- to upper-2s.   We definitely _try_  not to let too much time elapse btwn software upgrades.  The main reason for this being that it is generally a smoother process to do smaller version bumps on an in-production POS.
