### ISSUE TITLE
Install/Receipt Footer modules display

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#965]
Minor issue, but the footer mods dont show up in install GUI, the values ARE present in `opdata.parameters` so this seems pretty trivial.  Here 2 footer mods are assigned, hence the 3 dropdowns.
![image](https://user-images.githubusercontent.com/52835/28632975-363e35b4-7200-11e7-8fbd-b7eb15c8ecf5.png)

Noticed in versions as recent as 2.7

**Comment by gohanman** [comment]
Huh. I'm not able to replicate this at all. Both current and 2.7 show footer modules names fine. Are the dropdowns empty or populated but not selecting the right value?

**Comment by joelbrock** [comment]
Dropdowns are populated.

**Comment by gohanman** [comment]
Ah, sorry. I was looking at the Footers section on the Extras tab. The fix here is simple.

I did come across a slightly different issue that if you have a *lot* of these receipt modules enabled it can exceed the 255 character limit of `param_value`. Widening the field is a simple enough fix but it'll ever so slightly bump the minimum supported MySQL version.
