### ISSUE TITLE
Recommended method to submit code suggestions?

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#967]
I’ve made some relatively minor changes (in this case, to `LaneTrimTask.php`) which I believe would slightly improve the shared codebase. More informative error messages, in this case.

What’s the best way to submit them?

I’ve been trying to create a pull request branch in my local copy of CORE-POS/IS4C, but git seems reluctant to create a pull request from my branch. Not sure what I’m missing.

* Version of CORE?
all

* Issue with Office, Lane, or both?
all

* Is this [mostly] a bug report, feature request, or question?
question

**Comment by gohanman** [comment]
A pull request would definitely be the preferred mechanism. What exactly are you seeing?

**Comment by scannerdarkly** [comment]
1. My local repo was initially generated by `git clone https://github.com/CORE-POS/IS4C.git version-2.7`.
2. I created a new local branch for the pull request by `git checkout -b pull-request`.
3. I made edits to local `fannie/cron/tasks/LaneTrimTask.php`.
4. I added and committed those edits (`5c056668504ad97e2347e1001ef53ff23cf27a0b`) to the local repo.
5. (This is where I can’t figure out what to do. I want @gohanman to be able to see a pull request with this one commit.)

Running some status commands:
> $ git remote show origin
> \* remote origin
>&nbsp;&nbsp; Fetch URL: https://github.com/CORE-POS/IS4C.git
>&nbsp;&nbsp; Push&nbsp;&nbsp;URL: https://github.com/CORE-POS/IS4C.git
>&nbsp;&nbsp; HEAD branch: master
>&nbsp;&nbsp; Remote branches:
>&nbsp;&nbsp;&nbsp;&nbsp; gh-pages&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; tracked
>&nbsp;&nbsp;&nbsp;&nbsp; master&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; tracked
>&nbsp;&nbsp;&nbsp;&nbsp; shrink-editor&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tracked
>&nbsp;&nbsp;&nbsp;&nbsp; sync-products-notinUse tracked
>&nbsp;&nbsp;&nbsp;&nbsp; touch-numpad&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; tracked
>&nbsp;&nbsp;&nbsp;&nbsp; version-1.10&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; tracked
>&nbsp;&nbsp;&nbsp;&nbsp; version-1.2&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tracked
>&nbsp;&nbsp;&nbsp;&nbsp; version-1.3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tracked
>&nbsp;&nbsp;&nbsp;&nbsp; version-1.4&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tracked
>&nbsp;&nbsp;&nbsp;&nbsp; version-1.5&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tracked
>&nbsp;&nbsp;&nbsp;&nbsp; version-1.6&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tracked
>&nbsp;&nbsp;&nbsp;&nbsp; version-1.7&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tracked
>&nbsp;&nbsp;&nbsp;&nbsp; version-1.8&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tracked
>&nbsp;&nbsp;&nbsp;&nbsp; version-1.9&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tracked
>&nbsp;&nbsp;&nbsp;&nbsp; version-2.0&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tracked
>&nbsp;&nbsp;&nbsp;&nbsp; version-2.1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tracked
>&nbsp;&nbsp;&nbsp;&nbsp; version-2.2&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tracked
>&nbsp;&nbsp;&nbsp;&nbsp; version-2.3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tracked
>&nbsp;&nbsp;&nbsp;&nbsp; version-2.4&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tracked
>&nbsp;&nbsp;&nbsp;&nbsp; version-2.5&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tracked
>&nbsp;&nbsp;&nbsp;&nbsp; version-2.6&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tracked
>&nbsp;&nbsp;&nbsp;&nbsp; version-2.7&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tracked
>&nbsp;&nbsp;&nbsp;&nbsp; version-2.8&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tracked
>&nbsp;&nbsp; Local branch configured for 'git pull':
>&nbsp;&nbsp;&nbsp;&nbsp; version-2.7 merges with remote version-2.7
>&nbsp;&nbsp; Local ref configured for 'git push':
>&nbsp;&nbsp;&nbsp;&nbsp; version-2.7 pushes to version-2.7 (fast-forwardable)

> $ git branch
> \* pull-request
>   version-2.7

> $ git status
> On branch pull-request
> You are currently cherry-picking commit 5c05666.
>   (all conflicts fixed: run "git cherry-pick --continue")
>   (use "git cherry-pick --abort" to cancel the cherry-pick operation)
>
> nothing to commit, working directory clean

**Comment by gohanman** [comment]
With github's model you'd have to work from a fork, e.g. https://github.com/scannerdarkly/IS4C.git. Then you can push your local branch up to your fork and PR back to here.

**Comment by scannerdarkly** [comment]
Ah, okay. That fork would have to be hosted on GitHub?

**Comment by scannerdarkly** [comment]
When making the edits to my fork, is it preferred that I edit in an older branch (e.g. 1.10-dev), a current branch (e.g. 2.7), or master?

**Comment by gohanman** [comment]
PRs are generally only going to be accepted against master.

**Comment by scannerdarkly** [comment]
Is there any generally accepted approach for getting code backported into a previous release branch?

Do you accept cartons of cigarettes as a bribe? :)

**Comment by gohanman** [comment]
Not really. The only further commits to release branches are bug fixes.
Even then unless the fix is extremely tiny it needs to target master first
for testing & verification before getting backported. Whether fixes go back
further than the most recent release basically depends how cleanly the fix
fits into the older release.

It's ultimately a resources thing. Supporting several different releases
isn't feasible long-term. Being consistent about what is and is not brought
backward is better than being haphazard.

**Comment by scannerdarkly** [comment]
Totally understandable, thanks.
