### ISSUE TITLE
ProductsModel does not match the schema but cannot be updated

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#970]
Just upgraded from version-1.10dev to version-2.7, and running the install pages I see the following from the Schema Updates page. Any thoughts what I should do?
```
COREPOS\pos\lib\models\op\ProductsModel does not match the schema but cannot be updated. Details

==========================================
Checking table core_opdata.products
==========================================
Ignoring unknown column: created in current definition (delete manually if desired)
==========================================
Check complete. Need to adjust 0 columns.
==========================================
```

* Version of CORE?
2.7

* Issue with Office, Lane, or both?
lane

* Is this [mostly] a bug report, feature request, or question?
bug report

**Comment by gohanman** [comment]
It's addressed in 2.8 52c990b408285c853b9d58225b7b786b69ae0404

From a practical standpoint it doesn't matter at all. The lane doesn't used `created` for anything and works fine with or without it. Making this particular message go away is the only effect of the change.

**Comment by scannerdarkly** [comment]
Good to know, thanks! Does this message only show up on the DB Updates page, or will the error logs also be filling up with this message (or something similar)?

**Comment by gohanman** [comment]
Just on that page.

**Comment by scannerdarkly** [comment]
Thanks again!
