### ISSUE TITLE
Update seems not to be reading “scanner” and “scale” files

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#971]
George Street is using our own ssd which uses a configuration file (ssd.conf) to set its port, log levels and files, and output files. Right now it’s configured to output to “scanner” and “scale” (in the rs232 directory), which I believe is what CORE-POS generally expects. Permissions on those two files are `rw-rw-rw-`, and they’re changing with each new scan or weigh, just as expected.

The POS, however, doesn’t seem to detect any scans ~~or weighs~~. (**CORRECTION**, it is actually detecting weights no problem — but scans are ignored.)

What’s going to be the most efficient way to troubleshoot this?

* Version of CORE?
2.7

* Issue with Office, Lane, or both?
lane

* Is this [mostly] a bug report, feature request, or question?
bug report

**Comment by gohanman** [comment]
I'm not entirely sure. I've never used ssd before and can't recall anyone else using it in a long time.

[AjaxPollScale](https://github.com/CORE-POS/IS4C/blob/master/pos/is4c-nf/ajax/AjaxPollScale.php) should be calling [ssd](https://github.com/CORE-POS/IS4C/blob/master/pos/is4c-nf/lib/DriverWrappers/ssd.php) to read the scanner and scale files. Nothing there jumps out at me as obviously wrong.

**Comment by scannerdarkly** [comment]
Actually I’ve misidentified the problem, so I’m going to close this thread and open another with a more accurate title!

**Comment by scannerdarkly** [comment]
Apropos ssd’s apparent obsolescence: NewMagellan works under Ubuntu?

**Comment by joelbrock** [comment]
Yes, it does!  You can see the README file in NewMagellan for instructions on building the driver.
https://github.com/CORE-POS/IS4C/blob/master/pos/is4c-nf/scale-drivers/drivers/NewMagellan/README

**Comment by gohanman** [comment]
FWIW, ssd probably can work if you prefer it. If scale weights worked and scans didn't the culprit is probably #972. Scans go through input parsing and weights don't.

**Comment by scannerdarkly** [comment]
@gohanman that had been my conclusion as well.

@joelbrock I’ll see about mono. Does NewMagellan perform better than ssd that you’re aware of?

**Comment by joelbrock** [comment]
I've never deployed CORE with ssd in production.  My experience with ssd was entirely with IS4C, so i'm not sure I can offer a helpful comparison.  I can attest to NewMagellan performing just great under Ubuntu.

**Comment by gohanman** [comment]
I wouldn't expect any major difference in performance. They both write to files that are then read by a polling AJAX request.
