### ISSUE TITLE
After 2.7 update, all instructions are ignored.

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#972]
The subject line mostly says it — I’ve logged in after updating to version 2.7, and the POS now ignores all typed commands. Anything we type shows up in the `reginput` box, but upon pressing `Enter` the box simply clears out again. The unfortunate result is that we can’t scan items, can’t enter them manually, can’t use Quick Menus, can’t do anything at all.

We can’t even log out. But when the system locks after X minutes of inactivity, it does let us re-enter the password and unlocks again.

Suggestions where to start my troubleshooting efforts?

* Version of CORE?
2.7

* Issue with Office, Lane, or both?
lane

* Is this [mostly] a bug report, feature request, or question?
bug report

**Comment by gohanman** [comment]
It sounds like something's going haywire in parsing inputs. [Parsing Test](https://github.com/CORE-POS/IS4C/blob/master/pos/is4c-nf/test/parsingTest.php) is a good general starting point to see what, if anything, is coming back on entering an input. Usually the culprit would be something errorring out entirely and you'll just get a blank screen, or something echo'ing out extra output such that the result isn't valid JSON. e3c244d605cdfc25ba7a1a778742d1f54f7d7513 might help in the former case if you want to verify logs are written correctly on fatal errors (should cherry-pick cleanly since it's nothing but new files).

There's also a Show AJAX Errors option on the install/debug tab. It's not as verbose as the browser's console but might give some clues what's going wrong.

**Comment by scannerdarkly** [comment]
`http://lane2/lane/ajax/AjaxParser.php?input=cl` returns the message:

`{"error":"Interface 'JsonSerializable' not found (\/CORE-POS\/pos\/is4c-nf\/parser\/ParseResult.php line 15)"}`

(As does any other input)

**Comment by flathat** [comment]
@scannerdarkly 
What version of PHP are you running?  If < `5.4` try this in `pos/is4c-nf/ajax/AjaxParser.php`

```PHP
        /*
         * Account for the absence of the JsonSerializable interface
         *  in the ParseResult object by returning a plain array.
         * Not necessary if using PHP >= 5.4.0 and ParseResult
         * has JsonSerializable.
         */
        if (is_object($json)) {
            $json = $json->toArray();
        }
        return $json;
```

**Comment by scannerdarkly** [comment]
Yeah, I just noticed I’ve got PHP 5.3 on this box. Back in a few...

**Comment by scannerdarkly** [comment]
Does CORE-POS also run well under PHP 5.6?

PHP 7.0?

**Comment by flathat** [comment]
Also, in `pos/is4c-nf/parser/ParseResult.php`
```PHP
class ParseResult implements ArrayAccess, Countable, Iterator, Serializable, JsonSerializable
```
remove `JsonSerializable`

**Comment by flathat** [comment]
Or upgrade PHP, but o/s version may inhibit that, as was my case.

**Comment by scannerdarkly** [comment]
Looks like there’s no repo for php5.5 or php5.6 for Ubuntu 12.04.5 LTS (Precise Pangolin). @flathat, was this your situation as well?

**Comment by flathat** [comment]
Similar, but older.  See #930. Also #827.  Getting to `5.4.0` helps a lot.  I don't remember in detail what is lost/unavailable without later releases.

**Comment by flathat** [comment]
I discovered too late that it is a bad idea to let one's Ubuntu get past end of life because the upgrade resources for it become unavailable.

**Comment by gohanman** [comment]
> Does CORE-POS also run well under PHP 5.6?
> PHP 7.0?

I'm running a mix of 5.6 and 7.1 myself. I don't know of anything specifically problematic about 7.0; just haven't tried it.

You guys have identified the main problem. It'll probably work on 5.4 although nothing gets tested regularly on < 5.5. Building PHP from source is relatively straightforward but 3rd party repos do tend to shutdown as the OS itself passes out of support. Ubuntu's in-place upgrades of the OS itself usually work well. I think running a supported & patched OS is generally a good idea.

**Comment by scannerdarkly** [comment]
Upgrading Ubuntu to 14.04.5 LTS (Trusty Tahr) brought PHP up to 5.5.9, and now things are working again. Thank you both for helping me through this!
