### ISSUE TITLE
Lightweight httpd anyone?

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#974]
Since upgrading from Ubuntu 12 Precise to Ubuntu 14 Trusty (necessitated by upgrading from CORE-POS 1.10dev to 2.7), our lane has slowed down significantly. Especially frustrating are the many-seconds-long stalls, which in my experience are usually problems with memory swapping.

Before replacing our hard drives with SSDs, I’m wondering if we can reduce the overall memory footprint and make disk swapping less necessary. To that end: Has anyone in Linux-land run CORE-POS with an httpd other than Apache?

I’m looking hardest at lighttpd and nginx right now, but I’m open to all suggestions!

* Version of CORE?
2.7

* Issue with Office, Lane, or both?
lane

* Is this [mostly] a bug report, feature request, or question?
question

**Comment by gohanman** [comment]
I'm using nginx albeit on the backend. There shouldn't be any issue with lighttpd either. Nothing's Apache-specific.

That said, my own experience in profiling performance is that the webserver isn't the issue. It's disk usage triggered by CORE itself trying to locate classes. The two biggest speed-ups I've found are:
[Searching fewer places less often](4944ee21ca4e43c9d10e7edb76b22d768ff57bf2) and
[Not searching recursively](862ceaaf064efc71fe8a531ed9ffa9bcdd6a515d)

**Comment by scannerdarkly** [comment]
Also, any general memory-saving Ubuntu/Apache/MySQL/PHP suggestions not covered [here](https://github.com/CORE-POS/IS4C/wiki/Installation#user-content-performance-tuning)?

**Comment by scannerdarkly** [comment]
@gohanman, thanks for replying. Unfortunately those two links seem to be broken.

**Comment by gohanman** [comment]
Sorry, github's markdown parser apparently doesn't handle that

https://github.com/CORE-POS/IS4C/commit/4944ee21ca4e43c9d10e7edb76b22d768ff57bf2
https://github.com/CORE-POS/IS4C/commit/862ceaaf064efc71fe8a531ed9ffa9bcdd6a515d

**Comment by flathat** [comment]
Is it possible to try backporting either or both of those to pre-2.8 lanes?  That is, is there code elsewhere in 2.8 that is needed to support those changes?  By "try" I mean experiment, see if normal operations still work.

**Comment by gohanman** [comment]
I don't believe they depend on anything else. The change to only searching for classes within `plugins` does mean if you have a class that:

* isn't present upstream
* and isn't in `plugins`
* and isn't namespaced

it won't ever discovered or loaded. That's fixable though by giving it a namespace appropriate for its filesystem location.

It also depends how far you're trying to backport. If most lane classes aren't namespaced (< 2.2) then this won't work at all and walking everything is still necessary to find things. Although [this change](https://github.com/CORE-POS/IS4C/blob/master/pos/is4c-nf/lib/AutoLoader.php#L71-L75) could go back to basically anywhere. If a class isn't in the map of known classes, don't rewalk the filesystem trying to find it. Treat it as non-existent until the map is rebuilt on the next sign in.
