### ISSUE TITLE
Cycle in PV search screen

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#977]
It’s the same brand new installation (Ubuntu 16.04.4 LTS / nginx 1.10.3 / mysql 5.7.21 / PHP 7.0.25, CORE-POS 2.7), and `PV` searches are stuck in a loop; no matter what selection we choose, it displays the same search screen again.

Digging into the internals, I’m seeing `FormValueContainer::__construct()` copies values from `$_POST`, then from `$_GET`. This means that if we show the search screen `http://lane2/lane/gui-modules/productlist.php?search=BANANA`, them select the line item “0000000094011” (which transmits through `$_POST`), `productlist::preprocess()` runs its `if (is_numeric($entered) && strlen($entered) == 13)` test on “BANANA” not “0000000094011”, which triggers a repeat search.

I notice that on our older production lane, the URL for a `PV` search screen doesn’t include a `?search=BANANA` component. Is this a clue to where things are going wrong?

* Version of CORE?
2.7

* Issue with Office, Lane, or both?
Lane

* Is this [mostly] a bug report, feature request, or question?
Bug report

**Comment by gohanman** [comment]
This is the larger problem I was referring to in #976. Because your nginx config is somehow breaking [PHP_SELF](https://github.com/CORE-POS/IS4C/blob/version-2.7/pos/is4c-nf/gui-modules/productlist.php#L162) the form posts to `/productlist.php?search=BANANA` instead of to `productlist.php`.

**Comment by gohanman** [comment]
This is fixed in 2.9.0
