### ISSUE TITLE
Blank “Thank You” line?

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#978]
Absent writing a custom (though trivial) module in namespace `COREPOS\pos\lib\ReceiptBuilding\ThankYou`, is there a way to turn off any thank you message from printing?
 

* Version of CORE?
2.7

* Issue with Office, Lane, or both?
Lane

* Is this [mostly] a bug report, feature request, or question?
Question

**Comment by gohanman** [comment]
Nope. The issue's backwards compatibility. Absent a customization the system should do what it always did - in this case, print a thank you message.

**Comment by scannerdarkly** [comment]
Extra thanks for your name choice!
