### ISSUE TITLE
AutoLoader::listModules() skips symlinks

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#979]
For modules which aren’t in the main CORE-POS repo, we’re currently using a strategy of keeping them in our own repo and symlinking to our versions from the appropriate CORE-POS directory. For example, our tender report resides physically outside the CORE-POS tree, but there’s a symlink from `/CORE-POS/pos/is4c-nf/lib/ReceiptBuilding/TenderReports/GeorgeStreetTenderReport.php` to `/CORE-Support/GeorgeStreetTenderReport.php`.

Unfortunately `http://lane/install/extra_config.php`, which uses `AutoLoader::listModules()`, doesn’t list such symlinked scripts as options in the “Tender Report:” dropdown. I can confirm this is solely due to the symlink issue; moving the file into the CORE-POS tree (same location and name, overwriting the symlink) makes it show up.

I can set the needed setting in the database, and it prints just fine — but it would be a great help to have the install scripts directly support symlinks. Any chance this could happen?

* Version of CORE?
2.7

* Issue with Office, Lane, or both?
Lane

* Is this [mostly] a bug report, feature request, or question?
Feature request

**Comment by gohanman** [comment]
I don't think it's possible. `realpath` resolves symbolic links and it'd be difficult to reliably resolve namespaces without that function. Perhaps more importantly dropping custom classes like this into a plugin is the intended solution. Tender report classes **do not** need to be in `/CORE-POS/pos/is4c-nf/lib/ReceiptBuilding/TenderReports`.

**Comment by scannerdarkly** [comment]
Do they need to be in the /CORE-POS tree at all?

**Comment by gohanman** [comment]
I'm not 100% sure. `realpath` does get used to resolve which plugin a given file belongs to, but symlinking a whole directory into `plugins` might be such that all the paths work out.
