### ISSUE TITLE
Where to maintain Product Scores

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#983]
* Version of CORE? 2.8, or any since 30Mar2017

* Issue with Office, Lane, or both? Office

* Is this [mostly] a bug report, feature request, or question? Question, mostly.

I want to maintain "product score" data, an integer in the range 6-30 representing the relative goodness of items in `products`.  The score is calculated from the integer scores in six categories but initially I'm only interested in the single, final number.  The value is mostly for display purposes, would not need to be directly searchable in the sense of `WHERE score < 10`.

Since this is a co-op specific thing I wonder if an Item Maintenance plugin-module using the `ProductAttributes` mechanism of #833 might be the place the keep the value?  Currently, as far as I know, that only holds the booleans of the Flags Module, for example `{"Local":true,"Organic":true,"Fair Trade":false,"Gluten Free":false,"Vegan":true,"Producer-Member":false}`.

The array of key/value pairs in `ProductAttributes.attributes` looks like it could take integer strings.  Is there a reason that the use of that array couldn't be extended to other modules?  A way needed to to indicate which module the keys belong to, or an array for for the module containing its key/value pairs?

It may turn out that we want to maintain all of the contributing scores in Item Maintenance as well, so there would be six + one values instead of one.

Other suggestions of where to store this data?

**Comment by gohanman** [comment]
Can you say more about how scores are calculated? Attributes are intended to capture the history of attribute value at a given time. If scores are changing daily or weekly this could generate a lot of noise and extra data.

Otherwise, the field can contain anything JSON-encodable. Item Flags' editor would need some tweaks to share the field with other sources correctly.

**Comment by flathat** [comment]
The final score is just  a sum of the constituent scores.  They may change, but not very often. History would probably be a plus.

**Comment by flathat** [comment]
The store is no longer in a position to pursue this, so closing.
