### ISSUE TITLE
Login hangs in offline mode

### ISSUE THREAD

**Issue by roberski** [CORE-POS/IS4C#985]
* Version of CORE?
Master

* Issue with Office, Lane, or both?
Lane

* Is this [mostly] a bug report, feature request, or question?
Bug

If a lane is in offline mode and you try to log in it sticks at the spinning animation and throws this error:

"Mar 26 10:13:45 GFM-LANE-05 corepos[4848]: (debug) javascript: {"message":"Uncaught TypeError: Cannot read property 'success' of null","url":"http://localhost/CORE/pos/is4c-nf/gui-modules/js/login2.js","line":31,"col":22,"detail":{}}"

I"m probably going to fix this today because I wanted to take my lanes offline to do some maintenance on the server.

**Comment by roberski** [comment]
Mar 26 10:45:12 GFM-LANE-05 corepos[4848]: (debug) mysqli_real_connect(): (HY000/1045): Access denied for user 'root'@'localhost' (using password: YES) Line 124, C:\Apache24\htdocs\CORE\common\adodb5\drivers\adodb-mysqli.inc.php
Mar 26 10:45:12 GFM-LANE-05 corepos[4848]: (debug) mysqli_real_connect(): (HY000/1045): Access denied for user 'root'@'localhost' (using password: YES) Line 124, C:\Apache24\htdocs\CORE\common\adodb5\drivers\adodb-mysqli.inc.php
Mar 26 10:45:12 GFM-LANE-05 corepos[4848]: (debug) mysqli_query() expects parameter 1 to be mysqli, boolean given Line 796, C:\Apache24\htdocs\CORE\common\adodb5\drivers\adodb-mysqli.inc.php
Mar 26 10:45:12 GFM-LANE-05 corepos[4848]: (debug) Uncaught exception: Could not create database core_trans (Access denied for user 'root'@'localhost' (using password: YES)) Line 249, C:\Apache24\htdocs\CORE\common\SQLManager.php
Mar 26 10:45:12 GFM-LANE-05 corepos[4848]: (debug) javascript: {"message":"Uncaught TypeError: Cannot read property 'success' of null","url":"http://localhost/CORE/pos/is4c-nf/gui-modules/js/login2.js","line":31,"col":22,"detail":{}}

And it only specifically happens when the password is wrong.
When I want to take a lane offline I usually just change the password, now I'll just change the ip.

I don't know if it's worth fixing now that I know this but what is happening as far as I can tell is this.
login2.js calls AjaxLogin.php which calls Database::testremote();
Database::testremote(); checks if the IP is reachable then tries to connect to the remote server which throws the above password errors and login.js doesn't like it.

**Comment by gohanman** [comment]
In principle I think the exception ought to be caught. Changing the credentials to take a lane offline isn't a use case I'd considered before, but dying with a fatal error isn't exactly the most graceful way to handle that scenario.

**Comment by gohanman** [comment]
This is fixed as of 2.9.0
