### ISSUE TITLE
SPINS install for George Street

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#987]
We’re getting George Street on board with [SPINS](http://www.spins.com/), and we’re wondering what the gotchas are with getting CORE-POS’ [SPINS plugin](https://github.com/CORE-POS/IS4C/tree/master/fannie/modules/plugins2.0/SPINS) functioning well. The [week offset](https://github.com/CORE-POS/IS4C/blob/master/fannie/modules/plugins2.0/SPINS/SpinsDate.php) seems like a potential difficulty, but are there any other challenges that might not be obvious from a naive scan of the codebase?

Tagging @joelbrock here because SPINS says he’s got a great deal of experience with SPINS setup!

* Version of CORE?
2.7

* Issue with Office, Lane, or both?
Office

* Is this [mostly] a bug report, feature request, or question?
question

**Comment by scannerdarkly** [comment]
Sounds good! So SPINS offset should be 0, except every once in a blue moon it (temporarily) shouldn’t?

**Comment by scannerdarkly** [comment]
Also, they need an initial product export file: Just UPCs and descriptions, I think — maybe prices. Is there a particularly efficient / recommended method for generating this from CORE-POS?

**Comment by gohanman** [comment]
I've never had to provide one before. Product List should theoretically be able to pull everything. The sticking point would be how big "everything" is and whether the browser bombs out trying to draw the table. If that happens then phpmyadmin or another SQL tool might be the best way to extract the products table as a CSV.

**Comment by joelbrock** [comment]
SPINS will generally want 2 years of transaction/movement history, but i've never had to provide them with the item file data.

Either the "Product List tool" under Item Maintenance menu, or what @gohanman said.  CLI or PHPMyAdmin

**Comment by scannerdarkly** [comment]
I just did (as superuser):
```
cd /CORE-POS/fannie/modules/plugins2.0/SPINS/
php -f ../../../classlib2.0/FannieTask.php SpinsSubmitTask 12
```
and now the SPINS directory has a zero-byte file called `03252018.csv`, owned by root and with 644 permissions.

Any idea where I should look to figure out why this file would be zero bytes? I think file permissions errors can be ruled out already...

**Comment by joelbrock** [comment]
Not entirely sure i'd rule out permissions just yet.  Do you get a
different result if you prepend the `php -f`command with `sudo`?

FWIW:  `SpinsSubmitTask 12` was just an example. You can run the tool
without a week number and it'll just do the most recent full week available.

**Comment by scannerdarkly** [comment]
I ran the export a third time and it worked (with nothing underlying having changed that I know of). So I deleted my zero-size-export post. @joelbrock, I see you replied to that post while I was deleting it, and I thank you. Should we delete your reply and pretend this particular bump in the road never happened? :)

**Comment by scannerdarkly** [comment]
I assume the cron task I want to enable is “weekly spins”? (Asking only because it looks like a legacy task, and because the helptext says “This script isn't yet in active use and may contain bugs.”

**Comment by gohanman** [comment]
There should be a non-legacy one named "Submit SPINS data". It'll only show
up as an option if the plugin is enabled.

**Comment by scannerdarkly** [comment]
Ah, I see. Thanks!

**Comment by gohanman** [comment]
This looks wrapped up
