### ISSUE TITLE
SUSPEND command hangs

### ISSUE THREAD

**Issue by otc-narendra** [CORE-POS/IS4C#988]
* Version of CORE?: 
2.7
* Issue with Office, Lane, or both?
Lane
* Is this [mostly] a bug report, feature request, or question?
Bug

The SUSPEND command causes a hang which can only be resolved by closing the browser and restarting.

**Comment by gohanman** [comment]
I think that's most likely fixed by 3f6108e1cb3b2855c23f5ac18f0d53827fd4edf1.

**Comment by otc-narendra** [comment]
That works - thanks!
