### ISSUE TITLE
Remote print on network printer from Ubuntu lane

### ISSUE THREAD

**Issue by otc-narendra** [CORE-POS/IS4C#990]
* Version of CORE?
2.8
* Issue with Office, Lane, or both?
Lane
* Is this [mostly] a bug report, feature request, or question?
Question

I set up an Ubuntu lane in a VM and am accessing it via a browser from a tablet. I have a network printer setup for my kitchen and would like the lane to use this printer as a remote printer with the remoteprint plugin. This is easy in Windows because I can port map LPT1: (or any other port) to the IP address of the printer using the Epson port mapping tool and then tell the plugin to print to that port. On Linux, I have used the Epson port mapping tool to set up a port and have also installed the printer via CUPS but cannot figure out how to get the plugin to print to it. It seems that the PHP fopen command doesn't like anything I've tried. Joel tried to troubleshoot for an hour or two last week without success as well. Wondering if there is some linux trick to getting a /dev/xxx mapping to an IP printer...

If not, I'll switch to running Windows on the VM and do it that way but Ubuntu is so much lighter!

- Narendra

**Comment by joelbrock** [comment]
I did stumble across socat <http://www.dest-unreach.org/socat/>, which
sounds a lot like the tool for the job.
Havent had a chance yet to take a closer look.  Is your Ubuntu VM online?
I tried SSHing to .104 but it appears to be offline.

http://www.dest-unreach.org/socat/

**Comment by otc-narendra** [comment]
Lane is online now. Printer is offline but is usually at static IP 192.168.1.49.

**Comment by gohanman** [comment]
This reminded me of an old bit of theoretical functionality brought back here (f13722d3985e3c75be4609db1b9f8102730067d7) and here (1c69c179186446745eaffd4abc246c51cb8182d1).

The basic idea is that instead of configuring the printer as `LPT1:` or `/dev/lp0` you'd use something like `tcp://192.168.1.49:9100`. Instead of opening a device file and writing raw print data to it POS would open a socket connection and write raw print data to it.

I have no idea if this will work and don't have any hardware with which to try it myself, but it wouldn't surprise me if it's that simple. I didn't have any luck googling for what port Epson printers use but 9100 is pretty common for printers. Or I guess just `nmap` it. If it does work I strongly suspect the sockets approach will fail a lot more gracefully when the printer is offline.

**Comment by otc-narendra** [comment]
The Epson printer is on port 9100. I believe Joel tried putting tcp://... but I can't remember for sure. I can certainly try it.

- Narendra
On Apr 30, 2018, at 12:12 PM, Andy Theuninck <notifications@github.com<mailto:notifications@github.com>> wrote:

This reminded me of an old bit of theoretical functionality brought back here (f13722d<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCORE-POS%2FIS4C%2Fcommit%2Ff13722d3985e3c75be4609db1b9f8102730067d7&data=02%7C01%7C%7C727865351a264450ee5c08d5aece45de%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636607123311922365&sdata=RcswNkbLCveR%2FuBM0E4qzlmSodHd7aj%2FnFTAYkbLfxs%3D&reserved=0>) and here (1c69c17<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCORE-POS%2FIS4C%2Fcommit%2F1c69c179186446745eaffd4abc246c51cb8182d1&data=02%7C01%7C%7C727865351a264450ee5c08d5aece45de%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636607123311922365&sdata=kQ%2Bbz4ret3188roFGSqWcyo8SeR5vWuYzVkgaJWe%2BVA%3D&reserved=0>).

The basic idea is that instead of configuring the printer as LPT1: or /dev/lp0 you'd use something like tcp://192.168.1.49:9100. Instead of opening a device file and writing raw print data to it POS would open a socket connection and write raw print data to it.

I have no idea if this will work and don't have any hardware with which to try it myself, but it wouldn't surprise me if it's that simple. I didn't have any luck googling for what port Epson printers use but 9100 is pretty common for printers. Or I guess just nmap it. If it does work I strongly suspect the sockets approach will fail a lot more gracefully when the printer is offline.

**Comment by gohanman** [comment]
Follow-up: I had a chance to try this on a TM-88V. Setting the printer port to `tcp://printer.ip.address:9100` on an Ubuntu CORE lane install seems to work just fine. It does accept RAW input via port 9100 the same way it would over USB or parallel.

**Comment by gohanman** [comment]
This is included in 2.10
