### ISSUE TITLE
RESUME command does not warn if transaction in progress

### ISSUE THREAD

**Issue by otc-narendra** [CORE-POS/IS4C#991]
* Version of CORE? 2.7
* Issue with Office, Lane, or both? Lane
* Is this [mostly] a bug report, feature request, or question? Bug

If you have a transaction in progress and then bring up the Manager menu and select Resume, you get a warning message saying: "Transaction in progress" which is the expected and correct behavior. However, if you do the same thing using the RESUME command, no warning message is displayed and the resumed transaction is "added" to the current transaction creating all sorts of havoc.
- Narendra

**Comment by gohanman** [comment]
That's definitely not optimal. This should prevent RESUME from making that particular mess: b12fb5f0eeffb8ea4a08f243c77a9c2579456306

**Comment by otc-narendra** [comment]
Works beautifully - thanks!
