### ISSUE TITLE
Fannie UI to edit remoteprint table

### ISSUE THREAD

**Issue by otc-narendra** [CORE-POS/IS4C#994]
* Version of CORE? 2.7
* Issue with Office, Lane, or both? Office
* Is this [mostly] a bug report, feature request, or question? Feature Request

The remote printing plugin added the ability to send specific upcs/departments to a remote printer.  The only way to edit the list of items to be remote printed is to use phpmyadmin or some other tool to edit the table directly. It sure would be lovely to have some UI in fannie for this. Either a checkbox in the item editor or, even simpler, just a simple table editor.

- Narendra

**Comment by gohanman** [comment]
^ Simple table editor

**Comment by gohanman** [comment]
That just mean the table name is wrong in the local install.

**Comment by otc-narendra** [comment]
I'm assuming that when the table was initially created, it got named "remoteprint" instead of "RemotePrint" although I have no clue how that happened. Since I'm in a mixed Windows/Unix environment (Ubuntu for Fannie and Windows for lanes), I'm wondering what you recommend for the MySql setting --lower-case-table-names (https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html) which I imagine this was the problem...

**Comment by gohanman** [comment]
My environment's the same. I use 0 for `lower_case_table_names` on Ubuntu and 1 on Windows. As far as I know this has been the out-of-the-box defaults with MySQL on the respective OSes basically forever.

I'd guess what happened is someone `mysqldump`ed the table from the lane where it's lower case and case insensitive and restored it onto the server where case matters. CORE itself never copies tables in that direction so the details of exactly how that should work have never been a concern.

As far as I know everything would work fine with the server setting flipped to 1 but I'd be wary of trying that on a live system. The MySQL doc doesn't really say what will happen to tables whose names aren't currently all lowercase.

**Comment by otc-narendra** [comment]
I fixed the problem by recreating the tables on fannie. Thanks for the help!

**Comment by otc-narendra** [comment]
I fixed it by re-creating the tables on Fannie. Thanks!
