### ISSUE TITLE
Undefined index error in NormalPricing.php

### ISSUE THREAD

**Issue by otc-narendra** [CORE-POS/IS4C#996]
* Version of CORE? 2.7
* Issue with Office, Lane, or both? 2.7
* Is this [mostly] a bug report, feature request, or question? Bug/question

My lane debug log has the following entries on a regular basis:
Undefined index: line_item_discountable Line 42, C:\xampp\htdocs\Our-Table\pos\is4c-nf\lib\Scanning\DiscountTypes\NormalPricing.php

Any ideas?

**Comment by otc-narendra** [comment]
Assuming we are talking about database indexes here, my products table does not have an index on the line_item_discountable column - is it supposed to?

**Comment by gohanman** [comment]
No, not database indexes. The array index that the notice says doesn't exist. I can't find any way that index would not exist so I'm not sure what's leading to the notice.

**Comment by gohanman** [comment]
Closing this one as not reproducible.
