### ISSUE TITLE
Can't add auth_class to Group

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#997]
* Version of CORE? 2.7

* Issue with Office, Lane, or both? Office

* Is this [mostly] a bug report, feature request, or question? Bug report

Adding an authorization to an existing Group using `AuthGroupsPage()` doesn't work. The "Add Authorization" submission from `get_newAuth_view()` never gets to `post_id_authClass_start_end_handler()`.

This *does* make it work, although I don't know whether it's the way it *ought* to work:
+ Add `<input type="hidden" name="_method" value="put" />'` to the form in `get_newAuth_view()`.
+ Change the `route` from `post<id><authClass><start><end>` to `put<id><authClass><start><end>`
+ Rename the handler from ` post_id_authClass_start_end_handler()` to ` put_id_authClass_start_end_handler()`

**Comment by gohanman** [comment]
I can't replicate this one. If I go to the list of groups and use the Add Auth button, it works. If I go to the list of groups, select a group, and then use the Add Auth button that also works.

What changing `post` to `put` is doing is bypassing whatever underlying problem is happening matching the request to a route. That's not a great solution insofar as `FannieRESTfulPage` is used all over the place and a problem in the underlying route selection most likely breaks lots of things. Route debugging isn't built into 2.7 so you'd have to manually inspect what value `$__route_stem` is selecting when the form is submitted - e.g., replacing `return parent::preprocess();` with something like:

```php
$ret = parent::preprocess();
if (count($_POST) > 0) {
    var_dump($this->__route_stem); exit;
}
return $ret;
```

You could log to a file instead if temp-breaking the page for debugging is too disruptive.

**Comment by flathat** [comment]
Using that, with the `name="_method"` removed, I get:
```
string(6) "get_id"
```
What should it be?

(With `_method`, but no handler for it, I get `HTTP 400 - Bad Requeststring(6) "put_id"`)

I was initially using `PHP 7.2` but have changed to `5.6` for the test reported in this post, although the result is the same as for 7.2

I'm doing this on a new installation of Fannie, cloning `https://github.com/flathat/IS4C`, which had `CORE 2.7` merged on it.  The problem of saving changes in Users seems to affect all types of changes in the new installation but there are no problems with those changes on the server the repo was developed under.
```
+-------------------------------------------------------+
|             | Old installation  | New installation    |
+-------------------------------------------------------+
| O/S         | Ubuntu 10.0.4     | CentOS 7            |
| PHP         | 5.4.39            | 5.6.36              |
| MySQL       | 5.1.73            | 5.6.39-83.1         |
|  collation  | latin1_swedish_ci | utf8mb4_general_ci  |
+-------------------------------------------------------+

**Comment by gohanman** [comment]
Hmm. It should be `post_id_authClass_start_end` but more generally it should be `post_` if the browser is in fact submitting the form via a HTTP POST.

[Relevant Logic](https://github.com/CORE-POS/IS4C/blob/version-2.7/fannie/classlib2.0/FannieRESTfulPage.php#L128-L136)

```php
        // routes begin with method
        try {
            $this->__method = $this->form->_method;
        } catch (Exception $ex) {
            $this->__method = filter_input(INPUT_SERVER, 'REQUEST_METHOD');
            if ($this->__method === null) {
                $this->__method = 'get';
            }
        }
        $this->__method = strtolower($this->__method);
```

* If `_method` is present in the form submission, use that [1]
* Otherwise read from `$_SERVER['REQUEST_METHOD']`
* If everything failed, default to `get`.

My guess would be `$_SERVER['REQUEST_METHOD']` is undefined and that's why the proper `post_` route isn't chosen but I have no idea why. I've never encountered a webserver+OS environment where that variable isn't populated.

[1] An old Rails-ism since browsers didn't/don't support PUT or DELETE

**Comment by flathat** [comment]
It seems that `filter_input(INPUT_SERVER, 'REQUEST_METHOD');` incorrectly returning `NULL` is a [known problem](https://stackoverflow.com/questions/25232975/php-filter-inputinput-server-request-method-returns-null) (and [still unresolved](https://bugs.php.net/bug.php?id=49184)) under Apache FastCGI.

The helper function suggested [there](https://stackoverflow.com/questions/25232975/php-filter-inputinput-server-request-method-returns-null), when added to `FannieRESTfulPage.php` works:
```PHP
protected function filter_input_fix ($type, $variable_name, $filter = FILTER_DEFAULT, 
$options = NULL )
{
    $checkTypes =[
        INPUT_GET,
        INPUT_POST,
        INPUT_COOKIE
    ];

    if ($options === NULL) {
        // No idea if this should be here or not
        // Maybe someone could let me know if this should be removed?
        $options = FILTER_NULL_ON_FAILURE;
    }

    if (in_array($type, $checkTypes) || filter_has_var($type, $variable_name)) {
        return filter_input($type, $variable_name, $filter, $options);
    } else if ($type == INPUT_SERVER && isset($_SERVER[$variable_name])) {
        return filter_var($_SERVER[$variable_name], $filter, $options);
    } else if ($type == INPUT_ENV && isset($_ENV[$variable_name])) {
        return filter_var($_ENV[$variable_name], $filter, $options);
    } else {
        return NULL;
    }
}
```
then
```PHP
$this->__method = $this->filter_input_fix(INPUT_SERVER, 'REQUEST_METHOD');
```
as does this additional search of `$_SERVER` (one fix or the other, not both):
```PHP
        try {
            $this->__method = $this->form->_method;
        } catch (Exception $ex) {
            $this->__method = $this->filter_input(INPUT_SERVER, 'REQUEST_METHOD');
            if ($this->__method === null) {
                if (isset($_SERVER['REQUEST_METHOD'])) {
                    $this->__method = $_SERVER['REQUEST_METHOD'];
                } else {
                    $this->__method = 'get';
                }
            }
        }
        $this->__method = strtolower($this->__method);
```
The suggested change to `php.ini`:
```
variables_order = "GPCSE"
```
did not help in my case.

`filter_input(INPUT_SERVER, )` is used quite a lot in `fannie/` but for `REQUEST_METHOD` only in `classlib2.0/webservices/JsonEndPoint.php` that I've found, so I'll make this change locally there too.   It isn't used at all with `REQUEST_METHOD` in `pos/is4c-nf`.  It isn't clear where else `filter_input(INPUT_SERVER` may be failing so I may have to see about not using `FastCGI`.

And thanks, @gohanman , for `$debug_routing` in `FannieRESTfulPage` in `2.8`, something I've been wanting; I imported it locally.

**Comment by gohanman** [comment]
Interesting. My own experience with FastCGI is primarily with nginx, but I tried this on a couple different hosts using Apache + FastCGI and `filter_input(INPUT_SERVER, 'REQUEST_METHOD')` works fine on those too. I assume that means the issue is fixable although I'm not sure specifically how (I'm trying it on Dreamhost boxes and don't have access to their config files in /etc).

**Comment by flathat** [comment]
It seems that, in my case, the problem is only when _not_ in `FastCGI` mode.  It wasn't clear to me whether the webserver was just capable of FastCGI or actually using FastCGI.

To enable `FastCGI`, in `.htaccess` (I'm on a shared host and the value may be installation-specific.):
```
<FilesMatch \.php$>
    SetHandler php56-fcgi
</FilesMatch>
```

One way to tell if `FastCGI` is being used is that in the `phpinfo()` report a value such as PHP Variables > `$_SERVER['ORIG_SCRIPT_NAME']` is `/cgi-bin/php56.fcgi` instead of `/cgi-bin/php56.cgi`, although the exact filenames may be installation-specific.

I've changed back to PHP 7.2 and it is still OK.

**Comment by gohanman** [comment]
The main indicator should be in the 2nd line of `phpinfo()`, Server API.

**Comment by flathat** [comment]
At least in this installation the 2nd line of `phpinfo()` says `CGI/FastCGI` whether FastCGI is actually being used or not.

**Comment by gohanman** [comment]
I'd interpret that as meaning you're switching between two different configurations that are both using the FastCGI SAPI.

**Comment by flathat** [comment]
What do you mean by "switching between two different configurations that are both using the FastCGI SAPI"?

I thought `CGI/FastCGI` might mean "the mod is enabled in this shared instance but you're not necessarily using it".  If there's no `SetHandler` in `.htaccess` then it behaves as though FastCGI is not enabled; the var `$_SERVER['ORIG_SCRIPT_NAME']` is `/cgi-bin/php56.cgi`, not `php56.fcgi`.  According to the host's docs the `SetHandler php56-fcgi` is how you choose to use FastCGI.

**Comment by gohanman** [comment]
Ah, I see. `CGI/FastCGI` for SAPI technically means it's running PHP via CGI **or** FastCGI. I hadn't considered the possibility that a modern hosting provider would actually be using plain CGI. In any event it's not a mod; it's identifying what protocol the webserver is using to communicate with PHP.

`$_SERVER['ORIG_SCRIPT_NAME']` is itself a nonstandard oddity. The official docs for `$_SERVER` don't list it all nor is it present in default configs I've seen for Apache+mod_php, Apache+FastCGI, or nginx+FastCGI. My impression is for whatever reason this hosting provider has a very strange setup.
