### ISSUE TITLE
Allocate Patronage to clear current patronage?

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#998]
* Version of CORE? master

* Issue with Office, Lane, or both? Office

* Is this [mostly] a bug report, feature request, or question? Bug

Patronage > [Allocate Patronage](https://github.com/CORE-POS/IS4C/blob/master/fannie/mem/patronage/AllocatePatronagePage.php) currently `UPDATE`s `patronage_workingcopy` based on the values in the form but `INSERT`s to `patronage`.  Since the Primary Key on `patronage` is `cardno` + `FY` (fiscal year) an attempt to run it a second time for the fiscal year currently in `patronage_workingcopy` fails on a duplicate primary key error.

It seems to me a good way to avoid this would be to `DELETE FROM patronage WHERE patronage.FY =` the current `patronage_workingcopy.FY` prior to `INSERT`ing to `patronage`.   Is there a use case where this wouldn't be a good idea?  I was thinking of making it an option, with checkbox, but just making it the normal behaviour seems simpler if there's no case where one would not want to.

On a related issue, the page, at `post_view()`, currently reports `'<div class="alert alert-success">Patronage Allocated to Owners</div>'` even when the `INSERT`  in `post_handler()` described above fails.  What would be the `RESTful` way of reporting the failure?

**Comment by gohanman** [comment]
> Is there a use case where this wouldn't be a good idea? I was thinking of making it an option, with checkbox, but just making it the normal behaviour seems simpler if there's no case where one would not want to.

It creates a pretty serious potential mistake. If the org's fiscal year isn't the same as a calendar year, the user is going to get a drop-down choice for FY with the two calendar years their chosen date range spans. Making a mistake here and then proceeding through the rest of the process would overwrite the previous FY's data. Reconstructing this data could be fairly difficult if there's any backtracking required to figure out owner account statuses at the time of the original allocation.

The current behavior isn't helpful, but I think it should go beyond just a checkbox. `get_view` should check for a conflict and when there is one provide both a checkbox and a prominent message along the lines of "Patronage has already been allocated for this fiscal year. Are you sure you want to overwrite the existing allocations?"

> On a related issue, the page, at post_view(), currently reports `<div class="alert alert-success">Patronage Allocated to Owners</div>` even when the INSERT in post_handler() described above fails. What would be the RESTful way of reporting the failure?

I'd probably just assign a `$this->message` value in `post_handler` and simply return it in `post_view`.

**Comment by gohanman** [comment]
Here's mostly the requested fix. Instead of deleting from the patronage table I'm moving the existing data out of the way by negating the fiscal year and subtracting a random value from it. The subtraction will make it a little harder to recover the data in the event of a mistake but makes it so you can overwrite the same FY multiple times. Keeping the old data in the table at least provides a recover option in the event of a mistake.
